### ISSUE TITLE
【新人戳这里】 意见反馈须知

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#1]
意见反馈区迁移至这里，点击 “New issue” 的绿色按钮以发起新的意见 ~

本区仅受理百科的BUG和意见，MC玩法相关提问请转到百科提问区 (建设中)

**Comment by 3TUSK** [comment]
Got a question:
新人真的能看到这个issue吗...还是说占掉#1是在卖萌...

**Comment by Meow-J** [comment]
@3TUSK 现在这一部分的内容已经转移到主页的README上去了，这个的存在其实都可有可无了
