### ISSUE TITLE
搜索显示的时候会直接替换搜索条目里面的内容，大小写也会给替换成搜索时候的大小写

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#10]
![qq 20150811182852](https://cloud.githubusercontent.com/assets/5229241/9195628/d54bacf0-4056-11e5-98a1-1ab364651ae7.png)
应为Extra Utilities

**Comment by Ahrwing** [comment]
搜索已改版~ 不会出现这样的问题了w
