### ISSUE TITLE
转义符问题仍然存在

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#100]
![image](https://cloud.githubusercontent.com/assets/5229241/10714187/c31b805e-7b1c-11e5-82e2-97dd1b8ec422.png)

**Comment by Ahrwing** [comment]
这个是只有在审核的时候会出现咩？ 还是审核以后也会出现……

**Comment by Ahrwing** [comment]
按错了... /w\..

**Comment by Meow-J** [comment]
忘了/w\，总之都检查一下吧

**Comment by Ahrwing** [comment]
修好了~ 不是后台的问题…… 是编辑时取值转义问题
