### ISSUE TITLE
关于百科的建议（非专业

### ISSUE THREAD

**Issue by hzy4619666** [Ahrwing/mcmod#101]
我是一个mod爱好者。主动帮助喜欢的mod添加百科。加入MC百科仅1天有余。
使用中，有一些个人的想法，说出来。如果合理的，方便的话请考虑一下。
1、审核流程方面的。
我提交了几个方块、日志。进入了审核状态。于是产生了以下想法：
如果。当一个词条进入审核状态。审核流程不变，如果在正文中以预发布的形式（红色字体带星号）提前更新出来，方便查看。或者干脆在分类中放一个待审核的分类。再或者仅该条编辑者可查看。
2、百科各mod的管理。
审核是个费时费力的工作。在此向各位审核君致敬。
我的想法则是：以模组为单位，编辑者自行向百科管理组申请审核权限。一正多副（类似百度贴吧大小吧务的样子）。由志愿者构成一审团队自行管理审核。由百科团队审核君负责二审或抽审。同时对每个模组开放单独备份权限。
以上为个人使用时产生的一些想法。不懂编程方面的事。海涵。

**Comment by Meow-J** [comment]
1. 想让公开看到的情况还是算了，之前发生过乱改的事件，加了反而会有问题。至于编辑者可查看这一个只需要点击下对应词条的编辑就能看到了。
2. 这个之前考虑过，不过好像一直没搞

p.s.: 物品英文名请写本地化之后的名字而不是mod内部注册的名字

**Comment by hzy4619666** [comment]
谢谢。明白了。
