### ISSUE TITLE
开放JSON批量添加并增加审核

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#103]
或者在添加物品的时候给个提示让找审核员也行/w\

**Comment by Meow-J** [comment]
顺便加删除权限

**Comment by Ahrwing** [comment]
怎么说呢 _(:з」∠)_ 这是一个非常吃CPU的操作.. 所以理论上最多只能开放给资深编辑员使用~

**Comment by Meow-J** [comment]
不能上传文件之后延迟执行什么的吗/w\

**Comment by sxjeru** [comment]
emmm，两年前的issue。
@Ahrwing 既然现在还没有提交窗口，那就开一个帖吧。

**Comment by Ahrwing** [comment]
发到这里吧~ http://bbs.mcmod.cn/thread-1281-1-1.html
