### ISSUE TITLE
建议：资料类型自定、资料分类排序

### ISSUE THREAD

**Issue by hzy4619666** [Ahrwing/mcmod#106]
1、模组都是多种多样的。保不准哪个mod就添加了什么。固定的资料类型并不能完全满足需要。
个人认为，魔法、技能、能力什么的需要单独一个资料页。
2、单从物品方块来说。部分分类顺序会影响美观。
比如矿物→材料→机械这样看就感觉比较顺。分类中若顺序反过来或者颠倒，则乱。
个人愚见，以上。

**Comment by Ahrwing** [comment]
1... 这个可以实现，但目前还不知道该怎么实现比较合适.. 如果规定所有编辑者都可以自定义添加，可能会出现乱加类型的情况，类型小图标之类的也都无法确认.....如果规划好了一个详细的分类流程的话.. 我想这个功能应该能很快就会上线。

2. 由于所有物品分类都是由编辑者添加， 暂时没方案让系统自动按照预设的排序.. 可变性太多..

**Comment by Meow-J** [comment]
不是有审核嘛/w\

**Comment by 3TUSK** [comment]
参考一下http://ftbwiki.org 和 http://ftb.gamepedia.com ？（写作两个wiki站点读作Mediawiki）
审核的话，如何保证分类是最合适的呢...（又是考验资历的时候了）

**Comment by hzy4619666** [comment]
问题1，资料类型可以像物品分类一样，增加一个自定义名称功能吧。不知道我想的跟你们想的是不是一回事= =
问题2，旨在手动排序功能。可能我无法描述清楚。可以参考一下bilibili的板块排序吧。

可能，你们出于管理员开发者角度考虑问题会复杂一些，因为牵扯甚广。
我只是作为一个非专业的用户和给喜欢的mod做点贡献的玩家来看，这些功能也许有些繁琐和不必要，但对于浏览网页的人来说也许会稍微感觉人性化一点。

个人疑问。搞管理和做程序的一般都是汉子吧。为毛我会见到一堆妹子用的头像？

**Comment by Meow-J** [comment]
1. 上面主要是怕分类乱掉。关于审核问题，感觉现在是不是真的需要单mod管理员了
2. 在完成用户自定义排序之前估计先考虑编辑员后台排序。不过用户手动排序那样的话，感觉实用性不强，总不能每个mod来一遍排序/w\

最后一个问题无法回答

**Comment by hzy4619666** [comment]
R2：这个可以有。展示出来的排序由编辑员来做就可以了。其实可以给用户排序加入到cookies里。前提是要把板块模块化吧？不知道是不是这么一种概念。
最后一个问题其实很容易回答的吧o(︶︿︶)o （技术）宅都是这样。

**Comment by 3TUSK** [comment]
A world without girlfriend never seen before. XD
>个人疑问。搞管理和做程序的一般都是汉子吧。为毛我会见到一堆妹子用的头像？

**Comment by liach** [comment]
@3TUSK Because you **guys** do not code.

**Comment by 3TUSK** [comment]
@liach Are _you_ sure...

**Comment by Ahrwing** [comment]
1暂时不能实现
2已完成~
