### ISSUE TITLE
日志自动排序功能

### ISSUE THREAD

**Issue by bakaxyf** [Ahrwing/mcmod#108]

**Comment by bakaxyf** [comment]
Any progress? 
碰到[这样的](http://www.mcmod.cn/class/version/5.html?jump=1461)人工排序太麻烦了

**Comment by Ahrwing** [comment]
以前好像提到过这个问题.. 想过类似的算法，1月3号试试。

**Comment by Meow-J** [comment]
1月3号?

**Comment by 3TUSK** [comment]
目测2月3号。

**Comment by AstonIceDog** [comment]
如果要实现自动排序的话，必须得规范化日志名称

**Comment by Meow-J** [comment]
这个没法规范，每个mod有自己的版本记法

**Comment by AstonIceDog** [comment]
我意思是编辑者写日志名称时要规范一点，比如MOD名+版本名+支持版本名（可选填）

**Comment by Meow-J** [comment]
不都是按照官方发布时的版本写的/w\

**Comment by AstonIceDog** [comment]
没看懂↑↑说清楚点

**Comment by Ahrwing** [comment]
@AstonIceDog 显而易见 与作者发布的版本号一致

**Comment by AstonIceDog** [comment]
哦

**Comment by Ahrwing** [comment]
改好了 /w\

**Comment by 3TUSK** [comment]
@bakaxyf Time to sort changelog! Yeah!

**Comment by Ahrwing** [comment]
貌似还有问题… _(:з」∠)_ (哭

**Comment by Ahrwing** [comment]
v3后台已增加拖动排序与自动排序 √
