### ISSUE TITLE
消息中心反人类设定，新消息出现在最上面

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#11]
![qq 20150811183035](https://cloud.githubusercontent.com/assets/5229241/9195654/15237e48-4057-11e5-88c1-b69f15ca5135.png)
看时间

**Comment by Ahrwing** [comment]
虽然不是BUG.. 当初设计成这样的.. 但为了用户体验.. 已经改成新消息出现在下方了..
