### ISSUE TITLE
资料分页

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#113]
否则进一次GT6就80MB/w\会炸的

**Comment by elctove** [comment]
然而这是谁的锅/w\

**Comment by Ahrwing** [comment]
搞定 /w\..

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/11324300/e84c7d4e-9168-11e5-8b79-db8530a2e877.png)
这里还需要换成下一页

**Comment by Ahrwing** [comment]
搞定了~ww

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/11329531/39035d38-91d8-11e5-8654-c9802d14a3be.png)

**Comment by Ahrwing** [comment]
哪个页面的 orz.....
