### ISSUE TITLE
限制编辑器内远程图片

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#114]
![image](https://cloud.githubusercontent.com/assets/5229241/11317454/9bfd3932-906a-11e5-9ab1-d369769c9fa7.png)

**Comment by Meow-J** [comment]
另外还有编辑器里显示图片的比例

**Comment by Ahrwing** [comment]
已修复 /w\.. 不过不是在编辑器里提示的~ 是在提交的时候~

**Comment by Meow-J** [comment]
@Ahrwing 图片比例呢/w\

**Comment by Ahrwing** [comment]
忘记了 /w\...

**Comment by Meow-J** [comment]
开个新的吧/w\
