### ISSUE TITLE
矿物词典依旧不存在……

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#117]
何时能填这个巨坑的说/w\

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/11369214/bb42824e-92f8-11e5-8ace-9d2f0517221b.png)
有的，不过目前好像只作为合成的一个辅助

**Comment by elctove** [comment]
好吧我说的是页面，就是www.mcmod.cn/dict/

**Comment by Ahrwing** [comment]
矿物词典手动录入功能已移除，请使用IRR批量导入~
