### ISSUE TITLE
批量编辑

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#119]
- [x] 确定按钮
- [x] 全 ! 选 !
- [x] 已有分类下拉选项 + 创建新分类选项
- [x] 分类全选
- [x] 分类改名
- [x] 分类内批量编辑
- [x] 批量删除物品
- [ ] ...

**Comment by Meow-J** [comment]
更新目标啦!!! @Ahrwing

**Comment by AstonIceDog** [comment]
<li class="task-list-item">
<input type="checkbox" class="task-list-item-checkbox" disabled=""> 批量添加合成表2333</li>

**Comment by Ahrwing** [comment]
v3后台支持这些所有 √ (除了创建分类..)
