### ISSUE TITLE
是否考虑使用CC协议

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#120]
如题。不知道使用CC-BY这样的协议是不是可以会很有用。

**Comment by Ahrwing** [comment]
用BY-NC-SA如何？

**Comment by Meow-J** [comment]
加个选项不就好了/w\

**Comment by 3TUSK** [comment]
ND呢...？不知道为什么，但直觉告诉我这时ND会很有用

**Comment by 3TUSK** [comment]
啊最近遇到一个麻烦事，我最近有想法把FTB Wiki的一部分内容搬运到mcmod百科，但是FTB Wiki用CC-BY-NC-SA 3.0啊，于是就不敢乱碰了...

**Comment by Meow-J** [comment]
好像没什么问题，BY署个来源，SA只要不修改就行了

**Comment by Ahrwing** [comment]
那就决定用 BY-NC-ND 了吧... 有人有异议吗...
确定的话, 我在底部和显眼的地方标明一下..

**Comment by Meow-J** [comment]
ND总觉得有点过了

**Comment by Meow-J** [comment]
另外，如果是私有教程，最好能给一个选择，让作者决定使用什么协议

**Comment by Ahrwing** [comment]
/w\.. 好.. 教程特殊处理...…

**Comment by 3TUSK** [comment]
CC-BY-NC-SA吧

**Comment by Ahrwing** [comment]
弄好了，百科全站使用 CC-BY-NC-SA 
教程内作者可以自己设置CC协议，也可以关闭
详细专题：www.mcmod.cn/notice/9.html - automatic!
[关于CC协议的专题](www.mcmod.cn/notice/9.html)

**Comment by 3TUSK** [comment]
![image](https://cloud.githubusercontent.com/assets/9113033/12072494/84b70ce4-b0ae-11e5-94bb-f13684f9a935.png)
还好没关，怎么有两个NC，吓得我以为我眼花+脑残了...

**Comment by Ahrwing** [comment]
吓得我赶紧修好了.. 

话说

**Comment by 3TUSK** [comment]
啊，格雷资料不全，于是爆肝翻译了一大片……

**Comment by Meow-J** [comment]
修改了没用
![image](https://cloud.githubusercontent.com/assets/5229241/12072990/c5993710-b13e-11e5-8af3-0af07ed36cee.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12072992/d622b5a2-b13e-11e5-8118-aeb2a214a65f.png)

**Comment by Ahrwing** [comment]
我的锅 dns缓存忘记更新 现在应该没问题了

**Comment by Meow-J** [comment]
站上不去了/w\

**Comment by Ahrwing** [comment]
- - 貌似大姨妈了几分钟..

**Comment by Meow-J** [comment]
还是不行

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/12073276/3be19fea-b151-11e5-809f-faf98e6410b8.png)
悬浮这里写本站所有教程除特殊说明采用CC BY-NC-SA 3.0协议吧

**Comment by Ahrwing** [comment]
w
