### ISSUE TITLE
资料作者未出现在贡献栏

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#121]
最好再加一个特殊的标记标示作者/w\

**Comment by Ahrwing** [comment]
妥了 /w\...
话说这个问题很早以前就打算改的..  记得当时是无从下手.. 现在竟然成功了....

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/11812703/5c9d3f78-a378-11e5-8459-042aab4472a0.png)
 右边那奇怪的字母是啥/w\

**Comment by Ahrwing** [comment]
/w\... 这个.. 可以当做医生手术后留在病人身体里的东西……

已经修好了... 鱼唇的我用错误的方法试了半天...
