### ISSUE TITLE
修改物品图标无效？

### ISSUE THREAD

**Issue by xpenxpen** [Ahrwing/mcmod#122]
第一次新增物品，未加图标。
第二次修改物品，添加了图标，但是审核通过后图标依旧不显示，还是显示一个问号。
也就是说第一次添加物品时若忘记添加图标，以后再也加不了了。
已经遇到过2次，不知是否是issue。

**Comment by Meow-J** [comment]
#72

**Comment by Ahrwing** [comment]
已修复~ (经检测是一个愚蠢的问题导致的... orz
