### ISSUE TITLE
[备忘] 合成表根据模组分类

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#126]
例如工业2的某物品中的某合成表需要加格雷科技5才会出现，那么就在所有合成表最顶上自动出现“所有 | 工业2 | 格雷科技5”

点击工业2：       只显示当前模组自己添加的合成表；
点击格雷科技5：只显示格雷科技5追加的合成表；
点击全部：         显示所有合成表。

**Comment by 3TUSK** [comment]
如果一个合成要三个或以上模组才能出现呢？（笑）

**Comment by Heteroreceptor** [comment]
还有个建议, 大致是把其它合成表都放到"详细合成表"那个页面里去, 然后再用几种方式分类

**Comment by Ahrwing** [comment]
@3TUSK 不可能，合成表是在哪个MOD里注册的，就算是需要哪个MOD，这是一对一的关系。

**Comment by Ahrwing** [comment]
会放在那个详细合成表页面的~

**Comment by 3TUSK** [comment]
@Ahrwing 举个例子吧……比如这个：https://github.com/jadedcat/JadedTweaks
