### ISSUE TITLE
关于后台管理的一些建议

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#130]
1. ![image](https://cloud.githubusercontent.com/assets/13271372/12073372/461affc2-b158-11e5-812e-95b963e0d2a3.png)
比如这个出问题啦，怎么回事啊
2. 后台管理中上传合成表终端还是不能上传，这关系到模组的完善，因为有好些模组都有自己的*终端合成表*，比如***Foodcraft***里面有好多合成台终端，然而无法上传，阻碍了我编译词条的脚步。<del>其实是我懒。</del>

**Comment by Ahrwing** [comment]
这两个应该都是浏览器兼容问题 你用的是什么浏览器

**Comment by AstonIceDog** [comment]
360

**Comment by AstonIceDog** [comment]
。。。是不是360浏览器的问题？

**Comment by Ahrwing** [comment]
有。。。 很大问题。。。以前用360浏览器注册都注册不了。。 不知道抽什么风

**Comment by AstonIceDog** [comment]
好吧

**Comment by 3TUSK** [comment]
@AstonIceDog 试试Firefox、Chrome和Safari

**Comment by AstonIceDog** [comment]
我试试FireFox

**Comment by AstonIceDog** [comment]
原来是浏览器的问题，火狐都可以的

**Comment by AstonIceDog** [comment]
然而希望出个合成表终端上传教程
