### ISSUE TITLE
较长的用户名在显示时会被放大镜挡住

### ISSUE THREAD

**Issue by XieEDeHeiShou** [Ahrwing/mcmod#131]
较长的用户名在显示时会被放大镜图标挡住。

**Comment by Meow-J** [comment]
放大镜?

**Comment by XieEDeHeiShou** [comment]
额，就是右上角，没错，就是那个地方。像我这么帅的ID（pia就会被挡住一部分。

**Comment by AstonIceDog** [comment]
我的AstonIceDog也会诶，被放大镜挡住好困扰啊
![image](https://cloud.githubusercontent.com/assets/13271372/12215222/9ad0ac56-b6ee-11e5-8544-ae62c693a37d.png)
@XieEDeHeiShou 你是说的这个吧
@Meow-J 吃掉了一个A看到没

**Comment by XieEDeHeiShou** [comment]
是的。

**Comment by 3TUSK** [comment]
@CannonFotter 你不是一个人。
（短id的好处）

**Comment by AstonIceDog** [comment]
![image](https://cloud.githubusercontent.com/assets/13271372/12534237/20a9af84-c28a-11e5-825d-c3357bb51a00.png)
又发现一个问题，在后台管理，名字会这样↑·

**Comment by Ahrwing** [comment]
已换顶栏
