### ISSUE TITLE
个人动态显示已提交条目

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#132]
![image](https://cloud.githubusercontent.com/assets/5229241/12079605/5e21ec48-b27a-11e5-901e-ec06b850a21d.png)

**Comment by Ahrwing** [comment]
个人中心里的时间已加~

**Comment by Meow-J** [comment]
并没有不通过那块的功能/w\，而且现在动态能显示的条数太少了

**Comment by Ahrwing** [comment]
@Meow-J I have an idea...

**Comment by Ahrwing** [comment]
_(:з」∠)_ 还是加个分页吧………

**Comment by AstonIceDog** [comment]
建议已提交条目分MOD显示

**Comment by Ahrwing** [comment]
用户历史审核记录已加~
