### ISSUE TITLE
教程修改理由非必填

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#133]
![image](https://cloud.githubusercontent.com/assets/5229241/12107224/d423668c-b3a2-11e5-88a5-54fec99048ae.png)

**Comment by Ahrwing** [comment]
好了 /w\..

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/12754204/52370af6-ca05-11e5-9028-afec43592b22.png)
完全没有/w\

**Comment by Ahrwing** [comment]
好了~ (愚蠢的错误..
