### ISSUE TITLE
主页物品图标问题

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#134]
![n](https://cloud.githubusercontent.com/assets/5229241/12202000/57cce8d4-b662-11e5-9cea-db0963e7477b.gif)
![l](https://cloud.githubusercontent.com/assets/5229241/12201999/57a92494-b662-11e5-8127-56ee7acbc3db.gif)
鼠标悬停在图标上出现的名称会不断闪烁，看不清

而且每次其中一个图标的晃动根本不会停

**Comment by 3TUSK** [comment]
什么时候这些图标还带tooltip了...

**Comment by Ahrwing** [comment]
@3TUSK 早就有了……………………
话说已经修好了.. 顺便修了一下滑块会跳广场舞的bug.. (233

**Comment by Meow-J** [comment]
广场舞/w\
