### ISSUE TITLE
资料网址需要忽略空格

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#135]
![image](https://cloud.githubusercontent.com/assets/5229241/12203324/4d4aae4e-b669-11e5-8158-b1fd40cdcbae.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12203334/575b6e1e-b669-11e5-94bd-f3c48895aa83.png)

**Comment by Ahrwing** [comment]
弄好了~~ 把所有需要的地方都加了去空格~~
