### ISSUE TITLE
日志排序bug

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#137]
Mod主页编辑：
![image](https://cloud.githubusercontent.com/assets/5229241/12203971/89683e8e-b66c-11e5-828f-9f0817f76adc.png)
日志显示：
![image](https://cloud.githubusercontent.com/assets/5229241/12203977/8dcdcdcc-b66c-11e5-983d-7d19e2123fc5.png)
后台排序：
![image](https://cloud.githubusercontent.com/assets/5229241/12203989/9eb68764-b66c-11e5-8f15-e1d99d23e9a6.png)

**Comment by Meow-J** [comment]
相关 #4

**Comment by Ahrwing** [comment]
修了一下.. 应该没问题了~

**Comment by Meow-J** [comment]
好了
