### ISSUE TITLE
编辑器复制无法复制文字格式

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#138]
复制过后全变成普通字体了

**Comment by Ahrwing** [comment]
因为纯文本化了… 已经改好~ 增加可选项~ 默认可以直接把样式粘贴出来~

**Comment by Meow-J** [comment]
不行/w\

**Comment by Ahrwing** [comment]
@Meow-J 一定是缓存的锅… 在地址栏按回车试试...

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/12215371/ec31a630-b6f4-11e5-9c14-cd35d976fdcb.png)
 有时候行有时候不行

**Comment by Ahrwing** [comment]
因为我只设置了p标签允许复制.. 你复制的文字里面还包含其他标签吗 /w\... 可以在那个页面呆一会儿存到自动保存里... 我看看~

**Comment by Meow-J** [comment]
好像可以了/w\

**Comment by Ahrwing** [comment]
/w\....

**Comment by Ahrwing** [comment]
/w\\........

**Comment by Meow-J** [comment]
![f](https://cloud.githubusercontent.com/assets/5229241/12215452/d90ad83a-b6f7-11e5-8d10-6d01d35430d9.gif)

**Comment by AstonIceDog** [comment]
<del>厉害</del>

**Comment by Ahrwing** [comment]
@Meow-J 这又是什么鬼 /w\

**Comment by Meow-J** [comment]
我只是点了底下那三个按钮文字就消失了

**Comment by Ahrwing** [comment]
好了~
