### ISSUE TITLE
消息中心滚动条定位偏差

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#140]
![image](https://cloud.githubusercontent.com/assets/5229241/12205135/be80e420-b673-11e5-99e6-2fd5e31feb75.png)
首次点击进入对话打开滚动条并不在底部

**Comment by Ahrwing** [comment]
这个在出论坛以后打算用论坛消息/提醒替换掉了.. /w\

**Comment by AstonIceDog** [comment]
消息中心根本没用好吗

**Comment by Ahrwing** [comment]
已经取消现在的消息中心了
