### ISSUE TITLE
主页大图小图切换不能快速自适应

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#143]
![image](https://cloud.githubusercontent.com/assets/5229241/12205616/c96f68b8-b676-11e5-9fa6-0ed160260c4f.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12205636/d85d6f0a-b676-11e5-8609-e642fd5dc7eb.png)
 不知道自适应更新激活条件是什么，不过反正不是及时更新啦/w\

**Comment by Ahrwing** [comment]
改好了.. /w\
