### ISSUE TITLE
默认用户头像不同步

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#144]
![image](https://cloud.githubusercontent.com/assets/5229241/12214311/3136d046-b6ca-11e5-831e-cb4180ac8d2a.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12214312/35d36dda-b6ca-11e5-82c2-4eda83c557eb.png)

**Comment by AstonIceDog** [comment]
2333

**Comment by Ahrwing** [comment]
修好了 /w\~~
