### ISSUE TITLE
默认用户头像为静态

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#145]
Identicon一般不都随IP变化的吗/w\

![image](https://cloud.githubusercontent.com/assets/5229241/12214326/a83e124e-b6ca-11e5-86bc-81c7959cfcb4.png)
其中有不同IP的回复
![image](https://cloud.githubusercontent.com/assets/5229241/12214917/9cd6d0fa-b6e1-11e5-9ba9-a404be13397c.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12214918/a5ae90e6-b6e1-11e5-8cf3-9d961485dfaf.png)

见：https://en.wikipedia.org/wiki/Identicon

**Comment by Ahrwing** [comment]
现在会变化了~~
