### ISSUE TITLE
物品分类存在冗余条目

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#147]
![image](https://cloud.githubusercontent.com/assets/5229241/12216702/01c86656-b726-11e5-80fc-d897bdf79f45.png)
某些分类已经没物品了仍然能在这里显示

**Comment by Ahrwing** [comment]
好了~ 现在只要一有物品被修改，就会自动清理多余的分类 /w\..

**Comment by Meow-J** [comment]
仍未修复  
http://www.mcmod.cn/item/add/1

**Comment by Ahrwing** [comment]
又是一个愚蠢的错误…… 已修复 _(:з」∠)_
