### ISSUE TITLE
审核资料类型错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#148]
![image](https://cloud.githubusercontent.com/assets/5229241/12254592/4e145d66-b925-11e5-9c92-ce82cae18ea4.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12254596/528b21f4-b925-11e5-9aaa-9749688f4613.png)

**Comment by Ahrwing** [comment]
在什么情况下发生的 /w\

**Comment by Meow-J** [comment]
不知道/w\，总之见到好多次了

就是生物资料改动之后显示是由物品改为生物的

**Comment by Ahrwing** [comment]
上回应该已经修复了..
