### ISSUE TITLE
物品更新算法 v2

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#150]
![9e6284d0-7f61-11e5-81a6-41d71a2d63e4](https://cloud.githubusercontent.com/assets/5229241/12327037/2fc4f276-bb0f-11e5-8e93-0010137f26a5.png)

防止出现物品重名现象(神秘的晶化源质等那一堆物品)

**Comment by 3TUSK** [comment]
晶化源质建议合并

**Comment by Ahrwing** [comment]
> 晶化源质建议合并
晶化源质不是已经合并了吗…………

**Comment by Ahrwing** [comment]
好像没有看太懂... 是

```php
if(new_EN == old_EN)
{

	if(new_CN == old_CN)
	{
		更新data
	}
	else
	{

		更新中文名
		更新data

	}

}
else
{
	
	if(new_CN == old_CN)
	{
		更新英文名
		更新data
	}
	else
	{

		if(!icon)
		{
			添加物品
		}

	}

}
```

这个意思咩..

话说... 现在如果批量添加物品，重名物品会先添加第一个，之后的重名物品都返回物品已存在...

**Comment by Meow-J** [comment]
是的

**Comment by Meow-J** [comment]
> 话说... 现在如果批量添加物品，重名物品会先添加第一个，之后的重名物品都返回物品已存在...

勾了更新不就变成只留最后一个了/w\

**Comment by Ahrwing** [comment]
噗.. 有道理... 机智的喵呜J...

**Comment by Meow-J** [comment]
晶化源质的物品图标怎么办，不同的晶化源质都有不同的图标(是不是可以有新功能了/w\

**Comment by 3TUSK** [comment]
（我的锅，但是自动导入的话万一破坏合并怎么破，还是说有特殊的handler）

**Comment by 3TUSK** [comment]
@Meow-J 于是可以参考一下ftb.gamepedia.com的一个奇葩特性了，让一个infobox有多个图标

**Comment by Meow-J** [comment]
不是合并，没有新加物品这个特性，导致导入的时候直接被最后一个覆盖了，也就是只添加了一个

**Comment by Meow-J** [comment]
是不是一个物品多个图标循环播放/w\

**Comment by Ahrwing** [comment]
> 是不是一个物品多个图标循环播放/w\ <- 这个好像挺不错

我也是这么想的... 但是如果物品很多.. 会不会不方便 (

**Comment by 3TUSK** [comment]
> 是不是一个物品多个图标循环播放/w\ <- 这个好像挺不错 
> 我也是这么想的... 但是如果物品很多.. 会不会不方便 (
这是写条目的人的锅，不是重生的

**Comment by 3TUSK** [comment]
@CannonFotter 还是叫一个专业的来吧。

**Comment by Ahrwing** [comment]
现已改为按regName与metadata匹配物品是否重复, 允许重名物品的存在~
