### ISSUE TITLE
API支持内容过时

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#151]
![image](https://cloud.githubusercontent.com/assets/5229241/12357204/891076f2-bbe1-11e5-8aca-fa4515b8fbc8.png)

目前很少会有mod会使用ModLoader和PlayerAPI了，更多的是作者自己的前置，所以这里最好加上自定义API并且删除那两个过时选项，并且可以考虑加入LiteLoader等常用的

**Comment by Ahrwing** [comment]
这里我有个好点子.. 不过得清空原有的API设置...

**Comment by Ahrwing** [comment]
就是把MOD本身可以当做一个API.. 然后API支持可以添加所有相关属于API的MOD....

**Comment by Ahrwing** [comment]
话说 coremod 和 api 是啥关系...

**Comment by Meow-J** [comment]
API可能是coremod，coremod不一定是API

**Comment by Meow-J** [comment]
总之没决定性关系/w\

**Comment by Ahrwing** [comment]
另一个方案：添加模组依赖系统，A MOD 没有 B MOD 的情况下无法启动，则 B MOD 是 A MOD 的依赖MOD，依赖MOD包括API或COREMOD，然后把现在的API选项改为当前模组类型，可以选择是MOD、CoreMod、API

**Comment by Meow-J** [comment]
依赖的全写mod就行了，不需要这样分

**Comment by Ahrwing** [comment]
资料：
类型 - 例:物品、多方块结构
分类 - 例:发电机、已移除

模组：
类型 - 例: CoreMod、API
分类 - 例:综合类

**Comment by Meow-J** [comment]
我该怎么解释coremod orz

**Comment by Ahrwing** [comment]
orz..

**Comment by Meow-J** [comment]
coremod其实已经不太分了，现在基本大一点的mod都要用这玩意，现在已经可以和正常的mod放在一起了

**Comment by 3TUSK** [comment]
CoreMod不就是那些带ASM的mod吗...比如，NEI和Fastcraft。
按照ftb.gamepedia.com的`{{Infobox mod}}`模版，它只是这么分的：
Required:

**Comment by Meow-J** [comment]
> 所以建议弄一个东西可以从mcmod百科站既有的mod中直接选取，作为依赖项。

这就是我想改的orz，不过现在选择一个新日志我都觉得很麻烦了，再新加一个mod会很大程度上提高编辑的复杂度。

> 还有一个奇怪的问题，如果以mod形式在Forge环境下加载LiteLoader，此时LiteLoader算什么？

不还是算一个mod loader+API，有什么问题吗/w\

**Comment by liach** [comment]
@3TUSK 这时候LiteLoader算一个[Tweaker](https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/ITweaker.java)。别告诉我你不知道Tweaker是什么还有怎么用Tweaker。

**Comment by 3TUSK** [comment]
@liach 然而并不想讨论深层的玩意，因为你告诉普通玩家这是一个Tweaker也并没有什么用。

**Comment by 3TUSK** [comment]
@Meow-J 这个修了吗

**Comment by Ahrwing** [comment]
老的API选项已经去掉了 现有模组关系系统完全可以替代 ww

**Comment by 3TUSK** [comment]
@Ahrwing 照这么一说总感觉有很多修了没关的issue...
