### ISSUE TITLE
搜索功能rank算法bug

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#152]
![image](https://cloud.githubusercontent.com/assets/5229241/12358234/29f91146-bbe7-11e5-9add-015b58b007b6.png)

搜索的是mod名称，真正的mod却排在第四个，其它的全是页面内的内容

**Comment by Meow-J** [comment]
并且截取的简介信息大部分都是从句子中间切断，截取算法也有问题。

这个东西想修可能会有点麻烦吧/w\

**Comment by Ahrwing** [comment]
这玩意儿自己写果然不靠谱... orz

**Comment by Ahrwing** [comment]
问题原因应该是内容中有图片，被去掉了代码，于是字符串空了一块…… 截取描红就看不到了……

**Comment by Meow-J** [comment]
不是这个问题，你看每个简洁的开头都是半句话，或者标点什么的

**Comment by Ahrwing** [comment]
因为要定位到描红的字段… 所以截取了一部分字符串... 但是忽略了被去掉的图片标签之类的东西…

**Comment by Ahrwing** [comment]
搜索已改版 / 撒花
