### ISSUE TITLE
模式的提示存在多余句子

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#153]
![image](https://cloud.githubusercontent.com/assets/5229241/12358908/92b8d632-bbea-11e5-8f09-b4e209ea716a.png)

没有LAN这个选项

**Comment by Ahrwing** [comment]
于是.. 去掉LAN 还是加个选项 /w\..

**Comment by Meow-J** [comment]
根本没有存在LAN的必要啊/w\

**Comment by Ahrwing** [comment]
妥了 /w\..
