### ISSUE TITLE
[讨论]用语与排版规范

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#154]
http://mcmod.readthedocs.org/zh/latest/editor/

主要是为了这个文档，这个规范肯定是要讨论决定的，暂时我还没思路分什么点写/w\

**Comment by Ahrwing** [comment]
油库里 /w\..

**Comment by Meow-J** [comment]
等我期末考完在说吧/w\，暂时没时间弄

**Comment by Ahrwing** [comment]
\ 干巴爹 //

**Comment by Meow-J** [comment]
我需要治疗下懒癌了orz

**Comment by Ahrwing** [comment]
一定是被我给传染了 /w\,,, 
还好是良性的……

**Comment by AstonIceDog** [comment]
表示看不了

**Comment by 3TUSK** [comment]
来给两个参考：
[Official FTB Wiki的Article Creation Guideline（ACG，条目创建方针）][ACG]
[Official FTB Wiki的Manual of Style（MOS，格式手册）][MOS]

[ACG]: http://ftb.gamepedia.com/Feed_The_Beast_Wiki:Article_creation_guideline
[MOS]: http://ftb.gamepedia.com/Feed_The_Beast_Wiki:Manual_of_Style

**Comment by Ahrwing** [comment]
http://bbs.mcmod.cn/forum.php?mod=viewthread&tid=646#lastpost
编辑规范草案 (
