### ISSUE TITLE
splash在一个背景图下看不清

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#155]
![image](https://cloud.githubusercontent.com/assets/5229241/12370990/35ef26e2-bc60-11e5-8556-ea3523d01540.png)

![image](https://cloud.githubusercontent.com/assets/5229241/12370994/4753b358-bc60-11e5-8f0f-df117a967fbf.png)
这个

**Comment by Ahrwing** [comment]
如果能找到更好的替代图片.. ftb的图就可以撤下来了..

**Comment by Ahrwing** [comment]
v3已解决
