### ISSUE TITLE
mod资料增加Addon板块

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#158]
方便找addon

**Comment by 3TUSK** [comment]
建议规范化Tag...根据Tag来分类mod。

**Comment by Ahrwing** [comment]
这个靠之前讨论的MOD依赖功能就可以了……

**Comment by Ahrwing** [comment]
不过另一个关于MOD类型的讨论不是说不分 mod api coremod 嘛…  那 mod addon 就这样分？

**Comment by 3TUSK** [comment]
所以我觉得还是规范下Tag比较好，按照不同的Tag来分类mod，但主页的那个分类（综合／世界生成／辅助）可以保持不变。

**Comment by Meow-J** [comment]
Tag为选定的几个，要添加Tag需要审核?

**Comment by 3TUSK** [comment]
Yep... Tag也要审核，然后把诸如“抖M科技”、"抖M传说"这样的Tag去掉，相似的Tag并入一个，然后为相同tag的mod建立一个新的页面来放...
（Don't ask me why: this is adapted from `Category` in Mediawiki）

**Comment by 3TUSK** [comment]
![image](https://cloud.githubusercontent.com/assets/9113033/12650252/150fa70e-c5b0-11e5-9ac3-e615f4425e24.png)
说起Tag，那个高达什么鬼

**Comment by 3TUSK** [comment]
或者这样吧...标签要审核，然后新开一个“关键字”，关键字无需审核，玩家来改。图片来源#65

**Comment by Meow-J** [comment]
我想的是关键字审核，之后添加的时候就顺带在mod条目审核里了

**Comment by mmt50** [comment]
在一些有addon的mod的页面里加一个“附属mod”的版块吧，方便顺藤摸瓜的寻找扩展mod

**Comment by Ahrwing** [comment]
已解决
