### ISSUE TITLE
请点击 "Issues" 进入意见反馈区

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#159]

**Comment by 3TUSK** [comment]
> 1.材质包、地图、皮肤 这三个板块准备怎么运作？是否需要授权声明？

CC协议的话可以只写CC协议，all rights reserved的需要出示授权。

> 2.各个板块的板规没有详细规定

照抄一个（雾）。

> 3.精品帖审核标准

建议找几个老油条（比如mcbbs的mod大区版主、mc工业2吧吧主@Glease ）来当顾问，详细讨论下。

几个问题：
1.百科杂谈 == 水版？
2.插件、软件资源、mod发布是否可以合并？如果可以，那么软件开发是否可以也一并合并？
3.你问我答和崩溃解答重复？或者你问我答和崩溃解答一并并入百科杂谈的子板块（再次@Glease）
4.“作品分享”是什么鬼？有视频教程没视频实况？

暂且想到这么多，~~~~
（^ThaumicTechTinker Urey.S.Knowledge，Mediawiki签名用多了）

**Comment by 3TUSK** [comment]
Ah, i18n!
One issue: Will this forum support i18n.

**Comment by Ahrwing** [comment]
> 1.百科杂谈 == 水版？
一些无法分类到其他任何板块的内容都可以在这里发
> 2.插件、软件资源、mod发布是否可以合并？如果可以，那么软件开发是否可以也一并合并？
插件和软件是两种东西… 貌似没有mod发布板块，是否需要？（如果需要，可以每个MOD自动生成一个板块，可供发布/讨论，但是缺点是讨论容易分散）。软件开发待定，专门讨论mod制作的地方，还需要一个MOD开发教程（又是大坑，一步一步来吧）
> 3.你问我答和崩溃解答重复？或者你问我答和崩溃解答一并并入百科杂谈的子板块（再次@Glease）
这个可以有...
> 4.“作品分享”是什么鬼？有视频教程没视频
作品分享的话…… 好像真的有点多余了…… 试试改成其他主题...?
视频教程可以改成“视频专区” 然后再分教程/实况 好了...

另：意见反馈板会直接跳到github

**Comment by Ahrwing** [comment]
在每个技术讨论板块加一个作品分享的分类，然后去掉作品分享板块，怎么样？

**Comment by Ahrwing** [comment]
> Ah, i18n!
> One issue: Will this forum support i18n.

这个具体还没想好 /w\... 
还有上次讨论的那个国际化语言文件导入也要一起做……

**Comment by 3TUSK** [comment]
> 插件和软件是两种东西… 貌似没有mod发布板块，是否需要？

不建议要插件版。Mod发布版...建议专门为mod开一个版，下设mod讨论和mod开发，其中mod开发兼职mod发布的作用，这样即便是测试版的mod也可以在此发布进行公开测试。

> 在每个技术讨论板块加一个作品分享的分类，然后去掉作品分享板块，怎么样？

能分享的作品：地图，视频教程，视频实况，mod发布，resourcepack发布，没了？mod发布并到mod开发，然后剩下的都可以单开一版。

> 这个具体还没想好 /w\... 

i18n不着急。

**Comment by Meow-J** [comment]
要不要发布直接改成指路版吧，防止协议什么的出问题

**Comment by 3TUSK** [comment]
指路版也可……只允许原地址。

**Comment by bakaxyf** [comment]
开个modpack版怎么样

**Comment by 3TUSK** [comment]
@bakaxyf 我要mcmod百科专属启动器（喷）

**Comment by Ahrwing** [comment]
@bakaxyf 这个已经计划在主站中做了

**Comment by Ahrwing** [comment]
@3TUSK capp启动器是用百科账号登陆的.. 算么..

**Comment by 3TUSK** [comment]
Ah, 我的想法是一个可以一键下载安装整合的启动器...

**Comment by Ahrwing** [comment]
@3TUSK 要做盗版资源吗…

**Comment by 3TUSK** [comment]
@Ahrwing 绝不容忍盗版资源。= =

**Comment by Ahrwing** [comment]
@3TUSK 所以说.. 目前来讲不好做..  
真要做的话.. 百科需要提前招募一支搬运团队去和作者侃大山..

**Comment by 3TUSK** [comment]
.....没事，还是有很多mod使用GPL和MIT的。（论ATLauncher）@Ahrwing

**Comment by Meow-J** [comment]
一个一个找作者估计不太可能啦，不过curse上的东西应该能调用

**Comment by Ahrwing** [comment]
@Meow-J 行，在这之前还需要做两步：

1.增加MOD依赖系统 (在做了)，并且完善MOD依赖项。
2.增加modpack专区。

**Comment by Meow-J** [comment]
话说这个让我突然想起来之前看到的[这个](https://modlister.com/user/madjake45)，不过这个里面的内容都是从mod里读取的

p.s. 好像可以做一个整mod导入功能/w\

**Comment by AstonIceDog** [comment]
吐槽一下，我们这是准备取代MCBBS了吗。。。。2333

**Comment by 3TUSK** [comment]
what?

**Comment by AstonIceDog** [comment]
WTF
