### ISSUE TITLE
版本管理系统

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#161]
一直以为已经在issue里了，翻了一下发现没有

总之就是需要一个像Git这样的版本管理系统啦

**Comment by Ahrwing** [comment]
想过哦~ 还可以对每个版本对比前一个版本，开放用户评分，从而计算编辑质量~~

**Comment by Meow-J** [comment]
当然想过/w\，之前还讨论过来着

**Comment by AstonIceDog** [comment]
你是指什么版本？是指MOD版本还是编辑的版本？

**Comment by Meow-J** [comment]
编辑的版本啦

**Comment by 3TUSK** [comment]
#24 翻了一下突然意识到还有这个

**Comment by LasmGratel** [comment]
我觉得应该模仿Wikipedia的做法，有若干版本，可以回退到某个版本或全部回退。
如果类似Git的话，你觉得**一个页面可能有多分支吗**？所以应该效仿的是一些**百科网站**，毕竟你们也在做一个百科网站。根据他们的**页面版本管理办法**，加以**自己的修改**，小范围**_实践_**，岂不是更好？

**Comment by 3TUSK** [comment]
@LasmGratel 一个页面多个分支——>mcmod百科专属沙盒

**Comment by Meow-J** [comment]
对一个百科来说分支好像作用不大

**Comment by Ahrwing** [comment]
貌似你们都忽略了这个……
![](http://7xo6vj.com1.z0.glb.clouddn.com/16-3-6/74948104.jpg)

![](http://7xo6vj.com1.z0.glb.clouddn.com/16-3-6/45653232.jpg)

![](http://7xo6vj.com1.z0.glb.clouddn.com/16-3-6/49481915.jpg)

**Comment by Ahrwing** [comment]
已添加版本记录 (教程区试行)

**Comment by Ahrwing** [comment]
版本记录系统已正式上线至 模组/物品/教程 区了 新的问题：#385

**Comment by 3TUSK** [comment]
自己实现的？
