### ISSUE TITLE
楼层显示问题

### ISSUE THREAD

**Issue by G-quardruplex** [Ahrwing/mcmod#164]
![nadmhtcenu9s9g llkz5a4h](https://cloud.githubusercontent.com/assets/16934954/12695724/1adb10a4-c792-11e5-99b7-9c722ed89aee.png)
↓
![qq 20160130204309](https://cloud.githubusercontent.com/assets/16934954/12695725/1d3f5102-c792-11e5-8d2e-799046473bcb.jpg)

感觉能自动重新排列会比较好

**Comment by Meow-J** [comment]
没看出来问题0 0

**Comment by G-quardruplex** [comment]
比如删掉1楼后, 原来的2楼能自动变成1楼, 希望有这样的功能~

**Comment by Meow-J** [comment]
这不就看不出来哪被爆破了/w\

**Comment by G-quardruplex** [comment]
知道哪被爆破了也没什么帮助/w\ 而且像这样和谐一波后评论区就满身疮痍了/w\

**Comment by AstonIceDog** [comment]
这个功能不实际吧，强迫症才要这样吧

**Comment by Ahrwing** [comment]
其实…… 以前就是你希望的那样…… 后来又故意改成这样了…… Orz....

**Comment by G-quardruplex** [comment]
....
那这当我没说
