### ISSUE TITLE
编辑器中添加常用图标

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#165]
![icons](https://cloud.githubusercontent.com/assets/5229241/12700633/afe55cfc-c825-11e5-9282-bfa01deb2ced.png)
上面那几个，看了EULA只要非商业用途就能用

**Comment by AstonIceDog** [comment]
哦，你是准备让这些变成表情吗

**Comment by AstonIceDog** [comment]
话说你是在哪个文件夹里面找到的？

**Comment by Meow-J** [comment]
不是啊，现在写伤害写添加的饱食度还有装备的效果全部都用的文字，可能会有歧义

**Comment by AstonIceDog** [comment]
赞同，填食物的时候饱食度直接可以输数字了是这意思吧

**Comment by bakaxyf** [comment]
applecore显示的那个呢

**Comment by AstonIceDog** [comment]
![image](https://cloud.githubusercontent.com/assets/13271372/12719142/4d0b3e44-c92e-11e5-9e84-6a5b80e1df3e.png)
@bakaxyf 差不多就是这意思啊

**Comment by bakaxyf** [comment]
en

**Comment by Ahrwing** [comment]
已加~

**Comment by 3TUSK** [comment]
@Ahrwing Close?

**Comment by Ahrwing** [comment]
@3TUSK 忘了 /w\..

**Comment by Meow-J** [comment]
我说的是资料编辑器里的啦/w\

**Comment by Ahrwing** [comment]
资料编辑器里的有啊 0 0. 在表情里

**Comment by Meow-J** [comment]
还是没看到/w\

**Comment by AstonIceDog** [comment]
表示哪里有表情？

**Comment by Ahrwing** [comment]
![10](https://user-images.githubusercontent.com/5197567/34032326-87fe2b00-e1b0-11e7-8408-bc4f73453fc0.png)
