### ISSUE TITLE
关于物品添加的建议

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#167]
1.物品列表显示未完成合成表的物品，类似于未完成的介绍是红色![image](https://cloud.githubusercontent.com/assets/13271372/12709382/5ee6c180-c8e6-11e5-8d71-1f809d8040bd.png)的，没有合成表的可以黄色
2.不知道能不能批量添加物品时把图标也一起添加了

**Comment by Ahrwing** [comment]
json批量添加时是可以添加图标的

**Comment by AstonIceDog** [comment]
那是什么鬼，表示不了解啊

**Comment by Meow-J** [comment]
@AstonIceDog http://mcmod.readthedocs.org/zh/latest/itemrender/#_4

**Comment by AstonIceDog** [comment]
|||||这种网页从来没有打开过
![image](https://cloud.githubusercontent.com/assets/13271372/12719320/447144da-c92f-11e5-9453-11061875cd8c.png)

**Comment by AstonIceDog** [comment]
那么第一个特性可以吗

**Comment by Ahrwing** [comment]
那如果有些物品不是通过合成获得的呢… （例如魔导手册
或者是生存模式下无法获得的物品，也没有合成表...
AHHHH... 让我想想变成黄色文字的基岩...

**Comment by AstonIceDog** [comment]
不要在意这些好吗 ，如果没有合成表可以直接点没有合成表，然后就恢复原来的颜色啦

**Comment by Ahrwing** [comment]
那么有多少人会在意没有合成表这个按钮，弄得花花绿绿的只会增加复杂度...

**Comment by G-quardruplex** [comment]
魔导手册也可以做个获取途径可视化/w\

**Comment by AstonIceDog** [comment]
。。。有没有合成表主要是方便编辑员，不然要一个一个翻，看有没有漏添加合成表

**Comment by Ahrwing** [comment]
用其他方式标明无合成表也行，但最好不要用颜色。。。

**Comment by 3TUSK** [comment]
没有必要特别注明没有合成啊...
@G-quardruplex Mystical Structure那个效果...ftb.gamepedia有一个`{{Multiblock}}`的Template可以实现这个效果...不过特别看起来特别奇葩...
