### ISSUE TITLE
输入框自动跳到行尾

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#168]
只要光标一动就会自动跳到最后
![qq 20160201231154](https://cloud.githubusercontent.com/assets/5229241/12721142/361b2608-c939-11e5-8c29-fd5dbeeda7eb.gif)
![qq 20160201231144](https://cloud.githubusercontent.com/assets/5229241/12721143/3621b27a-c939-11e5-9a98-5d1b2a9f8ac0.gif)

**Comment by Ahrwing** [comment]
已修复~ ww 其实是上回自动去除空格功能造成的bug... (
