### ISSUE TITLE
评论区某些回复无法赞同或反对

### ISSUE THREAD

**Issue by G-quardruplex** [Ahrwing/mcmod#170]
![qq 20160203141626](https://cloud.githubusercontent.com/assets/16934954/12777888/8722bd1a-ca9a-11e5-8f0f-e1d91692c537.jpg)
一个小bug/w\ 像这样, 显示"不能顶自己"

**Comment by AstonIceDog** [comment]
本来就不能顶！d=====(￣▽￣*)b自己啊

**Comment by Meow-J** [comment]
那个不是自己

**Comment by Ahrwing** [comment]
我检查检查~

**Comment by Ahrwing** [comment]
暂时没发现问题原因…… 
我的验证是用户名和IP任意一项一样就不能投票……

**Comment by Ahrwing** [comment]
但是两条评论的IP从数据库里来看，并不一样……

**Comment by Ahrwing** [comment]
@G-quardruplex 我开了debug /w\.. 乃再去那个页面看下~ 然后截图给我吧..

**Comment by Ahrwing** [comment]
基本可以确定是IP获取的问题…………

**Comment by 3TUSK** [comment]
只检查是不是自己不就好了。id est, check if the username(s) are the same.

**Comment by Ahrwing** [comment]
@3TUSK 你有考虑过未注册用户的感受吗…… 
还有未注册发短评，又注册个号来顶自己的……

**Comment by 3TUSK** [comment]
没有。~~本来就不应该让未注册用户发言...~~似乎哪里不对...
Ah, 对于注册用户检查username，对于未注册用户检查IP，完

**Comment by AstonIceDog** [comment]
那就让游客不能顶任何人也不可以让任何人顶

**Comment by Ahrwing** [comment]
@3TUSK 刚才差点改成这样了…… 
转念一想，如果他退出登陆，不就可以顶自己了吗 = =..

**Comment by 3TUSK** [comment]
ahhhhhhhhhhhhhhhhhhh真是麻烦至极.............................

**Comment by Ahrwing** [comment]
@3TUSK 所以说~ 最佳的解决方案可能是~~

1.改成更精确IP获取的方式~
2.允许顶自己~

**Comment by Meow-J** [comment]
3. 不允许游客顶人

**Comment by 3TUSK** [comment]
0.不允许游客顶人，但可以匿名回复

**Comment by AstonIceDog** [comment]
就让游客只能留言，不能顶自己，也不能被别人顶

**Comment by Ahrwing** [comment]
已改为：游客不能顶踩，但是登陆用户可以顶游客，登陆后发表的自己也不能顶自己~
