### ISSUE TITLE
希望添加图片批量导入功能

### ISSUE THREAD

**Issue by a342617810** [Ahrwing/mcmod#171]
一个一个的加图好蛋疼，关键是我访问百科很卡
2个设想
1、统一使用nei导出图片的名字，进行mod图片批量上传之后的自动匹配
2、单纯的批量上传也可以，传完给一个缓存页面，进行手工的图片匹配，然后一次性提交

**Comment by Meow-J** [comment]
已有http://mcmod.readthedocs.org/zh/latest/itemrender/#_4
