### ISSUE TITLE
选择模组的时候未填写英文名的模组仍显示括号

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#172]
![image](https://cloud.githubusercontent.com/assets/5229241/12775422/e092e6a2-ca88-11e5-82de-abd29377e481.png)

**Comment by Meow-J** [comment]
这个是json导入里的啦

**Comment by Ahrwing** [comment]
baka..

**Comment by Ahrwing** [comment]
应该没问题了
