### ISSUE TITLE
合成表列出物品存在已删除或非物品资料

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#174]
![image](https://cloud.githubusercontent.com/assets/5229241/12781304/834513e6-caae-11e5-8c23-fed6b27d2a04.png)
这几个都是

**Comment by Ahrwing** [comment]
已修复 （未检查）

**Comment by Meow-J** [comment]
已删除的不显示了，其他类别的还有

**Comment by Ahrwing** [comment]
确认已解决
