### ISSUE TITLE
合成表版本支持改进

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#176]
![image](https://cloud.githubusercontent.com/assets/5229241/12783422/7a705b64-cabc-11e5-8757-df4412864aa9.png)
目前只能选择添加时的版本

![image](https://cloud.githubusercontent.com/assets/5229241/12783460/b5d3bfde-cabc-11e5-8f7c-97d55dacfbe5.png)
这样的不就显示不了了吗/w\

所以应该分为添加版本和移除版本的/w\

**Comment by Ahrwing** [comment]
quq 没看懂…… (蹲墙角哭

**Comment by 3TUSK** [comment]
> Meow-J：我们看不到旧版合成
> 重生：what

**Comment by Ahrwing** [comment]
soga... 物品在MOD中添加时的版本咩…… 我理解成在百科添加时的版本了 / w \\..

**Comment by Ahrwing** [comment]
已增加选项： 开始版本、移除版本

移除“版本支持”选项
