### ISSUE TITLE
合成表点击消除选中之后会把带颜色的点一起消除

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#177]
![image](https://cloud.githubusercontent.com/assets/5229241/12783623/9e3665ba-cabd-11e5-9114-cb4743e5b0b2.png)

**Comment by Ahrwing** [comment]
介个.. 记得当初不知道怎么改.. 于是就暂时放着了.. 我现在再看看吧 0 0..

**Comment by Meow-J** [comment]
点击消除选中 -> 放置对应的点

**Comment by Ahrwing** [comment]
主要那个点是背景图片…… /w\...

**Comment by Ahrwing** [comment]
已确认解决！ 机智的我~~ >w<
