### ISSUE TITLE
合成表无法正确显示非oredict物品配方

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#178]
![image](https://cloud.githubusercontent.com/assets/5229241/12818557/58f26942-cb92-11e5-86ff-ff6310b7cc34.png)
这里合成时候必须要是橡木木板，加一个启用oredict选项就行了

**Comment by Ahrwing** [comment]
已增加合成表添加/编辑时是否允许使用矿物词典~ （顺便修了一下合成表相关的其他问题
