### ISSUE TITLE
Ahhhhhhhhhhhh.. 编辑员的一件非常纠结的事情

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#179]
就是关于 实习编辑员、分区编辑员、正式编辑员 之间的关系问题...

“实习编辑员” 到底是一个用户组 还是一个前缀呢？

like: 

       实习编辑员  晋升>  正式编辑员
       分区编辑员  不能晋升

or 

       实习编辑员  晋升>  正式编辑员
       实习分区编辑员  晋升>  正式编辑员

**Comment by 3TUSK** [comment]
从来没听说过分区编辑.....什么时候有的...

**Comment by Ahrwing** [comment]
@3TUSK 不是计划中加的咩... 上回还在主群里发了投票了来着……

**Comment by 3TUSK** [comment]
已屏蔽主群...disgusted...

**Comment by Ahrwing** [comment]
我在想，要不就暂时不用考虑分区编辑员这个身份了...

**Comment by 3TUSK** [comment]
看上去分区编辑员就是能编辑某个分区的样子？

**Comment by Ahrwing** [comment]
是的..  只能免审核编辑某个分区内的条目（包括资料、模组日志、公共教程等）

**Comment by 3TUSK** [comment]
如果是这样的话，实习->分区->正式

**Comment by Ahrwing** [comment]
问题是现在的实习编辑员能免审核所有.. (吐血
实习编辑员和正式编辑员的区别就是能不能进入后台了……

**Comment by 3TUSK** [comment]
实习编辑员：编辑+强制审核
分区编辑员：编辑+部分强制审核
正式：编辑+大部分免审核+批量编辑工具
“黑幕”：编辑+完全免审核+批量编辑工具+完全后台
^
我的构想

**Comment by Ahrwing** [comment]
那实习编辑员和普通用户的区别就是有没有验证码 对吗

**Comment by Ahrwing** [comment]
我觉得实习编辑员应该也开放部分后台功能…

**Comment by 3TUSK** [comment]
To be specific:

用户组 | 强制审核 | 批量编辑 | 验证码
------------- | ------------- | ------------- | -------------
未登录 | 是 | 否 | 是
普通|是|否|是
实习|是|否|否
分区|是|部分|否
正式|是|大部分|否

好像哪里不对。

**Comment by Meow-J** [comment]
0 0这两个感觉少了哪个都不好

**Comment by Meow-J** [comment]
不过实际情况来讲的话分区编辑员比较常用，而实习的会鸡肋一点。既然都要编辑员了，用户需求的是效率，而很少会有人分散式编辑来获取效率的吧。给了实习编辑员反而增大了出事的可能。

**Comment by Meow-J** [comment]
仅仅为了零散编辑而申请编辑员这给的权限就太大了。

关于用户组晋级，可以在分区编辑员挑选优秀的进阶为正式编辑员

**Comment by Ahrwing** [comment]
人工晋级咩~ 或者可以主动申请再评估?

我之前写了一个自动晋级方案来着…
![晋级方案](http://i13.tietuku.com/60284c681bf50cf5.png)

**Comment by Meow-J** [comment]
主动申请吧，另外这需求的总编辑数量也太高了/w\

**Comment by 3TUSK** [comment]
主动申请+1

**Comment by xingyunE** [comment]
主动申请+2

**Comment by AstonIceDog** [comment]
主动申请+3，不过@3TUSK提议的正式编辑员权限是不是有点低，正式编辑员建议大部分不要审核

**Comment by 3TUSK** [comment]
好了新的问题出现了，编辑质量又是人为评定的吧？标准是什么？

**Comment by AstonIceDog** [comment]
你觉得怎样的是好的

**Comment by AstonIceDog** [comment]
我认为要自己要求加精然后审核员自己决定

**Comment by Ahrwing** [comment]
编辑质量说了多少次... 是在历史版本对比里让用户打分的....

**Comment by AstonIceDog** [comment]
好吧，话说最近的资深编辑员是什么鬼
