### ISSUE TITLE
Mod缩略图裁剪功能(而不是拉伸)

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#18]
![qq 20150811183646](https://cloud.githubusercontent.com/assets/5229241/9195755/f100a620-4057-11e5-95a7-2ef8fa070f18.png)
强迫症系列

**Comment by Ahrwing** [comment]
首页打算改版来着 _(:з」∠)_ 但还没有详细的规划..

**Comment by Ahrwing** [comment]
已解决
