### ISSUE TITLE
合成表成品被隙间啦！！！

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#181]
![image](https://cloud.githubusercontent.com/assets/5229241/12848348/4a19f95e-cc54-11e5-83df-c256040432f8.png)
编辑的时候/w\

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/12848396/9d46e0d8-cc54-11e5-9dac-367e2b993c08.png)
还有这下面多了一横杠

**Comment by Ahrwing** [comment]
不只有成品才会出现... 所有用了base64的都会出问题.. 正在检查~

**Comment by Ahrwing** [comment]
那个横杠 =  = !! 
其实是没有备注时输出的内容…… 之前没想到那里除了备注还会放那么多东西.... 后来一直没去掉来着…

**Comment by Ahrwing** [comment]
已修复~ 横线等我把新功能弄好上传以后 也会消失
