### ISSUE TITLE
显示各mod上传者及mod资料上传者

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#182]
这样应该可以促进填坑的积极性（才怪）吧……

**Comment by Ahrwing** [comment]
现在就有显示啊.. 在左边边栏...
红框的就是添加者(没有其他编辑者时不会显示红框)
不过如果条目编辑的人多，添加者会被挤到后面去隐藏掉..

**Comment by elctove** [comment]
那个红框存在感太低了吧喂……

**Comment by Ahrwing** [comment]
难道要在创建者头顶上加一个皇冠，再加一个纯金相框，然后加上绚丽的特效，最后放几个大箭头，写明是他捷足先登，第一个创立的此条目吗.. QwQ..

**Comment by elctove** [comment]
有一行小字就行了吧……
（至少比红框存在感高……

**Comment by Ahrwing** [comment]
是要显示一行小字 例如 -> 该条目由XXX创建 吗？

我觉得这样不好……

**Comment by 3TUSK** [comment]
@elctove 你可是想要一个类似MediaWiki的历史记录的功能？

**Comment by AstonIceDog** [comment]
感觉现在就挺好的呀

**Comment by Meow-J** [comment]
感觉还是红框最简洁/w\

**Comment by elctove** [comment]
讲道理红框毫无存在感……
或者我们可以加一个介绍页面来介绍这些毫无存在感的特性……

**Comment by AstonIceDog** [comment]
。

**Comment by Ahrwing** [comment]
_(:з」∠)_ 保留现在的样式就好了 没必要把挖坑者的贡献放大化吧.. 教程里如果是私人教程的话 是会在很显眼的地方显示名字的
