### ISSUE TITLE
对文件的存在性进行验证并隐藏PHP报错信息

### ISSUE THREAD

**Issue by CannonFotter** [Ahrwing/mcmod#183]
![2016 2 7 212650](https://cloud.githubusercontent.com/assets/11025035/12872585/e7b9abee-cde1-11e5-92e7-3d05b939f567.PNG)
在随意输入小图标的内容后，正常提交会导致报错，且报错信息直接输出

![2016-02-07213235](https://cloud.githubusercontent.com/assets/11025035/12872646/b99829d8-cde2-11e5-9ac9-422f60bd3400.PNG)
看来是没对文件是否存在进行判断啊= =
~~P.S.过年上线新功能可是加班修bug的节奏~~

Edit:
建议强制限制15字，而不是为最佳

**Comment by 3TUSK** [comment]
@CannonFotter 快去帮重生写代码（雾）

**Comment by Ahrwing** [comment]
已修复~
