### ISSUE TITLE
成就生成器物品存在背景

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#184]
![image](https://cloud.githubusercontent.com/assets/5229241/12873187/008da5f2-cdf2-11e5-9b8f-3fa742b693bc.png)
base64里面记得没有背景的样子

**Comment by 3TUSK** [comment]
是时候使用NEI了，NEI导出的图标并没有背景（NEI大法好，笑）

**Comment by Meow-J** [comment]
这个不是导出时候的问题，物品本身的图标是透明的，只是在这里重生给带上了

**Comment by 3TUSK** [comment]
好吧...

**Comment by AstonIceDog** [comment]
![qq 20140821174900](https://cloud.githubusercontent.com/assets/13271372/12916661/15ce3688-cf6f-11e5-98c6-4d3bcd10bc27.jpg)

**Comment by elctove** [comment]
@AstonIceDog 喂这不是重点吧

**Comment by AstonIceDog** [comment]
2333

**Comment by Ahrwing** [comment]
已修复~
