### ISSUE TITLE
楼层数重复显示

### ISSUE THREAD

**Issue by enzchiroptera** [Ahrwing/mcmod#185]
![qq 20160212211210](https://cloud.githubusercontent.com/assets/16934954/13007770/695570d6-d1cd-11e5-8f6d-1e2938ab5352.jpg)

小问题,查一下原因吧/w\

**Comment by Ahrwing** [comment]
这不科学……………… 哪个短评里的 0A0

**Comment by enzchiroptera** [comment]
www.mcmod.cn/item/251.html

**Comment by Ahrwing** [comment]
修好了... 系统木有问题.. 应该是很久远的评论在楼层改版校对时出的问题...
