### ISSUE TITLE
关于个人中心的建议

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#187]
建议1.个人中心增加一个板块：创建的MOD编辑（大概就是这个意思，取名不会取），这可以和红框呼应啊，显示自己创建的MOD介绍。
建议2.个人中心增加一个板块：喜欢的MOD（让访客知道你的取♂向）。也可以让自己知道自己的爱过

**Comment by Meow-J** [comment]
0 0如果加的话记得加一个开关控制

**Comment by Ahrwing** [comment]
0 0

**Comment by AstonIceDog** [comment]
什么开关控制？

**Comment by 3TUSK** [comment]
@AstonIceDog 对外人可见不可见。

**Comment by AstonIceDog** [comment]
哦，可以

**Comment by AstonIceDog** [comment]
建议2个人觉得不用了
