### ISSUE TITLE
导航条最右边按钮提示错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#188]
![image](https://cloud.githubusercontent.com/assets/5229241/13042161/e0f82f66-d3f8-11e5-8ad4-0f80f3ebd871.png)
应该改成回到顶部吧/w\

**Comment by Ahrwing** [comment]
这个不是返回顶部..... 提醒系统现在还没弄好.... 临时改成了# 所以会自动跑到顶部去 /w\\........

**Comment by AstonIceDog** [comment]
返回顶部不是右边那个<delete>楚楚动人的大眼睛<delete》妹子吗

**Comment by Ahrwing** [comment]
... /w\
