### ISSUE TITLE
前端引用了不存在的js

### ISSUE THREAD

**Issue by CannonFotter** [Ahrwing/mcmod#189]
![22](https://cloud.githubusercontent.com/assets/11025035/13048593/ed71a88e-d421-11e5-95b4-4958c5c992fe.PNG)
看上去，这个位置的ZeroClipboard并不存在.....

**Comment by Ahrwing** [comment]
待我升级UEditor...

**Comment by Ahrwing** [comment]
新版UE用的是统一接口，目录结构也不一样...
所以整合相册/牛排等功能会粗问题.. (待解决)

**Comment by Meow-J** [comment]
好像还能用

**Comment by CannonFotter** [comment]
缺了zeroclipboard就是ueditor在某些浏览器的复制功能会受到影响...(maybe)
