### ISSUE TITLE
编辑Markdown支持(或者选项)

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#19]
现在的编辑器非常卡，并且需要鼠标操作太多了

找到几个工程，不知道行不行:
- https://github.com/SegmentFault/HyperDown (这个刚出来)
- http://epiceditor.com/ (https://github.com/OscarGodson/EpicEditor)
- http://vuejs.org/examples/ (https://github.com/yyx990803/vue)
- http://lab.lepture.com/editor/ (https://github.com/lepture/editor)

**Comment by Meow-J** [comment]
半个小时前刚出了个新的Parser，看起来还不错，不过没编辑器。https://github.com/SegmentFault/HyperDown

**Comment by 3TUSK** [comment]
How about adding some mcmod.cn-flavored MarkDown syntax, just like GitHub?
E.g.
1.@bakaxyf (Reference to certain people, mod page entry, tutorial, et cetera; also, please consider about support markdown in comment)
2.Simple way to create a form

Option: How about supporting HTML itself...

**Comment by Meow-J** [comment]
@3TUSK @Ahrwing  @提及功能还没实现，表格功能基本只要不是标准Markdown基本都会有支持的。另外Markdown本身也应该支持HTML标签(不过很坑爹GFM没有)<font=red>测试一下</font>

**Comment by Ahrwing** [comment]
对比一下的话…… 四种哪个最推荐捏...

**Comment by Meow-J** [comment]
其实哪个都无所谓，只要有个parser就行了，编辑就算是最简单的文本框都行/w\

**Comment by 3TUSK** [comment]
没仔细看四个编辑器，但是我觉得哪个对用户最友好就用哪个..

**Comment by Ahrwing** [comment]
我觉得http://lab.lepture.com/editor/不错

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/12724349/8092da3c-c948-11e5-9f01-1659608dfadb.png)
好像有误报格式错误

**Comment by 3TUSK** [comment]
要不要弄一个[里程碑][Milestone]来庆祝一下mcmod百科全面使用Markdown呢？

[Milestone]: https://github.com/Ahrwing/mcmod/milestones

**Comment by Ahrwing** [comment]
cool! 顺便也把历史加上吧：

2012/11/28 百科计划开始
2013/4/27 百科建立百科群 我要加群
2013/5/17 百科首次公开宣传 查看宣传贴
2013/7/29 百科由老域名 mcbbc.com 更换为新域名 mcmod.cn
2013/12/26 - 2014/03/28 百科系统大改，保留原始数据
2014/3/29 新百科群内测试
2014/4/1 新百科公开宣传 查看宣传帖

**Comment by Ahrwing** [comment]
@Meow-J orz.. 那还是谨慎选择好了..

**Comment by Meow-J** [comment]
你可以把我文档里的那堆md文件放进去进行测试

**Comment by Meow-J** [comment]
好像也就最后一个功能最全了/w\

**Comment by Ahrwing** [comment]
已添加markdown编辑器~

**Comment by 3TUSK** [comment]
欢呼！！！！！！！！！！！！！！！！！！！！！！！
@bakaxyf
