### ISSUE TITLE
mcmod百科条目内部链接

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#190]
怎么说呢...看下[这个条目](http://www.mcmod.cn/class/448.html)吧：
![image](https://cloud.githubusercontent.com/assets/9113033/13066157/5873273e-d431-11e5-8046-69dc32452247.png)
我想让这些mod名全部链接到百科的对应条目，但是一个一个手动复制粘贴地址实在太恶心了。
然后我想起了在编辑Official FTB Wiki时用的内链模板...
就是这样，内链/快速链接添加（仅针对百科内页面）。

**Comment by 3TUSK** [comment]
暂时先这样加标签好了= =

**Comment by Meow-J** [comment]
有的，点编辑器上面那个牛排就行了

**Comment by 3TUSK** [comment]
原来牛排是这个………我火星了。
