### ISSUE TITLE
牛排不识别特殊符号

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#191]
![image](https://cloud.githubusercontent.com/assets/5229241/13066821/c1704d34-d4a4-11e5-85fd-6d1316872ff3.png)
 比如说这个，带个'就匹配不了了

**Comment by 3TUSK** [comment]
那就暂时去掉'，Tinkers Construct也是允许的

**Comment by Ahrwing** [comment]
修复惹~
