### ISSUE TITLE
如何简单地查看所有模组或所有教程？

### ISSUE THREAD

**Issue by GWYOG** [Ahrwing/mcmod#192]
RT，平常不怎么逛百科站，今天来看看时发现完全不会玩了.....有没有办法不一个分区一个分区地查看模组，而是按照全部模组的排名一页一页地查看所有模组？
此外，如何查看百科站的全部教程？因为有些教程只有百科站有，所以我很想逛逛，但是发现完全无法逛的起来.......(即使像贴吧精品区那样也好)
总之，感觉百科站的”查询“系统有待改进.......

**Comment by enzchiroptera** [comment]
建议完善 升级百科检索系统+1

**Comment by AstonIceDog** [comment]
那么可以建立一个教程区。还有你提出的模组排名，应该按什么指标排名？
还有查询系统确实有些许缺陷，感觉查不到多少有用的东西。

**Comment by GWYOG** [comment]
排名可以有很多方式啊，比如模组可以按照人气来排名，教程可以按照发布时间来排名

**Comment by Meow-J** [comment]
目前百科基本排名，历史，还有列表普通用户都看不全，一些只有编辑员能看的资料列表还不能排序(教程后台也没有列表)。搜索功能还不完善，rank算法应该是没有/w\。

所以现在的问题是：
1. 检索能力微弱
2. 有特殊排名算法无法进行分析
3. 资料列表封闭(全都连续的id这个应该很快，现在更需要的是mod列表)
4. 目前的排序用处不大(综合往往并不能找到想要的mod，这个是一个百科网站不是一个作品展示网站；发布时间和编辑时间普通用户往往用不上；所以需要试试把综合排名里的东西全部分开进行排序)

**Comment by AstonIceDog** [comment]
毕竟MCMOD站是供人查询的，查询系统要弄好，让人能方便查到自己的MOD。

**Comment by 3TUSK** [comment]
key words, key words, key words...

**Comment by Ahrwing** [comment]
新增两个页面：
MOD列表：http://www.mcmod.cn/modlist
教程列表：http://www.mcmod.cn/courselist

只是测试版，筛选/排序等更多功能正在完善...

**Comment by 3TUSK** [comment]
这玩意的默认排序是？

**Comment by Ahrwing** [comment]
最后被顶的时间

**Comment by Ahrwing** [comment]
睡觉去了.. 明天还要早起..烫烫烫烫烫烫烫烫 棍斤

**Comment by Meow-J** [comment]
左侧那个热门去掉吧，太难看了，用排序功能来代替

**Comment by Meow-J** [comment]
另外
![image](https://cloud.githubusercontent.com/assets/5229241/13119304/6aca175e-d5e3-11e5-8d28-44ed62d7e769.png)
![image](https://cloud.githubusercontent.com/assets/5229241/13119306/6e455d76-d5e3-11e5-849a-39210144d7ce.png)

**Comment by Ahrwing** [comment]
筛选排序准备放上面的 /w\ 左边可以加一个隐藏.. 

话说 http://www.mcmod.cn/modlist?name=3 可以只看英文名

**Comment by Meow-J** [comment]
不是这个问题，关键是有了权重排序之后也用不到左边的这个/w\

**Comment by 3TUSK** [comment]
![screen shot 2016-02-17 at 1 19 52 pm](https://cloud.githubusercontent.com/assets/9113033/13119867/30f65188-d579-11e5-9131-6916d94df611.png)
WHAT?

**Comment by Ahrwing** [comment]
噗。不小心多上传了与论坛结合的文件 等我明天修复吧。。。

**Comment by 3TUSK** [comment]
Break the login issue into #196

**Comment by AstonIceDog** [comment]
这两个页面还是测试版的吗，表示没有连接起来，只能直接输网址进去吗

**Comment by AstonIceDog** [comment]
还有上边栏搜索按钮不见了诶，建议保留，或者挂在右边栏也可以

**Comment by Meow-J** [comment]
@AstonIceDog 那个在下边栏

**Comment by AstonIceDog** [comment]
好吧

**Comment by Ahrwing** [comment]
@AstonIceDog 因为上面没地方放了…… 另外..  搜索以后准备改版到list里的筛选，不用公共搜索了

**Comment by Meow-J** [comment]
搜索是需要的/w\

**Comment by AstonIceDog** [comment]
没有搜索还算百科吗

**Comment by Ahrwing** [comment]
会根据跳内容直接跳转到类似 http://www.mcmod.cn/modlist 的索引页 或物品/教程等索引页 不然搜索会显得冗余了
当然这只是一个设想
