### ISSUE TITLE
关于百科排版的一些建议

### ISSUE THREAD

**Issue by GWYOG** [Ahrwing/mcmod#193]
每次来百科站时，都被首页那一幅幅图搞的眼花缭乱...图片过多过大是一方面，还有一部分是因为那些鼠标悬停会滚上来的文字....以及那些不断滚动的条目...
反观其他wiki或下载站等地方，图片都少于文字，且没有那些滚动的条目：
[FTB官方wiki](http://ftb.gamepedia.com/FTB_Wiki)   基本没有图片，很清爽
[mcbbs的mod版](http://www.mcbbs.net/forum-mod-1.html)   同样图片很少，看起来很方便
[curse/curseforge](http://minecraft.curseforge.com/mc-mods)    以小图配合文字
[mc中文wiki](http://minecraft-zh.gamepedia.com/Minecraft_Wiki)    小图，多字
其他一些就不列举了

而百科站的首页首先图片太多了，除去模组的logo外，还有各个mod物品的图片，占了不小的版面.
此外，图也太大了.图片比文字多了太多，但是图片本身质量又不高，很多图片都被压缩根本看不清画了些什么.
点进某个mod的分区，图片和文字的比例就更失调了，别的先不说，许多模组的名字甚至因为图片占据了版面而无法显示完全，这对于逛百科站相当不便(#192)

总之，我建议百科站优化排版，减少图片的比例（这对于手机端也是很有好处的），首页的那些物品的小图完全可以换成上一页/下一页等按钮，这样检索模组起来会更方便些(见#192)。
此外，对于首页模组的简介，那些浮动的文字也许写的太多了，像curse一样的一句话简评会使首页更加清爽些.

**Comment by AstonIceDog** [comment]
可是我们站的“眼花缭乱”的图，不正是我们站的特色吗？密密麻麻的字是不会有人有耐心看的。

**Comment by AstonIceDog** [comment]
哦，首页的图片确实有点问题，有些文字无法看全，希望修改。
![image](https://cloud.githubusercontent.com/assets/13271372/13076699/0ddf2b8c-d4ef-11e5-9f12-7c31b4dd3568.png)

**Comment by GWYOG** [comment]
即使不是像FTB官方wiki那样密密麻麻的字，像Curse一样的小图配少字一样也很好啊

**Comment by AstonIceDog** [comment]
关于图片太大
![image](https://cloud.githubusercontent.com/assets/13271372/13076872/3ab5b210-d4f0-11e5-8991-7188e39e1d76.png)这个其实可以调图片大小的，调小了应该不会感觉太不协调了

**Comment by GWYOG** [comment]
嗯....是稍微好点，但感觉排版还是有点不习惯，也许是因为网格状的排列方式及向上滚动的文字？

**Comment by AstonIceDog** [comment]
+ 向上滚动的文字确实有点蛋疼，而且文字还看不全。
+ 排版的话，看久了就习惯了吧23333

**Comment by enzchiroptera** [comment]
以前就反馈过类似的问题,站长的意见是要保留百科自己的特色, 和@AstonIceDog的想法一样

**Comment by 3TUSK** [comment]
图片大小无所谓，匠魂的bannar那种严重拉伸的呢？

**Comment by Meow-J** [comment]
#194 说的不是那个问题，拉伸那个是 #18 ， #194 说的是大图标和小图标模式下拉伸比例不一样

**Comment by 3TUSK** [comment]
已修改。
但不知为何，我觉得mcmod百科在亲民的同时却损失了一定专业性...
诚然FTB Wiki（ftb.gamepedia.com）的文本特别多，但是这些文本都是建立在一定专业性的基础上的。The point is that, picture is not the problem, the problem is level of specialization.

**Comment by Ahrwing** [comment]
@GWYOG @Ouabain 
排版是确定要改的，但不会改成和wiki一样，否则当初就没有自己设计的意义了，直接用 mediawiki 又省时又省力。

**Comment by Ouabain** [comment]
也是没人要求改成wiki那样, 至少图片比例这些问题要解决吧

**Comment by Meow-J** [comment]
改成剪切图片就好_(:3」∠)_

**Comment by Ahrwing** [comment]
@Ouabain @Meow-J 已经在公司捉了一只美工帮我设计百科改版页面了 _(:з」∠)_ 不过咱要把需求和大体的框架先写出来……

**Comment by GWYOG** [comment]
滋磁！图片多不多其实没太大关系，版面美观就好（话说mediawiki确实不是很好看:P）

**Comment by Ahrwing** [comment]
@GWYOG 百科首页已改版~
