### ISSUE TITLE
首页切换到大图标之后图片被拉伸

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#194]
![image](https://cloud.githubusercontent.com/assets/5229241/13077175/2e8636de-d4f2-11e5-8e28-59f6518a0b79.png)
![image](https://cloud.githubusercontent.com/assets/5229241/13077180/337c5f4c-d4f2-11e5-85bc-96ddc5d7b568.png)

很明显切换到大图标之后图片变宽了。既然这样那原来的200x125图片还有什么用。另外快把缩略图剪裁功能搞好吧/w\ #18

**Comment by AstonIceDog** [comment]
所以说让别人困扰到了@GWYOG，建议只保留上面形式，下面的有多别扭就有多别扭

**Comment by Meow-J** [comment]
现在应该没有了
