### ISSUE TITLE
教程标题特殊符号编辑仍变为转义符

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#195]
![image](https://cloud.githubusercontent.com/assets/5229241/13119304/6aca175e-d5e3-11e5-8d28-44ed62d7e769.png)
![image](https://cloud.githubusercontent.com/assets/5229241/13119306/6e455d76-d5e3-11e5-849a-39210144d7ce.png)

**Comment by Ahrwing** [comment]
经检测，提交的时候是没有问题的... 问题出在重新编辑时的获取上……

**Comment by Ahrwing** [comment]
搞定w
