### ISSUE TITLE
论坛突然无法登陆

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#196]
![image](https://cloud.githubusercontent.com/assets/9113033/13121997/da9d6574-d582-11e5-821f-c7ebaef6366d.png)
如图。

**Comment by 3TUSK** [comment]
据说是暂时的，所以专开一个issue好了。
从[这里](https://github.com/Ahrwing/mcmod/issues/192#issuecomment-185333984)分离出来的issue。

**Comment by 3TUSK** [comment]
引用#192的原话：
> 噗。不小心多上传了与论坛结合的文件 等我明天修复吧。。。

**Comment by AstonIceDog** [comment]
还有论坛我怎么不知道

**Comment by Ahrwing** [comment]
@AstonIceDog 已经做好，还没开放。。。

**Comment by AstonIceDog** [comment]
什么时候开放？4.1吗

**Comment by Ahrwing** [comment]
已修复
