### ISSUE TITLE
评论回复/顶踩/删除键消失

### ISSUE THREAD

**Issue by DaidoujiTomoyo** [Ahrwing/mcmod#197]
![qq 20160218165048](https://cloud.githubusercontent.com/assets/16934954/13138069/e4ff49fa-d65f-11e5-96a5-d94d364294d0.jpg)

www.mcmod.cn/item/8085.html

**Comment by Ahrwing** [comment]
这不是bug... 你仔细往底下看…… - -..
这家伙无聊打了一堆回车符... orz

**Comment by Ahrwing** [comment]
能 /w\
