### ISSUE TITLE
验证码&提交信息

### ISSUE THREAD

**Issue by LasmGratel** [Ahrwing/mcmod#198]
1. 验证码在浏览器使用返回(PrevBack)的时候**不会刷新**。
2. 在提交之后submit网页**应返回至上一个网页**而**不是主页**。

**Comment by Ahrwing** [comment]
第二项是指的登录嘛？这个可以修一下，除了登录还有其他地方需要加吗？

**Comment by Meow-J** [comment]
估计是指资料的修改

**Comment by Ahrwing** [comment]
有免审核的用户组编辑完是直接跳转到内容页面没错… 
普通用户会跳转到提交成功页面，也不是首页.. /w\\...

**Comment by LasmGratel** [comment]
@Ahrwing 跳转到提交成功页面之后也会自动跳转至首页

**Comment by Ahrwing** [comment]
我记得有个返回首页按钮 但是不会自动跳转啊.. 0 0

**Comment by Ahrwing** [comment]
验证码问题已修复~
跳转页面无打算修复...  因为登录打开的是一个新窗口...

**Comment by LasmGratel** [comment]
thanks
