### ISSUE TITLE
论坛出现的部分BUG/缺陷，和一点点小疑问

### ISSUE THREAD

**Issue by CannonFotter** [Ahrwing/mcmod#200]
1. 无论坛明显入口~~(在源代码里发现了被注释的链接)
![1](https://cloud.githubusercontent.com/assets/11025035/13202480/54f7cd8a-d8d7-11e5-8686-b40bd7f47fb5.png)

2. 首次进入BBS引发报错（图片来源[@bakaxyf](https://github.com/bakaxyf) ）
![2](https://cloud.githubusercontent.com/assets/11025035/13202486/6e12b24e-d8d7-11e5-9954-21f88078856f.png)

3. 修改头像后，导航条头像不刷新
![3](https://cloud.githubusercontent.com/assets/11025035/13202493/b03dc8b6-d8d7-11e5-82ad-fd9dbaa602f2.png)

4. 我是46年前最后登陆的么（这个好像是discuz的锅？反正再登陆一次大概就没事了）
![4](https://cloud.githubusercontent.com/assets/11025035/13202496/d252b8c6-d8d7-11e5-99c0-fde71a0a9f26.png)

5. 可怜的长ID
![5](https://cloud.githubusercontent.com/assets/11025035/13202500/070bcea4-d8d8-11e5-8930-36831349eace.png)

6. 主站用户组不同步（xyf为编辑员）
![6](https://cloud.githubusercontent.com/assets/11025035/13202505/16a2ae82-d8d8-11e5-8e9e-5ff35c8ac8bd.png)

7. 见图（我有一个新提醒）
![7](https://cloud.githubusercontent.com/assets/11025035/13202507/414ba2ce-d8d8-11e5-9bbd-dfc819fc8675.png)

8. 恼人的横线滚动条(产生原因：友链和底部共同作用)
![8](https://cloud.githubusercontent.com/assets/11025035/13202511/5b9037e4-d8d8-11e5-964c-18ca5885d387.png)

9. 最新合成表栏目显示有问题
![9](https://cloud.githubusercontent.com/assets/11025035/13202516/8252b532-d8d8-11e5-9ff4-85b0263aa795.png)

10. 每日签到显示问题
这是主站：
![10-1](https://cloud.githubusercontent.com/assets/11025035/13202528/f810668e-d8d8-11e5-90ee-8dc2d310242c.png)
这是bbs：
![10-2](https://cloud.githubusercontent.com/assets/11025035/13202530/04403452-d8d9-11e5-8188-b3c8bfb1d4f9.png)

11. 可以进行多次每日签到
原因未知，我在bbs签到两次后（这个很迷，~~我不知道为啥~~ 只需要刷新页面即可）在主站还能签到

12.疑问：签到获得那些要素点的用途是什么？

13.疑问：为什么普通用户都没有类似mcbbs的评分权限呢？

14.不是疑问：
祝mcmod越办越好喵~
一个人写程序很累的说，加油~~~
~~(上线论坛又是修bug的节奏)~~
15. 提示信息是空的
![15](https://cloud.githubusercontent.com/assets/11025035/13202760/96dcab4e-d8e1-11e5-961f-e05896fca05d.png)
16. 复制粘贴的不小心
![16](https://cloud.githubusercontent.com/assets/11025035/13202781/383fd0f6-d8e2-11e5-9fc2-e4758e75c2ed.png)
17. 详情页签到按钮无效
![17](https://cloud.githubusercontent.com/assets/11025035/13202939/7f0cfcd6-d8e5-11e5-8aff-c4e007fd2e65.png)
18. jQuery都走丢了(未经详细求证，怀疑网络问题)~~
![18](https://cloud.githubusercontent.com/assets/11025035/13202968/2b3b7438-d8e6-11e5-9435-6503a2256cc8.png)
19. 论坛右侧浮动条对小屏幕不友好
看上去（黑色是应该在的位置）
![19-1](https://cloud.githubusercontent.com/assets/11025035/13207716/9c3b2db6-d94c-11e5-96e6-b0fd0a5cad08.PNG)
实际上
![19-2](https://cloud.githubusercontent.com/assets/11025035/13207718/a0eb4328-d94c-11e5-952a-98b8c80a5187.PNG)
这个看上去还不是很影响，不过mod详情页导航条的横条会挡上按钮的一部分，十分难看。。。
20. 404
![20](https://cloud.githubusercontent.com/assets/11025035/13207906/c7a22566-d94e-11e5-8c86-e2dff1c8266b.PNG)
21. 文本域出框
![21](https://cloud.githubusercontent.com/assets/11025035/13209212/52e94066-d95c-11e5-8aae-de656dd7a21a.PNG)
22. 在线时间不增长
![22](https://cloud.githubusercontent.com/assets/11025035/13210140/18f2b63e-d967-11e5-9277-0eed8250fa7b.PNG)
23. 最新教程
详情页：
![23-1](https://cloud.githubusercontent.com/assets/11025035/13212592/612ad4b6-d97d-11e5-80d2-df542db0460c.PNG)
主页：
![23-2](https://cloud.githubusercontent.com/assets/11025035/13212593/6134949c-d97d-11e5-80bd-d822cd4b1a1d.PNG)
24. 轮播器图片
![24](https://cloud.githubusercontent.com/assets/11025035/13214304/c86fba90-d989-11e5-88ee-958851b3c32a.PNG)

(可能会继续更新?如果找到bug的话)
(Update1 15,16)
(Update2 11)
(Update3 17,18)
(Update4 19,20)
(Update5 21,22)
(Update6 23,24)

**Comment by Meow-J** [comment]
论坛应该还没正式开放呢/w\

**Comment by CannonFotter** [comment]
已经可以进入了，导航条上有入口

**Comment by Meow-J** [comment]
帖子都是好久以前发的/w\

**Comment by Ahrwing** [comment]
1.论坛还没公开…
2.未知错误，有待排查
3.头像暂时还是用的主站的接口，一旦移到论坛，所有在主站上传的头像都会消失.. 因为论坛暂时没公开，所以没有开始解决这个问题
4.应该是最后登录时间为空导致的..
5.噗.. 这个怎么弄.. = = (虽然现在已经限制新用户注册长度了
6.未知错误，有待排查
7.未知错误，有待排查
8.未知错误，有待排查
9.这个应该是路径问题，正在修
10.未知错误，有待排查
11.未知错误，有待排查
12.暂无用途 = =.. 以前考虑过每日用两种随机要素可以合成积分什么的.. 
13.评分是指点评吗？帖子点评已经是允许的...
~~14.喵喵喵喵喵喵喵喵喵喵喵喵~~

**Comment by CannonFotter** [comment]
@Ahrwing 指的是评分（点评右面那个）

**Comment by DaidoujiTomoyo** [comment]
还有提示我未登录/w\

![image](https://cloud.githubusercontent.com/assets/16934954/13203224/17614142-d8ee-11e5-9a29-9659520aac07.png)

**Comment by CannonFotter** [comment]
刷新一下就好= =
这个也应该当作bug看待？（当初截图了来着，不过没发）

**Comment by DaidoujiTomoyo** [comment]
刷新并没用

**Comment by CannonFotter** [comment]
第一次登陆我也遇到了一样的情况/w\
![](https://cloud.githubusercontent.com/assets/11025035/13203255/2cc09546-d8ef-11e5-91d6-7d6f59ab1e70.png)

**Comment by Ahrwing** [comment]
那个应该是图片附件权限问题~ 已经修复~

另：目前主站与论坛的通信是以JS方式进行的..  在发送通信的时候页面就已经加载出来了.. 所以才会判断为未登录，此时再刷新一下就木有问题了~~

**Comment by Ahrwing** [comment]
另：游客改为允许查看图片，不允许下载附件

**Comment by Ahrwing** [comment]
2016年2月22日00:10:02 修复情况：

~~1.修了一下，应该没问题了… ~~
2.头像暂时还是用的主站的接口，一旦移到论坛，所有在主站上传的头像都会消失.. 因为论坛暂时没公开，所以没有开始解决这个问题
3.应该是最后登录时间为空导致的..
4.噗.. 这个怎么弄.. = = (虽然现在已经限制新用户注册长度了
~~5.已解决~~
~~6.已解决~~ (愚蠢的错误...~~
7.奇怪.. 我这边是正常的.. 你用的是什么浏览器 0 0?
~~8.路径问题，已修复~~
9.我这边是正常的.. 怀疑是浏览器问题 (?
~~10.可能是打开了多个页面。。也可能是session问题.. 不过无论签到多少次.. 当天只有第一次的有效 = =..~~
~~12.暂无用途 = =.. 以前考虑过每日用两种随机要素可以合成积分什么的..~~
~~13.评分功能已加ww~~
~~14.感谢体谅quq!!~~

1.这个… 待解决……
~~2.时间转换格式大小写问题，已解决喵..~~

**Comment by Meow-J** [comment]
第9个我之前也有那个问题，但是现在好了。另外合成表物品地址是错的，前面不应该有bbs.

**Comment by Meow-J** [comment]
另外这个东西戳穿屏幕啦
![image](https://cloud.githubusercontent.com/assets/5229241/13203916/74fad2e6-d8fd-11e5-90ed-0530d5e886b1.png)

**Comment by Meow-J** [comment]
7.正常
![image](https://cloud.githubusercontent.com/assets/5229241/13203925/abc32c92-d8fd-11e5-9ee0-d4c03a70f340.png)

**Comment by Meow-J** [comment]
8.现在主站也有这个问题了

**Comment by Ahrwing** [comment]
合成表物品地址已修复 √

**Comment by Ahrwing** [comment]
戳穿屏幕.. 屏幕太小造成的.. _(:з」∠)_ 肿么解决好捏..

**Comment by Meow-J** [comment]
- [ ] 无论坛明显入口~~(在源代码里发现了被注释的链接)
![1](https://cloud.githubusercontent.com/assets/11025035/13202480/54f7cd8a-d8d7-11e5-8686-b40bd7f47fb5.png)

- [ ] 首次进入BBS引发报错（图片来源[@bakaxyf](https://github.com/bakaxyf) ）
![2](https://cloud.githubusercontent.com/assets/11025035/13202486/6e12b24e-d8d7-11e5-9954-21f88078856f.png)

- [ ] 修改头像后，导航条头像不刷新
![3](https://cloud.githubusercontent.com/assets/11025035/13202493/b03dc8b6-d8d7-11e5-82ad-fd9dbaa602f2.png)

- [ ] 我是46年前最后登陆的么（这个好像是discuz的锅？反正再登陆一次大概就没事了）
![4](https://cloud.githubusercontent.com/assets/11025035/13202496/d252b8c6-d8d7-11e5-99c0-fde71a0a9f26.png)

- [ ] 可怜的长ID
![5](https://cloud.githubusercontent.com/assets/11025035/13202500/070bcea4-d8d8-11e5-8930-36831349eace.png)

- [ ] 主站用户组不同步（xyf为编辑员）
![6](https://cloud.githubusercontent.com/assets/11025035/13202505/16a2ae82-d8d8-11e5-8e9e-5ff35c8ac8bd.png)

- [ ] 见图（我有一个新提醒）
![7](https://cloud.githubusercontent.com/assets/11025035/13202507/414ba2ce-d8d8-11e5-9bbd-dfc819fc8675.png)

- [ ] 恼人的横线滚动条
![8](https://cloud.githubusercontent.com/assets/11025035/13202511/5b9037e4-d8d8-11e5-964c-18ca5885d387.png)

- [ ] 最新合成表栏目显示有问题
![9](https://cloud.githubusercontent.com/assets/11025035/13202516/8252b532-d8d8-11e5-9ff4-85b0263aa795.png)

- [ ] 每日签到显示问题
这是主站：
![10-1](https://cloud.githubusercontent.com/assets/11025035/13202528/f810668e-d8d8-11e5-90ee-8dc2d310242c.png)
这是bbs：
![10-2](https://cloud.githubusercontent.com/assets/11025035/13202530/04403452-d8d9-11e5-8188-b3c8bfb1d4f9.png)

- [ ] 可以进行多次每日签到
原因未知，我在bbs签到两次后（这个很迷，~~我不知道为啥~~ 只需要刷新页面即可）在主站还能签到

- [ ] 疑问：签到获得那些要素点的用途是什么？

- [ ] 疑问：为什么普通用户都没有类似mcbbs的评分权限呢？

- [ ] 不是疑问：
祝mcmod越办越好喵~
一个人写程序很累的说，加油~~~
~~(上线论坛又是修bug的节奏)~~
- [ ] 提示信息是空的
![15](https://cloud.githubusercontent.com/assets/11025035/13202760/96dcab4e-d8e1-11e5-961f-e05896fca05d.png)
- [ ] 复制粘贴的不小心
![16](https://cloud.githubusercontent.com/assets/11025035/13202781/383fd0f6-d8e2-11e5-9fc2-e4758e75c2ed.png)
- [ ] 详情页签到按钮无效
![17](https://cloud.githubusercontent.com/assets/11025035/13202939/7f0cfcd6-d8e5-11e5-8aff-c4e007fd2e65.png)
- [ ] jQuery都走丢了(未经详细求证，怀疑网络问题)~~
![18](https://cloud.githubusercontent.com/assets/11025035/13202968/2b3b7438-d8e6-11e5-9435-6503a2256cc8.png)

**Comment by Meow-J** [comment]
完成了记得打个勾

**Comment by mmt50** [comment]
补充一个问题，点击百科底部的“联系百科”的“意见反馈”后，虽然会正确跳转至这边，但是同时也会打开一个javascrpit:void(0);的空页面，使用的是谷歌浏览器48.0.2564.116 m，以及火狐浏览器

**Comment by Ahrwing** [comment]
@mmt50 修好了 √

**Comment by mmt50** [comment]
不好意思，刚才发现旁边的“百科帮助”也有这个问题= =

**Comment by Ahrwing** [comment]
QwQ.. 改好惹ww 顺便把友情链接申请跳转到了论坛

**Comment by Ahrwing** [comment]
除了几个线索太少的BUG，其他问题都解决完了~

**Comment by Ahrwing** [comment]
如果24小时候木有新问题出现的话，就先结帖咯~

**Comment by CannonFotter** [comment]
最新图片那里图片溢出
横向滚动条(遇到过相似情况，大概是因为底部友链(含)以下位置长了一点点，然后就出现了滚动条君)
以及主页和板块页面的最新教程显示不一致....(主页全部显示未知，板块页面里显示没问题)

**Comment by Ahrwing** [comment]
1.的确是只显示一部分.. 不然又会像MOD缩略图一样被挤压的感觉了……
2.讲道理，现在论坛没有友链...
3.这个可以修

**Comment by Ahrwing** [comment]
主页教程时间BUG已修复~

**Comment by Ahrwing** [comment]
主页教程时间BUG已修复~

**Comment by CannonFotter** [comment]
主站也是一样的bug....有横向滚动条

**Comment by Ahrwing** [comment]
@CannonFotter 暂时没找到原因..  (我这边无论用什么浏览器/分辨率看 都是正常的... orz

**Comment by CannonFotter** [comment]
1920*1080分辨率
chrome
~~因为重生你电脑屏幕大呀~~
顺便感觉图片不显示完全真的好难受....不如改成像mcbbs一样人工推荐那种

**Comment by CannonFotter** [comment]
Time to close. :)
