### ISSUE TITLE
设立对物品的二级分类

### ISSUE THREAD

**Issue by mmt50** [Ahrwing/mcmod#202]
这个想法主要是对查阅资料的一点优化，毕竟在一个“材料”或者类似的大类里去查茫茫多的东西有时候是很头疼的，虽然有ctrl+f这个方法在，但是这个。。。参考minecraft wiki对于子类的处理，似乎可以参考

**Comment by mmt50** [comment]
此外这样对于物品排序也可以起到作用，我希望在一个分类下，有着相同特征的几样物品能够靠的比较紧，例如粉末类的放一起，那样

**Comment by Ahrwing** [comment]
因为暂时没有缓存系统，现在在一级分类多的情况下已经很占资源了.. 再加个二级分类.... Orz..
不过或许是算法的问题..?  可以参考一下wiki是怎么实现的...

**Comment by Ahrwing** [comment]
分类排序可以加一个的

**Comment by 3TUSK** [comment]
强行安利FTB Wiki（ftb.gamepedia.com）。

**Comment by luhaoz** [comment]
我们需要标签
更多的标签！！还要更多！还要更多！
材料：粉末 材料：ic：粉末 
更多的标签！！还要更多！还要更多！

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/90048483-2c3da080-dd06-11ea-88f5-3bddfa256b17.png)
👌
