### ISSUE TITLE
主站个人中心最近访客BUG

### ISSUE THREAD

**Issue by CannonFotter** [Ahrwing/mcmod#203]
![](https://cloud.githubusercontent.com/assets/11025035/13216689/598eef4c-d998-11e5-99bf-3d0fe480e74a.PNG)
自己看会显示一些奇奇怪怪的东西

**Comment by Ahrwing** [comment]
哪有  /w\\..

**Comment by CannonFotter** [comment]
应该显示没有访客而不是“登陆，成为第一个留下脚印的人吧”

**Comment by Meow-J** [comment]
到底一共有多少个登陆0 0

**Comment by Ahrwing** [comment]
解决了 0 0
