### ISSUE TITLE
搜索时候的一个bug

### ISSUE THREAD

**Issue by mmt50** [Ahrwing/mcmod#204]
搜索模组时一切正常，不提了
但是如果在搜索结果页切成“教程”或“物品”，那么这个bug就出现了：
![](http://i11.tietuku.com/554384421f50144a.png)
![](http://i11.tietuku.com/c5995428eb16eb85.png)
对了那个木齿轮的第二个指向了一个空链接（可以确定是BC的，不过BC的里面的木齿轮的名字叫“木制齿轮”（还有一个未编辑的“木质齿轮”）回头我删一下重复内容）
所以说高级搜索功能能进入考虑范围吗？

**Comment by Ahrwing** [comment]
那个重复的已经删了.. 搜索忘记加条件了.... 所以把回收站里的东西也都显示出来了.. Orz..

**Comment by Ahrwing** [comment]
另：bug在哪儿... 我肿么没有看到 orz..

**Comment by mmt50** [comment]
那个“未知”和一串的0啊= =

**Comment by Ahrwing** [comment]
soga.. 这个早就有了 orz.. 字符串的话应该截取后的描红定位问题

**Comment by mmt50** [comment]
删除重复物品的时候，跟游戏内的译名对比也发现一个比较头疼的事情就是译名不统一。。。
BC里的“木齿轮”，游戏内叫“木齿轮”（最新版），百科里有资料的那个叫“木制齿轮”，添加了一个重复的叫“木质齿轮”，编辑起来还好，删掉一个，改或不改另一个，可是一般用户搜索的时候就麻烦了，搜“木齿轮”结果什么都没有（汉化组某种意义上得负责），
所以我意见是加上模糊搜索能力，将一些翻译有细微差别，但是其实是同一种物品的名称划成一组

**Comment by 3TUSK** [comment]
@mmt50 并没有所谓的汉化组，现在很多mod的本地化都是独立完成的，统一口径反倒更加麻烦...

**Comment by Meow-J** [comment]
要不要加个其它译名只在搜索时显示

**Comment by Ahrwing** [comment]
@Meow-J /w\ 多个译名的话会不会很麻烦… 容易弄混哪个是官方的译名版本……

**Comment by 3TUSK** [comment]
哪有**官方**版本，都是社区驱动，随时可能会变#(喷)

**Comment by mmt50** [comment]
我的意见是百科里设定一个译名做主译名，再设置一些关键词，在搜索这些关键词时候搜索结果也会显示主译名的那个物品

**Comment by Ahrwing** [comment]
@mmt50 关键词就是类似标签的东西咯？

**Comment by 3TUSK** [comment]
@mmt50 @Ahrwing 于是又撞上了我之前提出地category+tag系统，Category给出合理的系统分类，tag方便玩家搜索。

**Comment by mmt50** [comment]
嗯差不多吧，只不过这个是玩家不可见的

**Comment by Meow-J** [comment]
这不还是其它译名/w\

**Comment by Ahrwing** [comment]
搜索已改版~
