### ISSUE TITLE
鼠标光标指向单个链接时出现多个悬浮框

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#206]
![screen shot 2016-02-26 at 12 15 12 pm](https://cloud.githubusercontent.com/assets/9113033/13359528/c94037f0-dc82-11e5-91a0-7f22ca379861.png)

Duang的一声又出现了一个bug，Chrome 43.0.2357.132 (64-bit), OSX Yosemite 10.10.3

**Comment by 3TUSK** [comment]
等等，为什么现在又好了...
先Close。如有问题请重新打开。

**Comment by Ahrwing** [comment]
这个我也遇到过2333..
打算把顶上自带的栏换掉.. 但是还没想好怎么展现~

**Comment by CannonFotter** [comment]
这个只会在页面刚刚加载好的时候出现吧

**Comment by 3TUSK** [comment]
@CannonFotter 的确...但这个情况只是***偶发***，暂不清楚原因。
第二次看到是在OSX Maverick 10.9.4, Chrome版本号忘了= =。
（我们有一个“有时可以重现”的Tag吗）

**Comment by Ahrwing** [comment]
把鼠标移上的信息去掉了
