### ISSUE TITLE
横向滚动条

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#207]
从 #200 分离出来

![image](https://cloud.githubusercontent.com/assets/5229241/13372735/2d20ac6e-dd8c-11e5-8b8a-095199532618.png)

**Comment by Ahrwing** [comment]
好想远程你 (///

**Comment by CannonFotter** [comment]
Chrome `48.0.2564.116 m` 有此问题
Edge 无此问题
InternetExplorer `11.103.10586.0` 在BBS下无此问题（进入百科主页会直接卡死并出现显示异常）
Firefox `44.0.2` 无此问题
Opear和Safari未测试

**Comment by Ahrwing** [comment]
我把浏览器升级了一下.. 弄好了.. 愚蠢的错误 (///
