### ISSUE TITLE
回到顶部叠加错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#209]
![image](https://cloud.githubusercontent.com/assets/5229241/13372940/32dbc640-dd94-11e5-8573-48bec042a26c.png)
![image](https://cloud.githubusercontent.com/assets/5229241/13372941/371b9bb8-dd94-11e5-8b8a-0104e428b652.png)

**Comment by Ahrwing** [comment]
搞定~

**Comment by Meow-J** [comment]
哪里修了/w\

**Comment by CannonFotter** [comment]
确实修好了

**Comment by Meow-J** [comment]
现在好了
