### ISSUE TITLE
关于论坛最新图片显示问题

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#212]
![image](https://cloud.githubusercontent.com/assets/13271372/13377277/3abf2426-de0f-11e5-982a-97b0b47013ae.png)
![image](https://cloud.githubusercontent.com/assets/13271372/13377279/4167763e-de0f-11e5-91b9-e25b06afb0e8.png)
论坛最新图片显示不完全

**Comment by CannonFotter** [comment]
见 #200

**Comment by Ahrwing** [comment]
已解决… （早该解决的orz）
