### ISSUE TITLE
左下角彩蛋点开后基本只有GT4的物品

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#213]
为何全是GT4，就不能有点其他的么(比如GT5
/w\

**Comment by 3TUSK** [comment]
有啊，有青蛙工艺的气动压缩机和高级化学反应器。

**Comment by elctove** [comment]
基本只有……
以及3t你吓到我了

**Comment by 3TUSK** [comment]
I AM NOT GHOST

**Comment by Ahrwing** [comment]
因为不是即时获取，而是一个list... time to change..

**Comment by Ahrwing** [comment]
I HAVE NO IDEA... 因为许多图标是base64的，如果用list的话整个文件会变得很大…  即时获取又会占大量资源…… 纠结(x)

**Comment by CannonFotter** [comment]
用多个list，随机取一个怎么样？

**Comment by Ahrwing** [comment]
那得需要多少个list… 而且不能自动更新很头疼…… 专门做一个list生成机制成本太大也没必要 orz..
我觉得最好的解决办法，还是即时获取吧....

**Comment by Ahrwing** [comment]
即时获取会有被恶意使用占用大量资源的风险

**Comment by Ahrwing** [comment]
已解决~

**Comment by 3TUSK** [comment]
居然解决了
