### ISSUE TITLE
建议头像支持gravatar

### ISSUE THREAD

**Issue by panda2134** [Ahrwing/mcmod#214]
如题= =

**Comment by panda2134** [comment]
https://cn.gravatar.com/

**Comment by Meow-J** [comment]
感觉这有点麻烦了，换头像还要搞很长时间

**Comment by Ahrwing** [comment]
我连网站都打不开……

**Comment by Meow-J** [comment]
Github原来就用的Gravatar，现在不还是改成直接上传了/w\

**Comment by panda2134** [comment]
@Meow-J 我的意思是支持，而不是换用。。。
也就是同时保留gravator和上传两种

**Comment by CannonFotter** [comment]
Gravatar国内访问速度很慢，我这大部分时间图都是裂的...

**Comment by CannonFotter** [comment]
Gravatar国内访问速度很慢，我这大部分时间图都是裂的...

**Comment by Ahrwing** [comment]
用gravatar的结果(用ssl也一样)
通常会连接超时显示默认头像，或者显示一个叉叉，要么就一直加载拖速度…
暂不打算实现
