### ISSUE TITLE
多用户时Chrome Autofill密码不更新

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#215]
![qq 20160228234654](https://cloud.githubusercontent.com/assets/5229241/13380133/fc25ae6c-de75-11e5-810e-b665118d2744.png)
切换用户之后密码仍然是原来用户的密码

**Comment by Ahrwing** [comment]
可能是表单问题 这个跟浏览器计算规则有关

**Comment by Ahrwing** [comment]
把密码改成不保存了 /w\
