### ISSUE TITLE
关于百科加入“维护小组”的初步设想

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#216]
今天上午发现表群的几位用英文讨论炸开了锅… 
看到w君(w_jinrui)说不希望有太多萌新去编辑百科造成质量太差，于是想到了可以加一个“维护小组”的功能。

初步设想：
1.每个MOD都可以申请MOD维护小组；
2.一个MOD只能有一个小组，小组内成员有上下限(待定)；
3.申请者必须是所属MOD的实习编辑员或正式编辑员 (需先完成此功能)
4.当一个MOD的小组成立时，MOD禁止一般用户编辑 (或是需要通过小组成员审核)

...

**Comment by 3TUSK** [comment]
高标准才是关键。社区驱动的方针不能变，但是问题是对于误导内容一定要采取零容忍态度。
新问题——如何判定误导内容？像是IC2、BC这种资料比较全的还好说，但是遇到AoA（虚无世界）这种？

**Comment by Ahrwing** [comment]
所以需要会玩所属MOD的人去负责专区的维护… MOD区内的审核方面也可以交给组成员来负责...

**Comment by luhaoz** [comment]
这个虾米想提点建议
可以建立这样的机制
每个mod都有维护组维护（没有都交给Ahrwing吧）
然后在基础wiki内容上添加外围资讯功能，可以由萌新提供多个不同的版本资讯，然后这些资讯并非公式认定资讯，可以参考，然后由投票和维护组鉴定后可以合并到主条目中。这样未公式信息本身可以被阅读但并不保证正确性，条目主体的信息都保证是验证过有效的（在一定有效版本内）

**Comment by Ahrwing** [comment]
@luhaoz 很好的想法，不过规模太小是硬伤……

**Comment by mmt50** [comment]
所以怎么招人？
或者说维护小组主要用于维护那些人气高的以及主流的mod，再分摊一些小mod，毕竟后者的访问量不是很大（甚至有大量的未编辑内容）

**Comment by Ahrwing** [comment]
@mmt50 所有mod都可以设立维护小组，并且一个人可以参与多个小组……

**Comment by 3TUSK** [comment]
啊我想起来了！@Ahrwing Official FTB Wiki有一个Wiki托管计划，就是说Modder可以指定xxx作为管理员来帮助进行wiki撰写，并托管在Official FTB Wiki那里。我们是不是该给modder们打个广告？

**Comment by Meow-J** [comment]
这不还是分区编辑员/w\

**Comment by 3TUSK** [comment]
@Meow-J 所以说为什么我们都想一块了？

**Comment by mmt50** [comment]
那么，一个小组预计需要分配多少人

**Comment by 3TUSK** [comment]
@mmt50 1个最好——>个人想法。

**Comment by AstonIceDog** [comment]
表示百科固定的编辑员真的太少

**Comment by mmt50** [comment]
@3TUSK 我觉得一般得两个或三个人，毕竟一个人的话不确定性还是大了点，而且大型mod，不说别的，就说IC2或者AE2，一个人绝对是没法处理，再说编辑意见什么的到了一些细节上面需要讨论才能拍板

**Comment by 3TUSK** [comment]
@mmt50 一个人对付IC2/AE2其实问题不大的（比如我，雾）

**Comment by AstonIceDog** [comment]
4. 个人认为不应该禁止一般用户编辑，可以让MOD小组审核通过。

**Comment by mmt50** [comment]
@3TUSK 难以想象，对了，维护周期和一次维护的时间怎么安排

**Comment by mmt50** [comment]
@3TUSK 难以想象，对了，维护周期和一次维护的时间怎么安排

**Comment by 3TUSK** [comment]
@mmt50 不一定要时刻盯着...大概一星期看三眼，解决解决问题，就好。

**Comment by Meow-J** [comment]
不让一般用户编辑算什么百科/w\

**Comment by Ahrwing** [comment]
维护小组功能已上线~  (目前实现的功能和之前想的略有偏差)
加入小组后会在MOD页面和个人中心显示，

- 在有维护小组的情况下只能编辑所正在维护的MOD区内的MOD/资料/教程等内容~
- 在无维护小组的情况下默认为全局编辑员~

**Comment by AstonIceDog** [comment]
所以没有采用我的吗

**Comment by 3TUSK** [comment]
@AstonIceDog 慢慢改。

**Comment by Ahrwing** [comment]
@AstonIceDog 一般用户是指... ? 未登录用户吗？

**Comment by 3TUSK** [comment]
@Ahrwing 应该是一般的注册用户，注册一下方便使用这种。

**Comment by Ahrwing** [comment]
@3TUSK 啥时候禁止过了.. //w\

**Comment by AstonIceDog** [comment]
是指的**非小组用户**
当一个MOD有编辑小组时，**非小组用户**，编辑需要通过小组审核
当一个MOD没有编辑小组时，**百科用户**需要资深编辑员审核，

**Comment by Ahrwing** [comment]
分区管理已上线，如有其他疑问/bug可另行开贴~
