### ISSUE TITLE
分享列表戳破屏幕

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#218]
![image](https://cloud.githubusercontent.com/assets/5229241/13433523/29809834-e00d-11e5-9ee2-6849c560fe2a.png)

**Comment by Ahrwing** [comment]
咦.. 这是哪个帖子.. 记得以前发现有部分帖子会这样，部分帖子不会……

**Comment by Meow-J** [comment]
http://bbs.mcmod.cn/thread-117-1-1.html

**Comment by Ahrwing** [comment]
乃再看看 0 0

**Comment by Meow-J** [comment]
还是会

**Comment by Ahrwing** [comment]
好了 /w\ .. Chrome/FF 均测试正常~  
话说有个“特性”：鼠标移上“分享”时如果再用鼠标滚轮导致鼠标离开“分享”，悬浮框依然会显示，并且还是固定在原来的位置，不会跟随鼠标滚轮方向自动移动 = = 此时如果鼠标一开悬浮窗，就会消失了~
