### ISSUE TITLE
编辑之后提交审核时候增加变动说明

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#22]
这个应该说过了

**Comment by Meow-J** [comment]
**加急！加急！**已经有人开始编辑已有的物品来进行询问了。
![qq 20150813022530](https://cloud.githubusercontent.com/assets/5229241/9232861/a34be6ea-4162-11e5-9ea7-ccf014cc01c4.png)

**Comment by Ahrwing** [comment]
已添加~
