### ISSUE TITLE
查看物品/方块列表时图标加载延迟明显过长，且有极轻微卡顿感

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#220]
对比一下这几个的Navbox加载速度：
1.http://ftb.gamepedia.com/GregTech_4 下面的`{{Navbox GregTech 4}}`
2.http://ftbwiki.org/GregTech 下面的`{{Navbox/GregTech}}`
3.http://www.mcmod.cn/item/list/51-1.html 百科自己的
我们百科的是不是图标加载速度太慢了点...？有没有解决办法？如果没有请直接Close。
环境：OSX Yosemite 10.10.3, Safari 8.0.5 (10600.5.17), CPU: i5 1.5GHz 型号不明

**Comment by Ahrwing** [comment]
目前已使用静态缓存，把延迟加载暂时去掉了.. 本来是好事，主要是木有检测图片是否已被加载，每次刷新都会重新获取图片……

**Comment by Ahrwing** [comment]
啊不行…… 如果去掉延迟加载.. 第一次访问的时候会巨慢… 看来得优化一下延迟加载了……

**Comment by Ahrwing** [comment]
好了~ 优化后资料整页面速度提升10倍~

**Comment by Ahrwing** [comment]
stable like a dog!
