### ISSUE TITLE
审核列表排版错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#222]
![image](https://cloud.githubusercontent.com/assets/5229241/13535723/b0ea0c54-e276-11e5-863b-3c9a7e657305.png)
![image](https://cloud.githubusercontent.com/assets/5229241/13535726/b907e53c-e276-11e5-90c9-27b87f7bf023.png)

**Comment by Ahrwing** [comment]
貌似因为修复了utf8截取 截取字符的单位出了问题。。。

**Comment by Ahrwing** [comment]
修好了 乃看看w
