### ISSUE TITLE
关于论坛的登录问题

### ISSUE THREAD

**Issue by mmt50** [Ahrwing/mcmod#225]
昨天登录了百科，然后今天进主站，依旧是登录状态，按了论坛链接，也没事，然后我刷新了一下，登录状态没了
chrome浏览器，怀疑是之前的bug未解决

**Comment by Meow-J** [comment]
证实

**Comment by Ahrwing** [comment]
已修复~
观察一段时间，如果没有再次出现就可以关了 /w\\

**Comment by Meow-J** [comment]
![qq 20160418181945](https://cloud.githubusercontent.com/assets/5229241/14600998/28516c9a-0592-11e6-96be-f25d7d43c7d3.png)
更严重了，上面显示的账号和论坛实际发言的账号不匹配

**Comment by Ahrwing** [comment]
@Meow-J 把同步登录注释掉了.结果和预想的一样…. orz

**Comment by AstonIceDog** [comment]
![image](https://cloud.githubusercontent.com/assets/13271372/19014443/57befbc2-881f-11e6-8a98-1a8e5e1e6221.png)
![image](https://cloud.githubusercontent.com/assets/13271372/19014445/5ea81f72-881f-11e6-85f3-65fb3bf37211.png)
就是这种尴尬的情况，删过Cookies还是这样。

**Comment by Meow-J** [comment]
戳

**Comment by AstonIceDog** [comment]
已修复~

**Comment by Ahrwing** [comment]
~
