### ISSUE TITLE
关于百科改进的若干意见

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#226]
我对百科的改进意见稍微做了一下思考。作为一个百科需要做到如下几样
- 查询速度快
- 查询方便
- 内容正确 

对以上几点有以下几点改进建议
1.资料权威化、科学化 #216 就在讨论这个问题这里就不说了。
2. MOD再分类，在综合类下面继续分类
- 魔法类
- 科技类
- 便捷类
- ……

3.首页出现的应该是点击量最多的MOD，最新添加的MOD在专门新区显示就行了。
4.查询速度已经改进

**Comment by 3TUSK** [comment]
Botania is a tech mod --- Vazkii

**Comment by Ouabain** [comment]
这种文理分科一般的分类还是等于没分类

**Comment by AstonIceDog** [comment]
这个是为了更好的查询，不是为了分类而分类

**Comment by Ouabain** [comment]
这个分类是为了便于查询的话...
我记得3T以前提过相关的建议

**Comment by CannonFotter** [comment]
可以参考curseforge上的分类？

**Comment by AstonIceDog** [comment]
不知道3T的哪个，你#出来

**Comment by Ouabain** [comment]
> category+tag系统，Category给出合理的系统分类，tag方便玩家搜索。

#204 和 #158 都有提到 群里应该有更详细点的解释

**Comment by 3TUSK** [comment]
Tag（标签）：用于展示这个mod的核心内容，也就是key word(s)，关键字。
Category（分类）：正确的分类——用于系统化分类百科所记载的所有mod，方便玩家进行各种奇葩的比较（比如说横向对比各种物流mod，这个时候就需要所有物流相关的mod都需要正确归类进“物流”这个Category里，而不是一边BC归类进“管道”，一边AE归类进“外星科技”，然后SFM突然来了个“AE替代品”这种）。
我这大概第五次重复这个吧...

**Comment by LasmGratel** [comment]
@3TUSK 程序猿表示可以有**单继承**，但是可以有分类接口
例如Cagetory A implements B,C
Cagetory B extends A implements D,E
（23333其实我也有点懵逼了

**Comment by 3TUSK** [comment]
@Ouabain 不，我比较怕多重继承：
````
Category Automation extends Logistics, Energy, Processing
````
这种。

**Comment by AstonIceDog** [comment]
1. 对于Category个人建议不要分太细了，只要

+ 魔法类（Magic）（对于那个有争议的<del>毫无争议</del>Botania可以分在魔法类里。
+ 科技类（管道，外星科技都可以归到科技类里面）
+ 现实类（对不科技又不魔法的类我还没想出好的名字）

这些小类就可以了。对于那些奇葩的比较我认为没必要。我们只是为了查询方便而已。对于著名的格雷科技，只要到科技类去查找就可以了。如果要比较的话，在Tag里面比较。
2. 关于那个Category不能乱分类问题，可以让维护小组对自己维护的MOD分类，因为他们对自己维护的MOD比较熟悉。（或者说在一个分类里面出一个类维护小组，负责审核分类和新MOD审核。）

**Comment by AstonIceDog** [comment]
@3TUSK 你@错人了

**Comment by 3TUSK** [comment]
@AstonIceDog 不要再分了...
> 2.关于那个Category不能乱分类问题，可以让维护小组对自己维护的MOD分类，因为他们对自己维护的> MOD比较熟悉。（或者说在一个分类里面出一个类维护小组，负责审核分类和新MOD审核。）

让那些mod维护小组来决断他们管理的mod应该落在哪个/些Category里。Category总数不要太多...

**Comment by AstonIceDog** [comment]
@3TUSK Category只是分为综合类环境类生物类补丁类还是觉得类太大了

**Comment by AstonIceDog** [comment]
@CannonFotter 并不要curseforge分类的那么细

**Comment by 3TUSK** [comment]
@AstonIceDog 要的就是比综合/环境/生物/补丁更细的分类，但是并没有必要细致到：
* Pipe
* Conduit
* Duct

这种。只要一个Logistics就好。这是举个例子。

**Comment by AstonIceDog** [comment]
恩
