### ISSUE TITLE
图片地址复制无效

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#229]
![image](https://cloud.githubusercontent.com/assets/5229241/13774135/47224010-ead8-11e5-9771-df722fd23c55.png)
![image](https://cloud.githubusercontent.com/assets/5229241/13774139/4ca838fa-ead8-11e5-9f69-29d63df1f928.png)
实际上剪贴板并没有改变/w\

**Comment by Meow-J** [comment]
戳一下

**Comment by Meow-J** [comment]
戳，顺便我用的是Chrome

**Comment by Ahrwing** [comment]
修好了  去掉了自动复制 需要手动复制w

**Comment by Meow-J** [comment]
水印的问题呢

**Comment by Ahrwing** [comment]
我在想办法 /w\\...
