### ISSUE TITLE
水印

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#230]
总觉得好奇怪/w\，添加个选项让上传者选择一下吧，上传图片很多时候是要做缩略图的。另外最好再保存份原图片，我教程的图都没备份_(:з」∠)_。

**Comment by mmt50** [comment]
对，现在要改一些以前使用别的图床的mod的资料的时候，会提示修改缩略图链接，然后传到相册里却又是带水印的内容没法用于缩略图

**Comment by Ahrwing** [comment]
@mmt50 缩略图以后会加裁剪

**Comment by Meow-J** [comment]
受不了啦，缩略图一般都超过这个标准的： http://www.mcmod.cn/class/477.html

**Comment by 3TUSK** [comment]
干嘛要缩略图...啊我突然发觉FTB Wiki似乎有一样的情况，但因为FTB WIki用的缩略图不多（AFAIK），所以情况不如mod百科这样严重。

**Comment by partial-s** [comment]
FTBW 缩略图用的不多, 貌似用到的也是小于450*450的, 或者是logo

**Comment by Meow-J** [comment]
戳

**Comment by sxjeru** [comment]
我不觉得水印会淡。。
![image](https://cloud.githubusercontent.com/assets/20513115/21283785/0a98c5c4-c444-11e6-803e-b843c9e30fb8.png)

**Comment by sxjeru** [comment]
要是左下角这个链接能接到无水印原图就好了w
![image](https://cloud.githubusercontent.com/assets/20513115/21283793/3bbb6d46-c444-11e6-9e11-574e6680f2fa.png)

**Comment by Ahrwing** [comment]
水印暂时去掉了.. 想办法加上开关再放好了.. /w\

**Comment by Meow-J** [comment]
还原成以前的上传方式啦

**Comment by Meow-J** [comment]
戳

**Comment by sxjeru** [comment]
水印又出现了，然而还是不可选。

**Comment by Ahrwing** [comment]
改了一下水印 现在应该看起来比原来舒服了 _(:з」∠)_

**Comment by Meow-J** [comment]
重要的是可选啦

**Comment by Ahrwing** [comment]
加水印也是为了防止有人把百科当图床用转载到其他站点.. 带宽可吃不起.. 
况且现在"缩略图"也改成了"封面"，允许自定义裁剪(无水印)~

**Comment by Ahrwing** [comment]
`某抄袭事件凸显了水印的重要性`

**Comment by Ahrwing** [comment]
![水印测试成功](http://bbs.mcmod.cn/data/attachment/album/201712/15/141237lzrwpjcc70rr0cit.png)
