### ISSUE TITLE
审核结果短消息通知

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#234]
现在审核成功失败好像都没通知的样子，如果审核失败了最好通知一下原作者并附上原因，方便提醒用户进行修改

**Comment by CannonFotter** [comment]
非常同意...现在审核简直完全静默

**Comment by AstonIceDog** [comment]
赞同

**Comment by Meow-J** [comment]
戳，主要是审核失败的通知

**Comment by Ahrwing** [comment]
现在审核被退回后会提醒作者了ww 如果通过了，审核员留有附言的也会提醒~ 
(通过并且没有附言的不会提醒.. 不然感觉要被刷屏 _(:з」∠)_ )
