### ISSUE TITLE
特性请求：论坛中删除自己的回复

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#236]
论坛无法删除自己的回复
![image](https://cloud.githubusercontent.com/assets/13271372/14060408/9fd57d3e-f39e-11e5-9767-6fce9e16a12d.png)

**Comment by Ahrwing** [comment]
这不是bug，本来就没提供这个功能

**Comment by 3TUSK** [comment]
@AstonIceDog Here you go.

**Comment by Ahrwing** [comment]
无打算添加......... 删除自己回复的功能显然不是每个网站都必须要有的..

**Comment by 3TUSK** [comment]
@Ahrwing 比如我现在正在试图删除我的贴吧和mcbbs账号。（喷）

**Comment by SYNDIG1** [comment]
这个也不是严重的问题啦... 让删除的帖子进回收站, 或是允许论坛的管理员删帖(用户可以私信要求)
这样之类的也可以 _(:з」∠)_

**Comment by AstonIceDog** [comment]
@3TUSK 留点口德吧
