### ISSUE TITLE
特性请求：直接改变分类名称

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#241]
直接改变分类名称

**Comment by mmt50** [comment]
不认为这是一个人能干的，或者说这应该是一群人做的，而不该自作主张

**Comment by AstonIceDog** [comment]
因为如果要改变一个类的分类名称的话，要一个一个物品改。

**Comment by mmt50** [comment]
你并没有发现批量改分类这个功能，结论就是只要给一个物品分出新的分类，其他物品批量划过去即可
@AstonIceDog

**Comment by Ahrwing** [comment]
v3后台已加入修改分类名称
