### ISSUE TITLE
审核缩略图不显示

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#244]
![image](https://cloud.githubusercontent.com/assets/5229241/14526458/fb3a16f4-0275-11e6-98e6-15b54efacf39.png)
实际上是有图片的

好像还没修复，留着做备忘吧

**Comment by Ahrwing** [comment]
已尝试修复（待确认）

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/14580258/078bafae-03fb-11e6-8bbd-8746deeb93f5.png)
