### ISSUE TITLE
公共消息条数显示错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#246]
![image](https://cloud.githubusercontent.com/assets/5229241/14580239/323924da-03fa-11e6-808f-c862fbe6ee3f.png)

实际只有这一条

![image](https://cloud.githubusercontent.com/assets/5229241/14580240/383f1600-03fa-11e6-9140-75155f2bdb6a.png)

**Comment by Ahrwing** [comment]
只有在群发的时候会出现，原因不明.. dz的锅

**Comment by AstonIceDog** [comment]
这就是为什么你不群发更新消息的原因吗？理解。
