### ISSUE TITLE
变更说明必填提示之后输入框太像消息提示

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#247]
![image](https://cloud.githubusercontent.com/assets/5229241/14580248/9b02a702-03fa-11e6-892f-41de8cd0e0b6.png)

**Comment by Meow-J** [comment]
我baka了/w\\ 不过这个太像输入框消失了

**Comment by Ahrwing** [comment]
啥...

**Comment by Ahrwing** [comment]
orz 明显有个外框…

**Comment by Ahrwing** [comment]
![default](https://user-images.githubusercontent.com/5197567/35853672-22d94812-0b69-11e8-892d-439628271de7.png)
