### ISSUE TITLE
评分后评分楼层消失

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#249]
![image](https://cloud.githubusercontent.com/assets/5229241/14640493/4c280a60-0674-11e6-904d-4465c03e1713.png)
三楼不见了/w\，不过刷新就好了

**Comment by Ahrwing** [comment]
orz.. 模板的锅，理论上绝对可以修复~ 不过要找位置…~~

**Comment by Ahrwing** [comment]
2018-6-27 15:50:45 为帖子回复/评分时添加了提示，以解决操作楼层消失问题。
