### ISSUE TITLE
版主及最新回复用户名链接仍然错误

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#253]
![image](https://cloud.githubusercontent.com/assets/5229241/14765436/7a10683a-0a13-11e6-98ef-6cbb74010736.png)
转向的是http://bbs.mcmod.cn/center/CannonFotter和http://bbs.mcmod.cn/center/panda_2134

**Comment by sxjeru** [comment]
很早以前就修复了吧。
