### ISSUE TITLE
被删除的资料仍能搜索到

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#254]
![image](https://cloud.githubusercontent.com/assets/5229241/14891823/e7384538-0d9a-11e6-9e19-6bde937b110a.png)
最下面那个已经被删除过了

**Comment by AstonIceDog** [comment]
![z v u bw k52_hg9 o1 jx](https://cloud.githubusercontent.com/assets/13271372/14913553/6a1dfd44-0e36-11e6-8bbc-eece1ca8e357.png)
同，最下面一个已经被删除，点击后进入主页。

**Comment by Ahrwing** [comment]
已修复
