### ISSUE TITLE
HTML编辑器

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#257]
某些东西现有的富文本编辑器没法实现，比如改更大的字号之类的，粗体+字号解析也有点问题，微调的话HTML应该会好一点，不过这个应该是可以和富文本随时切换的，编辑时候发现问题实时修改。

**Comment by Ahrwing** [comment]
现已取消富文本编辑器允许设置字号的功能
>根据这两年的观察, 允许随意调整字号会乱套的…
