### ISSUE TITLE
关于论坛发展的两个建议

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#258]
1. 随着论坛的发展，以后将会有许多帖子，那么就要做出帖子搜索的功能。
2. MOD论坛是在MOD站基础上建立的，可以把帖子链接到MOD（貌似现在已经有了吧，不过我不知道怎么用），并且在MOD页下面添加与本MOD有关的帖子。那么就要在用户发帖子时链接相应的MOD.

**Comment by CannonFotter** [comment]
dz自带搜索，地址见传说中的百科群
然后就是那个功能需要在百科主站mod详情页里选发讨论贴才有的...

**Comment by 3TUSK** [comment]
@Meow-J 我觉得我们需要新的标签，“已实现”

**Comment by AstonIceDog** [comment]
1. 第一个群里并没有，我也没在论坛找到啊
2. 哦，第二个已经实现了，什么时候的事？

**Comment by SYNDIG1** [comment]
[bbs.mcmod.cn/search.php?mod=forum&adv=yes](url)

**Comment by Meow-J** [comment]
应该算解决了
