### ISSUE TITLE
批量上传后物品图标使用状态不更新

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#259]
上传后使用的是Base64，但这里不自动勾上

![image](https://cloud.githubusercontent.com/assets/5229241/15169260/fc35e7bc-176b-11e6-91b7-e4f1458e5c6e.png)

需要点击一下 `使用Base64码` 才能看到正在使用的Base64码

![image](https://cloud.githubusercontent.com/assets/5229241/15169261/0157d6ba-176c-11e6-843c-eb3846d113ae.png)

**Comment by Meow-J** [comment]
可以改一下显示吧，当base64存在的时候这个勾自动勾上，这样就不会出现想改图标没删base64码上传之后仍显示base64这种问题了。

**Comment by Ahrwing** [comment]
妥~
