### ISSUE TITLE
审核通过建议

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#26]
审核通过的时候最好也加一个给提交者的建议吧，有时候虽然内容没问题，但是还是很想让提交者再修改一下

**Comment by Ahrwing** [comment]
已增加~ 编辑模组/物品/教程时，会要求必填修改理由，编辑员不会显示这个窗口~
后台审核的时候可以看到编辑时填写的理由~

**Comment by Meow-J** [comment]
你关错问题了

**Comment by Ahrwing** [comment]
v3后台“不通过理由”已改成“附言”
