### ISSUE TITLE
使用markdown编辑器时预览内容不自动解析

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#261]
显示的只是文本内容，markdown格式信息没有进行解析

**Comment by Ahrwing** [comment]
目前只找到markdown转换html的API... 没有找到html反转换markdown的....

**Comment by AstonIceDog** [comment]
还有不能二次编辑

**Comment by Ahrwing** [comment]
> markdown编辑器已停止维护 将会在近期更新中移除
