### ISSUE TITLE
日志添加后顺序仍有问题

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#267]
虽然在列表里是正常了
![image](https://cloud.githubusercontent.com/assets/5229241/16355675/a699e1a2-3af0-11e6-988b-6020ff0d21b1.png)

下拉菜单选择的时候还是错乱的：

![image](https://cloud.githubusercontent.com/assets/5229241/16355670/9b08cf4c-3af0-11e6-8634-11e621cbc484.png)

后台这里也乱了：
![image](https://cloud.githubusercontent.com/assets/5229241/16355683/c2f10bbe-3af0-11e6-9406-078472ba2cf5.png)

**Comment by Ahrwing** [comment]
“最新MC版本”选项已废弃 改为“支持MC版本”
现在v3后台也可以排序了~
