### ISSUE TITLE
教程应标明版本号

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#268]
一个MOD会随着更新玩法会变得不同，如果用老版本教程来指导别人的话会让别人误入歧途的（？）。
这不是特性请求，这是缺陷

**Comment by 3TUSK** [comment]
以及，让最新版mod的教程最显眼

**Comment by Ahrwing** [comment]
这个需要由编辑者自行添加 因为无法保证该MOD中存在可选的更新日志
