### ISSUE TITLE
改进搜索功能

### ISSUE THREAD

**Issue by chr233** [Ahrwing/mcmod#272]
希望搜索的时候如果搜索不到相关模组就搜索相关物品再没有就搜索教程，而不是显示没找到等你手动选择需要搜索什么类型
另一点就是像mcbbs一样在搜索的时候提供一个过滤器，比如模组分类、模组类型

**Comment by 3TUSK** [comment]
mcbbs现在用的百度的站内搜索...

**Comment by sxjeru** [comment]
mod也不是很多，加分类没有什么意义

**Comment by mmt50** [comment]
快500了，还有其他很多的附属资料，挺多的了老兄，改进现有的搜索，哪怕是加一个高级搜索都是很有帮助的

**Comment by AstonIceDog** [comment]
mcbbs的搜索系统太差劲了

**Comment by Ahrwing** [comment]
百科搜索已改版v3.0~
