### ISSUE TITLE
多方块结构、自然生成、生物、BUFF等资料缩略图无法更新

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#276]
其它资料类型暂未测试（估计也不用测试了），已有的资料如果处于暂无缩略图的状态，补图不会有任何效果，似乎只有在创建资料时贴上缩略图才会有效。
另外经过测试，编辑员在自己的负责区域编辑资料时无此BUG。

**Comment by Ahrwing** [comment]
已修复~
