### ISSUE TITLE
物品耐久上限太低

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#277]
MC百科中物品耐久填写超过32767会自动变为32767
然而实际上有很多物品的耐久都能超过32767
比如群峦、格雷、MITE的工具都是用一次掉三位数耐久的这种计算方法，所以稍微耐用一点的工具耐久都能超过三万
IC2的碳转子耐久高达604800
MITE的艾德曼合金砧耐久更高达12697600

**Comment by sxjeru** [comment]
改这个搞不好就要换一种数据值了。。

**Comment by Ahrwing** [comment]
已解决~
