### ISSUE TITLE
主页资料标题换行错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#278]
![image](https://cloud.githubusercontent.com/assets/5229241/19350318/cd706478-9189-11e6-9421-4b102cfce10a.png)

**Comment by 3TUSK** [comment]
说起Sextiary Sector...可以考虑直译为“第六产业”。
参考第一产业 (Primary Sector)、第二产业 (Secondary Sector)、第三产业 (Tertiary Sector)、第四产业 (Quaternary Sector)、第五产业 (Quinary Sector)

**Comment by sxjeru** [comment]
它的意义是“六个产业”，并非单指一个

**Comment by 3TUSK** [comment]
构词，构词...

**Comment by sxjeru** [comment]
我错了……

**Comment by Ahrwing** [comment]
已解决~

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/23320801/371013b4-fb17-11e6-8b4f-5c1aa9b0b2f1.png)
又出来了/w\

**Comment by Ahrwing** [comment]
v3.0已解决此问题~
