### ISSUE TITLE
MC资料悬浮窗显示错误

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#281]
![image](https://cloud.githubusercontent.com/assets/21700377/19436377/4e45be20-94a2-11e6-924c-eb52c97fafe3.png)
已测试，所有“XX是YY的另外版本。”的模组都会显示YY的模组名而不是正确的。
其它没有继承关系的普通模组会直接显示“查看的**列表”，也不是一个正确的语句，删除“的”或者在“的”前加上模组名即可。

**Comment by sxjeru** [comment]
我也很奇怪，资料编辑里明明写的是合并模组，现在成了“xx是xx的另外版本”。。

**Comment by DLslime** [comment]
我觉得咱俩说得不是一回事……

**Comment by Ahrwing** [comment]
啊.. 愚蠢的错误.. 修好了~
