### ISSUE TITLE
两个图片跪了

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#284]
一个是donate界面的微信扫二维码捐款，扫了之后会提示“二维码已经过期，请发起者重新生成”
一个是主站最下方的友情链接，“百度贴吧-minecraft吧”的友链图标明显挂了，如下图所示：
![image](https://cloud.githubusercontent.com/assets/21700377/19829828/e94095c4-9e1d-11e6-8d25-41a179b1407b.png)

**Comment by sxjeru** [comment]
Minecraft中文论坛的图片也挂了。

**Comment by AstonIceDog** [comment]
百度贴吧的图片也挂了

**Comment by DLslime** [comment]
我说的不就是百度贴吧吗？orzz

**Comment by Ahrwing** [comment]
_(:з」∠)_ 友链的图片是用的mcbbs的地址…

**Comment by Ahrwing** [comment]
已处理~
