### ISSUE TITLE
物品资料添加bug

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#286]
添加的物品不会及时出现在物品列表页。
（有时是永久性）
另有一个由该bug产生的bug。。请见下图：
![image](https://cloud.githubusercontent.com/assets/20513115/19966070/0fdb533c-a205-11e6-9163-0156150acf0a.png)
![image](https://cloud.githubusercontent.com/assets/20513115/19966074/1874baec-a205-11e6-96b2-654d16d9bf8b.png)

**Comment by sxjeru** [comment]
“生物”处显示2个，
然而里面只有1个。
另一个咱几天前添加了，
到现在都没显示出来。。

**Comment by AstonIceDog** [comment]
你再去编辑一下应该就能出来了

**Comment by sxjeru** [comment]
然而我找不到那个条目，怎么编辑。。

**Comment by AstonIceDog** [comment]
你可以在个人主页-我的动态里面找到条目，或者编辑历史里面，有的可能是正在审核中？

**Comment by sxjeru** [comment]
我的动态里由于时间关系已经没了。
编辑历史里只有当日编辑的条目。
怎么办

**Comment by Meow-J** [comment]
编辑历史里面有bug，生物好像都显示不出来

**Comment by DLslime** [comment]
竹模组的生物对吧，我编辑了一下里面的“萤火虫”，审核通过后现在另一个生物已经可以显示出来了。

**Comment by Ahrwing** [comment]
缓存问题 /w\.. 批量添加的物品都不会更新缓存…

**Comment by Ahrwing** [comment]
done
