### ISSUE TITLE
支持MC版本错乱

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#288]
提交前：
![image](https://cloud.githubusercontent.com/assets/5229241/20347080/695c50e8-ac3a-11e6-937e-bae4743aae9d.png)

提交再编辑：
![image](https://cloud.githubusercontent.com/assets/5229241/20347079/66a498b0-ac3a-11e6-94c7-b80e7d6c89bf.png)

**Comment by Ahrwing** [comment]
尝试修了一下，现在应该好了~ 再核实一下吧w

**Comment by Ahrwing** [comment]
这回真的好了 [头向左侧面单手捂脸哭]

**Comment by Meow-J** [comment]
1.11的还是不行/w\

**Comment by Meow-J** [comment]
已经弄好了/w\
