### ISSUE TITLE
改进编辑量计算机制

### ISSUE THREAD

**Issue by mmt50** [Ahrwing/mcmod#289]
同一人在一段时间之内（如一天内）如果编辑了同一物品（或者同一个模组的描述，诸如此类）若干次，只记一次编辑，以防止刷编辑量的bug

**Comment by 3TUSK** [comment]
这是bug？

**Comment by mmt50** [comment]
潜在的漏洞更准确一些，总之可能需要注意一下

**Comment by sxjeru** [comment]
一天感觉太长，一小时就好。
咱作为编辑员有时候真的不好意思去多编辑几下。。
搞的被别人说是刷编辑数。

**Comment by mmt50** [comment]
就目前来说虽然还没人利用这一点，但是还是注意吧，至少像本人这种长期需要返工的总感觉哪里不对啊

**Comment by Ahrwing** [comment]
(?秘密更新) 已修复此问题ww
