### ISSUE TITLE
非编辑员无法修改矿物辞典

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#290]
非编辑员（或编辑编辑在自己负责区域之外的资料）无法修改矿物辞典，这个矿物辞典既包括物品资料拓展信息中的矿物辞典，也包括合成表具体哪格物品支持矿物辞典。
编辑员在自己的负责区域编辑资料时无此BUG（这一点和#276 如出一辙）。

**Comment by sxjeru** [comment]
矿物词典对目前的mcmod来说没多大用处了吧。
要知道有许多人浏览wiki时，
哪个物品是矿词的都不知道。

**Comment by DLslime** [comment]
你说的WIKI是单独模组的官方WIKI吧，那自然不会涉及太多OD，但百科是多模组的
OD就是为了告诉玩家哪些合成可以用哪些物品去取代

**Comment by sxjeru** [comment]
其实我是想说：不是编辑员也可以编辑矿词。

**Comment by DLslime** [comment]
你一开始想证明百科的OD完全没有存在的意义，现在又想证明这个Issue没有任何意义嘛？
不是编辑员也能编辑OD你倒是去给你负责区域以外的物品资料加OD呀

**Comment by 3TUSK** [comment]
其实...有一个比较严肃的问题：OreDict根据不同的整合也可以有不同。
换言之，即便是同一个Mod，在不同的整合环境下可能有不同的OD。这也要算？

**Comment by DLslime** [comment]
这个挺麻烦的，原版的一些物品的矿辞就是随着模组的增加而无限增多，因为一些物品的矿辞表达还没统一，一个模组给这个物品贴上一个矿辞，另一个模组可能给这个物品贴上另一个矿辞，这样一个物品就有至少两个以上的矿辞。
但百科的矿辞是“中文版”的，而且还是有限的，不能自定义的，一种物品一般只有一中文矿辞。如果一个模组的矿辞有更特殊的分支情况，在百科中也只能捡其最主要最普遍的矿辞去写。(所以百科的矿辞确实鸡肋，但也不能说是完全无用吧)

**Comment by 3TUSK** [comment]
独立的OD查询工具？i.e. 把OD信息从所有条目中剔除，然后专门做一个类似要素计算器这样的工具以供查询；如果遇到整合特有的情况也可以注明。

**Comment by DLslime** [comment]
不是，百科的OD因为不能自定义，所以根本不全，所以必须要强化目前百科的OD，比如允许资深编辑员增加新OD，才能再做一个OD查询工具(当然，前提是有编辑员去整理OD……)

**Comment by Ahrwing** [comment]
IRR已添加可以批量导入矿物词典的功能，矿物词典无需人工手动录入~
>解放双手
