### ISSUE TITLE
审核页面增加Note功能

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#291]
有些时候某些修改会不确定，会放置一下。这时候就需要一个note功能来提醒别的编辑员这个修改的问题啦。（我之前好像写过类似的issue？

**Comment by 3TUSK** [comment]
...我总觉得，应该拿git这样的系统来管理百科。只留一个分支就好，然后普通用户的请求可以看作Pull request，编辑员可以直接push，如此等等...好像脑洞太大了

**Comment by Meow-J** [comment]
又相关到 #161 上去了/w\

**Comment by 3TUSK** [comment]
我一直都支持git驱动百科站啊- -虽然我知道这样难度不小

**Comment by Ahrwing** [comment]
新后台有这项功能了 /w\
