### ISSUE TITLE
新版审核列表显示出错

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#294]
![image](https://cloud.githubusercontent.com/assets/21700377/20881187/1f443d82-bb16-11e6-8a86-79c661a0c20e.png)
如图，表格“退回理由”一栏巨宽，这里用的浏览器是WIN10的Edge，换其它浏览器的话就没有这个问题（比如Internet Explorer和安卓手机的浏览器）。
当然上述这个问题我早发现了，也不是很严重。关键就是那个“风之结晶”，应该是因为我在审核通过之前编辑了它两次，但是也不能把黑猫的记录给挖坟挖出来吧 (╯°Д°)╯︵ ┻━┻

**Comment by DLslime** [comment]
另外吐槽一点大家应该都已经发现的BUG：编辑时间和审核时间一模一样

**Comment by sxjeru** [comment]
看看edge的页面设置吧。

**Comment by DLslime** [comment]
edge又不是word，哪来页面设置？

**Comment by Ahrwing** [comment]
已修复~
