### ISSUE TITLE
百科上传图片可选添加水印&意见

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#296]
虽然水印的添加是一个好的功能，但有的时候还是过于鸡肋。
比如用作mod缩略图时。

另：
建议在编辑mod的下方提示（或强制性措施）
将用作mod缩略图的图片保存到百科相册再进行添加。
原因很简单，就是图片加载不能（缓慢），或某些未知防盗链措施。
例子：
![image](https://cloud.githubusercontent.com/assets/20513115/21263969/a1ce23dc-c3d4-11e6-9f36-ab0759115f4b.png)
像此类网站如果不进行另存为图片，那么百科mod缩略图就显示“暂无封面”。

最后想问一下，mod缩略图的解析超时时间是多久？

**Comment by sxjeru** [comment]
好吧是我不知道百科已经禁止非图床站点的缩略图了，下面那些省了吧。。

**Comment by Meow-J** [comment]
重复 #230

**Comment by 3TUSK** [comment]
重复的Issue应该关闭？

**Comment by Meow-J** [comment]
先留着吧，等解决了一起关掉

**Comment by Ahrwing** [comment]
水印暂时去掉了.. 想办法加上开关再放好了.. /w\

**Comment by sxjeru** [comment]
可我不觉得水印去掉了。。

**Comment by Ahrwing** [comment]
水印改了样式 现在看起来应该会舒服点了 :3

**Comment by Ahrwing** [comment]
png水印失真问题已解决
![水印测试](http://bbs.mcmod.cn/data/attachment/album/201712/15/141237lzrwpjcc70rr0cit.png)
