### ISSUE TITLE
模组标签删除之后页面没有更新

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#297]
![image](https://cloud.githubusercontent.com/assets/5229241/21549685/ea269be6-ce2e-11e6-8eae-a3c273d23a2f.png)
在这里已经把标签删除并提交了，但回到Mod页面时候仍然还是有原来的标签：
![image](https://cloud.githubusercontent.com/assets/5229241/21549705/05dd3c8c-ce2f-11e6-82ae-1f796b1252e5.png)

**Comment by Ahrwing** [comment]
模组标签是必填项.. /w\ 如果没填会失效的

**Comment by DLslime** [comment]
跑个题，把“多个标签用逗号隔开”改为“用回车建立多个标签”如何？

**Comment by sxjeru** [comment]
![image](https://cloud.githubusercontent.com/assets/20513115/21576985/bc397b62-cf83-11e6-9238-d4987ee90ea6.png)
这个所谓的提示误导了不少人。

**Comment by Ahrwing** [comment]
@DLslime 改好了 /w\
