### ISSUE TITLE
Markdown编辑器缺陷

### ISSUE THREAD

**Issue by AstonIceDog** [Ahrwing/mcmod#299]
如众人所知，Markdown编辑器第二次编辑会出问题。
![qq 20170108104345](https://cloud.githubusercontent.com/assets/13271372/21746870/5d6f7bb0-d58f-11e6-8f54-1ba7fc9973ea.png)

**Comment by Meow-J** [comment]
在 #261 里提过

**Comment by 3TUSK** [comment]
@Meow-J MCMOD-flavored markdown?

**Comment by Meow-J** [comment]
https://github.com/Ahrwing/mcmod/issues/19#issuecomment-134779990 /w\

**Comment by 3TUSK** [comment]
喷

**Comment by 3TUSK** [comment]
结果还是不能解决么...

**Comment by Ahrwing** [comment]
短期内无打算继续推进markdown..
原因很简单，目前编辑器状态为markdown的人数有 46 人，其中只有 29 人二次登录过。
![10](https://cloud.githubusercontent.com/assets/5197567/24892510/c2a606fc-1eaf-11e7-9eeb-81399d58cb4b.png)
基础建设还没搞好呢~ 就.. (被捂嘴

**Comment by DLslime** [comment]
那么是先有鸡还是先有蛋呢？

**Comment by Meow-J** [comment]
不，这个的问题是markdown编辑器不好用，问题太多了

**Comment by 3TUSK** [comment]
> 我的总编辑数是什么鬼

Markdown 编辑器不好用 -> 没人用 -> 拒绝修复 Markdown 编辑器 -> Markdown 编辑器不好用 -> 没人用 -> ...

**Comment by 3TUSK** [comment]
所以鸡生蛋蛋生鸡的循环怎么破...

**Comment by Ahrwing** [comment]
@3TUSK 因为现在同时可用两种编辑器，先用可视化编辑器编辑过一遍，再用markdown编辑时，里面的样式都会被清除掉.. 所以现在只支持添加时使用markdown

**Comment by Ahrwing** [comment]
> markdown编辑器已停止维护 将会在近期更新中移除
