### ISSUE TITLE
日志 + 正常的Mod介绍列表Node不显示

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#3]
![qq 20150811182311](https://cloud.githubusercontent.com/assets/5229241/9195529/168df76e-4056-11e5-924f-c0807a3bbbf9.png)

![qq 20150811182406](https://cloud.githubusercontent.com/assets/5229241/9195541/2d153f10-4056-11e5-9a1e-d33dfa38dcbc.png)

**Comment by Meow-J** [comment]
不止是这个了，太多的特性显示不出来了，像是代码什么的

**Comment by Ahrwing** [comment]
已优化样式~ 但是还没有全面测试，有BUG再反馈吧~
