### ISSUE TITLE
审核展开过大，屏幕小的情况下会很麻烦

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#30]
右边的侧边栏把展开都挡住了，还需要左右拉滚动条才能点击下一项的展开
![mc minecraft](https://cloud.githubusercontent.com/assets/5229241/9255858/9cb188d2-421e-11e5-819a-95f645a888f0.png)

**Comment by Meow-J** [comment]
话说能不能做成这种弹出式的设计：http://t4t5.github.io/sweetalert/

**Comment by Ahrwing** [comment]
@Meow-J 这个不错.. 可惜不能改大小又不支持IE8...

**Comment by Meow-J** [comment]
@Ahrwing 类似的也行/w\

**Comment by Meow-J** [comment]
话说现在审核变得更卡了

**Comment by Ahrwing** [comment]
已改成弹出式模态窗口
