### ISSUE TITLE
关于首页的最爱mod

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#300]
能否添加 移动最爱mod顺序 的功能呢？
![image](https://cloud.githubusercontent.com/assets/20513115/22634564/e6eb6042-ec65-11e6-8c8a-55b471b254f8.png)
如图右上打了爱心的mod。
由于习惯了第一列mod的排序顺序，现在新加了一个就经常点错qwq

**Comment by Ahrwing** [comment]
介个... 打算单独弄一栏出来~ 一个是如果喜欢的MOD比较多后面的就显示不了了.. 二是会和最新顶上来的MOD抢位置 - -..

**Comment by Ahrwing** [comment]
v3已更换最爱mod显示的位置~ 相关问题 #344
