### ISSUE TITLE
完善搜索范围

### ISSUE THREAD

**Issue by Iriasu** [Ahrwing/mcmod#301]
百科早在原有基础上增加了新的资料类型，希望能够同时在搜索范围中增加对应的选项。

主要是今天搜索「gear」时发现，[这项资料](http://www.mcmod.cn/item/33498.html)原本属于「世界」类型，而在百科搜索中却被划分到了「物品」的范围下。

**Comment by Ahrwing** [comment]
已将“物品”改为“资料”.. 之前物品区改成资料区时忘改了这里来着..

**Comment by Iriasu** [comment]
所以增加对应的选项？

**Comment by Iriasu** [comment]
可能我描述的不够清楚，希望能在搜索范围里增加世界/多方块结构/BUFF这些选项

**Comment by Ahrwing** [comment]
能理解啦..  我在想布局排版问题所以没回复 /w\..

**Comment by Ahrwing** [comment]
如果资料加了对应选项，模组也许也可以加一个

**Comment by Ahrwing** [comment]
![](http://i1.piimg.com/567571/549aaff7dc4c6f0d.png)
/w\\ 弄好了~ 先临时这样吧.. 我需要研究一下怎么用DZ的搜索引擎索去索引百科资料~

**Comment by Iriasu** [comment]
百科现在应该是全文搜索的吧？这样导致了搜中文关键词比搜英文关键词的精度要低很多，根据搜索结果的资料的名字中是否出现了关键词来判断的话。

我尝试以某种方式搜索，「thaumic」和「arcane」，分别与「神秘」和「奥术」/「奥法」对应，结果前者相关性在0.736842左右，后者只有0.409853左右。

**Comment by Ahrwing** [comment]
是的.. 现在的搜索结果排序毫无逻辑可言.. 搜TE竟然第一个不是TE
所以需要一个现成的搜索引擎去做这件事儿, 而不是自己去写 (

**Comment by Iriasu** [comment]
所以二次开发mediawiki这个问题会不会就没有了呢

**Comment by Ahrwing** [comment]
如果DZ索引无法使用的话 可以尝试二开mediawiki的搜索模块

**Comment by Meow-J** [comment]
现在的算法是什么呢，如果把资料标题属性的索引优先级提高应该就能改善很多
