### ISSUE TITLE
受多个模组组合影响的合成表

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#302]
比如Warp Drive这个模组的机器的合成表由你安装了哪些模组决定，别的什么都没装可能有一个合成表，装了IC、EIO、TE三者中的一个就会使用它们的机器框架，安装前三者两个以上的模组由会出现不同的合成表，比如机器框架会用IC的，锭会用TE的之类的，会有一个优先级规定最后到底用哪个模组的哪个材料合成出这个机器。
这么复杂的合成表，百科当前是很难表达出来的，能不能做一个系统让百科的浏览者自己勾选模组组合然后输出最终的合成表？

**Comment by Iriasu** [comment]
第一种在当前的百科是很容易表达出来的，只是个直观程度的问题。

这种情况相似于，MFR和TE和EIO同时存在时，TE或EIO的机器框架会覆盖MFR的机器框架。只需要增加一个合成表再说明就行了，可以参考FTB维基的做法: [http://ftb.gamepedia.com/Auto-Anvil#Recipe](url)

如果我没理解错的话，Warp Drive中框架会被何者覆盖取决于固定的优先级，这时候只需要列出四种情况就没问题了。

**Comment by Ahrwing** [comment]
"自己勾选模组组合然后输出最终的合成表" 是可以实现的
但它只能作为一个筛选，而模组组合是筛选条件
也就是说，为了能够显示出筛选的结果，依然需要手动为物品添加每种情况的合成表

**Comment by DLslime** [comment]
@Iriasu 哪来的第二种？

**Comment by Iriasu** [comment]
@DLslime 锭

**Comment by DLslime** [comment]
@Iriasu 我不知道你是怎么理解的，我举得例子即使能被分解成两个也都是为说明优先级服务的

**Comment by Iriasu** [comment]
@DLslime 我想问的是，一种锭在IC EIO TE里都有，就不能在Warp Drive的合成表里通用？

**Comment by DLslime** [comment]
@Iriasu 歪楼提问不予回答

**Comment by Iriasu** [comment]
@DLslime 我还真没意识到自己歪楼了，按照你的意思三个模组的不同组合会导致Warp Drive的合成表使用不同模组中的锭，然而一般这种情况都会被矿辞解决。

另外我想问我之前说的一大段话你难道只注意到了最后一句？

**Comment by DLslime** [comment]
@Iriasu 整个都没提矿辞半个字，某些人非要强加联系，我能怎么办？

**Comment by Ahrwing** [comment]
@DLslime 他说的是第二种啦..

**Comment by Ahrwing** [comment]
@Iriasu 你也别说了.. = = 已得出题主问题的答案结果是：可以

**Comment by Ahrwing** [comment]
噢.. 哎呀我怎么把问题关了.. 还没解决呢..

**Comment by Ahrwing** [comment]
已完善“模组要求”与矿辞功能。
