### ISSUE TITLE
模组单

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#308]
取消现有的“合并模组单”功能，并改为：

可建立一个模组单，并可将现有模组添加至模组单，添加至模组单的MOD不会直接在首页显示出来，而是显示模组单的名称。

例：
格雷科技 (模组单)
{
  格雷科技4(MOD),
  格雷科技5(MOD),
  格雷科技6(MOD),
  科技重生(MOD)
}

这样的话.. TE/BC/拔刀剑那些分part或是一堆扩展包的MOD处理也有着落了~

**Comment by sxjeru** [comment]
oops，百科终于要向FTBwiki学习了么。

**Comment by 3TUSK** [comment]
不过SlashBlade的话，扩展并非本体，还是要算独立Mod的，但FTBWiki的Navbox现在有个趋势就是同时索引扩展...

**Comment by Ahrwing** [comment]
只有“一个系列”的MOD才需要合并模组单
而 处理 附属/拓展/联动/前置 的是另外一个功能了

**Comment by Ahrwing** [comment]
弄好了 =w=

**Comment by Meow-J** [comment]
啥/w\

**Comment by Ahrwing** [comment]
@Meow-J 现在叫“合辑” /w\
