### ISSUE TITLE
审核铝方块报错

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#31]
之前有修改的时候点击通过就已经报错了，现在提示已经是审核过后的版本点击通过还是报错
![qq 20150814232623](https://cloud.githubusercontent.com/assets/5229241/9277362/1ea0d9a2-42dc-11e5-9126-927980c8d291.png)
 都是你的错！截图截不全w

**Comment by Ahrwing** [comment]
已修复
