### ISSUE TITLE
重新编辑时的错误=w=

### ISSUE THREAD

**Issue by zomb-676** [Ahrwing/mcmod#310]
在 ![image](https://cloud.githubusercontent.com/assets/26162862/23548058/be159e64-0040-11e7-9103-47fb89de2b28.png)
中点击
![image](https://cloud.githubusercontent.com/assets/26162862/23548106/f3e2c7a6-0040-11e7-82c5-1ee3ab5b213c.png)
中的重新编辑时会跳回百科主页
这是使用方式不正确还是我理解错误了？。。
=w=

**Comment by Ahrwing** [comment]
任何"添加"的操作目前不支持重新编辑...

**Comment by Meow-J** [comment]
那把添加项目的重新编辑删掉啦 /w\

**Comment by Ahrwing** [comment]
ouo 好了..
