### ISSUE TITLE
关于“模组关系”

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#311]
`前置：本模组必须依靠这些前置模组才能启动游戏。
附属：本模组可以脱离这些模组启动但是功能不完整，例如无法使用原MOD中的物品。
联动：两个模组之间皆可独立存在并启动游戏，可以使用对方的特性完成一些工作。
拓展：这些模组向此模组追加了一些东西，可有可无且无法独立运行。`

A是B的拓展，反过来说B就是A的前置。但目前给A模组添加前置模组B，在B模组界面下会显示“此模组是A模组的前置”；但给B模组添加拓展模组A，A模组界面下不会显示任何关于B模组的信息，如下两图所示：
![image](https://cloud.githubusercontent.com/assets/21700377/23656873/6f9241b4-0376-11e7-8542-0bba5caf847c.png)
![image](https://cloud.githubusercontent.com/assets/21700377/23656894/8541cf7a-0376-11e7-9a02-e3c27f2baa5f.png)
在“物流管道”模组的界面下，没有任何有关“建筑”模组是其前置模组的信息。

BTW：我还是不能很好地找到“附属模组”和“联动模组”的区别……

**Comment by 3TUSK** [comment]
...我一般这么分：
硬依赖：运行A Mod必须要先装B Mod
软依赖：运行A Mod不必装B Mod但装了会有新内容
完。

**Comment by DLslime** [comment]
我也是这样想的，重生的这个标准出来之前我个人的定义是：拓展=附属，然后联动就是双方互不以对方依赖……

**Comment by Ahrwing** [comment]
[工业2] 是 [核电控制] 的前置 、 [神秘时代4] 是 [神秘工匠] 的前置
[生长工艺-蜜蜂] 是 [生长工艺] 的附属 、 [红石计划-逻辑] 是 [红石计划] 的附属
[匠魂] 与 [热力膨胀] 存在联动关系 、 [神秘时代] 与 [拔刀剑] 存在联动关系
[更多管道] 是 [建筑] 的拓展 、 [更多蜜蜂] 是 [林业] 的拓展

**Comment by 3TUSK** [comment]
...异议，生长工艺|蜜蜂是生长工艺的模块 (Module)，红石计划-逻辑同理。

**Comment by DLslime** [comment]
附属指的是一个模组的官方拓展吗？比如[热力管道]是[热力膨胀4]的附属这样的……
另外重生你是不是一开始把附属和拓展搞反了，不是的话就是我记忆混乱了/w\

**Comment by 3TUSK** [comment]
@DLslime 所以这么多用词本身就是个错误啊...

**Comment by Ahrwing** [comment]
@DLslime /w\ 改回来了..

**Comment by Ahrwing** [comment]
@3TUSK 改了一下.. 生长工艺那些的确算是拓展...

**Comment by 3TUSK** [comment]
我觉得强行把分模块的Mod的每一个都算扩展是在耍流氓...

**Comment by Ahrwing** [comment]
@3TUSK 这叫模块化 (误)

**Comment by DLslime** [comment]
不对，严格来说 [热力管道] 和 [热力膨胀4] 是互为拓展模组的关系，它俩有且仅有共同的两个前置模组 [热力基本] 和 [cofhcore] ，所以应该说 [热力膨胀4] 是 [热力基本] 的附属这样？

**Comment by Ahrwing** [comment]
[热力膨胀4] 是 [热力基本] 的拓展.. 因为 [热力基本] 在脱离了 [热力膨胀4] 以后可以独立运行，并且在 [热力基本] 本体中没有无法使用的物品~

**Comment by Ahrwing** [comment]
好像有点乱..  这样的话热力膨胀4就不存在了

**Comment by DLslime** [comment]
那就是要看前置模组是否存在不安装某个官方拓展就无法使用的物品，如果有那个官方拓展模组就属于附属模组？

**Comment by Ahrwing** [comment]
![Uploading w.jpg…]()

真是的.. 好麻烦~! 干脆去掉“附属”好了.. 要改趁早改.. 不然以后改就麻烦了...

**Comment by 3TUSK** [comment]
果然还是因为“附属”和“扩展”没有严格定义吧...

**Comment by Ahrwing** [comment]
是 =-= 它们的分界线在于哪些东西是"理应"出现在某mod中的
