### ISSUE TITLE
关于MOD之间的关系结构改版设想

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#312]
首先，目前百科的状况是：
![cg oc 8r 4vas9 g ant](https://cloud.githubusercontent.com/assets/5197567/23660285/e05dd162-0383-11e7-8d81-0b2f77edd127.png)

是的，它很糟，所有MOD都堆在一起，随着MOD的增加，凌乱程度成倍增长。
但它即将改变：

![q5d3_tryp5eta1 e d1 j](https://cloud.githubusercontent.com/assets/5197567/23660416/5696cee2-0384-11e7-8b71-10679cb50f28.png)

做成这样是不是干净/清晰多了？这是本周计划中的下一个功能！

---------------------------------------

但我认为还能做得更好，只不过需要付出代价……

![x y9t kh s d xhx tbqf5](https://cloud.githubusercontent.com/assets/5197567/23660249/c0555b1a-0383-11e7-80b0-3c2f649cd8e6.png)

这是一个比较远的想法，将所有MOD模块化，每个MOD拥有自己的专区，每个版本分为一个MOD，子MOD独立出来，这样会有许多工作要做，也会改变现在的编辑方式和习惯，所以不推荐现在立即转型…

**Comment by 3TUSK** [comment]
我一直坚信“子Mod”的概念很容易被滥用...有办法严格定义吗？

**Comment by Ahrwing** [comment]
@3TUSK 按官方/非官方来定吗

**Comment by 3TUSK** [comment]
也不妥。Thermal Foundation本身是独立的Mod，Thermal Dynamics本身也无需依赖Thermal Expansion。

**Comment by mmt50** [comment]
个人觉得在API和/或某些必要物品是依赖某些mod才能运行的mod符合“子mod”的概念吧

**Comment by 3TUSK** [comment]
也不太对。
举个罕见点的例子：[一个我还在开发的Mod](https://github.com/3TUSK/IndustrialMachine)，本身要依赖[Shadowfacts' Forgelin](https://github.com/shadowfacts/Forgelin)，但这两者之间并无所谓的“子Mod”的概念...我不是十分清楚你说的子Mod到底是什么概念，所以我这个例子也不一定完全适用。

**Comment by 3TUSK** [comment]
说这么多其实就是为了说明这个设定本身就是天坑...

**Comment by Ahrwing** [comment]
@mmt50 TE的例子很明确… 既是狭义上的依赖又是广义上的子MOD...

**Comment by mmt50** [comment]
大约是两点
1.在mod的编写中，使用了另外的mod提供的方法等内容
2.此mod的内容中，需要其他mod的某些材料才能合成一些关键性物品，而在无此mod的支持下自身没有替代合成的方法

其实那些缺少了XX mod就直接让mc报错的应该就是吧，也就是1的情况，我是这么想的

**Comment by 3TUSK** [comment]
@mmt50 其实就一点：缺了要么能工作（有额外兼容），要么不能工作（硬性依赖）

**Comment by mmt50** [comment]
嗯，是的

**Comment by 3TUSK** [comment]
于是我想到了Curseforge的处理方式：Required Library和Optional Library，[例子](https://minecraft.curseforge.com/projects/thermalexpansion/files/2390237)

**Comment by mmt50** [comment]
@3TUSK 大工程啊，百科里面，作为library的mod不多吧，需要加一波才能这么来？

**Comment by 3TUSK** [comment]
纯lib的确不多。

**Comment by forestbat** [comment]
其实TE分类本身就是约定俗成的一个东西，TD尽管可以脱离TE，但考虑到历史的进程，以前根本是一个，现在大多数情况下依旧是捆绑安装，大家也更多地认为是，TF TE TD合在一起才是完整的TE（常见表述都是TE如何如何而没把TD和TF算上）。
对于同一个模组拆分出来的子模组（我不清楚TE和TF有没有拆分过但是确实都是thermal系列），完全可以在一个分类下，更多的是照顾习惯而不是看它们究竟干了什么……

**Comment by 3TUSK** [comment]
约定俗成的东西难道不需要与时具进吗？以及TF基本是TE的各种基础材料拆分的结果。现在的TE甚至都没有红石传导传输接收线圈了（都加进TF里了）。另外，重复声明，TF是独立Mod——你可以为了它的对TiC兼容而专门加TF然后根本不用TE，这样可以出一个主打TiC的包。（我曾经这么做过但那个包夭折了）

**Comment by forestbat** [comment]
可以归可以，但是实际玩的时候，一般都是全部装上这个系列才算完整，或者说，给大多数人感觉的完整——是的，这样分的逻辑比较混乱，以至于编辑者需要再三斟酌模组关系，出于编辑工作简便，我感觉还是维持老想法好一些，至少不会引发什么严重的不认同。

**Comment by Iriasu** [comment]
百科是面向玩家"整合"还是面向mod的问题 =. =

**Comment by Ahrwing** [comment]
@lriasu 玩家整合可能会有多个版本甚至会撕起来 如果面向mod则可以避免这个问题

**Comment by Iriasu** [comment]
@Ahrwing 别和我说啊…… 我没什么意见

**Comment by Ahrwing** [comment]
@Iriasu 傲娇是种病 (´･Д･)」

**Comment by Iriasu** [comment]
@Ahrwing 只是和森林蝙蝠解释下而已

**Comment by Ahrwing** [comment]
话说爪机上不能修改内容… 把I打成L什么的太丢人了…=A=

**Comment by 3TUSK** [comment]
@Ahrwing 已改

**Comment by Meow-J** [comment]
这个可以搞成一个单独的东西啦，像是 Mod Set 什么的。要在 Mod 类型的资料层面上连接起来会乱很多。

**Comment by 3TUSK** [comment]
modlister.com ?

**Comment by Meow-J** [comment]
不是啦，仅仅是相关 Mod 的集合。

**Comment by Meow-J** [comment]
就是把目前设想的新结构实现为一个新的对象，包括一个 Mod 相关的所有能够联动的 Mod，与 Mod 资料分开，这样能避免依赖的一系列问题。而且这样那种只加相关合成表的低程度联动 Mod 来说实施起来也很方便，只要链接一下就行了，还是避免依赖那堆问题。

**Comment by Meow-J** [comment]
其实还是专区啦，不过这个不是 Mod资料 这个类型了。

**Comment by Meow-J** [comment]
主要想把 is-a 关系转变为 has-a 关系

**Comment by 3TUSK** [comment]
还是想不太明白...我觉得只需要Dependency和Compatibility二元划分就够了？还是说我又掉进思维定势里了？

**Comment by Ahrwing** [comment]
>部分设想已由模组关系实现
