### ISSUE TITLE
模组作者/团队栏目改善

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#313]
作者/团队 => 制作组
添加制作组时 直接搜索选择全mod范围内已存在的制作组成员 没有则可以添加新制作组成员 
允许选择主要职位 组长/综合/策划/程序/美术/音效/模型/维护
改搜索的时候记得加按modder搜索

~~~可以创建并访问modder的页面 可以申请绑定百科ID~~~

**Comment by 3TUSK** [comment]
~~如何说服Modder来注册百科~~

**Comment by Ahrwing** [comment]
~~~@3TUSK /w\ 没有绑定百科ID也可以显示名字和介绍嘛 ~~~

**Comment by Meow-J** [comment]
好麻烦，又要变成日志那样了/w\

**Comment by forestbat** [comment]
@3TUSK 很好这是一个很有价值又有难度的挑战……

**Comment by limuness** [comment]
期待完工的那天啊！

**Comment by mamaruo** [comment]
2021年在QQ群里提出“独立作者页”的时候，我怎么也不会想到会推动4年前提案，让它变为了现实。
![image](https://user-images.githubusercontent.com/37480168/131306374-1e89dff9-7226-49b7-851f-e576b7efe590.png)
