### ISSUE TITLE
“自动链接”优先链接本模组下的资料

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#315]

**Comment by Ahrwing** [comment]
这个老早就想过 XD
然而貌似被遗忘了……

**Comment by Ahrwing** [comment]
...and...  DONE!

**Comment by 3TUSK** [comment]
搞来搞去居然是重复的？#99 @Meow-J

**Comment by DLslime** [comment]
搜索的时候没用“牛排”这个昵称，不过我确实对这个issue有点印象……
另外还有一个相对次要的特性请求：和“模组关系”相结合，比如本模组优先级最高，然后是前置模组，再然后是联动模组……这么一个层层递进的检索/w\
