### ISSUE TITLE
关于目前的合成表编辑

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#316]
感觉合成表编辑页的人性化做的较差，能否自定义编辑页设置呢？
比如现在的物品显示最大数量貌似固定了100，我感觉不够，毕竟没人会去打全物品名，但有些人又希望更少（配置原因）。
还有这搜索功能。跨mod搜索？我感觉很不合理，不如边上加一个选项，可选是否跨mod搜索。
然后就是搜索框能否支持多个关键词搜索？
比如搜“铜锭,锡锭”就出来两种结果。
还有希望能在物品页与搜索页之间切换。

- [ ] 可更改编辑页物品显示数量
- [ ] 可选是否跨mod搜索
- [ ] 多关键词搜索 功能追加
- [ ] 可切换搜索页
- [ ] （另）背景音乐外链 功能追加

以上为个人观点，有失多虑请谅解，也请酌情考虑。

**Comment by Ahrwing** [comment]
1.更改页面显示数量没必要… 填个9999 和不限制没区别
2.已添加单独模组内搜索选项卡~
3.多关键词用在这里不如去研究一下搜索系统的拆字搜索..
4.搜索页在底下.. 物品页在顶上.. 两个东西是在一个页面里的 = =..
5.这个和合成表编辑无关.. 可以另开issue

**Comment by sxjeru** [comment]
![image](https://cloud.githubusercontent.com/assets/20513115/24077155/7feec066-0c7f-11e7-85c0-c790b766e501.png)
。。。
好吧反正单独mod搜索功能加了，目的达到了。
谢了。
