### ISSUE TITLE
百科背景音乐

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#318]
知道百科的状态栏（没别的叫法了。。）上有个音乐播放器，目前是废弃状态。
当然即使它能用我也不看好了。
可能是xml没清？里面的歌单还在，搜索之后听了几首，感觉无感&无聊。

下面是重点：
- [x] 百科添加背景音乐
- [ ] 歌单自定义
- [ ] 背景音乐控件支持
- [ ] 背景音乐允许外链
- [ ] 不用flash控件
- [ ] 不出其他特性

同样的酌情选择，毕竟我没去研究过背景音乐，靠直觉提的意见。

**Comment by Meow-J** [comment]
其实那个xml文件就在repo的根目录

**Comment by 3TUSK** [comment]
> repo
每次开百科都会自动拉取？？？

**Comment by Meow-J** [comment]
百科那份是拷贝啦

**Comment by Ahrwing** [comment]
现在音乐已经可以播放了
