### ISSUE TITLE
[需求] 自动关键字检测

### ISSUE THREAD

**Issue by cfvbaibai** [Ahrwing/mcmod#32]
各类百科的一个最基本功能就是能自动检测出文章里的关键字并自动添加链接（例如文章作者只需在文章里写上“红石”，MCMOD能自动检测出这是一个关键字并且添加链接到“红石”条目“）。现在MCMOD的攻略文章并没有这个功能，每次都要手动添加链接给关键字非常麻烦

**Comment by Ahrwing** [comment]
以前这样做过，但是文章中会出现一大片链接…… 后来改成选中一键自动添加链接的形式（就是编辑器里的牛排）再一次更新中，偶然消失得无影无踪…… 这个问题目前正在解决中……

**Comment by Meow-J** [comment]
重复 #6

**Comment by Ahrwing** [comment]
已经把牛排加回来了~ ww
