### ISSUE TITLE
拼音字母检索自适应

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#320]
![image](https://cloud.githubusercontent.com/assets/5229241/24561183/65504f4c-1678-11e7-8507-b2ebc69cd18b.png)
这块，每点一下字母应该能够自动 resize的，现在这样无用的空白太多了

**Comment by Ahrwing** [comment]
会被右边撑开的...

**Comment by Ahrwing** [comment]
大小砍了一半 现在应该好些了 /w\
