### ISSUE TITLE
字体兼容性问题

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#322]
![image](https://cloud.githubusercontent.com/assets/5229241/24562237/ae9d8a76-167c-11e7-913c-4d03e53eabf7.png)
现在只有一个微软雅黑，如果没有的话就会被替换成其他字体了，于是在Linux上英文就很难看。在后面加一个 `sans-serif` 吧。

**Comment by 3TUSK** [comment]
`sans-serif`对应的中文字体是？

**Comment by Meow-J** [comment]
中文倒没有关系，至少`sans-serif`不太会对应到宋体之类的

**Comment by Meow-J** [comment]
这个很简单就能弄好的

**Comment by 3TUSK** [comment]
~~@Meow-J 我要`Source Han Serif`~~

**Comment by Meow-J** [comment]
如果要的话也是noto sans(source han sans)，而且只是作为无法显示中文的备用字体

**Comment by Ahrwing** [comment]
好了 /w\
