### ISSUE TITLE
Banner 文字被挡住

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#324]
![image](https://cloud.githubusercontent.com/assets/5229241/24563266/537076e6-1680-11e7-8264-f13c7e8d4133.png)
还有这个了解更多
![image](https://cloud.githubusercontent.com/assets/5229241/24563275/5a5465ee-1680-11e7-954f-5d3df03aaa69.png)

**Comment by Ahrwing** [comment]
这个只会在今天显示. 明天就没啦..
