### ISSUE TITLE
版本检索排序

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#325]
![image](https://cloud.githubusercontent.com/assets/5229241/24563325/83888346-1680-11e7-944c-0a6ff59cb192.png)
1.11.2 1.10.2 1.9.4 1.8.9 1.7.10 1.6.4 1.5.2 1.4.7 1.3.2 1.2.5 之后第二行再是不常用版本

**Comment by Meow-J** [comment]
好像还需要能够后台修改，否则更新会很麻烦

**Comment by Ahrwing** [comment]
![20](https://cloud.githubusercontent.com/assets/5197567/24577434/293c97ee-1700-11e7-9b65-d81c1e091d86.png)
弄好了~ 顺便..后台是可以改的w

**Comment by Ahrwing** [comment]
1.3.2 已加 √

**Comment by Ahrwing** [comment]
没问题的话就关掉吧 /w\

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/24577720/97816bf8-1705-11e7-8a68-3a03299c4a68.png)
 
哪里又出错了，每个版本里面最多只有这么多MOD了

**Comment by Meow-J** [comment]
后台更改在哪里？/w\

**Comment by Ahrwing** [comment]
介个没加到后台里 只能在数据库里改…

**Comment by Ahrwing** [comment]
另 不是bug 是修复了一个bug 之前能显示出范围之外的mod

**Comment by Meow-J** [comment]
每个版本的Mod数量都是这么多

**Comment by Meow-J** [comment]
你在仔细看看

**Comment by Ahrwing** [comment]
检查了 没问题

**Comment by DLslime** [comment]
这个没有翻页之类的功能吗……

**Comment by Meow-J** [comment]
现在好了
