### ISSUE TITLE
编辑状态滚动条超链接颜色过浅

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#326]
![image](https://cloud.githubusercontent.com/assets/5229241/24563452/e81f285a-1680-11e7-8dec-bcc9f24bab21.png)

2.0：
![image](https://cloud.githubusercontent.com/assets/5229241/24563494/0a687eca-1681-11e7-9563-87a2eb0c0be9.png)

**Comment by Ahrwing** [comment]
总览v3.0页面 里面没有一处超链接是蓝色的… 于是决定改成....

**Comment by Ahrwing** [comment]
好丑… 还是改成标准的#0066CC好了..

**Comment by Ahrwing** [comment]
没问题的话就关掉吧w
