### ISSUE TITLE
可选显示语言

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#327]
指的是 Mod 名称的显示语言，现在这样子有点太乱了
![image](https://cloud.githubusercontent.com/assets/5229241/24563803/43c169a6-1682-11e7-84ed-85376943126d.png)

这样子舒服多了（不过好像还是哪里有点奇怪）：
![image](https://cloud.githubusercontent.com/assets/5229241/24563889/9d88e6a8-1682-11e7-8099-1327cedba603.png)
![image](https://cloud.githubusercontent.com/assets/5229241/24564048/292b9048-1683-11e7-98b1-a465c066b354.png)

如果没有原名的话需要从中文继承。

**Comment by Ahrwing** [comment]
由于涉及SEO 这个会考虑加入”偏好设置”中

**Comment by Meow-J** [comment]
这个需要能够随时切换啦

**Comment by Meow-J** [comment]
需要能够方便检索使用

**Comment by Ahrwing** [comment]
@Meow-J 如果不是满足部分人的美观需求.. 那么此举并无意义.. /w\\

**Comment by Ahrwing** [comment]
已加入了换行~ 现在中文名和英文名各占一行w
