### ISSUE TITLE
合集功能拓展

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#328]
见 https://github.com/Ahrwing/mcmod/issues/312#issuecomment-285683309

主要是合集内容的进一步细分。

我现在设想的是合集里面的Mod大概分以下几个小分类（名称未确定）：
- 本体：Mod本体（可多于一个），如果是系列合集的话则添加一个系列的所有Mod
- Addon：基于本体进行拓展的Mod
- 依赖：本体运行所需的依赖 Mod（Forge除外）
- 联动：另外的独立Mod，并不是基于本体，但是如果加入的话本体Mod会增加相关的合成表，或者联动Mod会增加使用本体Mod物品的合成表。或者是能源能够互通，或者是本身就有IMC
- 复刻：类似于RP的那一堆啦

之后，每一个分类里面应该是能够支持添加合集的，这样系列的合集就不用添加那么多东西了。

拿GT来举个例子吧

GregTech（仍是一个合集，但用作系列合集）：
- GregTech 5（合集）：
    - 本体：GT5
    - 依赖：IC2
    - Addon：ExGregilo等
    - 联动：PFAA等，这个太多了，见[这个](https://gregtech.overminddl1.com/com/gregoriust/gregtech/gregtech_1.7.10/index.html)
    - 复刻：GT5 Unofficial（合集）等
- GT6（合集）
- GT4（合集）
- ...

**Comment by 3TUSK** [comment]
...如果有合集，一定不要把联动算进去，肯定会出问题的。

**Comment by Ahrwing** [comment]
合辑中的其中两个本体各自都有不同的Addon肿么办..
有一个解决办法就是 不用把前置/拓展/联动交给合辑，而是在每个本体底下显示各自的关系

**Comment by Meow-J** [comment]
所以我说分类里面需要支持合集啦

**Comment by Meow-J** [comment]
看GT那个例子，GregTech 5 是一个合集，不是一个 Mod。

**Comment by Ahrwing** [comment]
@Meow-J GT5不是MOD吗……

**Comment by Meow-J** [comment]
GregTech 5（合集）：
- 本体：GT5 **<- 这个是Mod**
- 依赖：IC2
- Addon：ExGregilo等
- 联动：PFAA等，这个太多了，见这个
- 复刻：GT5 Unofficial（合集）等

**Comment by mmt50** [comment]
广度与深度的区别？话说这样的话模组关系是不是可以进一步完善？我感觉这个可以归到模组关系那个功能里去？

**Comment by Meow-J** [comment]
这个想法就是在那个issue里提出来的

**Comment by Ahrwing** [comment]
这样的话大部分mod都能算是一个合集了...

**Comment by 3TUSK** [comment]
我总觉得@Meow-J试图用Venn图来表示树状的关系...

**Comment by DLslime** [comment]
现阶段似乎没必要把树杈分得那么细，比如现在GT5的编辑员就不愿意把GT5分成GT5、GT5U、GT5E三个部分。

**Comment by Meow-J** [comment]
我主要考虑的还是模组依赖的问题。  

这个不是Venn图，很明显能看出来根和分支关系的，这是个用于表示 **拥有关系** 的树，合集的每一个分类 **拥有** Mod，Mod为树的最底部分支，也就是末端。（见Interface的关系，每个Mod都看作一个Interface）

---

如果把依赖拆分到 Mod 本身的话，这就变成了一个 **继承关系** 的树（如果选定一个Mod作为根的话，不考虑Addon，Addon只是需要在更高的地方选择根），每个 Mod **继承** 有它的依赖，依赖可能还需要再继续继承下一个依赖。（这种模式就类似于 Multiple inheritance）

如果要这样做的话，依赖可能有两种选择：

### 第一种

依赖：
 - NEI
    - 依赖：
        - CCC

这样子是符合继承关系的，但是这样的话也就意味着 **依赖** 中并没有包含 本体（即Mod）运行所需的全部依赖。

### 第二种

依赖：
- NEI
    - 依赖：
        - CCC
- CCC

这样子能够解决上面提到的问题，但是这造成了下面这种继承关系：
![a](https://cloud.githubusercontent.com/assets/5229241/24584915/69748c3a-17b0-11e7-8c02-feca61e9af45.jpg)

如果要一直延伸下去的话是会造成混乱的（当然，可以直接遍历第一种的继承树来自动生成所需要的依赖，这样也是不错的解决方案，但什么时候需要遍历可能会需要一些思考）。

---

我这里提出来的方案是在弱化继承关系，由于我定义了依赖为**本体运行所需的依赖Mod**，也就是说依赖里面包含了本体（即Mod）运行所需的**全部**依赖（这里不能是合集）。但和第二种关系不同，Mod 为树的末端，并不会继续往下衍生，也就是说依赖分类的深度永远为1，这样就与继承关系本质上分开了。这样可能会需要非常多的合集（当然并不需要是这个名称，我当初在 #312 思考的时候是 Mod Set，好吧也差不多/w\），但构建应该是只要会做整合包的人都能够很短时间内轻松完成的。

**Comment by DLslime** [comment]
我又想到了“或”关系的依赖：比如A模组依赖B模组与C模组（B模组和C模组是A模组的前置，但B模组和C模组相互独立，互不作为对方的前置）和D模组依赖E模组或F模组（E模组和F模组至少有一个才能运行D模组）是不一样的。第二种情况我觉得不管用哪种继承关系的树都会很混乱

**Comment by 3TUSK** [comment]
怎么可能有“或”关系的依赖？

**Comment by DLslime** [comment]
比如Gergtech6依赖IC2-EXP or IC2-Class
比如Redstonic依赖TE4 or EIO
比如techgun依赖(cofhlib or cofhcore)and chisel

**Comment by 3TUSK** [comment]
...
1. Redstonics不依赖TE4也不依赖EIO
2. Techgun这样一看应该依赖CoFHLib（准确地说，RF？）
3. GT6依赖的是IC2的API。

**Comment by DLslime** [comment]
Redstonic 算是官方欺诈了

这个问题解决了，那有些addons又需要的是完整的IC2-EXP模组而不能只有IC2的API，要描述的话这似乎又要变成Venn图

**Comment by 3TUSK** [comment]
@DLslime 真正接触过基于Forge的Mod开发的都会明白，依赖只有两种：被依赖（dependent）和依赖（dependency）...

**Comment by DLslime** [comment]
是说文氏图和树状图“杂交”啦/w\
不过能实现的话好像没什么不行……

**Comment by Meow-J** [comment]
这不是讨论内部实现的问题，在这里依赖的最基础元素是一个Mod，并不是一个API。

**Comment by DLslime** [comment]
又回到原点了，讨论的单位是完整的模组不就又出现依赖模组或且非排列组合一大堆的情况了吗？

**Comment by Meow-J** [comment]
本来就不应该往API层面去想啦/w\。我觉得或和非得关系不必要添加，这类的Mod数量很少的，在介绍里提出来应该就行了

**Comment by DLslime** [comment]
抱歉我总是考虑一种极特殊的情况……

**Comment by Ahrwing** [comment]
合集功能已废弃
>现有合集重定向至了幸运的子MOD

提到的部分功能已被模组关系所替代~
