### ISSUE TITLE
合集页面改版

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#329]
![image](https://cloud.githubusercontent.com/assets/5229241/24565634/a03fd810-1688-11e7-9d79-a3e868bc142d.png)
不知道为什么，就是非常乱（是不是那一堆分享按钮的锅）

这里也最好去掉，这些东西只要点进Mod就能看到了：
![image](https://cloud.githubusercontent.com/assets/5229241/24565684/ea0e0782-1688-11e7-8da1-888e919424ba.png)

另外，我觉得需要改成树状结构，分成类似主页的面板，见 #328

**Comment by 3TUSK** [comment]
真的有人用过那些分享按钮吗...

**Comment by 3TUSK** [comment]
就不能把分享做成下拉菜单或弹窗么...

**Comment by Ahrwing** [comment]
合集功能已废弃
>现有合集重定向至了幸运的子MOD
