### ISSUE TITLE
新的审核窗口经常会在页面的最底部生成

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#33]
![- mc minecraft](https://cloud.githubusercontent.com/assets/5229241/9290159/ef479df0-43ba-11e5-9b1e-92fa81f02419.png)

**Comment by Ahrwing** [comment]
这是弹出插件的问题 /w\.. 以后能找到其他弹出插件代替就好了~ 
那个sweetalert不错 就是不能调整宽度..

**Comment by Meow-J** [comment]
仍未修复，还是留着做备注吧

**Comment by Ahrwing** [comment]
现在改到上面啦~ (感觉以后还会改..

**Comment by Meow-J** [comment]
现在的更不正常啦

**Comment by Ahrwing** [comment]
现在的是固定在顶端.. 如果浮动窗口的话 太长会顶下去.. 或者加个滚动条 ouo!

**Comment by Meow-J** [comment]
不，是把整个页面都撑满了
