### ISSUE TITLE
今日推送没填满

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#330]
![image](https://cloud.githubusercontent.com/assets/5229241/24565784/55947b3a-1689-11e7-8e74-d7444476db2a.png)

之前好像只有一个来着，这个在每天凌晨应该需要自动填满的吧，空着不对称好难受

**Comment by Ahrwing** [comment]
这个的判定是当日"PUSH"操作最多的MOD... 每日凌晨会自动清空今日PUSH

**Comment by Meow-J** [comment]
嘛，能留着前一天的 Push 吗，之后每天的新 Push 覆盖老的 Mod

**Comment by Ahrwing** [comment]
首页每日推送改为每周推送，在没有推送时显示最新编辑的MOD
