### ISSUE TITLE
重新编辑未过审的模组不能保存之前提交版本的模组关系，同时模组元素和支持MC版本会被清空

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#331]

**Comment by Ahrwing** [comment]
期初以为很简单，结果发现这是一个挑战..
正在处理，祝我好运。

**Comment by Ahrwing** [comment]
突破 40%

**Comment by Ahrwing** [comment]
太棒了 75%

**Comment by Ahrwing** [comment]
不要停 80%

**Comment by Ahrwing** [comment]
还能做得更好 100%

**Comment by Ahrwing** [comment]
已完美解决~ (因一个愚蠢的错误浪费了30分钟时间…)

<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=298 height=52 src="//music.163.com/outchain/player?type=2&id=26954885&auto=1&height=32"></iframe>

**Comment by DLslime** [comment]
重新编辑的时候发现模组关系一概都变成了“前置”

**Comment by Ahrwing** [comment]
@DLslime 我这边没这个问题.. 发个地址来？
