### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by zomb-676** [Ahrwing/mcmod#332]
请求增加一个在新词条确认编辑完成后，对还未审核前撤回或修改（修改功能好像仍然是坏掉的）的功能。有时候确认词条完成后突然想起要修改或笔误的地方，就不用等待审核完或重新编辑一个新的词条。还可减少审查员的工作量。一举两得=w=

**Comment by Ahrwing** [comment]
修改已经弄好了~ 添加也可以修改了w
