### ISSUE TITLE
关于首页的新窗口打开资料

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#333]
首页改版之后感觉不错。
（小水管什么时候能扩建==）
只是首页的**某些**资料链接貌似不太对劲。
目前是这样：
如果点击图片，则打开新窗口。
如果点击文字，则在当前页面跳转。

能统一吗？
能自定义吗？
0.0

**Comment by Ahrwing** [comment]
已统一成新窗口打开
