### ISSUE TITLE
关于编辑预览失效

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#334]
任何资料编辑页的“预览内容”均失效。
望修复。
![image](https://cloud.githubusercontent.com/assets/20513115/24594868/bfa7ef6c-1863-11e7-80fe-6b68242e6ada.png)
![image](https://cloud.githubusercontent.com/assets/20513115/24594873/d48e7590-1863-11e7-8f25-984882b50654.png)

**Comment by Ahrwing** [comment]
修好啦~
