### ISSUE TITLE
MOD搬运/下载

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#335]
- [ ] 选择特定mod文件后添加至“我的选单”
- [ ] 一键打包下载 (为缓解一定压力可以规定需要一定论坛等级才能使用)
- [x] 授权展示页面(可以是论坛新板块的帖子) 包含授权帖子/来源或截图

目的：建设一个能够永久保存得到授权的mod文件，并能提供方便的下载。

有些MOD要翻墙 有些老mod网盘挂了
于是想把他们永久保存在百科上

初步规划：
![10](https://cloud.githubusercontent.com/assets/5197567/24612495/0565fcc0-18b8-11e7-862e-dbaad7e91ae0.png)

**Comment by forestbat** [comment]
感觉“我的选单”可以和“常用模组”合并嘛。

**Comment by sxjeru** [comment]
我认为有一定等级的论坛用户下载资源可能用不到百科。。
当然如果建立下载区，我会贡献资源的。

**Comment by Ahrwing** [comment]
@forestbat 选单和常用模组是两个东西.. 选单里的mod是带有版本号的.. - -

**Comment by mmt50** [comment]
版本控制怎么办

**Comment by Ahrwing** [comment]
@mmt50 是指直接提供源码的那些MOD吗？

**Comment by mmt50** [comment]
是一部分了，还有就是过去mc版本的只需要提供最终版本，而当下的1710和1102的话，很多mod还在更新，提供下载就比较麻烦

**Comment by DLslime** [comment]
无需登陆就能下载确定和第二条的括号内容不矛盾？？
另外合并“常用模组”和选单不是说两个是一个东西，而是把一个版面切成两个用吧？我个人只收藏了两个模组(以后把坑填完了还可能“取关”)，这个版面就显得太空旷了。

**Comment by mmt50** [comment]
用cookie的话，过期时间怎么办，也没有自动登录（又扯到这个了

**Comment by forestbat** [comment]
@DLslime 我一开始确实想的是同一个东西，不过你这个切版面的想法不错……

**Comment by 3TUSK** [comment]
提问：
1. 先保存还是先问授权？
2. 如何确保我们保存的就是原始发布的Mod（而不是加了汉化的）？
3. 一键打包——确定这玩意能拿来组整合包？

**Comment by Ahrwing** [comment]
1.当前是先要授权再保存
2.从作者官网搬
3.我什么时候说它能用来做整合包了... 
它就像网盘里的批量下载一样，不能保证下载下来的mod无脑加到mods里就能跑起来.. 不过倒是提醒我了，可以在需要前置的MOD下载的位置显示“需要XXX前置”的链接来引导用户

**Comment by Ahrwing** [comment]
@DLslime 不矛盾.. 不登录就能下载，受限制的是批量下载

**Comment by Ahrwing** [comment]
@mmt50 你在淘宝买东西加入购物车以后会存多久 0 0

**Comment by 3TUSK** [comment]
关于3：
你用过[MultiMC](https://github.com/MultiMC/MultiMC5)吗...

**Comment by Ahrwing** [comment]
@3TUSK 要实现这个并不容易……

**Comment by 3TUSK** [comment]
不，现在似乎有很多启动器都有整合导出的功能了——能否直接这样快速组合出一个整合？

**Comment by Ahrwing** [comment]
@3TUSK 理论上有实现的办法 但是需要有人去维护和测试..

**Comment by 3TUSK** [comment]
那就无视这个要求吧

**Comment by Ahrwing** [comment]
@3TUSK 一步一步来w

**Comment by 3TUSK** [comment]
啊对了，记得贴SHA256...

**Comment by Ahrwing** [comment]
@3TUSK MD5 Crype SHA256 套餐一份

**Comment by 3TUSK** [comment]
我忽然有一个不太符合实际的想法——如果能做一个[这个](https://github.com/MCArchive/metarepo)的镜像站呢？

**Comment by Ahrwing** [comment]
@3TUSK API什么的现阶段的确不太符合实际 ← ←

**Comment by 3TUSK** [comment]
不不不——“镜像”——整个站上的资源全做缓存...

**Comment by mmt50** [comment]
@Ahrwing 全搬那压力就大了不止一倍啊。。。。购物车的话，一般我会存到买为止，否则我就放收藏夹了

**Comment by Ahrwing** [comment]
没问题的吧.. 给个1年的cookie生存周期 不清就会一直保存着~

**Comment by OldHuaJi** [comment]
@Ahrwing  某些全家桶好像自带cookie清理

**Comment by OldHuaJi** [comment]
另外全保存的话很担心硬盘和水管的问题

**Comment by Ahrwing** [comment]
能保证浏览百科时加载速度正常就行

**Comment by 3TUSK** [comment]
@Ahrwing 如果有一天百科服务器挂了怎么办。

**Comment by OldHuaJi** [comment]
镜像服务器？感觉又是一笔大钱

**Comment by Ahrwing** [comment]
@3TUSK 嗨呀.. 肯定要搭建一个下载专用服务器的.. 负载满了或者挂了都不会影响到网站..

**Comment by 3TUSK** [comment]
口误，我是指这个下载用的服务器...

**Comment by Ahrwing** [comment]
@3TUSK 挂了是指？

**Comment by 3TUSK** [comment]
> 目的：建设一个能够永久保存得到授权的mod文件，并能提供方便的下载。

如果服务器因为各种外力无法访问，那么...

**Comment by Ahrwing** [comment]
@3TUSK 找出原因并解决。

**Comment by YPXxiao** [comment]
我先去ic2 forum要点许可吧

**Comment by Ahrwing** [comment]
@YPXxiao 辛苦了.. 记得要带上mcmod的名字 以防止会被其他网站复制粘贴~
然后把许可统一放到这个帖子里吧~
http://bbs.mcmod.cn/thread-615-1-1.html

**Comment by 3TUSK** [comment]
@YPXxiao 我觉得你现在要做的第一件事就是换掉头像...

**Comment by DYColdWind** [comment]
如果已经弃坑的模组也联系不到作者着么办？直接上传？

**Comment by 3TUSK** [comment]
@DYColdWind 恭喜你发现了进退两难的情况。

**Comment by Ahrwing** [comment]
我的意见是直接传

**Comment by 3TUSK** [comment]
这明显是个 dilemma...

> @Ahrwing 顺带，刚才你看见群里讨论的那件事了吧

**Comment by DLslime** [comment]
我倒觉得设定这个MOD下载的最大意义就是保住那些已经弃坑/不提供下载的模组
另外我建议把百科下载区一分为二，分为Lawful版和Anarchy版，前者放置已经取得许可的模组下载，后者放置暂未/无法取得许可的模组下载

**Comment by Meow-J** [comment]
嘛，我还是觉得这种事情可行性很低啦

**Comment by 3TUSK** [comment]
@DLslime 你这Lawful和Anarchy的命名确定不是照抄的...？

**Comment by DLslime** [comment]
是照抄的，那我一个Anarchist用两个英语单词也要顾及版权吗？（手动滑稽）

**Comment by 3TUSK** [comment]
没说有版权。只是希望有我们自己的风格。

**Comment by Ahrwing** [comment]
@3T没 我还在外面 发生啥事…

**Comment by 3TUSK** [comment]
一些棘手的事情，不方便在这里讨论，你还是翻译下聊天记录吧...

**Comment by YPXxiao** [comment]
@3TUSK 头像已换==

**Comment by YPXxiao** [comment]
＠DYColdWind　那些弃坑Mod的作者，可能已经把Mod开源了啊，例如暮色森林

**Comment by DYColdWind** [comment]
@YPXxiao 巫术就不来源 呜呜呜~

**Comment by 3TUSK** [comment]
> 那是开源

可见源码不等于开源。@YPXxiao

**Comment by YPXxiao** [comment]
@3TUSK 好吧，懂了
