### ISSUE TITLE
首页版本检索栏的mod列表按照首字母顺序排列

### ISSUE THREAD

**Issue by KonakaSigma** [Ahrwing/mcmod#336]
就是在“版本检索栏”下，列出的mod列表按照中文或者英文的首字母顺序排列，方便检索
虽然下面有按中文拼音首字母排序，但是那个没法筛选支持的mc版本，

**Comment by Ahrwing** [comment]
这个会做一个独立的人功能的…

**Comment by mmt50** [comment]
需要吗，只是在排序上做一点调整就行吧，还是说加一个按条件排序功能？

**Comment by 3TUSK** [comment]
> 突然就没有标签可用了

**Comment by sxjeru** [comment]
独立模组检索页已存在：https://www.mcmod.cn/modlist.html

虽然仍不支持按首字母顺序排序，不过目前百科mod数量众多，怀疑即便有按字母排序也不会大大改善检索的便利性。
（另有百科搜索存在）
