### ISSUE TITLE
关于“评比排行”栏目的算法问题

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#337]
对于该栏目的算法存在一点疑惑：

1. 一些小票数、鲜有问津的模组可以轻松脱颖而出；
2. 对于一些发展均衡的模组，可能所有方面的票数都很多，无法判断出在某一方面是否真的不如其他模组。如栏目描述所说：“不是每个MOD都拥有一个完整的世界。”那么拥有一个完整世界的MOD该在哪里存在呢？

**Comment by Ahrwing** [comment]
这个一开始是打算改成每种票数必须超过100才会显示的 但这样会有大量空白 所以打算先征集一下票数 之后再改

**Comment by Snownee** [comment]
2017/5/3更新：
今天逛站的时候发现“中文输入修复补丁”排在了趣味排行的第一位。

**Comment by 3TUSK** [comment]
> “中文输入修复补丁”

一股没人投票，然后结果 biased 的感觉

**Comment by Ahrwing** [comment]
模组属性评比系统大改：评比栏目精简到4项，每个账户可以提高/降低每个MOD中的每项评比1次且不可撤销~ (11:40)
