### ISSUE TITLE
热度出现问题

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#34]
![qq 20150816022346](https://cloud.githubusercontent.com/assets/5229241/9290251/f56c19b0-43bd-11e5-8f13-dc80c1628ec8.jpg)
![qq 20150816022314](https://cloud.githubusercontent.com/assets/5229241/9290252/f59ad732-43bd-11e5-8f7a-6ed9922baf37.png)

估计明天就消失了，正常应该是0.0的

**Comment by Ahrwing** [comment]
已修复.. 原因是为0直接跳到最后一个等级了... 现在已改成热度0或者以下则分到新的“初出茅庐”等级内~
并且修改了一下等级评分比为按照百分比的方式计算而不是固定值~

**Comment by Meow-J** [comment]
问题仍然存在

**Comment by Ahrwing** [comment]
妥
