### ISSUE TITLE
百科大使馆？

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#340]
https://zh.wikipedia.org/zh-cn/Wikipedia:%E5%A4%A7%E4%BD%BF%E9%A4%A8
^
突然想到维基百科是有这个东西的，回想起这几天发生的事情，我们是不是有必要也在**合适的时候**建设一个？

另外我惊奇地发现这个 issue 我加不动标签... 完完全全不知道哪个标签合适。

**Comment by sxjeru** [comment]
英语就直接去官方wiki上搬？

**Comment by 3TUSK** [comment]
官方wiki是啥？

**Comment by mmt50** [comment]
那个是社区管理的wiki

**Comment by 3TUSK** [comment]
于是现在有了两个架子... 然后呢

**Comment by 3TUSK** [comment]
暂时先关了吧... `IRC 那边彻底没人了.jpg`
