### ISSUE TITLE
物品添加新类型：综合介绍

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#341]
有些物品合辑没有一个统一的介绍位置，例如BC管线的条目：
http://www.mcmod.cn/item/11684.html

通常都是合并至第一个物品，这样大部分介绍就会挤到一个物品上
所以打算给资料加一种类型：综合介绍

~~设为综合介绍的物品没有小图标和耐久等栏目~~

综合介绍计划用于解决过多同类物品的问题，例如GT各种材质的板材、镐头，林业的各种木头等。
合并到综合介绍里的物品 不会在物品列表出现 但是依然能被搜索到

**Comment by sxjeru** [comment]
如果合并的物品已经显示在物品页了，那么设为综合介绍的物品是否需要显示。

**Comment by 3TUSK** [comment]
![image](https://cloud.githubusercontent.com/assets/9113033/25068026/e70acbc8-2223-11e7-87bf-e5580a446c11.png)
...G键是什么鬼啊？？

**Comment by Ahrwing** [comment]
@sxjeru 合并关系是多对一的.. 故不会出现这样的情况~

**Comment by Ahrwing** [comment]
> 早已解决
