### ISSUE TITLE
关于日志排序

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#342]
希望将日志排序的功能下放。
当然我到现在都不理解为何无法开放排序。
例图：
![QQ图片20170421205731.png](https://ooo.0o0.ooo/2017/04/21/58fa01c8d968b.png)

**Comment by sxjeru** [comment]
最新情况：允许该模组编辑员排序。

**Comment by Ahrwing** [comment]
最新情况：点击表头可以快速排序 √
