### ISSUE TITLE
收藏夹自定义功能

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#344]
RT，不觉得进页面选mod会便捷。
下面是几个建议：

- [x] 支持自由排序
- [x] 支持创建多个分类

[ x ] ~支持自定义首页显示数量~（v4首页已不显示常用模组）
[ x ] ~支持列表化内容~

请酌情选择，优先级默认由大到小。
以上。

论坛追加（收藏夹已移至个人中心）：

[ x ] 支持首页显示
[ x ] 支持分类

**Comment by sxjeru** [comment]
目前首页取消显示常用模组，建议二失效。
建议三无实用意义。

**Comment by sxjeru** [comment]
引用论坛的建议。
https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=1721&extra=

**Comment by Ahrwing** [comment]
主站通用收藏夹功能已上线~
![图片](https://user-images.githubusercontent.com/5197567/131315425-b6092f9b-be20-4058-8c1a-f7e9cdacdfc1.png)

**Comment by sxjeru** [comment]
追加希望收藏夹内容可以拖动排序。

**Comment by sxjeru** [comment]
![image](https://github.com/Ahrwing/mcmod/assets/20513115/e4eacb00-914d-4b16-b4b2-83d895e79e71)
