### ISSUE TITLE
主页右下方的浮动提示被右边的Index Nav挡住

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#345]
感觉层级不太对？

**Comment by 3TUSK** [comment]
@Meow-J 那这个 issue 的标签应该是？

**Comment by Meow-J** [comment]
我这边没这种情况

**Comment by Ahrwing** [comment]
分辨率低的情况下会出现吧.. /w\\

**Comment by Meow-J** [comment]
@3TUSK 噗，我正在添加标签的时候看见你已经添加了，之后就反勾选我选的标签了，结果判定成我把标签都取消了/w\

**Comment by Snownee** [comment]
![举栗子](http://i4.buimg.com/567571/706d16c8f3af6558.png)举栗子

**Comment by Meow-J** [comment]
可以把导航条叠在提示的下面？感觉这样子至少可以保证用户能把提示关掉

**Comment by Snownee** [comment]
不如换成H5播放器？
或者
考虑调查一下这个功能的使用状况？

**Comment by Meow-J** [comment]
应该指的是 #346 吧/w\

**Comment by Snownee** [comment]
搞混了/w\
