### ISSUE TITLE
下方播放器歌名显示对比度过低

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#346]

**Comment by Ahrwing** [comment]
/w\\ 这是播放器固定的样式 也并非开源 除非更换播放器..

http://www.cledeals.com/ - dewplayer
“Dewplayer n'est plus, mais renaîtra, un jour.”

**Comment by Meow-J** [comment]
应该还有很多其它的吧

**Comment by Snownee** [comment]
不如换成H5播放器？
或者
考虑调查一下这个功能的使用状况？

**Comment by Ahrwing** [comment]
已取消播放器的功能,
>在工作了3年后终于退役了
