### ISSUE TITLE
模组预览图在不同页面的纵横比不同

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#348]
之前提过，举个栗子：
/class/：212×141
/item/*/：200×120

**Comment by Ahrwing** [comment]
打算抽空统一改一下~ 话说首页的MOD名字现在看着会不会舒服些…

**Comment by Snownee** [comment]
诶？MOD名字？抱歉没注意到有啥明显的变化

**Comment by Ahrwing** [comment]
..由原来你提出的不换行堆在一起 改成了现在的原文+换行+译文了

**Comment by Snownee** [comment]
抱歉，虽然后者确实更舒服，但好像不是我提出的……

**Comment by Ahrwing** [comment]
是吗.. 可能是我记错了 /w\\

**Comment by Meow-J** [comment]
相关 #193 #18

**Comment by Snownee** [comment]
重复？感觉和之前的问题不太一样吧？@3TUSK

**Comment by 3TUSK** [comment]
确实不太像。抱歉。

**Comment by Ahrwing** [comment]
已解决w
