### ISSUE TITLE
中文名称作为可选内容

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#35]
某些mod很难翻译也没必要翻译，像是FastCraft或者Forge等mod，如果硬加上去个中文名字会很难受。本来能通过不填英文名直接写名称来解决，现在英文名成必填项反而有点麻烦了orz

或者可以把英文名放上面必填，中文名放下面选填

**Comment by Ahrwing** [comment]
如果不写中文名显示那里会变得很奇怪... /w\
遇到这种情况中文名和英文名都填一样的就好了~
或者可以考虑加个选项 “不使用中文名” 然后中文名和英文名都显示英文名~ 如何捏~

**Comment by Meow-J** [comment]
@Ahrwing 好吧，或者可以检测Mod名称一样的话不显示括号内的内容
