### ISSUE TITLE
主页贡献榜的一个小bug

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#352]
当某人在贡献榜中的比率是100%时，“%”没有显示。
![image](https://cloud.githubusercontent.com/assets/20513115/26020701/5423f180-37b4-11e7-8274-6e1e701eb925.png)

**Comment by 3TUSK** [comment]
怕不是那个`%`又被截断了？

**Comment by Ahrwing** [comment]
原因显而易见… 百分比会保留最后一位小数点，且在小数点为0时仍旧显示..

**Comment by Ahrwing** [comment]
解决了~

**Comment by sxjeru** [comment]
@Ahrwing 确定？
![image](https://cloud.githubusercontent.com/assets/20513115/26272973/48fd1d32-3d58-11e7-9b22-32a3bdd85768.png)

**Comment by Ahrwing** [comment]
确定，那只是老截图hhh
