### ISSUE TITLE
搜索页主页输入框未居中对齐

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#353]

**Comment by Meow-J** [comment]
不知道你那是什么样子的，我这里只是感觉视觉上有点不平衡，把Logo往下移动一点感觉会好一点

**Comment by Snownee** [comment]
简单来说输入框不够宽，或者应该再往右移动一点。(话说为什么不用flex box)

**Comment by Meow-J** [comment]
看了下百度，输入框也是不居中的，输入框+按钮的整体是与Logo居中的。不过我们的看起来更不平衡点

**Comment by Snownee** [comment]
我说的就是“输入框+按钮的整体”

**Comment by Meow-J** [comment]
截个图吧

**Comment by Snownee** [comment]
![gif](https://cloud.githubusercontent.com/assets/16059084/26257022/8e4ea0ca-3cf1-11e7-843a-e28929e30f44.gif)
不好意思，本人最近老眼昏花了= =

**Comment by Ahrwing** [comment]
>搜索页面已更新
