### ISSUE TITLE
鼠标hover至主页的卡片后导致fixed的元素轻微抖动

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#354]

**Comment by Meow-J** [comment]
我这没这个问题，是不是还是分辨率问题

**Comment by Snownee** [comment]
![gif](https://cloud.githubusercontent.com/assets/16059084/26257161/283f86e0-3cf2-11e7-9933-1756a44ff48f.gif)
目测不是分辨率问题，复现方式很迷，需要滚轮多滚动几次

**Comment by Ahrwing** [comment]
:3 不会出现+1 不知道问题出现的原因 暂时无法解决这个细节问题..

**Comment by Meow-J** [comment]
等等，这个好像是chrome的bug，我记得之前我在其它网站里有过这种情况

**Comment by Snownee** [comment]
经测试，给fixed的元素加上如下代码，奇迹般地解决了：
`-webkit-transform: translateZ(0);`

**Comment by Ahrwing** [comment]
好了~ 你再看看w

**Comment by Snownee** [comment]
问题依然存在

**Comment by Ahrwing** [comment]
你能看到那个新加的css样式存在吗...

**Comment by Snownee** [comment]
我没找到加到哪里了

**Comment by Ahrwing** [comment]
噗，我懂了，CDN。

**Comment by Snownee** [comment]
似乎忘记给Topbar加样式了？

**Comment by Ahrwing** [comment]
@Snownee 现在还会出现这情况吗

**Comment by Meow-J** [comment]
最顶端的那个菜单还是没修

**Comment by Ahrwing** [comment]
@Meow-J 哪个 /w\

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/26675180/7dc06ba4-46f5-11e7-8a61-0f29d57c6b98.png)

**Comment by Ahrwing** [comment]
已解决w
