### ISSUE TITLE
登录时浏览器不记录账号密码

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#355]

**Comment by sxjeru** [comment]
抱歉我无此问题。
浏览器 Chromium.
内核 50.0.2661.102.

**Comment by Ahrwing** [comment]
提供一下浏览器信息...

**Comment by Snownee** [comment]
Chrome 57.0.2987.133

**Comment by Ahrwing** [comment]
I'll look into it.

**Comment by Snownee** [comment]
在 Chrome 58.0.3029.110 （最新稳定版）下同样不行

**Comment by Meow-J** [comment]
相关 #215

**Comment by Meow-J** [comment]
我这现在是使用第三方的插件才能自动填充密码的

**Comment by Snownee** [comment]
表单里面也可以用ajax吧...

**Comment by Snownee** [comment]
![gif](https://cloud.githubusercontent.com/assets/16059084/26257022/8e4ea0ca-3cf1-11e7-843a-e28929e30f44.gif)

**Comment by Ahrwing** [comment]
@Snownee 这是另一个问题了 XD

**Comment by Meow-J** [comment]
又错issue了/w\

**Comment by Ahrwing** [comment]
wait.. 我可能理解错问题的意思了... 不记账号密码，是指在用登录过的电脑重新登录时，表单里不会自动填充用户名密码对吗？
如果是的话... 就是这样设计的... /w\

**Comment by Snownee** [comment]
but...为什么？

**Comment by Meow-J** [comment]
这是什么设计啊/w\

**Comment by 3TUSK** [comment]
> 吓得我加了“无打算修复”然后又去掉了

自动填写密码又是什么设计... 一直觉得这样很不安全...

**Comment by sxjeru** [comment]
不自动填写密码那cookies七天保质期是不是该延长。

**Comment by Snownee** [comment]
> 不自动填写密码那cookies七天保质期是不是该延长。

@sxjeru 个人觉得关键不在于此，是否自动填写密码是可以通过对话框由用户自行决定的。

**Comment by Meow-J** [comment]
@3TUSK 如果觉得不安全不用浏览器的填充密码的话这是用户的选择，但既然浏览器提供了这一功能并且其他网站上都能工作正常，不设置这一功能会使选择使用自动填充的用户感到不方便。

话说自动填充的输入框应该都是自动解析出来的结果，如果填不上这更像是一个兼容性bug而不是设计

**Comment by sxjeru** [comment]
有没有可能是因为这个？
![image](https://user-images.githubusercontent.com/20513115/28741251-b31bd1c2-7444-11e7-88da-a65a95bb17dd.png)

**Comment by Ahrwing** [comment]
已解决，现在会自动记录并提供保持登录选项了。
