### ISSUE TITLE
个人主页中活跃度显示不必要的时间“00:00:00”

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#357]

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/26274936/495a1430-3d88-11e7-93bb-4a663ea8d149.png)
图

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/166133758-a14372e3-0a60-4626-9a87-b468ff1a9cf3.png)
![image](https://user-images.githubusercontent.com/20513115/166133767-b76a21e6-70d0-4ea8-a2b4-55db4ba5e392.png)
