### ISSUE TITLE
个人主页中活跃度展示过多未来时间的区域

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#358]

**Comment by sxjeru** [comment]
这相当于一张表，参照github。

**Comment by Snownee** [comment]
> 这相当于一张表，参照github。

![default](https://cloud.githubusercontent.com/assets/16059084/26272831/17976e12-3d55-11e7-8651-fbdb3302172b.png)

@sxjeru  参照Github，应该最晚显示到当天。

**Comment by 3TUSK** [comment]
于是问题来了：这应该算是 bug 还是算一个改进？

**Comment by Snownee** [comment]
@3TUSK 改进

**Comment by sxjeru** [comment]
@Snownee 这样前面不就空出来了。

**Comment by Snownee** [comment]
@sxjeru 你的意思是，展示的第一天是此功能上线的时间？

**Comment by sxjeru** [comment]
@Snownee 是。这样排也没什么问题吧。

**Comment by Snownee** [comment]
0.0
