### ISSUE TITLE
将Mod介绍页面的Tab改为点击切换

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#359]
![image](https://cloud.githubusercontent.com/assets/5229241/26274950/85707b8a-3d88-11e7-9e9b-25bae1691d86.png)
这个东西，现在是只要鼠标扫过就能切换面板的，但这样太容易误操作了，滚动页面的时候经常会碰到

**Comment by Ahrwing** [comment]
鼠标移上去有半秒的延迟才会切换… /w \\

**Comment by Meow-J** [comment]
直接改成点击啦/w\

**Comment by Ahrwing** [comment]
现在是点击或移上0.5s都会切换了w

**Comment by Ahrwing** [comment]
已支持点击切换 /w\..

**Comment by sxjeru** [comment]
应该是在这个issue关闭之后，出现mod下载页消失的情况。
如图，鼠标放在“MOD下载”上：
![image](https://user-images.githubusercontent.com/20513115/36130333-4144bb0e-10a7-11e8-9437-c22ce660d479.png)

**Comment by Ahrwing** [comment]
已修复~
