### ISSUE TITLE
预览功能

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#36]
发现基本每次编辑词条我都会刷屏orz，强迫症没办法/w\，幸好我还是个审核员，要是普通用户就更麻烦了

**Comment by Ahrwing** [comment]
弄好了 /w\~

**Comment by Meow-J** [comment]
http://www.mcmod.cn/class/edit/460 去预览这个

**Comment by Ahrwing** [comment]
好了 /w\..
