### ISSUE TITLE
部分原版资料无法链接至正确的中文wiki界面中

### ISSUE THREAD

**Issue by DLslime** [Ahrwing/mcmod#360]
比如钻石护腿（1094），中文wiki中把原版所有护腿全部写进一个页面并且没有给重定向，所以会出现这个问题。
我的建议是把这个链接也变为编辑员可以编辑的状态，这样可以手动修复这种错误。

**Comment by Snownee** [comment]
之前给重生提过这个问题……

**Comment by Ahrwing** [comment]
介个是自动的…

**Comment by Ahrwing** [comment]
可以考虑加一个字段单独控制
