### ISSUE TITLE
论坛个人签名支持图片显示

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#363]
目前个人签名在帖子里只能显示文字，无法显示图片。
![image](https://cloud.githubusercontent.com/assets/20513115/26725801/cfa70fd0-47d2-11e7-8d4f-7f4298cf4d24.png)
但在论坛个人中心可正常显示。
望解决。

**Comment by Ahrwing** [comment]
签名最大高度已由100px增加到了450px

**Comment by sxjeru** [comment]
wait!!
经检验该问题并未得到解决。
在解决之前先open吧。

**Comment by 3TUSK** [comment]
Reopen per request. Re-close it if necessary.

**Comment by Ahrwing** [comment]
你的签名里没有图片诶……

**Comment by sxjeru** [comment]
我添加图片后试的，又删掉罢了。
但问题确实没有解决。

**Comment by Ahrwing** [comment]
你加的图片是多高的…

**Comment by Ahrwing** [comment]
如果加的图片高是450px的话… 我需要对你使用高级智商喷雾…

**Comment by Ahrwing** [comment]
爪机上不能修改发言 就很气… 🐔
你试试加一张200px的吧 如果除了图片还有文字的话 可能会超过450 这个数值就不该暴露出来(?

**Comment by Ahrwing** [comment]
已解决

**Comment by sxjeru** [comment]
please reopen...
原因：未解决。
用两张图解释。
![image](https://user-images.githubusercontent.com/20513115/27784794-fe3a3ef0-600d-11e7-90fb-6bae8a2bca53.png)
![image](https://user-images.githubusercontent.com/20513115/27784834-2e03ab62-600e-11e7-836c-dc9b1f4223f3.png)

**Comment by 3TUSK** [comment]
Reopened

> what the...

**Comment by sxjeru** [comment]
目前看来，是其html标签全部没有保留的原因。
![image](https://user-images.githubusercontent.com/20513115/34646781-4710bd34-f3ac-11e7-8acb-1f1b1c2b9c7a.png)
![image](https://user-images.githubusercontent.com/20513115/34646773-20c88bac-f3ac-11e7-84e4-a1e302604cf3.png)
![image](https://user-images.githubusercontent.com/20513115/34646782-4bf09004-f3ac-11e7-825d-fbd2f6e96a93.png)
![image](https://user-images.githubusercontent.com/20513115/34646778-4170eaca-f3ac-11e7-9149-223ce0c47fbf.png)
