### ISSUE TITLE
百科资料页支持<audio>标签

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#364]
RT。
这是wiki常用的功能，百科也借鉴下吧。
![image](https://cloud.githubusercontent.com/assets/20513115/26726462/c2eb777e-47d5-11e7-8347-c840bd293fa5.png)

**Comment by Ahrwing** [comment]
这个会加入到未来的某个新功能里

**Comment by sxjeru** [comment]
原来本来就支持的……在编辑器加个功能吧。
![image](https://user-images.githubusercontent.com/20513115/37462279-5a72b6f6-288c-11e8-83cb-e2fa794b9da0.png)

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/37462752-fb702ff6-288d-11e8-9cd4-a595cdd3c871.png)

**Comment by sxjeru** [comment]
二次编辑时不显示了……
![image](https://user-images.githubusercontent.com/20513115/37462862-4eac5028-288e-11e8-9040-48dadeffe6a1.png)
