### ISSUE TITLE
百科网站ssl证书

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#366]
#一个没什么用的建议，如果可以请无视，并close。。
有CA机构为个人网站&非盈利网站提供了免费的ssl证书服务，百科有意愿升级么？
下面是几个选择，当然并不只这些。
[https://portal.qiniu.com/certificate/apply](https://portal.qiniu.com/certificate/apply)（不支持泛域名）
[https://www.freessl.com/freessl/good-karma/](https://www.freessl.com/freessl/good-karma/)（支持通配符）
[https://www.startcomca.com/](https://www.startcomca.com/)
[https://www.sslshopper.com/article-free-ssl-certificates-from-a-free-certificate-authority.html](https://www.sslshopper.com/article-free-ssl-certificates-from-a-free-certificate-authority.html)

**Comment by Ahrwing** [comment]
这个不错 不过可能会有很多地方要改

**Comment by Ahrwing** [comment]
要改的地方太多 且需要承担一定额外费用 暂不考虑此项..

**Comment by sxjeru** [comment]
总觉得有机会。（将来普及https）
开着再说。

**Comment by sxjeru** [comment]
侦测到https。

**Comment by Ahrwing** [comment]
眼尖酱第一个发现 0 0
话说正在调链接.. 会有些文件加载不出来..

**Comment by sxjeru** [comment]
辛苦了～

**Comment by 3TUSK** [comment]
居然真加 https 了，特此撤销“无打算修复”标签。

**Comment by sxjeru** [comment]
@Ahrwing 友情链接就不用加https了。
![image](https://user-images.githubusercontent.com/20513115/38867385-7774a9fe-4276-11e8-8083-8f9a964a9e93.png)

**Comment by Krasjet** [comment]
没小绿锁是因为网页上外链的一些图片仍用的是HTTP链接，这个问题要修复会很麻烦。

**Comment by Ahrwing** [comment]
友情链接图片修复完成

**Comment by sxjeru** [comment]
不仅仅是图片，链接也得改一下，例如mcbbs就不支持https。

**Comment by sxjeru** [comment]
知晓为何没有小绿锁了……我给百科加了自定义背景，背景图用的不是https。
![image](https://user-images.githubusercontent.com/20513115/39581764-e612b4f0-4f1e-11e8-91df-85231fa255d1.png)

**Comment by sxjeru** [comment]
问题严重了……只要浏览过任意一个帖子，整个`bbs.mcmod.cn`域的网站都会显示红色“不安全”警告。
没有小绿锁忽略也罢，但这个问题建议修复。
![image](https://user-images.githubusercontent.com/20513115/39867545-fbf28af2-5487-11e8-8e5f-569e0af26511.png)
![image](https://user-images.githubusercontent.com/20513115/39867552-15b58b9c-5488-11e8-9029-e7a524ff6964.png)

**Comment by Ahrwing** [comment]
百度分享已撤~ (好像已经有几个月了
