### ISSUE TITLE
搜索引擎链接跳转bug

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#367]
目前测试了百度、360、Google、必应、DuckDuckGo、日本雅虎等搜索引擎，均出现403跳转错误。
范围限定于bbs.mcmod.cn域名。
![image](https://user-images.githubusercontent.com/20513115/27009062-b5572f8a-4eb6-11e7-8550-8091296b0f18.png)
![image](https://user-images.githubusercontent.com/20513115/27009063-b948c4d2-4eb6-11e7-8e0e-819b84675b9f.png)
然而像百科搜索，github超链接等使用原域名直接跳转则不会出错。
这是[bbs.mcmod.cn](http://bbs.mcmod.cn/)在Google的跳转地址，诸位可自行尝试。
[https://www.google.com/url?……](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjJpJ26nbXUAhUHO48KHdsACIwQFggmMAA&url=http%3a%2f%2fbbs%2emcmod%2ecn%2f&usg=AFQjCNFxSXyb2RdAi-tBq8VBKvG5NWf4cw&sig2=rdVqT6m-t77aNOcoxbS7gA)

**Comment by Ahrwing** [comment]
原因：使用了cdn并打开了防盗链所致

**Comment by sxjeru** [comment]
能否解决？
百科有了自己的搜索之后这问题就不怎么大了。

**Comment by Ahrwing** [comment]
现在cdn不支持黑名单 所以要么取消防盗链 要么关闭cdn… (花费太大了

**Comment by sxjeru** [comment]
据说https的cdn花费会更大。。
![2017-06-11155453.png](https://tuchuang001.com/images/2017/06/11/2017-06-11155453.png)

**Comment by Ahrwing** [comment]
已解决
