### ISSUE TITLE
封面添加图片支持网址解析

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#368]
![image](https://user-images.githubusercontent.com/20513115/27113664-d1e7dfa0-50f0-11e7-9f52-ca9de0f84cca.png)
目前只能上传，但某些地方不需要转存。
如wiki的图片。
为了加快编辑速度，请添加该功能。
![image](https://user-images.githubusercontent.com/20513115/27113733-5244df4a-50f1-11e7-8a3a-57c4f293d616.png)
以上。

**Comment by Ahrwing** [comment]
无打算添加，原因有：
1.裁剪的宽高是固定的，用其他地方的图片很难达到比例一致；
2.无法保证不会有人加一张接近1M的百科相册图片，会降低加载速度；

9.遇到这种情况右键另存为桌面再裁剪好了..

**Comment by sxjeru** [comment]
另外百科站内图床是不是可以参考下chevereto，它的上传真的很方便的说。
![image](https://user-images.githubusercontent.com/20513115/27113809-df7e5d00-50f1-11e7-8c25-06318220350b.png)

**Comment by Ahrwing** [comment]
这个要抽空重改一下编辑器

**Comment by sxjeru** [comment]
Clearly understand.
