### ISSUE TITLE
缩略图在某些情况下剪裁出现bug

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#371]
还是之前那个问题，不过感觉一时半会解决不了了。

![2017-06-18_16-40-20](https://user-images.githubusercontent.com/5229241/27259401-23792732-5445-11e7-828b-c6ea43ae939a.gif)

只要拖动一下transform就变成none了，调试了一下，这个函数的输入是不正常的。

![chrome_2017-06-18_16-34-49](https://user-images.githubusercontent.com/5229241/27259362-26f94348-5444-11e7-9fd9-755fd5c2881f.png)

**Comment by ChitoseRaame** [comment]
同款BUG，用着非常难受。而且如果图片小的话，裁剪出来直接就是一块白色。
