### ISSUE TITLE
合成界面输入格取消硬编码

### ISSUE THREAD

**Issue by 3TUSK** [Ahrwing/mcmod#372]
````
咸鱼王Aston  17:25:52
话说群峦传说能否加合成GUI呢
瓶之塞  17:28:43
输入格子超过10个就加不了 像是雕刻的那种肯定不行
咸鱼王Aston  17:29:51
好吧
````

**Comment by Ahrwing** [comment]
hard cor(d)e..

**Comment by 3TUSK** [comment]
依稀记得从2014年改版以来就一直是锁死在10个输入...

**Comment by Ahrwing** [comment]
2014年的改版的时候并没有改合成表系统.. :|

**Comment by 3TUSK** [comment]
~~或者说合成表根本就*没怎么*改过吧~~

**Comment by Ahrwing** [comment]
之前加了一些功能啊 例如设定出现时间和移除什么的 XD

**Comment by 3TUSK** [comment]
Ping, ping, ping
如果这个问题解决不了，隔壁 GT5U **蒸馏塔的 12 个输出格**就要完蛋了

**Comment by Ahrwing** [comment]
已解决~ 

合成表功能重写：
·调整存储结构 性能提升 >100 倍；
·修复格子显示错位问题；
·修复在编辑合成表时切换GUI 图片未重新读取的问题；
·输入/输出格最大限制由 20 提升至 100 ；
·宽度限制由 320 改为 320~520 ；
·燃料格最大限制由 1 提升至 100 并允许设定数量；
·添加自定义单位设定(如:mB)
·部分样式调整
