### ISSUE TITLE
【备忘】“官方网址”改为“相关网址”并可以选择来源

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#375]
可设定的网址（暂定）：
[官方]
[MinecraftForum]
[Curse]
[CurseForge]
[MCBBS]
[WIKI]
[GitHub]

p.s. 
1.每种网址最多只能添加1个
2.官方网址会置顶
3.如果官方网址是除了官方网址以外的任何网址，则不能再重复添加该网站的网址 （例：某国产MOD的官方网址被设定为作者在mcbbs的发布帖，则不可以再添加第二个mcbbs网址）

**Comment by sxjeru** [comment]
我的意思，curse还是改成curseforge为好。
毕竟cf是项目区，更新较curse来说更为及时。
而且cf与curse页面上都有链接跳转。
最后cf下载不需要等三秒。（滑稽）

**Comment by DYColdWind** [comment]
自定义哪去了！！！
例如：官方wiki 之类的....

**Comment by 3TUSK** [comment]
反对。Curse的界面更适合普通用户；Curseforge的页面更倾向于开发者。两者应该同时提供。

> 当然…… 确实Curseforge的页面无论怎么看都比Curse主站好用……

关于主问题：
我不反对“相关页面”这个想法，但请不要在数量和种类上设限制…… 看一下隔壁 MineTweaker 各位就会明白我的意思了：一堆相关页面需要添加……

**Comment by Ahrwing** [comment]
@DYColdWind wiki可以加，不打算加自定义，把常用网站枚举出来就好，不然谁也不知道会有人加什么~奇奇怪怪的网址~

**Comment by sxjeru** [comment]
@3TUSK 我觉得没必要，原因在于两个页面有链接可以互转。
而且我不觉得curseforge对普通用户不友好，恰恰相反，我认为curseforge更适合用户。

**Comment by DYColdWind** [comment]
并且有的作者现在只更新curseforge了 貌似林业就这样

**Comment by 3TUSK** [comment]
@sxjeru 你看完我的话了吗（笑）
@DYColdWind 那是因为 Curse 主站的内容都是与 Curseforge保持同步的——但只同步 Release 版本，不会同步 Alpha 或 Beta 版本。

**Comment by DYColdWind** [comment]
所以比较不方便...不过要放2个放也没啥事情

**Comment by Ahrwing** [comment]
已完成w
