### ISSUE TITLE
关于（完善）百科提议--持续更新

### ISSUE THREAD

**Issue by DYColdWind** [Ahrwing/mcmod#376]
Mod编辑类
1.希望添加更多的上传mod封面的方式.
（1）使用百科图床直接上传又分为2类：一类是直接上传（自动放大缩小）另一类是现在的选框（并且增加最大化与居中图片的功能，然后Shift拖动只能在单方向移动 @Meow-J  ）
（2）使用其他网站的图床（不然不支持GIF...= =）
注：优先显示百科图床，其次显示其他网站的图...
2.希望把‘作者/开发团队’分离出来，另外多添加些其他的...
（1）添加类似‘所有者’‘作者’‘管理者’一类...
3.合成表中能否添加一个选定的东西然后可以直接填入格子中无需在物品中再次点击填入大大节省时间...
其他类
4.合成表的GUI可以直行搜索...
1.百科每天登入都会增加5RF，希望添加类似有些游戏签到似的日历可以供人查看

**Comment by 3TUSK** [comment]
首先感谢对百科的认可与建议！
但是这里是GitHub，不是贴吧或者论坛…… 
把这些问题与建议全部分拆成独立的 Issue 其实更方便（重生站长）管理。

**Comment by Ahrwing** [comment]
姑且回复一下部分问题：
1.这个问题我已经回答很多次了.. 另外设立两种封面会变得很乱 不靠谱 （暂无打算让模组封面出现GIF..
2.已有此 issue 
3.这个可以有
4.每日登录 ≠ 签到 签到系统会另做

**Comment by Meow-J** [comment]
对了，之前签到获得的那一堆东西都去哪了

**Comment by Ahrwing** [comment]
@Meow-J 还留着 /w\ 只是不知道干嘛用… (

**Comment by DYColdWind** [comment]
@3TUSK 是的...
我基本都是发给重生我主要是怕重生久了忘了= =并且qq记录也不怎么靠谱
另外，我一无聊就瞎想...就怕都独立出来的话很乱又感觉像刷屏....

**Comment by Ahrwing** [comment]
@DYColdWind ← ← 只要是独立的非重复建设性问题 都是有必要的

**Comment by Meow-J** [comment]
第一个那个是封面吧，相册还是原来的那样

**Comment by DYColdWind** [comment]
@Meow-J 是
原谅我语音表述可能有些不好...

**Comment by Meow-J** [comment]
图片截取那个能修改吗/w\，增加一个最大化和居中的功能感觉会好很多

**Comment by Ahrwing** [comment]
@Meow-J 我可以试试 ovo

**Comment by Meow-J** [comment]
然后Shift拖动只能在单方向移动/w\

**Comment by 3TUSK** [comment]
@DYColdWind 我来解释一下为什么不能单发一个 Issue。就是这么简单。

**Comment by DYColdWind** [comment]
看到了....行下次我注意...

**Comment by 3TUSK** [comment]
（这标签加得我都开始害怕了... 我严重怀疑重生会干掉我）

**Comment by Ahrwing** [comment]
@DYColdWind /w\ 还是把问题单独提出来吧 （已经解决和重复的就别发了） 这个先关了
