### ISSUE TITLE
【备忘】上传封面的补白改为图片的主色调

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#378]
w

**Comment by sxjeru** [comment]
这是我做的依靠ps动作实现的一键式处理。
希望对你有帮助w。
http://o8zwoo6sz.bkt.clouddn.com/mc%E7%99%BE%E7%A7%91%E5%B0%81%E9%9D%A2.atn
（其实在你的帖子里发过的……）

**Comment by Ahrwing** [comment]
无打算添加… （因为并不会像预期的那样自动补上边缘处的主色调, 参考目前百科中的FTBLIB）
