### ISSUE TITLE
更改通知中的一些名称

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#379]
“系统提醒”改为“论坛提醒”
“应用提醒”改为“短评提醒”
避免引起歧义。
![image](https://user-images.githubusercontent.com/20513115/27778675-5c475d1c-5fef-11e7-8cd4-624f52a9b6ba.png)

**Comment by Ahrwing** [comment]
现在好了~ 
（之前想改.. 但是一时半会儿没找到位置.. =-=）
