### ISSUE TITLE
应该有更改用户名的功能

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#38]
然后登录用UID或者邮箱>w<

**Comment by Ahrwing** [comment]
现在已经可以用邮箱登陆了 0 0..
改名的目的是什么呢…… 如果只是为了显示不同的名字，可以出一个nickname昵称功能，没必要直接改原名吧…

**Comment by Ahrwing** [comment]
现在可以在论坛设定自定义头衔
