### ISSUE TITLE
论坛相册上传图片不支持透明

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#380]
最近才出现的问题，透明图片上传后透明部分变全黑。
望修复，毕竟有些地方还是需要的。
![image](https://user-images.githubusercontent.com/20513115/27782316-934889d4-6004-11e7-95d4-196afa64af43.png)

![image](https://user-images.githubusercontent.com/20513115/27782323-a1122700-6004-11e7-84c6-74d7bc2ab73e.png)

**Comment by Ahrwing** [comment]
已解决 （如果上传到论坛相册的话，缩略图会显示成黑色，暂时无解... 但不会影响到原图）
