### ISSUE TITLE
论坛链接统一打开新页面

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#381]
目前情况：
点击链接标题，打开新页面。
点击标题后页码，不打开新页面。
![image](https://user-images.githubusercontent.com/20513115/27812407-3eaafba8-60a1-11e7-9a4e-2000b726b262.png)

请统一下打开方式。
鉴于百科大部分链接均为打开新页面，建议统一为打开新页面的方式。

**Comment by liach** [comment]
?
