### ISSUE TITLE
能添加插件的百科么

### ISSUE THREAD

**Issue by Oyodo** [Ahrwing/mcmod#383]
一直觉得百科1是很好用的东西,但是只有mod的话...所以能不能添加有关插件的百科的.

**Comment by Ahrwing** [comment]
这个会考虑的… 不过现在已经有插件百科的存在了… 在百科友情链接里~

**Comment by sxjeru** [comment]
我可以说那个插件百科已经无法打开了吗。

**Comment by 3TUSK** [comment]
问题来了。
百科定义过什么是“Minecraft Mod”吗。如果有，那这就没有操作空间了...

**Comment by Ahrwing** [comment]
@3TUSK 可以限制一下允许的API什么的..

**Comment by 3TUSK** [comment]
> 死灵法师来了

http://mineplugin.org/ 刚才过了一眼插件百科，感觉... 挺好的？
