### ISSUE TITLE
属性评比排版错乱

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#384]
![chrome_2017-07-05_23-30-22](https://user-images.githubusercontent.com/5229241/27872061-17ce03f6-61da-11e7-8736-45d551525642.png)

不太信任重生的记忆力，还是放上来吧

**Comment by Ahrwing** [comment]
//w\..

**Comment by Ahrwing** [comment]
现在应该好了..? 确认没问题的话关一下吧 /w\\

**Comment by Meow-J** [comment]
![image](https://user-images.githubusercontent.com/5229241/28098183-6f1f8686-66e7-11e7-9f25-0fa5fc546a76.png)

字还是有两层啦

**Comment by Ahrwing** [comment]
经测试 Google Chrome 58.0.3029.81 (64-bit) 不会出现这个问题… (就是之前图片裁剪出问题的版本)

**Comment by Meow-J** [comment]
Version 59.0.3071.115 (Official Build) (64-bit) /w\

**Comment by Ahrwing** [comment]
版本 59.0.3071.115（正式版本） （64 位） 测试没问题

**Comment by Ahrwing** [comment]
试试 CTRL+F5 刷新一下...

**Comment by Meow-J** [comment]
还是不行/w\

**Comment by Ahrwing** [comment]
> 我一定下了一个假的 Chrome

**Comment by Ahrwing** [comment]
现在呢 会不会之前是缓存的问题？ /w\\

**Comment by Meow-J** [comment]
不行 \_(:з」∠)\_

**Comment by Ahrwing** [comment]
迷.. 还有人遇到类似的问题吗.. ~@全体成员~

**Comment by 3TUSK** [comment]
> 我们需要一个“无法修复“的标签

**Comment by Ahrwing** [comment]
模组评比已重做..
