### ISSUE TITLE
关于快速提交编辑内容

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#387]
能否在编辑右侧的“变更说明”和验证码框添加回车键提交编辑的功能。
也可以是整个编辑页。
键盘比鼠标快，毋庸置疑。

**Comment by sxjeru** [comment]
@Ahrwing 
问题已解决，但还有一个附加问题。
如果连着按两次回车，资料将不会提交，只有隔开半秒按回车才能提交。
以前按鼠标提交得很快也会出现这种情况。

**Comment by Ahrwing** [comment]
SweetAlert弹窗美化插件的问题 不止swal 用 BootStrap 也会... 除非用原生的 confirm 不过那样会很丑..

**Comment by sxjeru** [comment]
罢了。
