### ISSUE TITLE
论坛帖子分享功能失效

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#388]
![image](https://user-images.githubusercontent.com/20513115/27982388-03985fbc-63d3-11e7-9d90-a003ff2bafc1.png)
RT。
单击“分享”即前往[论坛首页](http://bbs.mcmod.cn/#)。
无任何与分享有关的内容弹出。

**Comment by Ahrwing** [comment]
> 请提供浏览器及版本…

**Comment by sxjeru** [comment]
抱歉，这可能是误报。
我在360极速浏览器（版本不清，已卸）中尝试，无法弹出。
已在chrome 59.0.3071.115中证实可弹出。

**Comment by sxjeru** [comment]
又不能弹出了。。
浏览器版本 chrome 59.0.3071.115

**Comment by Ahrwing** [comment]
看看F12是否有错误提示 怀疑是其他js包含错误导致的

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/28202226-f5c6e718-68a6-11e7-9f2a-73ad51b9b690.png)

**Comment by sxjeru** [comment]
Chrome 60.0.3112.90 & Firefox，七天内测试均无异常，故关闭。
