### ISSUE TITLE
更细化的分类mod

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#39]
现在mod就四个板块，然后综合区的mod相当于其他三个区的总和还要翻倍……
应该把综合区分成几个大区或者在综合区内部做细致的划分，比如魔法类，科技类，储存类，装饰类这样的
AE是科技mod！

**Comment by Ahrwing** [comment]
曾经在群里讨论过这个问题很长时间，由于魔法和科技没有一个明确的分界线，所以就维持现在的分类了....
像魔法、科技这些可以在模组标签里添加

目前分类的规则为：
综合类：
1.功能方块：增加了一些具有特殊功能方块的MOD；
2.矿石：增加了一些矿产及相关产品的MOD；
3.建筑方块：增加了作为装饰品方块的MOD；
4.普通方块：增加了无用途的方块或可作为材料的MOD；
5.武器工具装备：以增加新材料的武器工具及装备为主的MOD；
6.普通物品：以增加没有任何特性的普通物品为主的MOD；
7.食物物品：以增加新的食物或药水为主的MOD；
8.交通工具：以增加新的载具或飞行器为主的MOD。

环境类：
1.新生态：增加了新生物群落系统的MOD；
1.新地形：增加了新地形的MOD；
3.新世界：增加了新世界的MOD；
4.新植物：增加了新的植物或花卉；
5.新地牢：增加了新的地牢。

生物类：
1.敌对生物：对敌对生物增强或增加的MOD
2.中立生物：对中立生物增强或增加的MOD
3.可驯服生物：对可驯服生物增强或增加的MOD
4.非玩家控制角色：增加新的NPC或可自定义新的NPC的MOD

补丁类：
1.API；<br/>
2.游戏补丁：高清，优化，输入补丁；
3.游戏辅助：仅提供辅助性的小工具MOD；
4.作弊工具：提供非正常手段获得物品或修改数据的MOD；
5.扩展开发：提供通过简单方式可以自行增加新要素的MOD；
6.游戏性扩展：仅扩展或修改了游戏性的MOD

**Comment by Ahrwing** [comment]
目前的分类作为一对多式分类已经很严谨了，像”魔法、科技“这类的分类以后可以考虑做成多对多形式的分类~

**Comment by Ahrwing** [comment]
模组元素已解决此问题~
