### ISSUE TITLE
为模组添加“模组状态”的显示

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#391]
根据梨木~小姐姐~提出的建议整理出来的完整方案：

在模组页面显示模组状态，可以根据状态查看modlist。

目前想到的状态有5种：
绿色：正常状态 保持更新；
橙色：作者半弃坑状态(6个月内没有动态) 或 已经开源且作者明确表示完全弃坑；
红色：作者明确表示完全弃坑且闭源；

银色：WIP MOD 目前为止仅实现了计划中的部分功能，尚未放出完整版；（隐藏的状态）
黑色：MOD做到一半不做了 ~胎死腹中~；（隐藏的状态）
蓝色：MOD设想并未开工；（隐藏的状态）

**Comment by 3TUSK** [comment]
* 开源不等于弃坑，弃坑不等于开源
* 胎死腹中的 Mod 为什么要记录？
* Mod 设想为什么要记录？

**Comment by Ahrwing** [comment]
@3TUSK 把有歧义的地方改了一下 (
那两个是隐藏的 _^_

**Comment by 3TUSK** [comment]
这是什么鬼特殊情况啊... 一个成品都拿不出的 Mod 也值得记录吗？

**Comment by Ahrwing** [comment]
如果.. 只是如果.... 有某个MOD介绍里写了丰富的内容，但是做了一半还没做完就放出来了，随后弃坑... 于是这MOD该怎么分.. 233 难道要把多余的介绍删掉吗~ (

**Comment by 3TUSK** [comment]
那是一个全新的状态：  
银色：WIP Mod，有些想法已实现，有些没有。
照这么说黑色可以表示“Mod做到一半不做了”。

**Comment by sxjeru** [comment]
绿色标签补充构建地址，橙色标签补充开源地址，红色标签补充404？

**Comment by Ahrwing** [comment]
已完成 目前加了4种状态~
![6 r eln1 9 0b344p](https://user-images.githubusercontent.com/5197567/30517487-95ec4ffc-9b93-11e7-841b-07c9307b39f1.png)
