### ISSUE TITLE
短评输入框无法完全覆盖

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#393]
![image](https://user-images.githubusercontent.com/20513115/28003821-1202a03e-6573-11e7-861c-1753a3a93ff4.png)
问题不大，特别是没改背景的情况下。
但为了美观还是修一修吧。
/*可通过css更改。*/

**Comment by 3TUSK** [comment]
> 我需要一个“外观”的标签

**Comment by Ahrwing** [comment]
Done and done~

**Comment by sxjeru** [comment]
emmm... reopen pls.
短评评论框翻页前宽度为858px，翻页后宽度变为600px，麻烦固定一个值。
涉及范围：所有1200px页宽的页面短评框。

**Comment by sxjeru** [comment]
另外请调整一下一些页面的评论框宽度，调整值为个人建议，供参考。
“MC老黄历”：616px -> 866px ;
“TC研究助手”：616px -> 866px ;
“成就生成器”：616px -> 866px ;
“模组关系图”：616px -> 1088px ;

**Comment by Ahrwing** [comment]
4.0页面已改为自适应… 不再是固定值~
