### ISSUE TITLE
模组关系显示不全

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#395]
rt，见图。
![image](https://user-images.githubusercontent.com/20513115/28116779-399d6982-673d-11e7-9d69-1c10ab7fc6d1.png)

**Comment by Ahrwing** [comment]
这个是故意改的… 限制了高度 不然变成两行更丑.. ( 好像没有其他办法 除非缩减字数

**Comment by sxjeru** [comment]
目前的改进是将模组关系提升一级，省略模组名称，鼠标放置显示全名。
不得不说这改动不错。
![image](https://user-images.githubusercontent.com/20513115/34648028-d2cdebec-f3cc-11e7-9f53-467a42f7b5ea.png)
