### ISSUE TITLE
教程区改革

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#397]
before：
- 公共教程与私人教程都不受《百科编辑规则》的约束；
- 公共教程可以被作者随意设为私人教程；
- ~存在感低~。

after：
- 公共教程必须遵守《百科编辑规则》；
- 公共教程与私人教程不可互相转换；
- 不允许同时存在相同主题的公共教程，私人教程则不受限制；
- 为私人教程设立三种用户组“创建者”、“管理者”、“协作者”；
- 私人教程“创建者”与“管理者”可以指定“协作者”共同完成编辑；
- 私人教程“创建者”可以设定某位“协作者”成为“管理者”；
- 把教程区搬到首页显示并在首页增加添加教程按钮；
- 教程分为图文教程与视频教程；
- 限制或禁止分P教程的出现。

以上..

**Comment by 3TUSK** [comment]
`我怀疑你在照搬分布式协作.png`

**Comment by Ahrwing** [comment]
> 只是想提高教程的质量，以吸引更多人选择百科。。

**Comment by Snownee** [comment]
建议：
* 细化公共教程审核流程
* 私人教程可以不可逆地转为公共教程

**Comment by Ahrwing** [comment]
@Snownee 如果可以转换的话，会涉及到用语和重复的问题..

**Comment by Ahrwing** [comment]
√
