### ISSUE TITLE
统一“模组”与“MOD”的叫法

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#400]
举个例子，仅在“添加模组”一栏中就可看到：

> 如果MOD有LOGO请加上……

> MOD名称、MOD原名

> 模组关系、模组元素、模组标签

**Comment by Ahrwing** [comment]
模组关系、模组元素、模组标签 这三个是功能的名字..

**Comment by 3TUSK** [comment]
CC Meow-J/Mod-Translation-Styleguide#11

**Comment by Snownee** [comment]
首先，我个人对组件这一叫法表示反对，组件纯粹是网易放弃对低龄玩家解释区别所推出的包办策略。而在这样的特定语境下，普遍认为 MOD = 模组。实际上，一个玩家如果需要自己安装所谓的“组件”，仍然需要经过一个“区分” 的过程。

然后，正因为 MOD = 模组，所以“MOD关系”或是“模组关系“本质上没有区别，在”同一页面“出现”同一义项“的两种说法，反而让用户感到迷茫：难道这之中有什么不同？

**Comment by Ahrwing** [comment]
还有就是对搜索引擎优化(SEO)有益, 无论用户搜索“MOD”还是搜索“模组” 百科的页面都能排到前面~

**Comment by Snownee** [comment]
有道理，不过给浏览器收录的信息并不一定要展示给用户吧？

况且，添加模组的页面也要被收录吗？

**Comment by sxjeru** [comment]
>……在”同一页面“出现”同一义项“的两种说法，反而让用户感到迷茫……

我想除非这用户是个钻牛角尖的人，一般人不会感到迷茫。
甚至大多数人会忽略这两者的区别，因为本来就是一个意思。
~~另外用相同意义的不同词汇据说能防止审美疲劳。~~

**Comment by Snownee** [comment]
没错，我就是钻牛角尖的用户，忽略了它们本来一个意思，甚至放弃了审美和国际化的需求。

**Comment by Ahrwing** [comment]
@Snownee 编辑页面统一了 其他页面肯定也要统一 例如编辑页面是“MOD关系” 展示页面是“模组关系” 就显得更乱 本身“模组关系”就是功能的名字

**Comment by Ahrwing** [comment]
@sxjeru ~你不介意的话可以用css来帮雪妮解决此问题~

**Comment by Snownee** [comment]
我有说只修改单独的页面吗？

**Comment by Ahrwing** [comment]
> 那就涉及到我之前提到过的SEO特性

**Comment by Snownee** [comment]
> 有道理，不过给浏览器收录的信息并不一定要展示给用户吧？

> 况且，添加模组的页面也要被收录吗？

**Comment by Ahrwing** [comment]
> 你是说只改添加模组这类 不一定想要让用户从搜索引擎点进来的页面吗？

**Comment by Snownee** [comment]
不是的，如果是“模组”和“MOD”这两个关键词都要出现，可以放在标题或是meta里面，但是作为上下文的内容，应该是统一和标准化的。

**Comment by Ahrwing** [comment]
`你怀疑你没听说过“关键词密度”`

**Comment by Snownee** [comment]
我对 SEO 确实了解不多，如果是出于这个原因，目前看来也可以理解，但是对于“添加模组”这类页面，就显得说不通了。

另外，我还是觉得统一名称比较好。

**Comment by sxjeru** [comment]
@Ahrwing ~~抱歉不知道怎么用css删去原有的字。~~

**Comment by Ahrwing** [comment]
@sxjeru ~你可以再加一个JS~
