### ISSUE TITLE
关于AE积分的小建议

### ISSUE THREAD

**Issue by friendlyhj** [Ahrwing/mcmod#404]
对于建议添加AE的我来说，目前的AE积分与我当初所说的还是有很多不足的，所以想说下，并进行一些补充。
1.目前贡献榜已经按字数来算，于是我建议在每编辑一次加1AE基础上，添加贡献榜奖励制度。每日贡献榜第一+5AE，每周第一+15AE，每月第一+50AE
   ###2.对于教程添加，我建议加的AE多一些，+4AE。
3.对于需要审核的百科用户，我建议加一个审核通过率系统。申请相关板块需要用户AE≥50且审核通过率≥95%才可以在此发帖。

**Comment by sxjeru** [comment]
教程按字数加ae更好吧。
第三个是什么？申请编辑员吗。

**Comment by HGLMiddle** [comment]
建议按字数计算，按每100个汉字计算3AE。
觉得每日结算会占用百科

**Comment by DYColdWind** [comment]
@HGLMiddle  100个字1AE吧，3AE不就等于1.5积分了。不就赚死了。
