### ISSUE TITLE
首页编辑记录显示框异常

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#406]
偶尔发生，暂不知原因。
F5可解决，留个档。
见图。
![9](https://user-images.githubusercontent.com/20513115/28753618-bc036e1e-7569-11e7-8eb1-99c858273bdf.gif)

**Comment by Ahrwing** [comment]
原因是占了两行..

**Comment by Ahrwing** [comment]
解决了 _(:з」∠)_

**Comment by sxjeru** [comment]
reopen? 
@Ahrwing 还有论坛页的也改一下吧。
