### ISSUE TITLE
允许模组有远古版本

### ISSUE THREAD

**Issue by liach** [Ahrwing/mcmod#408]
有的mod，比如铁路mod有远古版本，有些东西加得太早，版本记录里面都没有，然后上面就放点很奇怪的版本，还都是错的。
同时希望支持有些有patron的模组的预览版，就是内测版本啦

**Comment by liach** [comment]
同时给我个Railcraft的编辑好吗？

**Comment by 3TUSK** [comment]
0.请不要把一堆 issue 打包成一个

**Comment by Ahrwing** [comment]
如要添加版本 请在mod页面左侧点击“添加日志”即可~

**Comment by liach** [comment]
我添加了一个一直没有批准，而且批准了以后才可以加新物品

**Comment by 3TUSK** [comment]
我总感觉这个 issue 里的问题都已经解决了...

**Comment by Ahrwing** [comment]
yep.
