### ISSUE TITLE
后台批量选取排序&自动排序功能追加

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#409]
批量选取，即选取多个条目一起移动，选取部分顺序不变，整体顺序变动。
自动排序，即按照标题或其他规则自动排序。
尽快添加？
竹mod剩下十几个日志等着批量排序哦。
以上。
- [ ] 批量排序
- [x] 自动排序

**Comment by Ahrwing** [comment]
点击表头可以自动排序

**Comment by sxjeru** [comment]
啊，确实。
不过准确性还是差点。
![image](https://user-images.githubusercontent.com/20513115/28926294-f05a3ade-7899-11e7-86c7-b9b11477a9a3.png)

**Comment by 3TUSK** [comment]
> @Meow-J Not Enough Tags

**Comment by Ahrwing** [comment]
关于第一条.. - - 因一些技术层面上原因无打算实现..
