### ISSUE TITLE
[BUG] 带链接或者粗体文字都显示成最小字号

### ISSUE THREAD

**Issue by cfvbaibai** [Ahrwing/mcmod#41]
Sample: http://www.mcmod.cn/post/181.html
粗体文字被显示成最小字号的段落（编辑时没有指定字号）：这里利用了传输类管道的一个特性：如果相连的容器或者机器已满，那么物品会随机挑选当前格的其它岔路继续传输。
![issue-41-1](https://cloud.githubusercontent.com/assets/3370676/9310742/32cba3b6-4544-11e5-871e-f5a7cc496886.png)
链接文字被显示成最小字号的段落（编辑时设定的是最大字号）：传输类：圆石管道、石制管道、沙石管道、石英管道、金制管道
![issue-41](https://cloud.githubusercontent.com/assets/3370676/9310719/14ac7068-4544-11e5-9e53-8f6e2fb72cb1.png)

总结：字号在编辑视图里是正确的，但是一旦保存后显示出来就强行变最小的了

**Comment by Meow-J** [comment]
相关 #3

**Comment by cfvbaibai** [comment]
主要原因是main.css里用 * 选择器规定了全局的字体，优先级过高，改成 body 选择器会让整个样式优先级自然许多

**Comment by Meow-J** [comment]
@Ahrwing

**Comment by Ahrwing** [comment]
已优化样式~ 但是还没有全面测试，有BUG再反馈吧~

**Comment by Meow-J** [comment]
戳一下

**Comment by Ahrwing** [comment]
已解决~
