### ISSUE TITLE
关于mod下载

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#412]
1. mod资源添加权限。
目前百科有一些mod取得了权限，却没有资源。诸位对于公开或授予该权限有何意见。
在我看来，公开权限不利于百科，也不现实。
主要问题在于心怀不轨之人可能将病毒等作为mod上传。
emmm...
授予或许是申请更好些。

2. mod资源添加提示。
添加一个资源明显比添加一个合成表要繁琐，所以请于最新变动页中加入，并计入编辑次数/字数（?字节），以此勉励贡献者。

3. mod资源审核。
实现起来怕是有难度，建议直接通过，跳过审核。

4. mod资源可信度。
这个涉及杀软扫描结果，如果可能，请在上传mod后自动杀毒，然后提供结果快照。
以下是几个在线扫描网站。
[VirusTotal](https://www.virustotal.com/#/home/upload)（有API）
[Jotti](https://virusscan.jotti.org/zh)（有API）
[VirScan](http://www.virscan.org/)（我认为已经失效……）
[ThreatBook](https://x.threatbook.cn/)（有API）

8.20追加：

5. mod资源排序。
这个如果能实现自动化那更好，起码要支持手动排序。

以上建议均为待论状态。

**Comment by 3TUSK** [comment]
CC #335

**Comment by 3TUSK** [comment]
1. #340 如果有一个“百科大使馆”这样的存在，那么这个问题就好解决得多——可以让“百科大使馆”代表百科与 mod 开发者进行沟通。
2. 暂无想法。但是我觉得可以做一个RESTful API 或者 RSS 推送？
3. 必须有审核。国内暂时没有已知案例；Tinkers' Construct 曾经出过其 CurseForge 上的项目的一名管理人员账号被盗然后上传了恶意软件（根本不是 mod，需要双击 jar 运行）的案例。暂时找不到相关链接- -
4. 同 3.。事实上我觉得你的 3. 和 4. 说的是一回事。

**Comment by sxjeru** [comment]
[https://www.reddit.com/r/Minecraft/comments/56jacp/if_you_have_downloaded_tinkers_construct_254/](https://www.reddit.com/r/Minecraft/comments/56jacp/if_you_have_downloaded_tinkers_construct_254/)
似乎意识到了严重性。。

另与开发者沟通，是打算让开发者在百科上传mod？

**Comment by 3TUSK** [comment]
kek. 刚才我一直在找的是这一个：
https://www.reddit.com/r/feedthebeast/comments/56gq12/delete_tic_254_if_you_downloaded_it/

**Comment by 3TUSK** [comment]
关于与开发者沟通：

> 目前百科有一些mod取得了权限，却没有资源。诸位对于公开或授予该权限有何意见。
> 在我看来，公开权限不利于百科，也不现实。
> 主要问题在于心怀不轨之人可能将病毒等作为mod上传。

百科如果这么做，就是在分发 (distribute) 编译过的二进制档 (binary executable)，当然需要确认版权情况咯。

**Comment by sxjeru** [comment]
如果作者已经在curse声明的版权情况，应该就不需要了吧。

另外开源mod是否可以不经授权分发二进制文件？
CC3.0/4.0 MIT LGPL Apachev2.0
我是依照维基中的“自由软件”条目，单方面认定为可以分发的。

**Comment by 3TUSK** [comment]
我建议不要看 Curse - 如果是开源的 Mod，以其源码所附带的 license 为准；否则直接联系作者。

不要看 Curse 是因为 Curse 的服务条款十分可疑。

**Comment by sxjeru** [comment]
受教了，感谢。
***
还真有这样的。。    
![image](https://user-images.githubusercontent.com/20513115/29401887-8215e36c-8365-11e7-9543-87db38b6531d.png)
![image](https://user-images.githubusercontent.com/20513115/29401912-9716deec-8365-11e7-9857-342fb542d16b.png)

**Comment by 3TUSK** [comment]
呃，你看一下 [NEI 1.8+ 的 CurseForge 的项目页面](https://minecraft.curseforge.com/projects/not-enough-items-1-8)？

**Comment by 3TUSK** [comment]
对。也算是某种意义上**按规则进行游戏，顺带提醒 mod 作者遵守游戏规则**了吧...

**Comment by yesterday17** [comment]
我个人建议可以直接从curseforge上爬下来（特指能够在curseforge上下载的mod）。对于已经得到许可的mod可以在数据库中增加相应条目，并且在服务器相对空闲时进行版本检查&下载。
对于未在curseforge上发布的mod再实行风险较大的人工上传。
当然，爬下来的mod也是需要经过一定的检查的。

题外话 话说上次is不是有人写了个curseforge爬虫爬了全站的数据吗（233

**Comment by 3TUSK** [comment]
@yesterday17 冷笑话：CurseForge 有 maven！
来看看这个你就知道啦：https://gist.github.com/3TUSK/862353d42c8cd84167eff1701b34721d

**Comment by Ahrwing** [comment]
1.只会给固定的人员开放上传权限 
2.已添加上传后的提示 
3.同1 
4.同1
5.`建设中`

**Comment by sxjeru** [comment]
另外文件上传者也可以写在文件信息里。
一些挫劣的例子。
![image](https://user-images.githubusercontent.com/20513115/32695819-1862aed8-c7a2-11e7-8eae-7ebfa05ba1d0.png)

**Comment by Ahrwing** [comment]
@sxjeru 先不加好了.. 如果想要看是谁上传的, 可以到编辑记录里看~

**Comment by 3TUSK** [comment]
> 一些挫劣的例子。

https://github.com/TeamCovertDragon/MooncakeCraft/releases/tag/1.2.0
~~我来查水表的~~

**Comment by Ahrwing** [comment]
@3TUSK = = 可以解释一下吗 [x
