### ISSUE TITLE
图片水印出错

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#413]
已验证三种格式：jpg、png、gif。
jpg&gif正常。![image](https://user-images.githubusercontent.com/20513115/29400425-f86aa512-835f-11e7-9d7b-6c6f24d22c7e.png)
png异常。![image](https://user-images.githubusercontent.com/20513115/29400451-065307a0-8360-11e7-808c-20f9fc2827de.png)

望处理。

**Comment by Ahrwing** [comment]
png水印失真问题已解决
![水印测试](http://bbs.mcmod.cn/data/attachment/album/201712/15/141237lzrwpjcc70rr0cit.png)
