### ISSUE TITLE
mod点赞功能失效

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#414]
目前所有mod均处于“已点赞”状态，实际并没有点赞。
等了三十分钟无变化，怀疑是bug。
已尝试退出登录，强制刷新，隐身窗口打开，均无变化。
![image](https://user-images.githubusercontent.com/20513115/29661439-9af4bc32-88f6-11e7-9475-ac4a7918540a.png)
![image](https://user-images.githubusercontent.com/20513115/29661472-b1f4d1b0-88f6-11e7-816a-f8376fe03af6.png)

**Comment by sxjeru** [comment]
状况更新，bug未修复。
![image](https://user-images.githubusercontent.com/20513115/29667896-c1df9a96-8910-11e7-8b02-6024d3d35a4c.png)

**Comment by sxjeru** [comment]
√

**Comment by sxjeru** [comment]
冷却时间似乎不是半小时？

**Comment by sxjeru** [comment]
结果又出现了所有mod都已点赞的情况。。

**Comment by Ahrwing** [comment]
原设定是每半小时可对任意MOD点一次赞 （因为点赞的同时MOD会被推向首页）

**Comment by Meow-J** [comment]
![image](https://user-images.githubusercontent.com/5229241/29798009-4e055e4c-8c28-11e7-8814-bd22e8238f99.png)
只要点赞一个，其它所有Mod的状态都变为已点赞了/w\

**Comment by Ahrwing** [comment]
为了避免误会.. “点赞”已改为“推荐”
