### ISSUE TITLE
百科对矿物辞典的理解错误

### ISSUE THREAD

**Issue by liach** [Ahrwing/mcmod#415]
1. 一个物品可以有多个矿物辞典，不只一个。
2. 矿物辞典可以自由添加，不应该像百科上面一个一个注册。最好要有原名。

**Comment by 3TUSK** [comment]
第二条难道不是为了防止破坏性编辑？

**Comment by Ahrwing** [comment]
矿物词典目前还是半成品…
关于第二条，大概像合并资料一样～ 要么需要审核要么只能编辑员操作吧～

**Comment by liach** [comment]
OreDictionary本身是以一个字符串作为id的，不应该需要删除啊。用英文名字就可以了，这样差不多永远不要合并了

**Comment by Ahrwing** [comment]
我是拿“物品合并”的功能来举例…

**Comment by Ahrwing** [comment]
矿物词典现已允许存在多个，且支持参与搜索，但由于手动添加工作量太大，因此请使用IRR批量导入~
