### ISSUE TITLE
为MOD区添加“发展路线”功能

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#416]
由于部分MOD在资料中并不能突出重点资料，以及模组的发展路线，这点很难超越传统的图文教程，所以打算增加一个“发展路线/模组科技树(?)”功能，可以自定义物品的发展阶段（允许存在多种发展路线），从而显示拓扑图，并可以生成/导出图片形式的文件。

例如 【时间和空间的相对维度 (TARDIS MOD)】 这个MOD，在资料中大部分是较为分散的方块介绍，且这些方块是生成出来不可获得的.. 玩家会一头雾水不知从何开始..
http://www.mcmod.cn/class/894.html

有更好的建议欢迎提出~

**Comment by 3TUSK** [comment]
为什么我的第一反应是“一百个玩家有一百种玩法”？

**Comment by Ahrwing** [comment]
@3TUSK 这个考虑到了… 初步打算做成 [公开编辑+绑定用户] 的形式 每个账号都可以为每个MOD添加一种发展路线..
