### ISSUE TITLE
无法对教程进行编辑

### ISSUE THREAD

**Issue by EstrousTom** [Ahrwing/mcmod#417]
rt，在提交修改时，提示一项或多项必填项未填。
同时窗口无法滑动。
但我已经把验证码和变更说明填完。
已经好几天了，望解决。
暗者的小技巧（二）增压超频 - [GT6]格雷科技6 (GregTech6) - MC百科|最大的MineCraft中文模组百科 http://www.mcmod.cn/post/440.html

**Comment by Ahrwing** [comment]
刚才测试了一下 我这边没有出现这样的情况… 麻烦提供一下浏览器类型和版本以便进一步测试~

**Comment by Ahrwing** [comment]
未收到回复且经测试无问题 问题关闭
