### ISSUE TITLE
几个月没来,网站改版了

### ISSUE THREAD

**Issue by wstars1994** [Ahrwing/mcmod#418]
首页是真的乱啊,你们的产品UI怎么想的....

**Comment by 3TUSK** [comment]
我想你应该具体描述一下“乱”在哪里... 每个人对乱的直观认识都或多或少有出入的。

**Comment by wstars1994** [comment]
我可能只是喜欢简洁一点的设计风格吧.刚才进首页浏览了一下觉得贵站就像把所有内容全都放到了首页,一眼望去密密麻麻(我没有所谓的密集恐惧症),还有检索功能(版本,拼音)应该放到进入网站就能看到的位置,毕竟我进来是找mod的,个人拙见.

**Comment by Ahrwing** [comment]
如果更喜欢以前的版本，是可以切换回老版本的：http://www.mcmod.cn/v2/ （这个链接在新版首页导航里有）
或者通过 http://www.mcmod.cn/about/ 联系产品UI提出你的建议~

**Comment by Meow-J** [comment]
现在的主页就是很乱啦_(:з」∠)_，文字量爆炸了
