### ISSUE TITLE
配方没考虑可否翻转

### ISSUE THREAD

**Issue by liach** [Ahrwing/mcmod#419]
forge的矿物辞典配方很多是可以翻转的，比如工具配方。
源码：https://github.com/MinecraftForge/MinecraftForge/blob/8803bf9a29f426f1025924b56c9d1572e01fde23/src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java#L63
希望能把这一个特点加到百科的配方编辑中。

**Comment by YoungGT** [comment]
你的意思是说所谓的镜像配方？

**Comment by liach** [comment]
@YoungGT 对。

**Comment by YoungGT** [comment]
这个玩意确实很有必要，比如原版的石铲子是[空,圆石,空],[空,木棍,空],[空,木棍,空]，但是很明显，在左边摆一竖遛也可以合成，那么该怎么选摆放要求就很难，选有序合成但也不用完全摆在中间，选无序合成就说明可以任意摆材料够了就可以不需要搞成某种形状。
不过，这个想法我也是有过的，在百科的主群说了，然后不了了之。当时我的想法是这样：搞个模板可以使用不同规格的合成台（类似2*2的），之后选模板加配方，当然这个肯定是不行的。。还不如搞个摆放要求叫镜像合成。

**Comment by liach** [comment]
有序合成本来是任何格子都可以放的，只是有些特殊合成不行（比如旗帜染色）

**Comment by Ahrwing** [comment]
>尝试加入了"灵巧合成"的设定
>被群员认为很鸡肋
>已恢复"出厂设置"
