### ISSUE TITLE
合成表 Tooltips 再次错位？

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#421]
![image](https://user-images.githubusercontent.com/16059084/29992098-537085fe-8fc6-11e7-8743-b254244ac5b1.png)

**Comment by sxjeru** [comment]
一般浏览器缩放开了就会这样，缩放比例越大偏移越大。

**Comment by Snownee** [comment]
然而我没开

**Comment by sxjeru** [comment]
但我没这种问题。
![image](https://user-images.githubusercontent.com/20513115/29992591-23aa5b2c-8fd2-11e7-89ec-339c99a64ee0.png)

**Comment by Snownee** [comment]
退一步讲，就是调整了缩放（或其他）设置，也理应正常显示的。

**Comment by sxjeru** [comment]
不然，调整缩放位置就变了。
position: absolute;

**Comment by Ahrwing** [comment]
在v4更新时此问题已被修复，支持所有主流浏览器。
