### ISSUE TITLE
首页推荐物品 Tooltips 缺失

### ISSUE THREAD

**Issue by Snownee** [Ahrwing/mcmod#422]
![image](https://user-images.githubusercontent.com/16059084/29992115-85e06798-8fc6-11e7-85e9-0bce1da7cb4a.png)

**Comment by sxjeru** [comment]
我还是建议检查下浏览器设置。
![image](https://user-images.githubusercontent.com/20513115/29992598-51306b36-8fd2-11e7-96c5-f78689f13c98.png)

**Comment by Snownee** [comment]
退一步讲，就是调整了缩放（或其他）设置，也理应正常显示的。

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/29992629-08d6c3fc-8fd3-11e7-8c25-f6767c08c093.png)

![image](https://user-images.githubusercontent.com/20513115/29992628-fe750176-8fd2-11e7-8d2c-f8483e2c3b9a.png)

**Comment by Snownee** [comment]
你要这么想我也没话可说。缩放和内容正常显示理应不冲突。

**Comment by Ahrwing** [comment]
早已修复（v3就修了）

> btw. 首页之后会更新至v4以支持移动端响应式适配。
