### ISSUE TITLE
首页推荐区总是跳到第一张

### ISSUE THREAD

**Issue by zhen-xianmao** [Ahrwing/mcmod#425]
就是那个贴着BC石管和金管的那个区域,好好的看其他的,点右边那些点还没等咱开进去就跳到了"百科带宽升级"这个公告
快修啊啊啊啊啊!!!(╯‵□′)╯︵┻━┻

**Comment by Ahrwing** [comment]
是不是用了鼠标滚轮…

**Comment by zhen-xianmao** [comment]
不是QWQ直接拿鼠标点旁边的白点的QWQ

**Comment by sxjeru** [comment]
有延迟的，大概是3.5s。
当然这是以你点击白点之前的画面开始计时的。
同样觉得这设计不太对，主要有两点需改进。
1. 点击白点后重新计时。
2. 从点击白点页开始向下滚动，而不是转至第一页，

**Comment by Ahrwing** [comment]
已解决~
