### ISSUE TITLE
审核名称修改识别错误

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#427]
![image](https://user-images.githubusercontent.com/5229241/30508228-0579f75a-9a60-11e7-8e58-04bcddfcf9e1.png)
全部修改：
![image](https://user-images.githubusercontent.com/5229241/30508231-115cd498-9a60-11e7-88b7-2dda0dccfdba.png)
 完全没有修改名字嘛/w\

**Comment by Ahrwing** [comment]
唔.. 目前没有填译名的条目会出现这个问题

**Comment by Ahrwing** [comment]
已解决~
