### ISSUE TITLE
编辑器粘贴不保留格式

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#433]
最近出的问题。
建议保留格式，否则对资料编辑，特别是日志添加有很大影响。

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/31888580-4c26a9c2-b82f-11e7-9c42-15c68e27c3ec.png)
![image](https://user-images.githubusercontent.com/20513115/31888587-548e7b3a-b82f-11e7-8a61-c632916e6fda.png)
![image](https://user-images.githubusercontent.com/20513115/31888598-5f44177e-b82f-11e7-9630-ad95b08c0b33.png)
![image](https://user-images.githubusercontent.com/20513115/31888630-6f64e052-b82f-11e7-944c-94f13230ffb3.png)
![image](https://user-images.githubusercontent.com/20513115/31888642-766783b4-b82f-11e7-82cd-e80a031be7f6.png)
![image](https://user-images.githubusercontent.com/20513115/31888650-7e27855e-b82f-11e7-9f07-0534c3762685.png)
![image](https://user-images.githubusercontent.com/20513115/31888726-c429b310-b82f-11e7-959e-7fe13b052b8d.png)
![image](https://user-images.githubusercontent.com/20513115/31888739-ceb6a428-b82f-11e7-9af5-e355bdd49e9a.png)
![image](https://user-images.githubusercontent.com/20513115/31888744-d2b14b78-b82f-11e7-9daf-0395f30f986e.png)
![image](https://user-images.githubusercontent.com/20513115/31888754-dbc52310-b82f-11e7-9055-4ba11fdf7286.png)
![image](https://user-images.githubusercontent.com/20513115/31888762-def69668-b82f-11e7-9ebd-05210e4a7a6f.png)
之后不了了之。

**Comment by Ahrwing** [comment]
把你复制的地址 或者html发过来 我试试看 0 0

**Comment by sxjeru** [comment]
@Ahrwing [http://gregtech.overminddl1.com/changelog/#Changelog](http://gregtech.overminddl1.com/changelog/#Changelog)

**Comment by Ahrwing** [comment]
已找到原因：这里出现的内容并非<br> 也非<p> 而是 \n ... 正在想解决方案

**Comment by 3TUSK** [comment]
`\n` 也是令人震惊的，能想办法编译到 html 么

**Comment by Ahrwing** [comment]
实际上.. 在粘贴的时候 `\n` 是包含在内容里面的，所以假如能做到在编辑器中将 `\n` 自动替换为 `<br/>` 就可以解决此问题…
此外还有一种办法，就是在提交之后在后端执行这个替换，但是在编辑器中看不到换行的效果，用户体验很差……

**Comment by 3TUSK** [comment]
> 所以假如能做到在编辑器中将 \n 自动替换为 <br/>

**Comment by Ahrwing** [comment]
XD 需要抽空去尝试一下
