### ISSUE TITLE
【备忘】为资料类型添加自定义项

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#434]
- 什么是资料类型？
在编辑资料时顶部可供选择的“物品”、“生物”、“多方块结构”等。
- 需要做什么？
允许任何用户添加全新的资料类型，与资料一同提交上去。
- 详细的流程？
在资料类型右上角点击创建新类型，填写类型的[名称] [简介] [主题色(非必填)] [图标(非必填)] 后方可提交创建新类型申请。

**Comment by 3TUSK** [comment]
> 终于来了

**Comment by mamaruo** [comment]
That's good.

**Comment by FunnyGoldApple** [comment]
这个创建新类型的按钮在哪呢？我在资料编辑页面没看到

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/60862544-6f4e5a00-a250-11e9-8321-35ba6c5ce0cb.png)
v4.0后台已增加此功能。
