### ISSUE TITLE
矿物辞典的完善与改进

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#435]
RT。目前，矿物词典只是个半成品，而且还是用ID来标记的，所以希望更改成用其矿辞名来标记。同时希望可以将矿辞当作一种物品来添加/编辑，并在后台建立模组矿辞列表，可以添加/更改矿辞，以及取消在某物品上的标记。
以上。

**Comment by 3TUSK** [comment]
#415...

**Comment by liach** [comment]
还有mezz的oreregistry被采用后百科怎么应付

**Comment by Ahrwing** [comment]
@liach 这个我还不了解 有资料吗？

**Comment by liach** [comment]
https://git.io/vdg8t

**Comment by 3TUSK** [comment]
@Ahrwing 未确定的特性就先不要考虑了。

**Comment by Ahrwing** [comment]
- 矿物词典现已改为隐藏字段，由批量导入时自动添加。
- 矿物词典现已支持参与搜索。
