### ISSUE TITLE
主站首页搜索框文字不同步

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#439]
RT——
不论从上框输还是从下框输。
![image](https://user-images.githubusercontent.com/20513115/32979129-8bde5564-cc8a-11e7-8154-82f4883dee46.png)

（我虽自认为没有强迫症，但这个我真看不顺眼。即便我不常用百科搜索。）

**Comment by sxjeru** [comment]
下框已被去除，结束issue。

**Comment by Ahrwing** [comment]
problem --> ~no problem~
