### ISSUE TITLE
编辑模组时由于图床问题无法上传

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#44]
然而图片问题并不是我的锅＞W＜

**Comment by Ahrwing** [comment]
没看懂 0 0.. 是某图床问题导致百科出错吗？ 如果是图床问题，换个图床就好了啊.. 或者用百科相册...

**Comment by elctove** [comment]
我想改其他的部分，但由于原有的图片导致没法提交

**Comment by Ahrwing** [comment]
还是不明白... 图片不是必填项啊.. 原有的图片无论是留着、还是删掉、还是替换成别的，都不会影响提交啊..

**Comment by Meow-J** [comment]
最好来个截图什么的吧

**Comment by Ahrwing** [comment]
群里看到截图了，这不是BUG……
某些图床因为非永久或外链问题已被禁止使用，请使用百科相册或者更换其他图床！
