### ISSUE TITLE
【备忘】“历史上的今天”功能

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#441]
可以显示历史上所有今天所发生的事（允许编辑）~
例如某MOD首次发布(跳转MOD页)、原版更新、MC大事记、生日(跳转个人中心) 等~

`话说今天发现盗版百科用http也可以正常访问了 怕不是要出事儿`

**Comment by sxjeru** [comment]
>话说今天发现盗版百科用http也可以正常访问了 怕不是要出事儿
![image](https://user-images.githubusercontent.com/20513115/32990859-cdfa419c-cd6b-11e7-83f6-42260eaa0c86.png)

**Comment by 3TUSK** [comment]
如何确认 Mod 的大事件的日期？
