### ISSUE TITLE
物品重名制度更改

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#442]
RT。目前百科对于重名物品基本上就是强制的不给予通过并且显示出重名的物品，这明显的方便了我们的编辑、保证了不会有重复；但是我们还知道的就是有些mod里面是有物品不是 **重复** 但是却 **重名** 的，例如BiblioCraft的[椅背](http://www.mcmod.cn/item/7523.html)（你可以看见这玩意的相关物品里面都是“重复”物品）、EIO的[储存控制面板](http://www.mcmod.cn/item/60622.html)。很明显，这不是 **重复** 的物品，但是百科自身并不能判断其是否是真正的重复物品，于是导致了这种现象的发生。故提出以下几点改进建议：
    1. 取消百科自身重名物品的检测
2.添加如敏感词提示一样的“重名物品提示”，让编辑者自身去判断
3.允许重名制（不知道百科的物品重名是仅限于编辑层面有问题还是允许之后是会出现一些奇怪的错误）

**Comment by sxjeru** [comment]
给个折中意见，中文名允许重名，原名不允许。

**Comment by 3TUSK** [comment]
http://www.mcmod.cn/item/60622.html

^ 名字里少一个 y。

我个人认为这其实是个 Bug，理由大概是百科的每一个条目似乎都有一个数字编号，理论上并不需要有禁止重名的设定... 不过，有更好的例子吗？BiblioCraft 的那个“椅背”的翻译并没有严格遵从原文，而 EIO 的那个 Inventory Panel 和 Inventory Panel Remote... 完全不知道是怎么回事，怎么翻译成一样的名字的。

**Comment by Ahrwing** [comment]
已允许编辑与创建重名资料
