### ISSUE TITLE
【备忘】“最新变动”页面上方字体大小不正常

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#443]
![](http://bbs.mcmod.cn/data/attachment/album/201711/22/210612x3eb2xsoktqbzi3t.png)
![](http://bbs.mcmod.cn/data/attachment/album/201711/22/210612gu42an29u242n2u9.png)
~~重生让我发issue加上备忘没毛病~~

**Comment by sxjeru** [comment]
说一下浏览器版本吧。
Chrome 62.0.3202.94 ( x64 ) 表示无异常。
![image](https://user-images.githubusercontent.com/20513115/33319134-417aea96-d478-11e7-82cd-5fea94dc2618.png)
![image](https://user-images.githubusercontent.com/20513115/33319151-4cb77cb2-d478-11e7-8240-9bc365838857.png)

**Comment by Ahrwing** [comment]
Firefox 57 也有这个情况出现

**Comment by sxjeru** [comment]
IE 11.0.9600.18793 无异常。
![image](https://user-images.githubusercontent.com/20513115/33480244-6ba17c68-d6cb-11e7-8e60-9ae7f1f46e6a.png)
![image](https://user-images.githubusercontent.com/20513115/33480262-7ea4b51e-d6cb-11e7-959a-500783e03555.png)

**Comment by sxjeru** [comment]
Firefox 50.1.0 无异常。
![image](https://user-images.githubusercontent.com/20513115/33480773-ddd93f7c-d6cc-11e7-9438-724ba57379dd.png)
![image](https://user-images.githubusercontent.com/20513115/33480785-e60665da-d6cc-11e7-8e3e-8cb8e954805d.png)

**Comment by YoungGT** [comment]
换了Chrome 62.0.3202.94 ×64仍旧有此问题....

**Comment by Ahrwing** [comment]
已解决~
