### ISSUE TITLE
“设计工坊”

### ISSUE THREAD

**Issue by Ahrwing** [Ahrwing/mcmod#445]
- 在MOD页面新建“设计工坊”栏目
- 每个MOD都有独立的“设计工坊”专区
- 注册用户可以上传自己的<作品>到“设计工坊”中
- 可以为自己的<作品>选择设计中使用了哪些MOD（多选，默认贴上当前MOD）
- <作品>会在所有贴上MOD标签的MOD页面中显示

**Comment by liach** [comment]
有什么具体意义吗？

**Comment by Ahrwing** [comment]
@liach 让玩家更了解多MOD配合，而不是一成不变的玩固定几个MOD~
试想自己从来没接触过甚至嗤之以鼻的MOD原来还可以用来和自己常玩的MOD搭配做一些有趣的事~
设计工坊与教程不同的是，教程是"教会你如何去做"，而设计工坊则是更倾向于"分享"~

**Comment by 3TUSK** [comment]
> BTM Moon

**Comment by 3TUSK** [comment]
@Ahrwing 当真这个“栏目”不放在论坛成为一个新的板块？

**Comment by Ahrwing** [comment]
@3TUSK 放在论坛时与现有数据结合比较困难.. 且谁都能做.. 没有竞争力... _(:з」∠)_
例如说在发表时可选择(百科中存在的)MOD用来标示这篇设计用到了哪些MOD 还有每周热度排行等

**Comment by Ahrwing** [comment]
教程已经允许绑定MOD，一定程度上已经实现了这个功能。
