### ISSUE TITLE
用户名与昵称分离制

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#446]
一个设想，能否把用户名和名称分开。
用户名只负责登录，而名称则公之于众。
用户名不得更改，而名称可更改，也可以加次数或时间限制。

原因则是因为许多人（包括我）都会误以为用户名只用作登录凭证，这也是多数网站的选择。
以上。

**Comment by sxjeru** [comment]
目前似乎有个替代功能，“自定义头衔”，但离设想还是差的太远了。

**Comment by Ahrwing** [comment]
可实现 #447 ~

**Comment by sxjeru** [comment]
All right——
（还以为重生爆肝了的说。。）

**Comment by Ahrwing** [comment]
done
