### ISSUE TITLE
允许更改用户名

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#447]
贴吧都允许改名称了，百科就别再吝啬了。
特别是现今的“QQ酱xxxxx”，我认为实现这类人群更改用户名的功能是当务之急。
想必他们也有强烈意愿改名的。
（#446 无法实现的备用方案）

**Comment by sxjeru** [comment]
群内有人提到了，优先级+1。

**Comment by Ahrwing** [comment]
更改用户名需要对大量的表进行操作，目前百科使用的数据库引擎不支持事物，因此在处理批量操作的时候如果出现任何问题难以回滚。

目前的可行方案：
1.增加“昵称”字段 与用户名分离可随意调整 但增加了程序的复杂度 （几乎所有出现用户名的地方都要改）
2.使用阿里RDS (云数据库)

**Comment by 3TUSK** [comment]
> 重构.php

**Comment by Ahrwing** [comment]
`出现了...!`

**Comment by Ahrwing** [comment]
done
