### ISSUE TITLE
删除无用页面

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#453]
建议删除 http://www.mcmod.cn/help 及其子页（http://www.mcmod.cn/help/access/ 除外，或重定向），放了四年的“建设中”也该寿终正寝了。
删除后的404问题可以重定向至 http://mcmod.readthedocs.io/zh/latest/ 
![image](https://user-images.githubusercontent.com/20513115/34318876-eae1ad84-e80c-11e7-9a27-c021fc3bdd51.png)

**Comment by Ahrwing** [comment]
done. (Efficiency III)

**Comment by sxjeru** [comment]
Happy Christmas! (Fortune III)
