### ISSUE TITLE
mod大文件无法上传

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#454]
相关 #412 .
该issue中对大文件的定义：~>17.5MB的文件。

上传大文件会出三种错误，但有极小几率成功。
错误一：
![image](https://user-images.githubusercontent.com/20513115/34380871-ab40fc62-eb3f-11e7-92ec-082a9ec4156f.png)
搜了一下，与阿里防火墙有关。

错误二：
![image](https://user-images.githubusercontent.com/20513115/34380883-c32280ee-eb3f-11e7-8425-7de3f6f6b042.png)
搜索后感觉是上传控件的问题。

错误三（新）：
![image](https://user-images.githubusercontent.com/20513115/34646445-50349920-f3a3-11e7-8195-73fc4dbfee08.png)
这是百科自身报错，搜不到有用信息。

留档，以上。

**Comment by sxjeru** [comment]
### 2018.01.07 update.
经过多次测试，证实错误一、二已无法重现，全部变为错误三。
仍有小几率上传成功。

**Comment by sxjeru** [comment]
换了一个26.7MB的文件测试，每次能上传到100%，但结果均返回错误如下：
`缺少参数`

**Comment by sxjeru** [comment]
重视度+1
`重复十多次没成功，脸黑 <`

**Comment by Ahrwing** [comment]
2018年2月2日
重构模组上传功能 增加进度条使其支持大模组文件上传 并移至后台 (17:32)

**Comment by sxjeru** [comment]
wait! 大文件还是无法上传。
![image](https://user-images.githubusercontent.com/20513115/35727885-a7ed6b0a-0844-11e8-955c-7df00e5a8a4a.png)

**Comment by Ahrwing** [comment]
OAO!? 发给我试试……

**Comment by sxjeru** [comment]
用qq传给你。

**Comment by Ahrwing** [comment]
原因： 这个进度条是指 `上传` 至 [百科服务器] 的进度，之后还需要`移动`至 [文件服务器] …… 
于是问题来了… `上传` 需要消耗上行带宽，一般充足够用。而`移动`是需要下行带宽的，一般下行带宽被塞得满满的，需要漫长的等待时间………

**Comment by sxjeru** [comment]
No closed...

**Comment by sxjeru** [comment]
叩叩叩——
@Ahrwing Reopen吧。
![image](https://user-images.githubusercontent.com/20513115/35774489-1f87e182-09ac-11e8-9240-a4845653c2d7.png)

**Comment by sxjeru** [comment]
错误四：
![image](https://user-images.githubusercontent.com/20513115/35774523-04a988e2-09ad-11e8-9aeb-82c183b1a7c5.png)

**Comment by Ahrwing** [comment]
还是带宽原因… 
目前的解决思路：
1.限制上传文件大小为10M~
2.大文件可以通过FTP上传至百科服务器
3.在后台追加一个按钮检测百科服务器中的文件上传至文件服务器~

**Comment by sxjeru** [comment]
10MB有些小吧，gt6 17MB上传成功率93%。

**Comment by Ahrwing** [comment]
okay.. 限制调成20M 如果上传不了依然可以用FTP上传的方式解决~ `这个FTP账号会开放给有上传权限的人使用`

**Comment by Ahrwing** [comment]
waaait... 还有个方案… 或许我可以尝试一下~

**Comment by sxjeru** [comment]
！

**Comment by Ahrwing** [comment]
搞定了~ 看来这个方案比较稳定~ 去后台试试吧w

**Comment by sxjeru** [comment]
确认了。

**Comment by sxjeru** [comment]
成功上传一个文件后就不行了。。
![image](https://user-images.githubusercontent.com/20513115/36152748-017c149e-1107-11e8-9aaf-b41c0c676b8c.png)
