### ISSUE TITLE
部分选取文件处指定文件类型

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#457]
“指定文件类型”定义：在“打开”对话框中可选文件类型。
![image](https://user-images.githubusercontent.com/20513115/34454383-5ad056a2-eda5-11e7-82ee-ec47c85c1767.png)
目标达成示例，即论坛的[图片上传处](http://bbs.mcmod.cn/home.php?mod=spacecp&ac=upload)，只显示图片文件。

1. mod文件上传区：
![image](https://user-images.githubusercontent.com/20513115/34454181-e33b57ee-eda0-11e7-9ccd-574362e794d2.png)
将文件类型指定为 jar, zip, litemod。

2. mod封面选择图片：
![image](https://user-images.githubusercontent.com/20513115/34454222-c666f410-eda1-11e7-9d08-15dd2bc4c184.png)
将文件类型指定为图片文件，
简单点就用常用格式 jpg, png, webp, gif, bmp。
认真点就用下面的：
![image](https://user-images.githubusercontent.com/20513115/34454445-bfacc0fa-eda6-11e7-9c46-f33fdde6b068.png)

另外@Ahrwing 你的上传控件提上日程了么？
以上。

**Comment by sxjeru** [comment]
很早就想到了，拖到现在真是不好意思。。

**Comment by Ahrwing** [comment]
![Uploading 
![qq 20180203014027](https://user-images.githubusercontent.com/5197567/35747174-4a530eb0-0884-11e8-97bb-66ef2f104a38.png)
20180203014027.png…]()


√

**Comment by sxjeru** [comment]
这儿也改一下吧，桌面太乱了ww
![image](https://user-images.githubusercontent.com/20513115/36009476-31f9bf78-0d87-11e8-823a-0d18f3068e23.png)
