### ISSUE TITLE
右上提醒指示灯需要二次点击熄灭

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#458]
Position: ![image](https://user-images.githubusercontent.com/20513115/34460699-dec273c2-ee50-11e7-873e-1a7d8764206e.png)
点击后进入提醒页，指示灯不熄灭。
在提醒页刷新或再次点击指示灯，指示灯熄灭。
望修复。

`重复操作≈浪费生命`

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/35656850-78c38ef6-0734-11e8-9a24-8c6e920b85cc.png)
修复失败。

**Comment by Ahrwing** [comment]
实测有效… （查看完消息后点另外的页面首次进入不会再次闪烁）
但是进入提醒页面立刻让所有页面都停止闪烁…就没办法了..

**Comment by sxjeru** [comment]
我在通知里点开一个帖子，点开的页面还是在闪烁。
