### ISSUE TITLE
编辑器粘贴内容后图片链接改变

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#461]
See title and images. 
![image](https://user-images.githubusercontent.com/20513115/34611983-d10a951e-f262-11e7-81df-ed96f8114434.png)
![image](https://user-images.githubusercontent.com/20513115/34612013-e012b1c2-f262-11e7-989f-daa03797cfb9.png)
改变后的链接指向404。

**Comment by Ahrwing** [comment]
已解决~
