### ISSUE TITLE
mod文件支持添加标签

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#463]
自我感觉在下载文件边上加备注，会使下载区臃肿，降低界面美观。用标签来代替备注是不错的方法。
外观可以类似于GitHub的label。
目前我能想到标签的作用就是标示文件的稳定性（alpha, beta, release），与多版本标识。
分别对应curse的：
![image](https://user-images.githubusercontent.com/20513115/35044353-09899162-fbcb-11e7-9bf6-c385a0ccd80e.png)
与：
![image](https://user-images.githubusercontent.com/20513115/35044368-1914bc92-fbcb-11e7-831d-f8bc34de9ca4.png)

归属 #412

**Comment by sxjeru** [comment]
附加文件功能，主要针对于模块化mod，如EIO。
![image](https://user-images.githubusercontent.com/20513115/38765103-e6c0a3f2-3fed-11e8-934c-c5f0531c8499.png)
![image](https://user-images.githubusercontent.com/20513115/38765107-f370607e-3fed-11e8-8564-d6be119f20db.png)

从MCF中能看出，该功能约有1%的人使用，因此优先级降低。

**Comment by sxjeru** [comment]
相关进展。
![image](https://user-images.githubusercontent.com/20513115/88478282-91a93780-cf79-11ea-9dcb-7ce5c2d10308.png)

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/88478454-02048880-cf7b-11ea-8035-40fbe3fd9d5b.png)
排版改进后~

**Comment by sxjeru** [comment]
需要批量修改功能。
