### ISSUE TITLE
mod下载出错

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#464]
看到短评有人在报告问题，搬了过来。
目前不知道出错范围，可以确认的范围为此页。
http://www.mcmod.cn/class/167.html
1.6.2-1.9.4的文件均无法下载，显示错误：
![image](https://user-images.githubusercontent.com/20513115/35046057-d8d19866-fbd0-11e7-86b1-77d4ad196dec.png)

**Comment by sxjeru** [comment]
我想，删掉这些再重新上传一次应该就行了。

**Comment by Ahrwing** [comment]
看起来像是上传失败，因为下载数都是0……

**Comment by Ahrwing** [comment]
已经把失效的文件标记删除了~ 再上传一遍就好了w

**Comment by sxjeru** [comment]
已上传——但重复上传了一个1.12的。
去删一下吧。

新上传文件可用。

**Comment by Ahrwing** [comment]
√

**Comment by sxjeru** [comment]
这儿还有一个失效文件，`gregtech-5.09.32pre1.jar`
http://www.mcmod.cn/class/327.html

**Comment by sxjeru** [comment]
可能是那一时段添加的mod有问题，不知道能不能追溯到所有出问题的文件。

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/35190417-0d8639ea-fe9c-11e7-87e3-806c8633f008.png)

**Comment by Ahrwing** [comment]
已处理.. 
另外尝试搜索下载量为0的文件~ 有将近100条..  随机抽查几条发现均能正常下载~ 
再发现再处理好了 (

**Comment by sxjeru** [comment]
好吧。另外添加了，能下载。

2018-01-21 11:59 GMT+08:00 RebirthIsHope <notifications@github.com>:

**Comment by Ahrwing** [comment]
已解决
