### ISSUE TITLE
相关链接不显示

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#465]
编辑页中可见一个相关链接。
![image](https://user-images.githubusercontent.com/20513115/35191276-bfebec78-feb1-11e7-8181-948f18926fb7.png)

但mod资料页没有显示。
![image](https://user-images.githubusercontent.com/20513115/35191278-cfc5a95e-feb1-11e7-8a7b-051686630e7b.png)

mod地址：http://www.mcmod.cn/class/991.html
未处于待审核状态。
以上。

**Comment by Ahrwing** [comment]
已修复~ 问(di)题(ji)不(cuo)大(wu) _(:з」∠)_
