### ISSUE TITLE
短评字数限制形同无物

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#469]
即便超出短评限制的120字节，仍可提交短评。
![image](https://user-images.githubusercontent.com/20513115/35723531-945d443e-0835-11e8-8d56-acb1c6695a75.png)

**Comment by sxjeru** [comment]
另经测试，短评最大字数为65532字。

**Comment by 3TUSK** [comment]
> 剩下四个字是不是某种元数据一般的存在.c

**Comment by Ahrwing** [comment]
![default](https://user-images.githubusercontent.com/5197567/35739881-0e77254a-086e-11e8-8f3d-61f5e352818c.png)
