### ISSUE TITLE
新版mod文件上传功能问题追踪

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#470]
相关 #454 

除了mc版本与mod选择，其余选项在已有条件下建议忽略。
![image](https://user-images.githubusercontent.com/20513115/35762684-22dd7968-08d6-11e8-9cf4-1a57402d7610.png)

**Comment by sxjeru** [comment]
原上传功能已重新启用，该issue优先度降低。

**Comment by sxjeru** [comment]
原上传功能废弃。

**Comment by sxjeru** [comment]
上传后文件大小显示错误。
![image](https://user-images.githubusercontent.com/20513115/36011137-5d255aa0-0d90-11e8-888c-fa577e06d9f0.png)

**Comment by Ahrwing** [comment]
已解决~

**Comment by sxjeru** [comment]
@Ahrwing 顶部的功能不能实现吗？

**Comment by sxjeru** [comment]
重申顶部问题。

**Comment by Ahrwing** [comment]
已解决~
