### ISSUE TITLE
mod文件数量过多的解决方案

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#472]
目前，由于一些mod处在活跃状态，或版本悠久，已经使mod文件页过于臃肿。
下面是两个方案。两个方案互不干扰，建议全部实现。
___
1. 相同游戏版本的mod文件数过多，请添加“展开更多”功能，类似模组关系处。
![image](https://user-images.githubusercontent.com/20513115/35774429-1d53e656-09aa-11e8-9c9a-3f86ed94a683.png)

2. 同一mod支持的游戏版本过多，请添加版本分类功能，类似curseforge。
![image](https://user-images.githubusercontent.com/20513115/35774441-99913598-09aa-11e8-9411-20fadb205e1f.png)

**Comment by Ahrwing** [comment]
分类支持已添加~

**Comment by Ahrwing** [comment]
方案2 已实现
