### ISSUE TITLE
关于首页『最受欢迎』与『评比排行』版块

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#473]
“最受欢迎”，字面意思理解即为一个不能轻易变动的榜单。而目前看来，推测是随机在一定好评范围内抽取六个mod作展示。甚至每次刷新都会变动。
我建议，固定“最受欢迎”中mod，以高到低排列，并可选做出一个列表页。

“评比排行”也是同样的问题。

另外，票数过少的结果需要过滤。

**Comment by Ahrwing** [comment]
这么做是为了提高冷门MOD的曝光率 如果固定榜单 其他MOD很难超越人气最高的MOD ~工业暮色拔刀剑~
目前大于10票才会显示

**Comment by sxjeru** [comment]
这样么……但这种操作已经使我对这两个版块的重视度降到最低了。
~虽然对别的版块也不太重视。~

罢了，也没什么，个人主观影响实际判断。

`重生辛苦了` :octocat:

**Comment by Ahrwing** [comment]
宽度微调 核心没变

**Comment by sxjeru** [comment]
收到。
互联网档案馆里的mod快照，v2能切换页面，v3就不行了，所以问了问。
