### ISSUE TITLE
允许空内容提交 并更改提交条件

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#474]
![image](https://user-images.githubusercontent.com/20513115/35954297-e58baaa2-0cc3-11e8-8f05-0f4638f784f1.png)
推测重生的意思是为了避免他人作无效（水）编辑，但强制添加内容提交还是较为不妥。
建议将“强制”改为“提醒”。
具体可见编辑群聊天。
___
另据群内聊天得知，有编辑员不做任何更改就提交来刷编辑数。
因此建议在提交前侦测下编辑页是否有改动，如无改动则不允许提交。

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/52542853-fbae3b00-2dde-11e9-869a-595d31e9a1a4.png)

**Comment by Ahrwing** [comment]
检测编辑页改动的功能在即将上线的编辑页v4更新里追加了
