### ISSUE TITLE
后台管理 域名前缀问题

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#476]
目前后台的用户与mod链接前缀均为`admin`，而正常应为`www`。
soon.

**Comment by Meow-J** [comment]
指的是后台里面全都用的相对路径

**Comment by Ahrwing** [comment]
检查了一遍链接 不过可能还有遗漏 记得及时反馈 0 0

**Comment by sxjeru** [comment]
还有这儿。
![image](https://user-images.githubusercontent.com/20513115/36664523-ee480176-1b1f-11e8-8410-fb31bbdb5b16.png)

**Comment by Ahrwing** [comment]
@sxjeru 好了
