### ISSUE TITLE
关于Mod物品列表信息编辑的提议

### ISSUE THREAD

**Issue by TROU2004** [Ahrwing/mcmod#479]
在查看部分mod信息的途中, 有许多已经过时的方块/物品, 这些方块物品已经在该Mod的更新中消失, 却无法被删除, 其中遗留着过时的信息, 可能会误导玩家, 所以提出该建议, 希望是添加物品删除的功能, 或者添加版本管理的功能.

**Comment by sxjeru** [comment]
关于物品删除：http://bbs.mcmod.cn/forum.php?mod=viewthread&tid=341&extra=
对于过时object的处理方式为分类“已移除”。
