### ISSUE TITLE
添加手机版网页或App

### ISSUE THREAD

**Issue by Widecss** [Ahrwing/mcmod#48]
希望mcmod百科有手机版网页吧，这样手机编辑起来舒服点，或者mcmodAPP?

**Comment by Ahrwing** [comment]
手机版在做了，争取国庆之前出WIP

**Comment by Ahrwing** [comment]
大部分页面现已支持各种尺寸的设备浏览。

**Comment by Ahrwing** [comment]
内容页现已按响应式布局开发 其他页面也在开发中 手机已可以正常浏览
