### ISSUE TITLE
顶部菜单栏宽度随页宽缩放

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#480]
这儿有些问题。

http://www.mcmod.cn/
![image](https://user-images.githubusercontent.com/20513115/36464062-98d1cc9c-1708-11e8-9741-f3868e9e2641.png)

http://www.mcmod.cn/history/
![image](https://user-images.githubusercontent.com/20513115/36464065-9c9a2cfc-1708-11e8-8c01-b31c6debda36.png)

**Comment by Ahrwing** [comment]
v4页顶部菜单已与主框架对齐，v3页会陆续更新至v4。
