### ISSUE TITLE
短评编辑框全屏异常

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#481]
测试了一下百科近乎所有的短评框，发现物品详情与mod详情页的短评编辑框无法全屏。
![image](https://user-images.githubusercontent.com/20513115/36598443-2588b9f4-18e7-11e8-8e3f-cd1ec3c936ac.png)

物品页尺寸为860x540，mod页尺寸为300x540。

**Comment by Ahrwing** [comment]
已取消短评全屏 (短评限制字数很少 没有全屏的必要.. 
资料编辑框全屏未发现此问题~
`~梨木村还行~`
