### ISSUE TITLE
网页经常Service Unavailable

### ISSUE THREAD

**Issue by ChromeHu** [Ahrwing/mcmod#482]
用户脚本和adblock关闭也依旧无效。hosts复原也没用。

浏览器：chrome  64.0.3282.167（正式版本） （32 位）
操作系统：windows 10 64位

**Comment by sxjeru** [comment]
我这儿无法重现问题，尝试更换网络环境。

**Comment by Ahrwing** [comment]
可能和地区或网络环境有关..
