### ISSUE TITLE
MOD文件上传选填协议

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#483]
这几天出的问题，针对新添加文件的mod。我试了LGPL3与作者授权协议，都不显示。
下图所选的协议是LGPL3。
![image](https://user-images.githubusercontent.com/20513115/36839741-e0c1a524-1d7d-11e8-8974-bba1597a2a35.png)
正常示例：
![image](https://user-images.githubusercontent.com/20513115/36839942-6318b42c-1d7e-11e8-92d0-7e6f8b12a424.png)

涉及mod：
http://www.mcmod.cn/class/1041.html
http://www.mcmod.cn/class/1043.html

**Comment by sxjeru** [comment]
相关 #470 顶部。

**Comment by Ahrwing** [comment]
唔.. 需要做的：
[ - ] 添加时判断是否已存在协议
[ - ] 追加修改协议

**Comment by sxjeru** [comment]
emmm，上传时写的协议显示在哪里？

**Comment by Ahrwing** [comment]
尝试修复了选择的授权被判定为空的问题

**Comment by Ahrwing** [comment]
已解决，协议与MOD文件的编辑现已分开，且可以自定义协议文本，具体可在后台看到~
