### ISSUE TITLE
希望能支持移动的网络访问

### ISSUE THREAD

**Issue by ChromeHu** [Ahrwing/mcmod#485]
我曾经发过一个说网页经常无法访问的问题，看了很久，觉得应该是运营商的问题，希望能支持一下移动。
裸连ping的话4次，3次ping不到。我还要用vpn才能稳定，但是速度慢

**Comment by sxjeru** [comment]
我也移动，没有这种情况。
ping不到是因为服务器禁ping。

**Comment by Ahrwing** [comment]
现在还会出现吗？

**Comment by ChromeHu** [comment]
@Ahrwing 抱歉现在看到回复，貌似邮件没有提示。
呃，我先说一下我的情况。
> 问题是在家的时候提出的，现在已经到学校了。
>
> 学校与家中是一样的宽带提供商，是移动的。
>
> 在学校，上次登录也是依旧的时常的链接不上。
>
> 因此应该是移动的问题。

现在的话学校这边网络，基本可以直接进入，ping的话也没有丢包。

**Comment by Ahrwing** [comment]
w
