### ISSUE TITLE
物品支持查询以它为GUI的合成表

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#488]
由 ![image](https://user-images.githubusercontent.com/20513115/37207978-82b1ecce-23da-11e8-80a6-b7da76f802cf.png) 与NEI/JEI点击合成进度条能查询关于合成机器的所有合成表得到的灵感。
百科既然有这项数据，那就多发挥一项效用吧。
在“GUI对应资料ID”指定的物品里，添加一个查询链接，或者在合成表页往下再加一页。

话说这个数据本身是干什么用的？

**Comment by sxjeru** [comment]
大概只有这一个作用吧。
![image](https://user-images.githubusercontent.com/20513115/37208250-a06a4800-23db-11e8-947c-0cd4bc59900d.png)

**Comment by Ahrwing** [comment]
已完成
