### ISSUE TITLE
GUI背景图片无法更改

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#489]
RT，已尝试多次。
![image](https://user-images.githubusercontent.com/20513115/37248499-cf36b05e-250e-11e8-926c-bd7eda5e053c.png)
![image](https://user-images.githubusercontent.com/20513115/37248500-d6225878-250e-11e8-8641-0e422641910f.png)

**Comment by sxjeru** [comment]
不打算将这个合成表恢复原样，请速修复。

**Comment by Ahrwing** [comment]
已确认是缓存问题 
待办：将GUI背景存储位置移动至 `i.mcmod.cn`

**Comment by Ahrwing** [comment]
存储位置暂时没改 已调整为不缓存 问题解决
