### ISSUE TITLE
合成表功能扩展

### ISSUE THREAD

**Issue by lycc193** [Ahrwing/mcmod#490]
- 在GT6“氢气”的条目下，添加了一个使用“**GT6电解机**“电解”**原版水**“生成”**氢气**“和”**氧气**“的合成表的同时，能不能在”原版水“和“氧气”的条目下自动生成一份。
- 提供一个查询**所有使用某个机器**（例如GT6电解机）的合成表的功能。
- ”原版水“的条目下，在合成表部分添加三级菜单：格雷科技6 - 用途 - GT6电解机，且**默认被折叠**（非本mod的GUI），“氢气”/“氧气”的合成表部分添加：格雷科技6 - 合成 - GT6电解机，且默认展示（本mod的GUI）。

**Comment by lycc193** [comment]
第一条是为了保持一致性并减少工作量（比如某个合成表，需要6个输入，12个输出，就需要把同一个合成写18份），以及联动mod的合成。
第二条是#488的扩展
第三条是因为 有可能存在多个合成表 比如不同配方产生同一个产物

**Comment by Ahrwing** [comment]
1.已存在 http://www.mcmod.cn/item/tab/941.html
2.重复 #488

**Comment by Ahrwing** [comment]
exm... 3还没弄呢

**Comment by Ahrwing** [comment]
仔细看了一下第三条 已经部分实现 只是没有分类
在物品页里做分类会和合成表列表页的功能重复（合成表列表在合成多的时候打算做筛选和搜索） 故第三条不打算在物品页面实现…
