### ISSUE TITLE
百科网页白屏无响应

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#493]
该问题在我的电脑上时常出现，已成日常。
问题表现为打开网页白屏（或加载到一半），等几秒后弹出无响应弹窗（有时不会弹）。此时多数页面操作无效，包括刷新、F12等。关闭问题网页后重进无效。
目前我的解决办法是在chrome的任务管理器中关闭白屏页进程，再进行刷新操作。
想问问其他人能否重现问题。

某些时候，等待一段时间，网页恢复正常。

关于我为何发这个issue，是因为我只在百科站如此频繁的遇到问题。

浏览器版本：Chrome 65.0.3325.181 x64

**Comment by Ahrwing** [comment]
CDN已升级 ~交了保护费~ 应该不会出现这样的情况了

**Comment by sxjeru** [comment]
今晚百科受到攻击了吗？我这儿频繁报错520，并且白屏无响应。
![image](https://user-images.githubusercontent.com/20513115/39663714-d7e6bb3c-50aa-11e8-9bd9-6183848ed1b1.png)

**Comment by Ahrwing** [comment]
检查了一下 目前没有发现异常 0 0

**Comment by sxjeru** [comment]
目前稳定了不少，大概是移动宽带的时段问题……打扰了。
