### ISSUE TITLE
网页加载问题

### ISSUE THREAD

**Issue by Huiaei** [Ahrwing/mcmod#494]
用chrome的开发者工具发现
>http://www.img4.9minecraft.net/img/Real-Train-Mod.jpg

无法加载，且使网页加载耗时多了20秒左右。

直接访问
>http://www.img4.9minecraft.net

发现我无法加载。应该需要科学上网。希望能使用国内的

>江西  移动 
>chrome  浏览器

**Comment by sxjeru** [comment]
9minecraft.net 是国外的一个MC综合性资讯网站，有百科用户用也不奇怪。
对于这种情况，建议用ABP ban掉该网站内容。

**Comment by ChromeHu** [comment]
@sxjeru OK，我已经加入了过滤规则，虽然不知道有没有写对，不过看样子是可以的。 加载的话快了10秒。现在finish是10.62s。之前的话是22.86s

**Comment by 3TUSK** [comment]
建议百科直接禁止使用 9minecraft。理由很简单，知名的二搬站。

**Comment by liach** [comment]
https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md

**Comment by Ahrwing** [comment]
已将 9minecraft.net 加入到禁止上传的图床列表。
封面已不再允许使用外链，而需要经过裁剪后重新生成，理论上不会有新的增加途径了，不过现有的需要手动处理一下。
且现在(v4)已可以异步加载，不再会因为一张图片影响到其他交互式功能。
