### ISSUE TITLE
建议增加挖矿页面以得到额外收入

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#495]
门罗币：https://getmonero.org/
据说是开着网页就能挖矿的的虚拟币种。
示例：
![image](https://user-images.githubusercontent.com/20513115/37910926-491d4f02-3141-11e8-88a4-b7d395f8f9de.png)

当然会有多少人愿意献出自己的cpu来增加收入就说不定了……

**Comment by sxjeru** [comment]
测试页：https://v2ray.com/chapter_00/cpu.html

**Comment by Ahrwing** [comment]
神不知鬼不觉的加上这个会出事的吧 0 0.. 如果让用户自己选择是否勾选“愿意贡献CPU资源”挖矿效率又太低... 况且平台还要抽成 _(:з」∠)_

**Comment by sxjeru** [comment]
是让用户确认后才开始挖矿的……
收入少也没办法吧，当做外快而已。（我做作业时会挂机的w）

**Comment by 3TUSK** [comment]
> 总感觉这个 issue 打死也不会通过，估计迟早要加入“无打算修复”全家桶
