### ISSUE TITLE
资料批量导入

### ISSUE THREAD

**Issue by ChromeHu** [Ahrwing/mcmod#499]
希望能直接上传json文件，加群的话感觉太麻烦。
>_其实是我找了半天群号没找到【笑哭】_

**Comment by Ahrwing** [comment]
发到这里吧~ http://bbs.mcmod.cn/thread-1281-1-1.html

**Comment by Ahrwing** [comment]
顺便改了一下这里的链接~
![default](https://user-images.githubusercontent.com/5197567/38764972-e50775b0-3feb-11e8-89a3-e4638c97bcbc.png)
