### ISSUE TITLE
“MOD对应MC版本”显示字数不足

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#501]
原内容为`1.9.4/1.10.2/1.11.x/1.12.x`
只显示`1.9.4/1.10.2/1.11.x/`
![image](https://user-images.githubusercontent.com/20513115/39632676-59971410-4fe8-11e8-8daa-e7602a24d7a1.png)

建议修复后删除这几个文件（末尾有斜杠的），我找时间重新上传。
或者#478

**Comment by Ahrwing** [comment]
MOD对应MC版本最大字节数由20改为255
`顺便改了上面那三个文件的版本`
