### ISSUE TITLE
mod添加资料的时候希望能一并提交合成表。

### ISSUE THREAD

**Issue by ChromeHu** [Ahrwing/mcmod#503]
RT，强烈希望，每次编辑完后还要等审核，然后添加合成表。
_一键添加物品有一键添加合成表的话多好。。。_

**Comment by Ahrwing** [comment]
在物品创建之前是不存在的 所以没有分配内部ID
如果要解决的话需要另外做一些工作
因为现在有json批量导入物品 因此这个功能的需求量应该不大

**Comment by ChromeHu** [comment]
json批量导入能导入合成表的吗？

**Comment by sxjeru** [comment]
不能。重生的意思是，json批量导入物品后，就可以不用等物品审核直接添加合成表了。

**Comment by ChromeHu** [comment]
emmm，的确，不过。我提交的一个.json不知道为什么少了物品 _虽然总共就两个物品_

**Comment by Ahrwing** [comment]
@ChromeHu 可能是因为名字重复, 现已改成按注册名与元数据(1.13以上仅注册名)来匹配重复物品了, 因此不会再跳过重名的物品.
