### ISSUE TITLE
imgchr.com图床可以正常使用吗？

### ISSUE THREAD

**Issue by ChromeHu** [Ahrwing/mcmod#504]
RT，不知道国内是否能正常访问到。给一个图片测试。![testpic](https://imgchr.com/i/Cy0w8I)

i.imgur.com的图床不知道为什么注册不了。

有推荐的免费的图床也行，不要太麻烦的。

**Comment by sxjeru** [comment]
imgur 国内无法访问，建议使用 [sm.ms](https://sm.ms/)
无需注册，未墙。

**Comment by ChromeHu** [comment]
ok,got.

**Comment by Ahrwing** [comment]
用直传就好啦

**Comment by sxjeru** [comment]
1.2MB，个人觉得基本够用了。
