### ISSUE TITLE
markdown编辑问题

### ISSUE THREAD

**Issue by ChromeHu** [Ahrwing/mcmod#505]
编辑器的工具栏图标都没显示，全是方块。

![0.bmp](https://i.loli.net/2018/05/16/5afc313db9790.bmp)

**Comment by sxjeru** [comment]
加载中，需要等待。

**Comment by 3TUSK** [comment]
> 可能需要一个类似“Work as Intended”的标签。

**Comment by 3TUSK** [comment]
> 暂时先加上“无打算修复”了。

**Comment by Ahrwing** [comment]
markdown编辑器已停止维护, 请使用富文本编辑器~
