### ISSUE TITLE
编辑字数统计错误

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#506]
想知道编辑字数统计是计算哪里的数据的？
注：“编辑字数统计”指[贡献榜](https://www.mcmod.cn/rank/)中的字数统计。

![image](https://user-images.githubusercontent.com/20513115/40570391-f45d8d5a-60bc-11e8-96bf-7f84246abae2.png)
![image](https://user-images.githubusercontent.com/20513115/40570396-03a850a6-60bd-11e8-9e7f-05486ad7469d.png)
![image](https://user-images.githubusercontent.com/20513115/40570398-0b3c363e-60bd-11e8-8e22-042987ab6a86.png)

图三还包括一次日志编辑。

**Comment by sxjeru** [comment]
目前我的猜测是，其只按增加字数计算，如果编辑后字数比原来少，仅算基本编辑字数（10字节）。

**Comment by Ahrwing** [comment]
![default](https://user-images.githubusercontent.com/5197567/40570538-772ccfe2-60be-11e8-80ae-662fbe25532b.png)

**Comment by sxjeru** [comment]
可能算图二中绿色字数会更公平些。

**Comment by Ahrwing** [comment]
如果有办法得到真实改动的字节数 文本对比问题早就解决了
