### ISSUE TITLE
mod介绍禁止使用第三方宣传图

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#508]
mc百科的影响力在众多贡献者的努力下逐渐扩大，站长也在改变网站的外在形象，给图片打水印即证明。

然而有个别“懵懂”的用户，大概是认为他站的宣传图较官方而言更为美观，就直接搬至百科mod资料中，甚至堂而皇之摆至封面位。

（例子见 [https://www.mcmod.cn/class/816.html](https://www.mcmod.cn/class/816.html)）

从我个人角度，认为这类图片应该禁止出现在mc百科的任何角落，起码是在mod介绍页（class）与各分资料页（item）中。

例子中可推测，用他站宣传图原因是官网的图片不太合适，此种情况如果我来编辑，我选择留空封面，或在游戏中截取一张有关该mod的图片，但绝不用他站图片。
尤其是打着水印的。

（该议项待论，本人观点不作最终决定）
注：“他站”“第三方”主要指 [StopModReposts](https://github.com/VictiniX888/Illegal-Mod-Sites) 中罗列的网站。

**Comment by limuness** [comment]
2/5000  
Reasonable.Avoid as copyright disputes as possible.

**Comment by Ahrwing** [comment]
封面已清理~

**Comment by sxjeru** [comment]
本意即如此。
[https://bbs.mcmod.cn/thread-646-1-1.html](https://bbs.mcmod.cn/thread-646-1-1.html)
![image](https://user-images.githubusercontent.com/20513115/78802132-074fbe80-79f0-11ea-8633-088be661c983.png)
![image](https://user-images.githubusercontent.com/20513115/78802095-fb63fc80-79ef-11ea-915e-9d5e664f0e35.png)

**Comment by Ahrwing** [comment]
v4编辑系统已包含正文/相关链接中的图片/链接黑名单
