### ISSUE TITLE
搜索结果为空的汇总表

### ISSUE THREAD

**Issue by Huiaei** [Ahrwing/mcmod#509]
用户搜索的内容在百科中没有结果的是否可以列出一张表。

主要是想到自己去一个一个去找有趣或者感兴趣的mod来添加，可能很久才找的到一个。假如提供这张表，可以拿来参考一下子，或者帮助完善。

**Comment by Ahrwing** [comment]
自这个issue发布至今, 无结果的搜索关键词前100条为:

关键词 | 人数 |  
-- | -- | --
矿石菌种 | 36
sevtech | 31
史诗攻城 | 29
原罪神 | 27
矿物菌种 | 25
矿石菌种mod | 25
eu2 3 | 24
immer | 24
飞机木偶刀 5 λ1 | 23
crimson | 22
运算工艺λ1 | 21
收割者附魔 | 20
拔刀剑七宗罪 | 20
万物皆刃 | 20
龙蛋镐 | 20
更大型的拔刀剑附属 | 19
世界生成 | 19
1 7 2rpg插件 | 18
万物皆可为兵刃 | 18
领地op λ1 | 17
极限反应堆λ2 | 17
me输导矩阵 | 17
探险者背包 | 17
tink | 17
欧氏菊 | 16
高塔5 λ1 | 16
明兽刃 阳牙冰狼 | 16
米特沙石λ2 | 16
mob λ2 | 16
植物生长加速mod | 16
流体管道λ1 | 16
镐子λ1 | 16
暴怒精魄 | 16
国产mod，原高级水力发电机 | 16
MITE 爱德曼合金 | 16
无垠装备 | 15
虚拟人生 | 15
eu2 5 3 | 15
治愈之斧 | 15
倪克斯 | 15
CyclopsCore | 15
神奇宝贝mod | 15
更好的附魔台 | 15
MITE 鸡 | 15
折越物品管道 | 15
EJML | 15
炽热的血 | 14
领地λ2 λ1 | 14
魔法科高中的劣等生 | 14
蕴魔秘银矿 | 14
巫毒娃娃 | 14
建筑3λ2 5 | 14
阿尔2线缆 | 14
小木斧λ1 | 14
红色染料λ2 | 14
高级采矿机ic２ | 14
英文id λ1 | 14
原罪 | 14
七原罪 | 14
万能重力工具 | 14
方块更新λ2 | 13
e7 20bb 209f | 13
林业木炭堆 | 13
在发条组装台 | 13
3锭方块λ2 5 | 13
高塔5处理λ2 | 13
电容储能库 | 13
ic2电炉2 | 13
op领地λ1 | 13
科学の超电磁炮 | 13
极寒之檀冰 | 13
hbm整合包 | 13
p455w0 | 13
南瓜灯 | 13
矿石λ1 λ2 5 | 13
异界剑魂 | 13
eu2 | 13
工匠武器λ2 | 13
无限手套 | 13
镐子λ1 λ2 | 13
project λ1 λ2 5 | 13
更好的地下城 | 13
镭射器变成 | 13
MITE 虚弱药水 | 13
进击巨人1 | 13
ro 500 | 12
无尽 长弓 | 12
木炭λ1 5 | 12
锂燃料棒 | 12
护甲λ1 5 λ2 | 12
inventory nei λ1 | 12
变成建筑4 λ1 | 12
nbt enough items λ1 | 12
loot of food λ1 | 12
this is 4 λ1 | 12
witchery λ1 | 12
领地插件λ2 | 12
论集成动力 | 12
1.10背包λ2 | 12
建造3 λ1 | 12

**Comment by ChromeHu** [comment]
好杂啊，各种类型，搜索有联想或者重定向的功能吗？
矿石菌种的话，mcbbs的内容貌似都指向了百科里的[Orespawn](https://www.mcmod.cn/class/524.html)模组。

**Comment by HGLMiddle** [comment]
显然……大部分的搜索目标实际上都是已有mod和物品。
也许搜索失败的原因是其中包含了不应存在的空格
而且不少人在这里搜索插件？

**Comment by 3TUSK** [comment]
还有搜索整合的。（比如那个 `sevtech`）。

**Comment by ChromeHu** [comment]
我觉得很有必要重定向这些搜索。大部分都有的mod以及物品。
神奇宝贝--〉精灵宝可梦。
还有打错字导致的搜索问题
极寒之檀冰--〉热力膨胀的 极寒之凛冰  。檀--凛

编辑加一个名称的多义？比如宝可梦，可以叫神奇宝贝一样。

**Comment by 3TUSK** [comment]
“口袋妖怪”、“神奇宝贝”作为”精灵宝可梦“的 alias 可以有。但是那个 `极寒之檀冰`... 这当真不需要更高端的字词分析？
