### ISSUE TITLE
论坛帖子链接复制功能在Chrome中失效

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#510]
相关 #389 

包括帖子顶部的“复制链接”，与每一层楼的楼号。

![image](https://user-images.githubusercontent.com/20513115/42198102-b67b6a06-7eb8-11e8-9420-d5acc8d50b1b.png)

![image](https://user-images.githubusercontent.com/20513115/42198112-c019a10e-7eb8-11e8-8a01-3bb09cd9d3d2.png)

**Comment by Ahrwing** [comment]
这个实际上是直接输出.. 不会操作你的剪贴板

**Comment by sxjeru** [comment]
那可以类似于这样吗……
![image](https://user-images.githubusercontent.com/20513115/42354254-2a20269a-80f8-11e8-8199-6d4bd13235d3.png)
