### ISSUE TITLE
“物品命令”点击即复制

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#511]
以便在游戏中输入指令。

点击范围建议包括整个黑框。
请只复制指令，无需“物品命令：”。

![image](https://user-images.githubusercontent.com/20513115/42298832-892edd7a-803a-11e8-9911-0ea60ccdb6b8.png)

**Comment by 3TUSK** [comment]
有一个问题，万一命名空间变了怎么办？

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/121762915-569cfc00-cb6b-11eb-9db6-c481afe86309.png)
----
![image](https://user-images.githubusercontent.com/20513115/121762854-23f30380-cb6b-11eb-8583-e592f9e596a8.png)
