### ISSUE TITLE
有关合成表“常用物品”的改进

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#512]
近期推出了的常用物品确实增加了添加合成表的效率，但是也确实有瑕疵。
举例：
![qq 20180713195904](https://user-images.githubusercontent.com/30253037/42690597-67ba27e6-86d7-11e8-968a-c5df9a7cc2be.png)
我这里在之前使用了一个物品，叫做”原理图 (1x1)“，之后使用了其他物品，于是原理图被挤出去了，变成如此：
![qq 20180713195932](https://user-images.githubusercontent.com/30253037/42690657-b664eb9c-86d7-11e8-98cd-e16a2b6eb2ec.png)
但之后再想使用，就出现了一个问题：**为了再如何搜索并且使用”原理图“这个物品，也无法使其重新归回视野**。

常用物品不是之前常用，是现在常用。所以我认为：**应该每使用一次物品，就将其提升到常用物品栏的最前。如果有多个物品，按使用次序排列**。

**Comment by Ahrwing** [comment]
已解决~
