### ISSUE TITLE
后台使用全选时会同时选择隐藏一些物品

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#513]
RT
这是之前我没有点击右上”全选“的情况，左边的“不显示一些资料“没有被选中
![qq 20180714112346](https://user-images.githubusercontent.com/30253037/42720394-cfdf974e-8758-11e8-9ab2-ec2855aff3d1.png)
但是等我点击”全选“后，左边的”不显示一些资料“也被选中了。
![qq 20180714112334](https://user-images.githubusercontent.com/30253037/42720403-0b2fba54-8759-11e8-945c-41ebc2112de3.png)
导致下一次我再次搜索的时候没有显示如上描述的资料

**Comment by Ahrwing** [comment]
已解决 √
