### ISSUE TITLE
个人中心活跃度失能

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#514]
某些人的活跃度统计失效，失效日期各不相同。

例如重生的（最后编辑20时前）：
![image](https://user-images.githubusercontent.com/20513115/42740205-807d0dc4-88d6-11e8-91a9-e9242876391d.png)

我的（最后编辑1天前）：
![image](https://user-images.githubusercontent.com/20513115/42740207-89f15180-88d6-11e8-8a17-08b7965284a7.png)

**Comment by Ahrwing** [comment]
已修复~
