### ISSUE TITLE
移动端页面切换回电脑版页面切换不回来

### ISSUE THREAD

**Issue by NellPoi** [Ahrwing/mcmod#520]
移动版页面底部有电脑版链接 切换成电脑版页面却没有切换回手机版页面的链接
手机版mc百科mod内没有教程这一栏

**Comment by sxjeru** [comment]
可以在地址栏输入 `m.mcmod.cn` 进入移动端页面。
移动端仍在开发，功能尚未完善。

**Comment by Ahrwing** [comment]
移动版与电脑版在v4.0更新中已合并，现已支持各种尺寸的设备。
