### ISSUE TITLE
后台GUI管理的样式中物品链接跳转错误

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#522]
RT
![image](https://user-images.githubusercontent.com/30253037/43200510-5d2fc7f2-9048-11e8-8f33-ee7fee752839.png)
![image](https://user-images.githubusercontent.com/30253037/43200517-6438f2c6-9048-11e8-83c8-43e1e87bfc0f.png)

**Comment by Ahrwing** [comment]
已修复此问题。
