### ISSUE TITLE
后台资料列表的按钮不当

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#525]
后台的资料列表有个“全选”按钮，但是这个按钮需要在选择了一个物品之后才能显示。其次一个，如果把物品全选之后就会有一个反选按钮，然而功能说着是“反选”实际却是 全不选 。
我认为按钮应该默认的显示 全选 反选 全不选 功能
后附加：同时应显示分类内物品数量

**Comment by Ahrwing** [comment]
v4.0后台已改进此问题：全选按钮随时显示、显示分类内物品数量。
