### ISSUE TITLE
显示合成表时，无介绍全引用的物品 会在左侧附加上 表示无内容的红色字体

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#529]
RT
![](http://bbs.mcmod.cn/data/attachment/album/201808/14/200353a8y3r3c75bc3ctpo.png)
![](http://bbs.mcmod.cn/data/attachment/album/201808/14/200353otx0zgfs0httggtc.png)
一个合成表使用了一个叫”编程电路:==2“的物品，且物品仅有引用无其他介绍，此时有引用，应作为含内容的资料来处理。

**Comment by Ahrwing** [comment]
已解决~
