### ISSUE TITLE
主页里面没有物品列表的入口

### ISSUE THREAD

**Issue by meowtec** [Ahrwing/mcmod#530]
比如潘马斯的[主页](https://www.mcmod.cn/class/218.html)
我想看潘马斯有哪些物品，在主页里面看不到，也找不到去[物品页](https://www.mcmod.cn/item/list/218-1.html)的链接

**Comment by YoungGT** [comment]
不是很明白你在说啥。
主页中部有“MOD资料”， 然后那里就有物品页面........进去就可以看到了

**Comment by meowtec** [comment]
对，我找的就是这个物品列表入口，能不能放显眼点的地方 @YoungGT
