### ISSUE TITLE
合成表设置概率应考虑几率0%

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#531]
RT。先不说概率为0%到底什么意思，首先我在添加或者编辑合成表时写上0%的概率，就会自己变成100%；然后就是概率为0%的含义，实际上就是说物品不会在过程中消耗，如果显示合成表的时候，应该显示为[物品] * 不消耗 的样式。

**Comment by HGLMiddle** [comment]
留0或许就是“未设置”的意思 也许可以用-1？

**Comment by YoungGT** [comment]
@HGLMiddle 总之就是希望有个几率特指不消耗而已

**Comment by Ahrwing** [comment]
已添加 不过还没有测试... 可以尝试一下~
