### ISSUE TITLE
上传文件支持自定义协议

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#533]
近期上传文件，被一名作者提及，即提此议。

部分作者会利用一些常见开源协议的演绎版本作为自己mod 的协议，此时如将其作为原版协议，会存在风险，并降低百科准确性。

另外有作者会自己起草协议，此时的备选仅剩“作者亲自授权”一项，未避免该项被滥用，希望添加自定义协议功能。

功能要求，即选择后出现文本框，用于复制粘贴作者的协议内容，并能在下载页用下拉等方式预览（浏览）协议全文。最好可以高亮显示以起提醒作用，避免他人随意分发，侵犯作者权益。

---
@Ahrwing 
另，请在该功能开发完成前隐藏（或删除）[料理工艺](https://www.mcmod.cn/class/1291.html)下所有文件。谢过。

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/60862668-d4a24b00-a250-11e9-8ae8-d895f7beca97.png)
v4.0后台已支持自定义协议。

**Comment by sxjeru** [comment]
添加协议全文内容？
另外，建议常用协议能自动添加官方文档链接（在下载页）。如果同意，文档地址我会整理。

**Comment by sxjeru** [comment]
添加协议全文内容？
另外，建议常用协议能自动添加官方文档链接（在下载页）。如果同意，文档地址我会整理。

**Comment by Ahrwing** [comment]
只用填写协议名称就好了~ 具体协议内容交给用户自行查询

**Comment by sxjeru** [comment]
烦请再次阅题。
>部分作者会利用一些常见开源协议的演绎版本作为自己mod 的协议，此时如将其作为原版协议，会存在风险，并降低百科准确性。

So，添加协议全文，应该是有必要的。

**Comment by Ahrwing** [comment]
这种情况可以写在授权证明/说明楼中
![图片](https://user-images.githubusercontent.com/5197567/60867906-6e242980-a25e-11e9-974c-bf2d1a9534d0.png)

**Comment by sxjeru** [comment]
OK…

`或许有keke的作者不认同，到时再说吧。`
