### ISSUE TITLE
写新教程后应直接添加我写教程时访问的Mod

### ISSUE THREAD

**Issue by Enteerman** [Ahrwing/mcmod#534]
![1](https://user-images.githubusercontent.com/43851243/46475390-fbda7080-c817-11e8-85d0-ca4ef301e105.png)
![2](https://user-images.githubusercontent.com/43851243/46475384-f8df8000-c817-11e8-8c1e-dcf5c5528949.png)
假想状态

**Comment by iamxm** [comment]
额有无联系方式

**Comment by Ahrwing** [comment]
现在有了~
