### ISSUE TITLE
多方块结构资料 添加合成表查询按钮

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#535]
Source: https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=1720&pid=13861&page=1&extra=

因部分GUI绑定了多方块结构，而该类型资料无合成表按钮，因此不便于查询该GUI合成。
遂提此议，如果能根据绑定状态选择部分资料添加按钮，则更友好。

**Comment by Ahrwing** [comment]
已添加~
