### ISSUE TITLE
后台添加刷新按钮

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#537]
RT。后台进行合并或者综合等操作之后，虽然更改完成了，但是不能及时浏览到更改后效果等。所以希望添加刷新按钮。

**Comment by sxjeru** [comment]
新版后台已添加。
![image](https://user-images.githubusercontent.com/20513115/60785521-df43de00-a185-11e9-9e91-1a91ec91f1e0.png)
