### ISSUE TITLE
使用回车快速提交编辑时有使用障碍

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#539]
RT。百科目前资料编辑和合成表编辑都可以使用回车键进行快速提交，但是使用时发现有问题。
首先是在页面内按回车不会触发编辑提交，其次是有时确认提交出现之后按回车，确认栏会消失但是并不会提交编辑，这种情况需要二次提交。
bug比较小，但是编辑的时候很费时间。

**Comment by sxjeru** [comment]
关于第二个问题，重生给过解释。#387

**Comment by Ahrwing** [comment]
此问题已修复~
