### ISSUE TITLE
普通人

### ISSUE THREAD

**Issue by shuirong123** [Ahrwing/mcmod#542]
普通用户也可以合并资料，太不爽

**Comment by limuness** [comment]
我能說我沒有看太懂嘛

**Comment by shuirong123** [comment]
意思是，普通用户也就可以像合并DMP的资料一样合并。

**Comment by Ahrwing** [comment]
实现合并是要分多个步骤来执行的，并且在前面的操作未完成之前，无法进行下一步的操作。
允许普通用户合并/综合会很难审核，因此只允许编辑员使用合并/综合功能。
