### ISSUE TITLE
添加合成表时物品浮动块的弹出会干扰左右键快速添加合成表的使用

### ISSUE THREAD

**Issue by YoungGT** [Ahrwing/mcmod#543]
RT
![tim 20190126092302](https://user-images.githubusercontent.com/30253037/51780829-e8e40700-214c-11e9-9302-6be6f13c0bcf.png)
大多数右侧物品的浮动框会使页面出现左右滚动条，而如果此时使用左右键快速添加合成表，就会使得页面滑动而阻碍合成表的快速添加。

**Comment by Ahrwing** [comment]
编辑页面已重做
