### ISSUE TITLE
无法在bug区添加模组bug

### ISSUE THREAD

**Issue by liach** [Ahrwing/mcmod#545]
比如railcraft有几个炸服的bug现在我想添加，但是不能添加

**Comment by sxjeru** [comment]
目前只能由重生添加，可将bug 内容发给重生。

**Comment by liach** [comment]
希望至少百科编辑员(比如我)可以给管理的mod加bug

**Comment by limuness** [comment]
以后也许可以允许那样做，但目前没有时间做那样的功能，只能先通过重生来进行添加。

在 2019年2月5日 週二 11:15，liach <notifications@github.com> 寫道：

**Comment by Ahrwing** [comment]
可在论坛漏洞版块反馈：https://bbs.mcmod.cn/forum.php?mod=forumdisplay&fid=38
