### ISSUE TITLE
服务器版块筛选

### ISSUE THREAD

**Issue by Liumingxun** [Ahrwing/mcmod#546]
服务器筛选建议添加mod名称筛选与反选，依据：有些mod已经通关，不想玩，需要反选；想体验新mod，需要自主筛选，
排列顺序增加人数正序与倒序，依据：部分玩家认定服务器在线人数以判断，人多与少体验不同

**Comment by Ahrwing** [comment]
反选的提议很不错，近日就会开发上线！
关于排序，原来是有人数排序的，但这样做会给人数较少的服务器带来不公平的对待，并且无法识别假人插件。
不应该让在线人数成为判断一个服务器好坏的默认标准，以后是打算完全去掉排序，只留默认随机排序，并添加更多筛选的选项。

**Comment by Ahrwing** [comment]
更新已上线：
- 新增按标题与介绍搜索筛选；
- 新增反选功能，可以筛选不包含指定MOD或内容的服务器；
- 新增MOD服筛选功能，可以只看MOD服；
- 部分效率优化与样式微调；
- 移除所有排序选项，统一为随机排序

![default](https://user-images.githubusercontent.com/5197567/52594622-eab90480-2e86-11e9-9952-ebb283b01881.png)
