### ISSUE TITLE
建议对每日短评数量加入限制

### ISSUE THREAD

**Issue by HGLMiddle** [Ahrwing/mcmod#547]
建议加入限制：单个账号的每天短评数量不能超过(a+总编辑次数/k)次。
a和k是参数。

**Comment by YoungGT** [comment]
建议可以通过相应的字节数、编辑数、评论数来调控一下短评数量。不然会导致多个用户稀释评论等情况。

**Comment by sxjeru** [comment]
如果要对用户采取限制，那也应该给游客定一个标准，避免恶意*。

**Comment by limuness** [comment]
well.......We should make reasonable arrangements according to various needs.For example, modder need more limit to answer any issue with player.

**Comment by Ahrwing** [comment]
主站等级与成就系统已上线，未来管理员可以设置Mod的短评与编辑门槛。
