### ISSUE TITLE
MCID长度限制不正确

### ISSUE THREAD

**Issue by timetraveler314** [Ahrwing/mcmod#551]
MC购买时id长度限制是到最高15位，而百科不允许15位

**Comment by Ahrwing** [comment]
已解决!
考虑到会有离线登录的常用ID 最大长度限制已扩增至18位

**Comment by 3TUSK** [comment]
> 话说这到底是什么地方要输入 Minecraft 的 ID

**Comment by timetraveler314** [comment]
> > 话说这到底是什么地方要输入 Minecraft 的 ID

在注册的时候

**Comment by 3TUSK** [comment]
> > > 话说这到底是什么地方要输入 Minecraft 的 ID

> > 在注册的时候

> 特此加入“用户”标签。
