### ISSUE TITLE
关于MOD搜索时的问题

### ISSUE THREAD

**Issue by TPCW-DRW-TP211** [Ahrwing/mcmod#556]
因为我们做怀旧服想装MOD但是只能搜名字搜不了版本，建议加一个用版本搜MOD的功能，这样就可以看哪个版本可以用那个MOD了

**Comment by Ahrwing** [comment]
可以在首页的“版本检索”中查找~
![图片](https://user-images.githubusercontent.com/5197567/57811180-31770d00-779c-11e9-977f-77eb97e1dd9b.png)

**Comment by TPCW-DRW-TP211** [comment]
谢谢，哎。。。最近BMCLAPI在中国快倒了。。。官方源我们这里得VPN啊希望能获得支持
