### ISSUE TITLE
模组重复

### ISSUE THREAD

**Issue by UncleMax** [Ahrwing/mcmod#557]
MrCrayfish's Vehicle：
https://www.mcmod.cn/class/1705.html

MrCrayfish's Vehicle Mod：
https://www.mcmod.cn/class/1680.html

以上2个模组重复了，在国外的curseforge中只能搜到MrCrayfish's Vehicle Mod
https://minecraft.curseforge.com/search?search=+MrCrayfish%27s+Vehicle

**Comment by UncleMax** [comment]
该模组初期版本只能使用命令召唤车辆，后期作者完善了模组使得可以制作出来。实质上该模组是同一个作者同一个模组。

**Comment by Ahrwing** [comment]
已合并
