### ISSUE TITLE
建议加入

### ISSUE THREAD

**Issue by EtaCarina** [Ahrwing/mcmod#558]

**Comment by EtaCarina** [comment]
建议加入教程收藏功能，这样可以省去一些麻烦

**Comment by Ahrwing** [comment]
已实现，现已支持收藏模组、整合包、资料、教程、作者：
![图片](https://user-images.githubusercontent.com/5197567/131321835-a7ef30ac-bc0f-43a2-9e59-674efe39cce7.png)
