### ISSUE TITLE
能开发一个手机端的app吗，手机上的网页mcmod太不友好了

### ISSUE THREAD

**Issue by Freeze-Dolphin** [Ahrwing/mcmod#559]
在iphone上用网页看mcmod，文字排版不友好

**Comment by 3TUSK** [comment]
与 #48 和 #492 重复。

**Comment by Ahrwing** [comment]
现在的模组/资料/教程页均同时支持各种尺寸的屏幕, 具体有哪些地方不友好呢, 可以举出几个例子来看看怎么改~

**Comment by Ahrwing** [comment]
> **[2019-6-26] 因性能问题, MC百科左下角的百科娘暂时隐藏...**
> 近日有人反馈访问百科出现浏览器卡死的情况, 经检查是由于百科娘Live2D资源消耗过大导致的, 通常浏览百科会打开许多页面, 而每个页面都会加载一只百科娘, 这样会使CPU占用非常高, 因此在研究出解决办法之前暂时隐藏! (功能都在同一个页面中进行的情况下会保留, 例如CBCreator命令生成器~)
