### ISSUE TITLE
转义符问题仍然存在

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#56]
![qq 20150822224521](https://cloud.githubusercontent.com/assets/5229241/9424812/b9c5d3d2-492c-11e5-817f-ee1ca0fd9a7f.png)

**Comment by Ahrwing** [comment]
修了一下~ 应该没问题了 （待测试

**Comment by Meow-J** [comment]
@Ahrwing 
![image](https://cloud.githubusercontent.com/assets/5229241/9427051/b55a0f30-4999-11e5-98a3-81a6cf236215.png)
![image](https://cloud.githubusercontent.com/assets/5229241/9427054/c33c50c2-4999-11e5-94fe-f65b2abfc966.png)

**Comment by Ahrwing** [comment]
@Meow-J 编辑一遍才行啊 原来的是不会变的

**Comment by Meow-J** [comment]
@Ahrwing 就是点了编辑才这样的

**Comment by Ahrwing** [comment]
修好了~ 原来不是后端的问题... 机智的我 /w\
