### ISSUE TITLE
希望增加一种新的资料类型

### ISSUE THREAD

**Issue by FunnyGoldApple** [Ahrwing/mcmod#561]
能不能添加流体的资料类型？专门集中介绍流体及其性质

**Comment by sxjeru** [comment]
相关 #434

**Comment by Ahrwing** [comment]
可联系编辑员添加，一般用户不能随意添加新的资料类型。

**Comment by 3TUSK** [comment]
> 有没有“拒绝修复”这个标签？

**Comment by Ahrwing** [comment]
自定义资料类型与模组是绑定的，除了基本提供的10种类型以外，在一个模组中添加的资料类型不会在其他资料中出现。
如果允许一般用户随意添加类型，会因编辑风格不同而乱套，因此需要编辑员或管理员来进行类型统一标准。

**Comment by sxjeru** [comment]
@FunnyGoldApple 
根据[MC Wiki](https://minecraft-zh.gamepedia.com/%E6%B6%B2%E4%BD%93)，流体应当被认为是一种特殊的方块。
且物品/方块下设分类，不存在流体无法区分的情况。
另流体除了“Flow”这一基本特性，多无其他可以过多陈述的地方，以我之见，这issue 实用性不够。
