### ISSUE TITLE
审核通过的提醒

### ISSUE THREAD

**Issue by FunnyGoldApple** [Ahrwing/mcmod#562]
能不能在教程创建/页面编辑时审核通过后，给用户发送站内短消息或者是电子邮件呢？每天盯着审核状态刷新看看自己的编辑有没有通过真的很累 :P

**Comment by Ahrwing** [comment]
目前只有审核退回或是通过时带有附言时才会提醒… 如果通过时会提醒编辑大量资料时会被刷屏的…
