### ISSUE TITLE
建议在命令方块指令生成器添加的功能

### ISSUE THREAD

**Issue by Time-ADF** [Ahrwing/mcmod#567]
希望在
命令方块指令生成器中的
铠甲架中的
装备锁定添加副手功能

**Comment by Ahrwing** [comment]
印象中副手是不能设置锁定的

**Comment by Time-ADF** [comment]
禁止放置/替换/拿取都不可以吗?




------------------ Original ------------------

**Comment by Ahrwing** [comment]
是的
