### ISSUE TITLE
手机端夸克浏览器使用主站时短评功能异常

### ISSUE THREAD

**Issue by FunnyGoldApple** [Ahrwing/mcmod#568]
android端夸克浏览器登录百科，只能看到别人的短评或者表态，而写短评的编辑器区域莫名其妙消失了。资料与模组编辑不受影响。

发不了图所以只能文字描述了

**Comment by Ahrwing** [comment]
浏览器不支持或者在载入中 刷新再等一下看看
如果还不行只能换浏览器了

**Comment by Ahrwing** [comment]
现在还会有这个问题吗？
