### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by ksfhjsf** [Ahrwing/mcmod#570]
第一次发的帖子不通过的话
再发一次修改过的帖子 会给通过吗
谢谢

**Comment by Ahrwing** [comment]
你在说论坛还是找服玩..
如果是论坛 发帖是不需要审核的
如果是找服玩 符合上架服务器时底部显示的规定就可以通过

**Comment by ksfhjsf** [comment]
找服玩

**Comment by ksfhjsf** [comment]
一般需要几个工作日

**Comment by Ahrwing** [comment]
目前一共有3名审核员，审核久了可以到群(926791492)里@一下。

**Comment by ksfhjsf** [comment]
嗯知道了
