### ISSUE TITLE
关于MC百科服务器审核问题

### ISSUE THREAD

**Issue by Mirror-XD** [Ahrwing/mcmod#572]
第一次我去添加，然后因为我填的公益服，然后审核人员去检查了，确实有氪金项目，然后呢，我也腐竹商议，然后决定本服务器是无偿捐款的公益服，所以我第二次申请，结果呢，这都没来检查直接给我未通过了，原因还是有氪金项目，这属实很无语。

**Comment by Ahrwing** [comment]
因为查到虚假宣传 信用太低 所以不能选公益服 提交时选商业服就好
