### ISSUE TITLE
关于审核速度

### ISSUE THREAD

**Issue by Fantlaxy** [Ahrwing/mcmod#573]
请问一下在百科一般添加模组和编辑模组的审核时间分别是多少？感觉有时候速度很快，有时候很慢，想知道一般时间是多久，好有个底。

**Comment by Ahrwing** [comment]
目前常驻的全局审核员只有站长一个人, 提交后通常1周内会有结果 (可能更早).
有管理员负责的模组审核会相对快一些.

**Comment by Ahrwing** [comment]
模组管理员申请现已开放，管理员拥有指定MOD区域内的审核权限以及可以指定模组区内编辑规则/风格。
具体请看：https://bbs.mcmod.cn/thread-2483-1-1.html
