### ISSUE TITLE
资料显示异常

### ISSUE THREAD

**Issue by FunnyGoldApple** [Ahrwing/mcmod#575]
模组苹果科技的“筛子”条目在多方块结构类型资料页面中是隐藏的，但是条目本身可以正常访问。https://www.mcmod.cn/item/192937.html （筛子条目）
https://www.mcmod.cn/item/list/1969-7.html （苹果科技的多方块结构类型资料，显示为空）

**Comment by Ahrwing** [comment]
已解决
