### ISSUE TITLE
mod介绍中的缺失项

### ISSUE THREAD

**Issue by mimo233** [Ahrwing/mcmod#579]
在为自己服务器选择mod的时候，很少有mod显示用于### **服务端**还是**客户端**，查了很久资料都没有找到，希望添加这个介绍标签，让大家去编辑，希望能够重视采纳我的意见，增加这个功能会方便更多人！

**Comment by SettingDust** [comment]
#581

**Comment by Ahrwing** [comment]
已加入开发日程 #581
