### ISSUE TITLE
应该有一个专门的矿物字典页面

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#58]
就像NEI那样/w\

**Comment by Meow-J** [comment]
目前后台有矿物词典的分类，但是还未完成

**Comment by Ahrwing** [comment]
可以这样添加物品到矿物词典里，然后合成表就可以像NEI一样自动切换显示了，但是矿物词典目前只能在后台添加~
![default](https://cloud.githubusercontent.com/assets/5197567/9433094/f4402ca4-4a5f-11e5-930a-e90f4b87631d.png)
