### ISSUE TITLE
SSP/SMP 修改

### ISSUE THREAD

**Issue by SettingDust** [Ahrwing/mcmod#581]
希望可以对 SSP/SMP 进行清晰解释，这样的缩写很难实现目的，现在除了介绍内容并没有渠道来得知一个mod是否可以只装到服务端/客户端。
SSP/SMP 大部分也是乱填的，填写者多半不解其意。
Forge，MC 发展至今这样来自10年前的简单的描述已经无法满足需求了，可以考虑将类型改为中文且添加类型，并添加激活（hover）提示
仅客户端（仅在客户端安装即可）
仅服务端（仅在服务端安装即可）
可客户端（SSP）（可能缺失部分功能）
可服务端（SMP）（可能缺失部分功能）

**Comment by 3TUSK** [comment]
SSP == Survival Single Player 单人生存模式
SMP == Survival Multi-Player 多人生存模式

与之相对应的，是不知还有没有人用的 CSP（Creative Single Player）和 CMP（Creative Multi-Player）。

所以 SSP/SMP 不能用来区别一个 Mod 是需要装哪边的。建议直接淘汰这两个称呼。

**Comment by SettingDust** [comment]
这些我是知道的，本意也是表达它们不适用了，后两项的括号是指直接替换现有的为此文本，没表述清楚不好意思

**Comment by Ahrwing** [comment]
两种方案，前者复杂具体，后者简洁明了，你们看看用哪种比较好
![0](https://user-images.githubusercontent.com/5197567/72243243-5de27200-3626-11ea-9563-a914c8440b25.png)
![1](https://user-images.githubusercontent.com/5197567/72243246-5fac3580-3626-11ea-90b0-8426ef24451a.png)

**Comment by SettingDust** [comment]
现有的 SMP/SSP 不做改动？

**Comment by Ahrwing** [comment]
现有的 SMP/SSP 和这个其实是表达的两个意思啦
由于用到的不多，所以打算移除了…

**Comment by SettingDust** [comment]
> 两种方案，前者复杂具体，后者简洁明了，你们看看用哪种比较好
> ![0](https://user-images.githubusercontent.com/5197567/72243243-5de27200-3626-11ea-9563-a914c8440b25.png)
> ![1](https://user-images.githubusercontent.com/5197567/72243246-5fac3580-3626-11ea-90b0-8426ef24451a.png)

第一种改为 可选 必要 易于理解

**Comment by 3TUSK** [comment]
前者。有些Mod是“可以只装在客户端上，但同时装在服务器上能启用更多功能”（如果没记错的话，Inventory Tweaks、Waila/TOP 这样的）。
暂时想不到“可以只装服务器上，但同时装客户端上能启用更多功能”的Mod。

**Comment by SettingDust** [comment]
> 前者。有些Mod是“可以只装在客户端上，但同时装在服务器上能启用更多功能”（如果没记错的话，Inventory Tweaks、Waila/TOP 这样的）。
> 暂时想不到“可以只装服务器上，但同时装客户端上能启用更多功能”的Mod。

不少的，比如各种优化类的MOD可以通过装在客户端获得gui而不是仅仅指令

**Comment by Ahrwing** [comment]
![0](https://user-images.githubusercontent.com/5197567/72345747-65ca1100-370f-11ea-82d7-5326b753c8f8.png)

这样如何？也方便理解~

**Comment by SettingDust** [comment]
后两者 语义上没办法同时存在 其实是可以的 主->可 
最极端情况可能后三者共存 太长了吧 这样还是像上方那样分成客户端，服务端吧

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/72364483-94f17a00-3731-11ea-87a3-061f23fc4053.png)

**Comment by 3TUSK** [comment]
“不必”改成“无效”？

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/72394676-0ea95800-3772-11ea-88f6-5da2265dcee8.png)

最终版 (?)

**Comment by SettingDust** [comment]
GOGOGO！

> ![图片](https://user-images.githubusercontent.com/5197567/72394783-56c87a80-3772-11ea-8d44-e6129782037c.png)
> 
> 最终版 (?)

**Comment by SettingDust** [comment]
敲敲？

**Comment by Ahrwing** [comment]
此修改已在编辑功能v4.0中上线，整体编辑功能还在内测中，特性修完了才能完全开放，具体可以看[开发日志](//www.mcmod.cn/log/)。
