### ISSUE TITLE
希望加入矿辞列表功能

### ISSUE THREAD

**Issue by 351768593** [Ahrwing/mcmod#582]
在mod开发过程中非常需要一个统一查询矿辞id的功能.
比如, 目前百科在单个资料, 比如[苍穹木-暮色森林](https://www.mcmod.cn/item/3825.html)的资料里, 可以查到这项物品/方块的矿物词典为`logWood`.
希望增加一个大列表, 可以把目前已经约定的、用得频率非常高的矿辞列出来.
毕竟虽然4z大佬的[教程](https://fmltutor.ustc-zzzz.net/2.5.2-%E6%B3%A8%E5%86%8C%E5%92%8C%E4%BD%BF%E7%94%A8%E7%9F%BF%E7%89%A9%E5%AD%97%E5%85%B8.html)里有提到矿辞规则, 还是不太放心写上的有没有错误.

**Comment by Ahrwing** [comment]
>矿辞列表已上线 
https://www.mcmod.cn/oredict.html
