### ISSUE TITLE
搜索界面对资料文本中的html标签的渲染有错误

### ISSUE THREAD

**Issue by 351768593** [Ahrwing/mcmod#583]
问题复现地址: [链接](https://www.mcmod.cn/s?key=%E7%9F%BF%E7%89%A9%E8%AF%8D%E5%85%B81&site=&filter=3) (发现此问题时, 是在此搜索的第3项结果项)
相关资料地址: [链接](https://www.mcmod.cn/post/756.html)

![问题截图](https://user-images.githubusercontent.com/13001378/72228914-b5142280-35e5-11ea-9125-6c3e69692c8f.png)

在搜索页面的结果项内对资料内容的预览, 资料文本中的html标签 (问题中是`<input>`和`<output>`标签) 被错误地直接渲染成了html内容.

**Comment by Ahrwing** [comment]
已修复
