### ISSUE TITLE
服务器没法SRV解析？

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [Ahrwing/mcmod#584]
我的服务器更换成了SRV解析
输入地址后提示：连接游戏服务器超时，请确认此MC服务器处于启动状态，或稍后再试。

**Comment by Ahrwing** [comment]
地址发一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Aira"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 中午1:31
收件人:&nbsp;"Ahrwing/mcmod"<mcmod@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Ahrwing/mcmod] 服务器没法SRV解析？ (#584)




我的服务器更换成了SRV解析
 输入地址后提示：连接游戏服务器超时，请确认此MC服务器处于启动状态，或稍后再试。

**Comment by Aira-Sakuranomiya** [comment]
> 地址发一下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Aira"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月7日(星期五) 中午1:31 收件人:&nbsp;"Ahrwing/mcmod"<mcmod@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Ahrwing/mcmod] 服务器没法SRV解析？ (#584) 我的服务器更换成了SRV解析 输入地址后提示：连接游戏服务器超时，请确认此MC服务器处于启动状态，或稍后再试。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

mc.calibur.tv

**Comment by Ahrwing** [comment]
……看样子是爬虫IP被加到MC服务器的黑名单里了 也有可能是防火墙的原因 具体问运营商吧
SRV解析没问题 本地测试也可以获取到
注意一下黑名单里有没有百度云的IP 爬虫会每隔10分钟~30分钟获取一次数据
