### ISSUE TITLE
找服玩显示服务器状态不正确

### ISSUE THREAD

**Issue by gundami** [Ahrwing/mcmod#585]
服务器在线时经常显示超高延时或者不在线
![image](https://user-images.githubusercontent.com/41334632/74515959-85d93400-4f4a-11ea-99ca-0f3c01b03269.png)
![image](https://user-images.githubusercontent.com/41334632/74515995-912c5f80-4f4a-11ea-88ec-172a4cb375c7.png)

**Comment by Ahrwing** [comment]
爬虫服务器在上海，对海外服务器连接容易超时（5000ms以上）
也有可能是防火墙原因
