### ISSUE TITLE
希望搜索功能能改进下

### ISSUE THREAD

**Issue by lqg5522** [Ahrwing/mcmod#586]
很多MOD的英文名称都是对的，就是因为没空格就搜不到，这很不友好啊

**Comment by Ahrwing** [comment]
目前只有中文分词，其它语言的分词可以等新的“追加关键词”功能出来以后用来解决此问题～


------------------ 原始邮件 ------------------
发件人: lqg5522 <notifications@github.com&gt;
发送时间: 2020年2月21日 12:55
收件人: Ahrwing/mcmod <mcmod@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Ahrwing/mcmod] 希望搜索功能能改进下 (#586)




很多MOD的英文名称都是对的，就是因为没空格就搜不到，这很不友好啊
