### ISSUE TITLE
网页主站无法退出登录，请检查前端/数据库BUG

### ISSUE THREAD

**Issue by CangNiMa** [Ahrwing/mcmod#587]
如题，点击退出登录无反应。2020-02-24；WIN10；360极速

**Comment by Ahrwing** [comment]
现在暂时只能在主站v4页面上退出登录（头像为圆形的页面）

------------------ 原始邮件 ------------------
发件人: CangNiMa <notifications@github.com&gt;
发送时间: 2020年2月25日 03:19
收件人: Ahrwing/mcmod <mcmod@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Ahrwing/mcmod] 网页主站无法退出登录，请检查前端/数据库BUG (#587)




如题，点击退出登录无反应。2020-02-24；WIN10；360极速
