### ISSUE TITLE
能否对管理员申请标准作出略微改动？

### ISSUE THREAD

**Issue by QianquanQAQ** [Ahrwing/mcmod#589]
现有的管理员申请规则：
1.30天以上的编辑员
2.50%(含)以上的编辑次数与45%(含)以上的编辑字数，高于400(含)次的总次数，高于20000(含)字节的总字数；
3.必须属实

但某些前置或是物品较少的mod，无论如何也无法完全达到这个要求。而其中的很多mod，空有原作者的许可，而mod的版本离最新版本十万八千里。仅靠现有的自身编辑员恐怕难以对这些mod下载进行及时更新。

能否对这些mod的管理员申请条件略微放宽，以便于mod下载，或是对这些mod中编辑量最大的编辑员也给予mod文件管理权限？

**Comment by Ahrwing** [comment]
单个模组的情况下，编辑员确实需要成为管理员后才可以上传模组文件。
不过有一个专门为更新文件而设立的小组，可以对任意MOD上传模组文件。
加入此小组需要尽可能的及时更新模组文件，以及处理授权帖中新的模组授权。
如果感兴趣的话欢迎加入~

**Comment by Ahrwing** [comment]
此外，目前还在策划“作者入驻”功能，为作者提供一个独立的公告区，用来发自己的话和网盘下载等地址，作者可以自己来更新文件，但对于国外MOD，暂时还只能靠搬运了…

**Comment by WuzgXY-GitHub** [comment]
> 
> 
> 单个模组的情况下，编辑员确实需要成为管理员后才可以上传模组文件。
> 不过有一个专门为更新文件而设立的小组，可以对任意MOD上传模组文件。
> 加入此小组需要尽可能的及时更新模组文件，以及处理授权帖中新的模组授权。
> 如果感兴趣的话欢迎加入~

:-D

**Comment by Ahrwing** [comment]
开发者现已可以自行上传模组文件
