### ISSUE TITLE
' 字符不能正常显示

### ISSUE THREAD

**Issue by Kianakiferi** [Ahrwing/mcmod#592]
![Screenshot_20200319-013324](https://user-images.githubusercontent.com/42063176/76989770-d72d7680-6981-11ea-87ba-a4a9e8eaceaa.jpg)
例如：
Kiana's 在服务器资料界面会显示为 Kiana#&039;s
，在编辑服务器资料界面显示正常，请开发dada修复一下~

**Comment by sxjeru** [comment]
确认已解决。
![image](https://user-images.githubusercontent.com/20513115/121824330-085c3a00-ccde-11eb-898d-d346535ade89.png)
