### ISSUE TITLE
服务器被恶意差评导致热度降低

### ISSUE THREAD

**Issue by Dreeam-qwq** [Ahrwing/mcmod#593]
rt，某些人恶意差评我的服务器，内容就好几段“垃圾服务器”

还有看到开小号刷5星评分的，属实无语

考虑搞个几级以上才能发评分的功能？qwq

**Comment by Ahrwing** [comment]
服务器宣传页地址发一下，纯灌水的评价会处理的。目前主站等级/新个人中心还在开发中，暂时没有合适可用的评价门槛，现在的要求是注册一定时间且改过昵称的用户才可以评价。
