### ISSUE TITLE
功能建议：对关联MOD进行自动版本分类

### ISSUE THREAD

**Issue by Gan-N** [Ahrwing/mcmod#597]
在每个MOD界面下一般都有一个MOD关系，但是他们混在一起，可能有些MOD是1.6，有些是1.7.10或者1.12.2
1.根据这些关联MOD已知的版本号进行自动排序分类
         ① 1.12.2
                 MOD列表...................
         ②1.7.10
                MOD列表...................
2.具备多个版本的MOD，在每个版本号页面中都显示
3.采用高版本在上，低版本在下的排序
5.可以让版本号放置在竖；前置、附属、联动放置在行。
5.1.以版本号为主，切换前置、附属、联动页面时不变动版本号页面
5.2.切换版本号页面时，优先显示前置
![image](https://user-images.githubusercontent.com/35490649/78146418-b6c2e900-7464-11ea-97da-97e26bdc44bf.png)

**Comment by WuzgXY-GitHub** [comment]
啊，如果联动模组只有一个版本是可行的，但是你怎么知道一个有很多版本的模组每个版本都联动呢？

**Comment by Gan-N** [comment]
> 啊，如果联动模组只有一个版本是可行的，但是你怎么知道一个有很多版本的模组每个版本都联动呢？

无敌的免责声明XD（划掉）

1. 联动mod采用编辑员手动设置关联版本制度，不设置就不在具体版本号页面显示
2. 对版本列新增一页面，表示所有联动列表
![image](https://user-images.githubusercontent.com/35490649/79629854-4663d980-817f-11ea-9088-7f8771cde8a6.png)


啊啊，又想到有些mod在1.7.10需要前置，1.12.2又不需要前置了。像格雷这个低版本是附属，后来另外做了个独立还好。我放弃思考了，忘了我吧

**Comment by Ahrwing** [comment]
现在已经有模组关系分组功能了~
![0](https://user-images.githubusercontent.com/5197567/79632279-f1c95a00-8190-11ea-8501-ba9f5766d20e.png)
