### ISSUE TITLE
关于模组下载方式的按钮位置不明显导致的问题

### ISSUE THREAD

**Issue by ShiningCube** [Ahrwing/mcmod#598]
许多好玩有趣的模组，百科都很贴心的准备了下载链接，但我们常会看见有玩家在评论区提问下载方式
这很有可能是由于下载按钮不够醒目，很容易被忽略。
建议适度放大下载按钮，把下载链接用有色字体等标出。
大胆的创意：放在页面左下角，还能增添一点互动（想法来自百科的命令方块指令生成器）
![A](https://s1.ax1x.com/2020/04/03/GaKTVH.png)
![B](https://s1.ax1x.com/2020/04/03/GaKHIA.png)

**Comment by WuzgXY-GitHub** [comment]
这，我看还是对百科不够熟悉的缘故，建议请新手去看看论坛FAQ

**Comment by Ahrwing** [comment]
已在模组页添加下载按钮与下载选项卡，两个位置足够醒目了  `吧…？`
