### ISSUE TITLE
用户功能严重异常

### ISSUE THREAD

**Issue by MineCommanderCN** [Ahrwing/mcmod#599]
- 无法登录账号，试图登陆账号会显示已登录一个名为“xuyang”的账号；
- 点进“xuyang”的个人主页又会显示登录了名为“Ethaxiuman”的账号；
- 但是所有操作均显示为访客模式。

**Comment by sxjeru** [comment]
不同页面似乎固定了登录状态。
我尝试用无痕模式浏览[论坛最新回复](https://bbs.mcmod.cn/forum.php?mod=guide&view=new)，未经登录就显示了“sxjsxj” 。
后台则是“Ethaxiuman” 。

**Comment by sxjeru** [comment]
确认恢复正常。
