### ISSUE TITLE
增加判断用户编辑质量的评分

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#60]
可以在审核的时候或者是由其他用户(有点风险，不过可以学SO)进行评分，之后审核编辑质量低的用户的编辑时候会有标记提醒让审核员注意一下/w\

**Comment by Meow-J** [comment]
相关 #21

**Comment by Ahrwing** [comment]
以前想过这个问题啊... 因为编辑员不需要审核评分…… 所以就没弄了……

**Comment by Ahrwing** [comment]
不过可以不显示编辑员的编辑质量评级…… 恩。。 就这样试试好了。。

**Comment by Ahrwing** [comment]
已增加评分功能，可在编辑历史记录中找到。
