### ISSUE TITLE
为什么我不能退出登录啊

### ISSUE THREAD

**Issue by Cha0syuan** [Ahrwing/mcmod#606]
登录的时候选择了自己的小号，结果发现自己不能退出登录然后换成自己的大号了

**Comment by Ahrwing** [comment]
到顶部导航栏内头像是圆形的页面可以退出登录
例如任意模组/资料/教程页面

------------------ 原始邮件 ------------------
发件人: Cha0syuan <notifications@github.com&gt;
发送时间: 2020年5月16日 20:38
收件人: Ahrwing/mcmod <mcmod@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Ahrwing/mcmod] 为什么我不能退出登录啊 (#606)





 
登录的时候选择了自己的小号，结果发现自己不能退出登录然后换成自己的大号了
