### ISSUE TITLE
找服玩板块添加删除服务器功能

### ISSUE THREAD

**Issue by LiamSho** [Ahrwing/mcmod#607]
服务器不可能一直运营下去，如果关服了找服玩上没有删除服务器的选项就很尴尬了。。。一直有玩家找到我的b站来问我怎么回事。。。

**Comment by Ahrwing** [comment]
可以通过任意渠道附上所有者证明发送给管理，便可完成删除操作~（邮箱、群内、站内私信、GitHub反馈皆可）
