### ISSUE TITLE
站外链接跳转提示框的滚动条影响美观

### ISSUE THREAD

**Issue by TheRiverElder** [Ahrwing/mcmod#609]
如图，站外链接提示框的滚动条太影响美观了。本人用的是Chrome浏览器。
出于强迫症，建议把跳转提示框中的链接文本样式设置为`word-break: break-all;`或者`overflow-wrap: anywhere;`，或使用其它方法避免图片中出现的滚动条，以增加美观性。
![包含滚动条的提示框](https://user-images.githubusercontent.com/38187271/84592880-6102b800-ae7b-11ea-9ed3-b64ad41b3daa.png)

**Comment by Ahrwing** [comment]
已解决~
