### ISSUE TITLE
站外链接我点了不要再提醒我，页面也刷新了，再点还是弹窗

### ISSUE THREAD

**Issue by tomoya92** [Ahrwing/mcmod#610]
浏览器 edge beta

**Comment by Ahrwing** [comment]
是不是禁用Cookie了

**Comment by tomoya92** [comment]
没有禁用 
![image](https://user-images.githubusercontent.com/6915570/85007268-e04eff00-b18d-11ea-8773-bd4c68ef7ef2.png)

**Comment by Ahrwing** [comment]
Microsoft Edge 42.17134.1098.0 测试正常

**Comment by tomoya92** [comment]
我这不是edge，是edge beta，chrome内核的那个版本

**Comment by Ahrwing** [comment]
Chrome/FF/Edge/IE11 均测试正常
Edge Beta 具体是哪个浏览器，有下载地址吗

**Comment by tomoya92** [comment]
我知道为啥了，不是刷新页面就行的，还要重启浏览器。。

刚不小心把浏览器关了，现在已经好了

**Comment by Ahrwing** [comment]
正常情况下刷新就可以了，应该是浏览器的问题或设置问题

**Comment by tomoya92** [comment]
https://www.microsoftedgeinsider.com/en-us/
