### ISSUE TITLE
整合包制作器

### ISSUE THREAD

**Issue by ming0209** [Ahrwing/mcmod#611]
我希望百科上有一个在线整合包制作器，可以在线下载整合包进行编辑或制作一个全新的整合包。

**Comment by HanlieChina** [comment]
CurseForge客户端可提供相关功能。

**Comment by ming0209** [comment]
好的谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 上午10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Ahrwing/mcmod] 整合包制作器 (#611)





 
CurseForge客户端可提供相关功能。
 
—
您收到此消息是因为你修改了打开/关闭状态。
直接回复此电子邮件，在 GitHub 上查看，或取消订阅。
