### ISSUE TITLE
请求你们检查“搜索物品”系统里是否包含所有minecraft原版的ID，方块，生物！！我找不到：鉴制砂岩，平滑砂岩！！！！

### ISSUE THREAD

**Issue by ghui9087** [Ahrwing/mcmod#614]
请求你们检查“搜索物品”系统里是否包含所有minecraft原版的ID，方块，生物！！！！！我找不到：鉴制砂岩，平滑砂岩！！！！
我在对[星门环方块](https://www.mcmod.cn/item/78111.html)填加合成表时无法找到这种方块！！

方块：
鉴制砂岩（minecraft:sandstone）
(#0024/1)

平滑砂岩（minecraft:sandstone）
(#0024/0)

系统只给我凿子mod，但是我需要minecrafty原版的！！

**Comment by Ahrwing** [comment]
两个都是可以搜到的，你再检查一下…?
![图片](https://user-images.githubusercontent.com/5197567/89743031-da143980-dad1-11ea-87ca-570e3af5bcb4.png)

**Comment by Ahrwing** [comment]
合成表搜索也是正常的，是不是打错字了……
![图片](https://user-images.githubusercontent.com/5197567/89743087-3d05d080-dad2-11ea-84c5-2a02e7844ab4.png)

**Comment by sxjeru** [comment]
注意是“錾制砂岩”而不是“鉴制砂岩”。

**Comment by ghui9087** [comment]
thanks

**Comment by ghui9087** [comment]
but i use english can not be find it

**Comment by ghui9087** [comment]
我用中文我能找到

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/89743602-565d4b80-dad7-11ea-988c-5f427125e857.png)

**Comment by ghui9087** [comment]
ok i get. Thank you!
