### ISSUE TITLE
服务器检索无法搜到1.16.1的Mod服

### ISSUE THREAD

**Issue by ColorfulGhost** [Ahrwing/mcmod#615]

**Comment by ColorfulGhost** [comment]
只能获取群组服列表

**Comment by Ahrwing** [comment]
可以搜到的，在列表（https://play.mcmod.cn/list/）选择1.16.1再勾上Mod服。

**Comment by ColorfulGhost** [comment]
https://play.mcmod.cn/sv20183583.html

fabric 端 勾选mod服+1.16.1， 无法用筛选搜到此服务器

**Comment by Ahrwing** [comment]
服务器信息每隔30分钟更新一次，具体更新时间可以根据历史在线人数节点推算。

**Comment by Ahrwing** [comment]
现在测试依然可以搜到
![图片](https://user-images.githubusercontent.com/5197567/95320676-62456e00-08cc-11eb-9be0-2dd83a1b6076.png)
