### ISSUE TITLE
安全检查无法结束

### ISSUE THREAD

**Issue by masakitenchi** [Ahrwing/mcmod#618]
坐标北海道。自从昨天开始访问任何页面均会被重定向至安全检查且安全检查无法完成。Chrome与edge均有此问题。

**Comment by Ahrwing** [comment]
外网IP段或CDN日本节点IP下有人访问触发了安检阈值，已对海外节点设置进行微调，这段时间你再看看还不会出现吧~

**Comment by Ahrwing** [comment]
现在还会出现吗？

**Comment by masakitenchi** [comment]
在我这里已经正常了
