### ISSUE TITLE
在不登陆的情况下可以看到所有用户的ip

### ISSUE THREAD

**Issue by IceHidden** [Ahrwing/mcmod#619]

**Comment by Ahrwing** [comment]
不会的，论坛的IP信息只有你自己和超管能看见，肯定是还在登录状态，不信你随机访问其他用户个人主页，或者换个浏览器再看。

------------------ 原始邮件 ------------------
发件人: IceHidden <notifications@github.com&gt;
发送时间: 2020年9月7日 22:14
收件人: Ahrwing/mcmod <mcmod@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Ahrwing/mcmod] 在不登陆的情况下可以看到所有用户的ip (#619)





 
我搜自己的关键信息的时候能搜到我的百科个人资料，而且在没登陆的情况下就能看到我的个人隐私包括地址和最后一次登录网站所用的ip，请问账号可以注销吗?我不想看到有人用这种方式把我人肉出来
