### ISSUE TITLE
电梯与意见反馈重叠

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#62]
![image](https://cloud.githubusercontent.com/assets/5229241/9437089/c8ca1b8a-4a86-11e5-805c-2db1bc81e595.png)
屏幕小/w\

**Comment by elctove** [comment]
可以点脚啊/w\

**Comment by Ahrwing** [comment]
已去掉签到/反馈按钮，考虑以后以更简洁的方式展现。
