### ISSUE TITLE
是否可以在mod界面加个是否开源的标志？

### ISSUE THREAD

**Issue by vzcrab** [Ahrwing/mcmod#620]
标志链接到官方的开源仓库，或者再进一步，将这个标志作为tag，可以索引到。  
这对开发者还是有点帮助的。想做mod的玩家也更方便去找

**Comment by mamaruo** [comment]
此功能已存在，请见`编辑页`-`官方信息`。

**Comment by vzcrab** [comment]
@mamaruo 不好意思，打扰了。刚又去重新看了一下，看到了。
