### ISSUE TITLE
不能查看自己短评 无故被以"地图炮"罪封一周

### ISSUE THREAD

**Issue by rikanotank1** [Ahrwing/mcmod#625]
我都不懂评论有没有发出去呢 下午一看还被禁止评论一周
而且我就记得我发的评论就一个顶,怎么就地图炮了?
贵管理真的强

**Comment by Ahrwing** [comment]
你好，发下站内昵称或ID，帮你看下

**Comment by Ahrwing** [comment]
你好，已查到封禁原因。
![图片](https://user-images.githubusercontent.com/5197567/100177223-9e7c6e80-2f0c-11eb-913c-40e5df0af93b.png)

**Comment by rikanotank1** [comment]
我说的是西班牙人,他们在官方discord鄙视中国人,不用rule规定的英语或者中文 服主根本不管discord像没有一样.....
抱歉迟回复和让您去找我用户了.
我觉得把很迷 我这也是真实反馈啊 我玩过那个服务器
