### ISSUE TITLE
审核列表 选择条件的方式过于复杂

### ISSUE THREAD

**Issue by TZ-2020** [Ahrwing/mcmod#626]
https://www.mcmod.cn/verify.html中上方是选择条件，以前的方式蛮快捷的，现在还要一个二级菜单。

但也毕竟是功能比较多才会折叠，所以我觉得可以把设计弄回以前那样，再弄个下拉菜单，放UID查找、最近一百条这些等。

**Comment by Ahrwing** [comment]
太占地方，以后还可能会加新的筛选条件与功能，不做成窗口在移动端体验也很差
