### ISSUE TITLE
Mod页面新功能建议

### ISSUE THREAD

**Issue by bao-cn** [Ahrwing/mcmod#630]
希望在Mod页面明显位置添加【是否需要同时安装在服务端和客户端才能运行】的图标，例如：JEI Mod仅需安装在客户端，就在JEI详情页中明显位置显示【客】，连锁挖矿Mod需要同时安装才能使用，则在详情页明显位置显示【服】
希望采纳此建议

**Comment by Ahrwing** [comment]
在这里有显示
![](https://ae01.alicdn.com/kf/U3326d36d2a1b4512bfc6ca98f21be6a0Z.jpg)

**Comment by mamaruo** [comment]
仅服务端的怎么办？写`客服`吗？（玩笑罢）

**Comment by bao-cn** [comment]
> 仅服务端的怎么办？写`客服`吗？

貌似没有只在服务端运行的Mod吧，那不是统一叫插件吗？

**Comment by Ahrwing** [comment]
目前这里已有文字说明，是否有必须要做成图标形式有待研究
[![https://ae01.alicdn.com/kf/U3326d36d2a1b4512bfc6ca98f21be6a0Z.jpg](https://ae01.alicdn.com/kf/U3326d36d2a1b4512bfc6ca98f21be6a0Z.jpg)](https://ae01.alicdn.com/kf/U3326d36d2a1b4512bfc6ca98f21be6a0Z.jpg)

**Comment by bao-cn** [comment]
> 目前这里已有文字说明，是否有必须要做成图标形式有待研究
> [![https://ae01.alicdn.com/kf/U3326d36d2a1b4512bfc6ca98f21be6a0Z.jpg](https://camo.githubusercontent.com/53737933f0df2b603a963f81029c1d71dd96ce4da52a6ad0fcc37d39005adbf1/68747470733a2f2f616530312e616c6963646e2e636f6d2f6b662f5533333236643336643261316234353132626663366361393866323162653661305a2e6a7067)](https://ae01.alicdn.com/kf/U3326d36d2a1b4512bfc6ca98f21be6a0Z.jpg)

我竟然没注意到有这个，还是觉得显著一点比较好 /笑哭

**Comment by Ahrwing** [comment]
> 
> 
> > 仅服务端的怎么办？写`客服`吗？
> 
> 貌似没有只在服务端运行的Mod吧，那不是统一叫插件吗？

您好，有的！
https://www.mcmod.cn/modlist.html?mode=2`

`我记得 Dynmap 貌似也有 Mod 版？`

**Comment by bao-cn** [comment]
> > > 仅服务端的怎么办？写`客服`吗？
> > 
> > 
> > 貌似没有只在服务端运行的Mod吧，那不是统一叫插件吗？
> 
> 您好，有的！
> [https：//www.mcmod.cn/modlist.html？mode = 2`](https://www.mcmod.cn/modlist.html?mode=2%60)
> 
> `我记得 Dynmap 貌似也有Mod版？`

大意了😂

**Comment by mamaruo** [comment]
> > > 仅服务端的怎么办？写`客服`吗？
> > 
> > 
> > 貌似没有只在服务端运行的Mod吧，那不是统一叫插件吗？
> 
> 您好，有的！
> [https://www.mcmod.cn/modlist.html?mode=2`](https://www.mcmod.cn/modlist.html?mode=2%60)
> 
> `我记得 Dynmap 貌似也有Mod版？`

当场发现 BUG，这个筛选，`客户端可选`的也一并进入了，按理说它们严格意义上不是`仅服务端`。

**Comment by Ahrwing** [comment]
> 
> 
> > > > 仅服务端的怎么办？写`客服`吗？
> > > 
> > > 
> > > 貌似没有只在服务端运行的Mod吧，那不是统一叫插件吗？
> > 
> > 
> > 您好，有的！
> > [https://www.mcmod.cn/modlist.html?mode=2`](https://www.mcmod.cn/modlist.html?mode=2%60)
> > `我记得 Dynmap 貌似也有Mod版？`
> 
> 当场发现 BUG，这个筛选，`客户端可选`的也一并进入了，按理说它们严格意义上不是`仅服务端`。

`当场改进`
[![https://ae01.alicdn.com/kf/Uf4c2ba1598ad48a39614f1231d485b99Q.jpg](https://ae01.alicdn.com/kf/Uf4c2ba1598ad48a39614f1231d485b99Q.jpg)](https://ae01.alicdn.com/kf/Uf4c2ba1598ad48a39614f1231d485b99Q.jpg)

**Comment by bao-cn** [comment]
> > > > > 仅服务端的怎么办？写`客服`吗？
> > > > 
> > > > 
> > > > 貌似没有只在服务端运行的Mod吧，那不是统一叫插件吗？
> > > 
> > > 
> > > 您好，有的！
> > > [https://www.mcmod.cn/modlist.html?mode=2`](https://www.mcmod.cn/modlist.html?mode=2%60) `我记得 Dynmap 貌似也有Mod版？`
> > 
> > 
> > 当场发现 BUG，这个筛选，`客户端可选`的也一并进入了，按理说它们严格意义上不是`仅服务端`。
> 
> `当场改进`
> [![https://ae01.alicdn.com/kf/Uf4c2ba1598ad48a39614f1231d485b99Q.jpg](https://camo.githubusercontent.com/04876870ca84c2d7d4a32aa841909ae736fb60df39e5546ac618b79b9015cefc/68747470733a2f2f616530312e616c6963646e2e636f6d2f6b662f556634633262613135393861643438613339363134663132333164343835623939512e6a7067)](https://ae01.alicdn.com/kf/Uf4c2ba1598ad48a39614f1231d485b99Q.jpg)

这就是传说中的速度吗？🤩🤩🤩
