### ISSUE TITLE
只要已登录就返回403拒绝访问。

### ISSUE THREAD

**Issue by kamionichan** [Ahrwing/mcmod#633]
我相信等有管理员看到了，这个问题可能早已解决....但还是说一下。

本来以为是科学问题，经测试，不管我用4G还是宽带，或者变更ip，只要一登录就返回403。拒绝访问。

只是因为百度云加速在为难我这一地区？
“403当前访问可能造成安全威胁，您的访问被阻断。 攻击类型:【应用程序漏洞攻击】
DuEdge Event ID: 9d6915e74dee2f4d”

**Comment by Ahrwing** [comment]
已收到，正在关注。

**Comment by CalaviHako** [comment]
我也是，1551287763QQ登陆的，黄绿色的蜡笔，这几天正在施工呢，突然就登不上了，早日修复吧

**Comment by CalaviHako** [comment]
我也是，QQ登陆的，黄绿色的蜡笔，这几天正在施工呢，突然就登不上了，早日修复吧

**Comment by CalaviHako** [comment]
@Ahrwing 我也是，QQ登陆的，黄绿色的蜡笔，这几天正在施工呢，突然就登不上了，早日修复吧

**Comment by pupfcom** [comment]
同问，我也是这个问题，只能在不登录的状态下浏览

**Comment by Ahrwing** [comment]
现在还会出现吗？

**Comment by pupfcom** [comment]
> 现在还会出现吗？

可以了，谢谢
