### ISSUE TITLE
神威刀系列拔刀剑无法检索

### ISSUE THREAD

**Issue by Aquk1n** [Ahrwing/mcmod#635]
神威刀系列的拔刀剑没法在站内搜索到 通过百度能够直接前往单个物品的界面

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/111885295-e7978780-8a01-11eb-8fcb-ad4888f52969.png)
![图片](https://user-images.githubusercontent.com/5197567/111885410-91771400-8a02-11eb-8abd-6ff645c7c154.png)
感谢反馈，已修复无模组归属的资料无法被搜索到的问题。
