### ISSUE TITLE
论坛服务器资料管理无法添加图片

### ISSUE THREAD

**Issue by wangyz1999** [Ahrwing/mcmod#636]
只要添加图片就会弹出警告

The PHP installation does not meet the minimum system requirements for CKFinder. Missing PHP extensions: Fileinfo. Please refer to CKFinder documentation for more details.

![Screenshot 2021-03-23 001231](https://user-images.githubusercontent.com/31289305/112107664-79bb9f00-8b6c-11eb-81d8-86ba19b8292b.png)

**Comment by Ahrwing** [comment]
找服玩的编辑器现已不支持文件上传，未来会更换编辑器以解决此问题。
现可用上传图床复制图片本体粘贴的方式添加图片。
