### ISSUE TITLE
网站是被墙了吗？

### ISSUE THREAD

**Issue by Tfs-Foe** [Ahrwing/mcmod#637]
如题，不挂V*N就无法访问，挂上V*N就好了

![未挂V*N](https://user-images.githubusercontent.com/67150107/112787495-3b057780-908b-11eb-955f-645ee20fd795.png)

**Comment by Tfs-Foe** [comment]
附链接V*N后图：

![image](https://user-images.githubusercontent.com/67150107/112787774-e7475e00-908b-11eb-953b-b8e7d67e374b.png)

**Comment by Ahrwing** [comment]
可能是区域性故障/CDN间歇性抽风，隔一段时间再试试看。

**Comment by Ahrwing** [comment]
现在还会出现吗？

**Comment by Tfs-Foe** [comment]
依然这样

**Comment by heipiao233** [comment]
无法复现（福建福州金融街电信）
