### ISSUE TITLE
[建议]增加服务器插件板块

### ISSUE THREAD

**Issue by Fluair** [Ahrwing/mcmod#638]
建议增加服务器插件板块,专门收录各种服务器(paper,spigot)插件,如:Essentials,MultiWorld等

**Comment by mamaruo** [comment]
已有插件百科 <https://mineplugin.org/> 存在

N14777787289 ***@***.***> 于2021年3月30日周二 上午12:38写道：

**Comment by Fluair** [comment]
感谢回复
