### ISSUE TITLE
找服玩发布服务器的建议

### ISSUE THREAD

**Issue by 4o4E** [Ahrwing/mcmod#642]
虽然我知道在github反馈这个问题可能不合适, 但是我在找服玩的界面找了一圈只在最下面找到一个意见反馈,
**以下为建议**
1. 找服玩发布界面的建议
  * 建议把发布服务器界面的核心和游戏版本的填写规则讲清楚
  * 或者给一个示例链接
  * 另外希望能有关于跨版本相关的提示
  * 比如在服务器使用跨版本插件支持1.16.x进入的情况下该怎么填写版本
  * 是单独选中1.16还是需要勾选所有1.16的版本
  * 还是一定要填写子服核心的版本
  * 现在只有一条提示'非群组服请勾选服务端核心版本；群组服请勾选子服核心版本，而非登录服版本。'
2. 找服玩帖子被退回后希望能打开编辑 (退回后的帖子不能打开编辑, 码的字都没了, 要重新码)
**以下是原因**
* 我的服务器用了BC和跨版本插件, 支持1.16.x进入
* 所以我发布的时候核心选的是BungeeCord,版本是1.16, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5
* 结果是被退回, 原因是请勾选服务端核心版本 
* 核心改成Paper, 还是同样的原因退回

**Comment by Ahrwing** [comment]
已修改描述，改成了“只需勾选服务器对外宣传时放出的客户端版本。”
退回再编辑功能已包含在下次更新中

**Comment by 4o4E** [comment]
ok
