### ISSUE TITLE
原版物品贴图错误

### ISSUE THREAD

**Issue by 4o4E** [Ahrwing/mcmod#643]
![image](https://user-images.githubusercontent.com/58851040/118393894-0cac1d80-b674-11eb-97dd-0094b86ccdd1.png)
![image](https://user-images.githubusercontent.com/58851040/118393899-12a1fe80-b674-11eb-8986-e244e88cc3c0.png)
![image](https://user-images.githubusercontent.com/58851040/118393908-1b92d000-b674-11eb-8b76-cba08cc0f4c6.png)
![image](https://user-images.githubusercontent.com/58851040/118393911-1e8dc080-b674-11eb-9eb1-eb60113233e6.png)
正确的贴图
![image](https://user-images.githubusercontent.com/58851040/118393927-3107fa00-b674-11eb-8664-6f93df841ac6.png)

**Comment by HanlieChina** [comment]
可自行修改提交。

**Comment by Ahrwing** [comment]
现已解决。
