### ISSUE TITLE
找服玩图片无法上传

### ISSUE THREAD

**Issue by skyfsj** [Ahrwing/mcmod#645]
![image](https://user-images.githubusercontent.com/47785500/119209322-988cd200-bad8-11eb-8c2d-8f76d45daf1b.png)

**Comment by Ahrwing** [comment]
找服玩区暂不支持图片上传，可以用上传至图床后复制图片本体粘贴进编辑框的形式来添加图片。

**Comment by skyfsj** [comment]
![image](https://user-images.githubusercontent.com/47785500/119997657-88a64e00-c002-11eb-9a20-44ccb31bd844.png)


> 找服玩区暂不支持图片上传，可以用上传至图床后复制图片本体插入进编辑框的形式来添加图片。

**Comment by skyfsj** [comment]
不行啊
图片复制curseforge的

**Comment by Ahrwing** [comment]
更换图床

**Comment by mamaruo** [comment]
https://www.baidu.com/s?ie=UTF-8&wd=%E5%9B%BE%E5%BA%8A

RebirthIsHope ***@***.***> 于2021年5月28日周五 下午10:22写道：

**Comment by skyfsj** [comment]
可以了，谢谢了
