### ISSUE TITLE
BOSS栏 (worldborder) 命令？

### ISSUE THREAD

**Issue by heipiao233** [Ahrwing/mcmod#652]
https://www.mcmod.cn/tools/cbcreator/#/pagebossbar/

**Comment by Ahrwing** [comment]
有什么问题

**Comment by Ahrwing** [comment]
未描述问题，请回复或重发Issue。

**Comment by heipiao233** [comment]
基础功能里的boss栏显示“BOSS栏 (**worldborder**) 命令允许管理员在游戏界面顶部增加一个带有自定义文字信息的进度条。”，应该为：bossbar

**Comment by Ahrwing** [comment]
已修改
