### ISSUE TITLE
[功能建议]收藏夹加入分组功能

### ISSUE THREAD

**Issue by yulinlin404** [Ahrwing/mcmod#654]
收藏夹加入分组功能，最好还能自己命名的
我想把一些延迟监测的mod丢在一起方便我查找

**Comment by HanlieChina** [comment]
在做了，在做了.png

**Comment by sxjeru** [comment]
![image](https://user-images.githubusercontent.com/20513115/126890529-b1112ed2-3a73-4fc9-8ae8-24f9c428885b.png)
![image](https://user-images.githubusercontent.com/20513115/126890492-995f78f0-d85e-4e35-9cb8-87fb046fe9d8.png)
