### ISSUE TITLE
[建议]在模组元素的杂项中加入tps或卡顿监测的标签

### ISSUE THREAD

**Issue by yulinlin404** [Ahrwing/mcmod#655]
在模组元素的杂项中加入tps或卡顿监测的标签
像什么carpet，lagmeter，Lag Removal就可以选了
（个人私心个人私心）

**Comment by HanlieChina** [comment]
通用性不足，可使用杂项-优化 或者添加 模组标签。

**Comment by Ahrwing** [comment]
先写到模组标签里吧，未来这类模组多了可以再细分
`另: 模组元素都是两个字的，卡顿监测要缩写成顿监吗..`

**Comment by yulinlin404** [comment]
> 
> 
> 通用性不足，可使用杂项-优化 或者添加 模组标签。

优化的话，这类模组没这个功能，模组标签慢慢来吧

**Comment by yulinlin404** [comment]
> 
> 
> 先写到模组标签里吧，未来这类模组多了可以再细分
> `另: 模组元素都是两个字的，卡顿监测要缩写成顿监吗..`

“分析”

**Comment by yulinlin404** [comment]
> 
> 
> 先写到模组标签里吧，未来这类模组多了可以再细分
> `另: 模组元素都是两个字的，卡顿监测要缩写成顿监吗..`

“信息”也不错
