### ISSUE TITLE
自定义NPCmod!!!秋梨膏！！！

### ISSUE THREAD

**Issue by alonemonst** [Ahrwing/mcmod#657]
自定义NPC突然找不到了！没有它孩子真的简直不能活！球球把这个mod的下载地址放到百科里吧！非常感谢！

**Comment by sxjeru** [comment]
下载地址如下，已置于百科相关链接处。

http://www.kodevelopment.nl/minecraft/customnpcs/downloads/
https://www.curseforge.com/minecraft/mc-mods/custom-npcs/files/all

**Comment by alonemonst** [comment]
> 下载地址如下，已经出现了相关链接处。
> 
> [http://www.kodevelopment.nl/minecraft/customnpcs/downloads/ ](http://www.kodevelopment.nl/minecraft/customnpcs/downloads/)
> https://www.curseforge.com/minecraft/mc-mods/custom-npcs/files/all

非常感谢！
