### ISSUE TITLE
[建议]功能改进及升级

### ISSUE THREAD

**Issue by yulinlin404** [Ahrwing/mcmod#663]
主站及社群存在跟踪性内容https://s13.cnzz.com
社群区疑似存在非加密链接，提示此网页上部分内容不安全，建议升级

**Comment by Ahrwing** [comment]
网站分析工具已在尝试过度至 Google Analytics，如果顺利，未来会在合适的时间取消 cnzz。
社群帖子内存在非加密链接的原因可能是用户内容、签名中使用了非SSL图床，比较难解决，因为DZ没有提供这方面的限制。
