### ISSUE TITLE
使用无序列表时超过10个将导致403拒绝访问

### ISSUE THREAD

**Issue by yulinlin404** [Ahrwing/mcmod#664]
将https://www.curseforge.com/minecraft/mc-mods/tweakmyclient     的feature toggle部分添加到资料时，多次提示403错误，检查网络情况后缩减正文发现，若超过10个无序列表，将导致403

**Comment by HanlieChina** [comment]
无关-日志中无序列表通常超过10个。

**Comment by Ahrwing** [comment]
已调整WAF策略，再观察一下。
