### ISSUE TITLE
无序列表异常

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#665]
光标放在无序列表标记后按下 Tab 降级无序列表
- 当降到4级（破折号）时，列表会变成数字编号，5级“小圆圈”也是。
- 破折号和小圆圈类型的无序列表无法直接使用。
- 无序列表级别可以无限次降级，建议增加限制。

**Comment by Ahrwing** [comment]
- 已尝试修复。
- 已移除冗余选项。
- 已限制列表级别最大为5。
