### ISSUE TITLE
希望有Boat

### ISSUE THREAD

**Issue by Pantyhose-X** [Ahrwing/mcmod#667]
希望你们构建一个[Boat](https://github.com/AOF-Dev/BoatApp/blob/boat-4/README-zh_CN.md)版

**Comment by mamaruo** [comment]
这个反馈空间的作用是
> 本区仅受理百科的BUG和意见，MC玩法相关提问请转到社群。

恐怕不能如愿了

**Comment by sxjeru** [comment]
实际上不需要构建，只要下载[MCinaBox](https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.4-p5-0119)（启动器）即可，各个版本的mc里面都可以直接下载。
