### ISSUE TITLE
连接被无限重置

### ISSUE THREAD

**Issue by masakitenchi** [Ahrwing/mcmod#669]
怀疑原因同#618。坐标依旧为北海道。
实际情况：
![image](https://user-images.githubusercontent.com/11086210/126473004-d7b0b6d9-4bb7-4b90-917f-890a9f14d319.png)

**Comment by Ahrwing** [comment]
ping 一下 www_mcmod_cn 看是哪个节点，能否 ping 通。

**Comment by masakitenchi** [comment]
目前是这个情况
![image](https://user-images.githubusercontent.com/11086210/126535461-e09b7709-fb5c-4c22-b0f8-88b8e986f9fa.png)

**Comment by sxjeru** [comment]
连上日本的 T 后确实无法访问百科了。
![image](https://user-images.githubusercontent.com/20513115/126574449-fe1a7fe3-1dad-4b79-8e13-c236bcd71139.png)

**Comment by masakitenchi** [comment]
昨天开始恢复正常。我就暂时先关掉这个issue了

**Comment by Ahrwing** [comment]
虽然什么都还没来得及做，但它自己就好了…… 
日本IP连到的却是国内广西的节点，应该只是CDN波动吧 ![图片](https://user-images.githubusercontent.com/5197567/126728752-21154066-ddce-4664-9528-43811a337dc9.png)

`惊.. CDN后台国外节点的开关居然消失了`

**Comment by masakitenchi** [comment]
今日开始继续出现这个问题……
![image](https://user-images.githubusercontent.com/11086210/126889426-c8fe164f-567b-4565-b301-04b7fd066021.png)

**Comment by Ahrwing** [comment]
在控制台输入 tracert www_mcmod_cn 等待完成后把结果截图发上来，这边做一下排查

**Comment by masakitenchi** [comment]
![image](https://user-images.githubusercontent.com/11086210/126889586-6060bbab-8151-4863-9b2f-5aac6bbe8272.png)
这……

**Comment by masakitenchi** [comment]
![image](https://user-images.githubusercontent.com/11086210/126889712-26356a06-08d3-447f-95ba-dbb9c57c0b2b.png)
我一脸懵逼

15:25更新：强制v4模式下与上图结果相同。强制v6模式下无法解析。

**Comment by Ahrwing** [comment]
本地都没路由出来… 那大概不是CDN和百科服务器的锅，具体原因也不太清楚，无能为力了……

**Comment by masakitenchi** [comment]
![image](https://user-images.githubusercontent.com/11086210/126890000-5097023d-7217-4aac-b752-35135ee1b957.png)
飞到越南以后是这样的（
`没啊，人确实在北海道啊，不然我折腾这个干嘛……`

1536更新：
![image](https://user-images.githubusercontent.com/11086210/126890107-32ee20d0-5389-4264-bc55-68621d8e13f4.png)
似乎没用

**Comment by Ahrwing** [comment]
设置为谷歌的dns试试
8.8.8.8

`好家伙，原来是用飞的，原以为你肉身就在北海道呢 (`
~国内直连不香吗~

**Comment by masakitenchi** [comment]
> 本地都没路由出来… 那大概不是CDN和百科服务器的锅，具体原因也不太清楚，无能为力了……

那就先这样吧，能上就上，不能就等它能了在上吧……
推しは推せるときに推せ！
