### ISSUE TITLE
对站内所有富文本编辑器添加GFM（GitHub Flavored Markdown）支持

### ISSUE THREAD

**Issue by rsp4jack** [Ahrwing/mcmod#673]
不同于直接在现有编辑器内添加，可以尝试额外添加一个GFM编辑器

**Comment by mamaruo** [comment]
#624

**Comment by rsp4jack** [comment]
> #624

我刚刚更新了issue.

**Comment by sxjeru** [comment]
本来是两者共存，可以切换的，但是有问题……
参考：https://github.com/Ahrwing/mcmod/issues/299

如果真心喜欢Markdown，可以在其他平台写好后，将预览复制粘贴到百科RTF编辑器，应该能保留格式。

**Comment by rsp4jack** [comment]
并不能，Hx标题会消失（Typora -> mcmod）

**Comment by sxjeru** [comment]
可以使用RTF编辑器自带的标题功能。

**Comment by mamaruo** [comment]
可以考虑开发单向导入功能，输入 Markdown 输出富文本，之后的编辑都基于富文本

**Comment by rsp4jack** [comment]
pandoc可以双向转换markdown和HTML
