### ISSUE TITLE
投票显示错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#68]
![image](https://cloud.githubusercontent.com/assets/5229241/9544391/f7178dfe-4db2-11e5-98dc-e302e778668f.png)
之前有一票赞同，投了反对之后就NaN了

**Comment by Ahrwing** [comment]
這是在什麽情況下導致的 /w\.... 投完以後票數增加了嗎？

**Comment by Meow-J** [comment]
@Ahrwing 上面那个NaN之前票数为1，投了反对票之后就没了

**Comment by Ahrwing** [comment]
刷新仍然顯示NaN嗎？ 頁面地址 /w\...

**Comment by Meow-J** [comment]
都过了好几天了，我哪记得地址/w\

**Comment by Meow-J** [comment]
随便又找了一个：http://www.mcmod.cn/class/94.html
![image](https://cloud.githubusercontent.com/assets/5229241/9575528/0de3d2d4-5003-11e5-89fa-20a0db8e3832.png)
刷新后
![image](https://cloud.githubusercontent.com/assets/5229241/9575530/11c3d714-5003-11e5-9eba-f37df55e91b4.png)

**Comment by Meow-J** [comment]
@Ahrwing 发现只要投反对票都会NaN

**Comment by Ahrwing** [comment]
修好了~ 果然一些解决不了的问题要晾会儿再重新去看才能完美解决 Orz...
