### ISSUE TITLE
正文内容异常解析<li>标签

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#680]
例如以下内容，解析出来是这样的。并且“清除格式”无法解决。这段来自Capsule模组的[CurseForge页面](https://www.curseforge.com/minecraft/mc-mods/capsule)。
![](https://i.mcmod.cn/editor/upload/20210821/1629534306_14273_WEkE.png)
```
<ul>
<li><span style="font-size:12px"><a href="/linkout?remoteUrl=https%253a%252f%252fimgur.com%252fgallery%252fRGQw1" rel="nofollow">Move you base!</a> An entire base packed in a 31x31x31 can be moved entirely including machines. You can be a real traveler now.</span></li>
<li><a href="/linkout?remoteUrl=https%253a%252f%252fimgur.com%252fgallery%252fvN1sJrf" rel="nofollow">Build faster with blueprints!</a> Blueprint capsules can take materials from chests or other inventories to duplicate a structure. It supports rotation and mirror.</li>
<li><a href="https://github.com/Lythom/capsule/wiki/Modpack-making" rel="nofollow">Modpack making options</a>, so that player can be rewarded with ready to deploy structures or loot them in chests.</li>
<li>A ton of possibilities ! Capsules can be used as early backpack moving a chest, as portable ladder, to deploy protecting walls to recover during a fight, to move machines or multiblocks, <a href="/linkout?remoteUrl=https%253a%252f%252fimgur.com%252fJ5QfvAx" rel="nofollow">and more…</a> unleash your creativity !</li>
</ul>
```

> HTML 相关术语说错了别打我，我啥也不是

**Comment by sxjeru** [comment]
都是`ul` 无序列表 tag，不过显示数字序号的少了样式`style="list-style-type: disc;"`。

![image](https://user-images.githubusercontent.com/20513115/130316074-7662ab61-2b0d-4b1a-9063-e4656881f5c2.png)

**Comment by Ahrwing** [comment]
我这边测试 FF/Chrome 粘贴正常（列表序号样式显示不同是异常，但未出现溢出的情况）：
![01](https://user-images.githubusercontent.com/5197567/130316116-de503ea8-05c8-4531-b97c-7d81752e240d.gif)

`遇到这种情况选中再重新设置列表就好了`

**Comment by sxjeru** [comment]
解决方案之一是对首行内容取消列表，再设置一次无序列表即可。
后面连着的内容会一起变。

**Comment by mamaruo** [comment]
360极速浏览器 版本号:13.0.2250.0内核版本:86.0.4240.198 直接不显示列表，不管是有序还是无序。
Microsoft Edge 版本 92.0.902.78 (官方内部版本) (64 位) 与我的 Chrome 结果（issue 头）相同。

列表溢出至少在审核的时候见过五次。可能有其他原因。

另一个解决方法是 Ctrl + X 剪切内容，Ctrl + Shift + V 纯文本粘贴，视情况重新设置列表。

**Comment by mamaruo** [comment]
另一个解决方法是 Ctrl + X 剪切内容，Ctrl + Shift + V 纯文本粘贴，视情况重新设置列表。
