### ISSUE TITLE
如果富文本编辑器为空，禁用自动存档和手动存档

### ISSUE THREAD

**Issue by rsp4jack** [Ahrwing/mcmod#682]
例如打开了一个编辑界面，然后不往富文本编辑器里输入任何东西，过一段时间后自动存档的内容会被覆盖为空内容，手动存档空内容也没有任何意义。

**Comment by Ahrwing** [comment]
`已改进`
![图片](https://user-images.githubusercontent.com/5197567/130352819-5f4af114-2104-423f-9550-c0f950e905b0.png)
