### ISSUE TITLE
模组的开发组申请无法跳转

### ISSUE THREAD

**Issue by HZDZ9495** [Ahrwing/mcmod#689]
经过多次尝试，不管是电脑还是手机都不行（手机的跳转会跳转到手机钱包上去（划掉）），都是最新版qq

**Comment by sxjeru** [comment]
申请链接的本意是邀请加入百科的编辑讨论群：1137659736
在群内直接申请，或者向群管理提出申请。

经测试电脑上确实无法跳转到qq，手机上只有在安装有qq的情况下才能跳转至加群页面。

**Comment by mamaruo** [comment]
经测试以下环境正常跳转
QQ9.4.9 (27849)
Chrome 版本 92.0.4515.159（正式版本） （64 位）
Microsoft Edge 版本 92.0.902.78 (官方内部版本) (64 位)
FireFox 91.0.2 (64 位)
360极速浏览器 版本号:13.5.1052.0内核版本:86.0.4240.198

<del>可能要跟腾讯方面反馈了。</del>

HZDZ9495 ***@***.***> 于2021年8月26日周四 下午10:16写道：

**Comment by mamaruo** [comment]
https://bbs.mcmod.cn/thread-7465-1-1.html
再次收到反馈，可能需要优化一下，通过一个类似“暂无下载”的窗口来提示开发者申请，在其中指出“开发者证明”的内容和“重生是谁”也是必要的。
![image](https://user-images.githubusercontent.com/37480168/134023395-8c651ea2-10b9-44ba-afaa-8e4e65b18761.png)

**Comment by mamaruo** [comment]
https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=8711
类似问题

**Comment by Ahrwing** [comment]
已修改申请方式，现在不用加群了，点原来的加群链接现在会弹出窗口介绍开发者的功能与具体申请方式。
