### ISSUE TITLE
教程选项卡大量Bug

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#69]
![image](https://cloud.githubusercontent.com/assets/5229241/9560742/e1cf8310-4e58-11e5-8c6f-8e486bc4717b.png)
首先，上面是Mod攻略，与教程不统一  
写新教程按钮样式很难看  
迷之未知

**Comment by Ahrwing** [comment]
1.已改
2.重複 #66 
3.原本以為是老教程發佈時間是 0000-00-00 原因導致，後來發現是修改教程后根本就沒更新時間... 已修復，重新編輯一次時間就恢復了
