### ISSUE TITLE
对于资料，分离内容，并支持CSS样式表

### ISSUE THREAD

**Issue by rsp4jack** [Ahrwing/mcmod#691]
资料包括 mcmod 里的教程、物品资料、Mod 介绍等各种可富文本编辑的资料（短评除外）
大致是将资料内容独立出一个 iframe，然后 head 里有百科默认 CSS 以及用户指定的 CSS 等，body 里是资料内容，balabala……
这或许可以方便排版、前后端分离（iframe 直接指定src）等

**Comment by mamaruo** [comment]
我看不懂，但我大受震撼
给用户开放HTML、CSS的编辑权怕不是要整出神仙排版
Wikipedia 据我知也只有权限很高的人能改全局样式

Creepercdn ***@***.***> 于2021年8月28日周六 下午12:45写道：

**Comment by rsp4jack** [comment]
或许可以有等级限制

**Comment by Ahrwing** [comment]
坏处太多，意义也不大。
现在主流网站前端已经几乎不会在生产环境中使用 iframe 了，对 SEO 也有影响，前后端分离是架构的事，和 iframe 也没有关系。
