### ISSUE TITLE
添加实名认证系统

### ISSUE THREAD

**Issue by HanlieChina** [Ahrwing/mcmod#692]
未成年人仅可在周五、周六、周日和法定节假日每日20时至21时访问MC百科。
不向未实名注册和登录的用户提供访问服务。

**Comment by Ahrwing** [comment]
一时间不知是在玩梗还是认真提问题 (

**Comment by HanlieChina** [comment]
> 一时间不知是在玩梗还是认真提问题（

玩梗。
