### ISSUE TITLE
建议物品合成采用jei形式

### ISSUE THREAD

**Issue by ghost** [Ahrwing/mcmod#693]
为什么物品合成不采用jei形式呢，随便找一个物品，比如钻石吧，一进去一大长条，眼睛都花了，建议使用jei形式，把处理方式放在上面，左面是参与此处理方式的工具（比如工作台和手持工作台），并在左键和右键物品大图标时显示用途/合成

**Comment by mamaruo** [comment]
我觉得把合成表做成翻页形式值得考虑。
一个 GUI 绑定多个资料也用应用前景。不过，如果像 GUI 那样，把所有“工作台”都显示出来的话，考虑到所有模组中的“工作台”太多，可能不能与 JEI 相同。
大多数 GUI 图片都把标题写在正上方了。
