### ISSUE TITLE
关于mcmod mod下载

### ISSUE THREAD

**Issue by ghost** [Ahrwing/mcmod#694]
我看过有人使用curseforge的api，跳过网站直接下载MOD，还有pcl和hmcl启动器也会提供此功能，我觉得mcmod开发人员可以研究一下，辛苦了https://www.mcbbs.net/thread-1119157-1-1.html

**Comment by ghost** [comment]
pcl和hmcl使用的方法好像不一样，pcl是全版本的，是不是bate也有显示，hmcl则不是，总是版本过低，不过你们是不是研究过这个东西了，因为你们没回我

**Comment by Ahrwing** [comment]
研究过，但最终能否上线现在还不好说。

**Comment by Ahrwing** [comment]
研究过，但最终能否上线现在还不好说

**Comment by sxjeru** [comment]
此方法提取的是 cursecdn 链接，国内下载速度可能并不会很快，只是省去了验证过程。
