### ISSUE TITLE
模组资料编辑 存在问题

### ISSUE THREAD

**Issue by OcrSu** [Ahrwing/mcmod#695]
我想修改镇守府模组的版本资料：新增1.16.5版本
可是总是提示系统出现一项异常，请重新刷新页面。
镇守府模组：https://www.mcmod.cn/class/1026.html

**Comment by sxjeru** [comment]
无法重现，建议清除缓存刷新、更换浏览器并检查本地网络连接。

![image](https://user-images.githubusercontent.com/20513115/132280820-a3206d68-5488-4b9f-acda-101618146bc4.png)
