### ISSUE TITLE
添加热键时没有填默认按键的地方

### ISSUE THREAD

**Issue by elctove** [Ahrwing/mcmod#70]
虽然好像根本没人添加这玩意……

**Comment by Meow-J** [comment]
热键?

**Comment by elctove** [comment]
绑定热键……我就说没人会管这块……除了我这么无聊弄了一个……

**Comment by Meow-J** [comment]
竟然还有这种功能/w\

**Comment by Ahrwing** [comment]
標題里填寫的就是默認按鍵啊…… 例如說：

MOD：NEI

標題：R鍵
內容：能夠查看該物品的合成方式 [截圖]  如果想要查看該物品能夠參與的合成，請查看U鍵[鏈接]相關說明 [截圖]
