### ISSUE TITLE
询问一下昨天编辑服务是炸了吗？

### ISSUE THREAD

**Issue by Huiaei** [Ahrwing/mcmod#717]
今天发现昨天提交的三项全部不在审核列表里了。

**Comment by Ahrwing** [comment]
检查筛选条件中的排序选项，修改排序条件后再试。未审核的内容“最后审核时间”为0，会排在最后面。

**Comment by Huiaei** [comment]
> 检查筛选条件中的排序选项，修改排序条件后再试。未审核的内容“最后审核时间”为0，会排在最后面。

好的，已经找到了。每次提交完弹出的审核列表让我以为是排在前面的。

**Comment by WuzgXY-GitHub** [comment]
> 检查筛选条件中的排序选项，修改排序条件后再试。未审核的内容“最后审核时间”为0，会排在最后面。

是不是应该修改一下这个设计

**Comment by Ahrwing** [comment]
已知未审核的内容“最后审核时间”为0，若倒序，未审核的内容始终会在最后，若正序，

**Comment by Ahrwing** [comment]
&gt;&nbsp;是不是应该修改一下这个设计


晚点再回复。

**Comment by Ahrwing** [comment]
> 是不是应该修改一下这个设计

尝试改为使未审核内容始终排在最前面，结果很不理想，还是维持现在的设定吧，或者你有更好的想法？
审核页面按审核时间排序的初衷也是为了方便查看最新过审的内容。
查看待审核项可以用筛选功能（提交编辑内容后自动跳转的也是用的这个筛选设置）：
![图片](https://user-images.githubusercontent.com/5197567/136064107-6353517b-94fc-476f-9bb7-394ba886be60.png)

**Comment by WuzgXY-GitHub** [comment]
理解。我是这么想的，由于审核项通过不会有提示，从主页直接点进 ./verify 的一般都想查看自己的待审核项是否被通过了，如果一次性提交了 —— 打个比方 —— 两项，那到这个页面后一看满眼绿的（已通过的，白底绿字），还得分辨这些绿的里面有没有自己刚提交的两项，看到一项还得再找另一项通过没有，如果不想作这种分辨，就得在筛选器里调一会；但如果待审核项默认始终置顶，那点进去就可以直接了解到自己还有没有待审核项（黑底白字）、有几个待审核项了，相当直观。毕竟「找到最新过审的内容」并非普遍需求，东西写完就写完了，一般不会有人再打开看一遍，反而「知道自己提交内容的审核情况」这种需求更常见一些

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/136143873-8a605b65-4eed-41f0-ba97-41f2b8882dc1.png)
已为登录且有待审项的用户添加链接，更方便跳转至「知道自己提交内容的审核情况」的专属页
