### ISSUE TITLE
mod文件归档/隐藏功能

### ISSUE THREAD

**Issue by sxjeru** [Ahrwing/mcmod#718]
部分作者不希望旧版本mod文件出现在下载页面中，为了互联网留痕，或许有必要添加此功能。
当有了此功能后，请收回多数人的删除权利，转为归档。

（目前他们的操作时直接删除旧文件）

**Comment by Ahrwing** [comment]
将Mod作者的“删除”改为“隐藏”，然后在列表中显示隐藏项并提供下载？

**Comment by sxjeru** [comment]
@Ahrwing 既然隐藏了就不该再对外提供下载，只是作为百科站的归档文件保留。

**Comment by Ahrwing** [comment]
部分作者爱删历史文件的习惯很难改掉，这样修改后可能会继续找管理要求删除，或是更谨慎的上传文件。

**Comment by Ahrwing** [comment]
或许可以追加“文件时间线”功能？现有删除功能维持不变，但可以看到是谁在什么时间上传或删除了哪些文件。

**Comment by sxjeru** [comment]
@Ahrwing 那样只有文件信息，应该没什么用……
（主要是站内mod文件多为搬运，时间线并不准确）

吃饭时想了想，感觉这个功能没什么必要性了。或许只是脑子一热吧—— v

**Comment by Ahrwing** [comment]
或许可以取消“模组管理员”删除文件的功能，改为向资深申请… 除非“模组开发者”要求只留最新，否则应该完整归档。

**Comment by sxjeru** [comment]
@Ahrwing 没有必要，如果开发者不要求只留最新，基本上没有人会去删除历史文件。
下放删除权到目前为止似乎没有受害者。（滥用删除操作）
上传页也已经有提示了。

![image](https://user-images.githubusercontent.com/20513115/135021439-79323eac-59ec-47f9-bd32-7f75cdff8cb4.png)
