### ISSUE TITLE
把“MC百科”链接图标字体改为Gayatri

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#719]
![image](https://user-images.githubusercontent.com/37480168/135026731-457c3cdd-f78b-4a69-b660-4a01d413ad31.png)
如上图，MC百科的图标稍显突兀。修改成现在百科icon相同的字体可能会更好。

**Comment by Ahrwing** [comment]
已修改。
`顺便修了 gitlab 图标的颜色填充异常`
