### ISSUE TITLE
删除短评后，页面内其他楼中楼消失

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#722]
删除某一短评后，同一页面内其他楼中楼消失，刷新后可见

**Comment by HanlieChina** [comment]
不就是这么设计的吗

**Comment by Ahrwing** [comment]
我这边测试正常（个人主页留言），此问题可以重现吗？

**Comment by sxjeru** [comment]
测试了一下mod页的短评——
短评楼中楼是随页面滚动加载的，如果不等页面拉到底（加载完楼中楼）就先删除短评，再往下拉就不会显示楼中楼了。

另外提交一次短评会刷新楼中楼。

**Comment by mamaruo** [comment]
我也无法重现了，顺着sxj的思路倒是发现了新的
