### ISSUE TITLE
chrome新版本中checkbox和radio在:focus会有很难看的黑框

### ISSUE THREAD

**Issue by roj234** [Ahrwing/mcmod#725]
可以使用
*:before {
  outline: 0 !important;
}
消除

**Comment by mamaruo** [comment]
可见于文件上传后台版本选择复选框、“加入收藏夹”弹出窗口中的复选框

**Comment by Ahrwing** [comment]
已解决！

**Comment by sxjeru** [comment]
主站确认解决，文件后台还没有。
![image](https://user-images.githubusercontent.com/20513115/138679371-26fa6d60-f828-46ee-832b-2b8d6da0ec85.png)

**Comment by Ahrwing** [comment]
> 主站确认解决，文件后台还没有。

缓存问题，现在主站后台也好了

**Comment by sxjeru** [comment]
已确认。√
