### ISSUE TITLE
合成表能量信息无 %s 时的处理

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#727]
现在没有 %s 的能量信息仍可在后台添加。
以“能量123”为例效果：
- 编辑页会出现该项目。
- 如果不向其中填入内容，该能量信息不会显示。
- 如果填入内容，显示为“能量123”。

相当于一个固定的可选信息提示，确实有一定的应用场景。

如果要保留这个效果，希望把它特化，以勾选形式出现。
如果不保留，拦截存在“无 %s 能量”的GUI的编辑/新建。

**Comment by Ahrwing** [comment]
已修复在缺少格式符或有多个格式符时仍能正常提交的问题。
利用此特性实现的效果未来如有需求可以新增“文本单选格”与“文本多选格”。
