### ISSUE TITLE
合成表（item/tab）页性能问题

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#728]
![image](https://user-images.githubusercontent.com/37480168/138564881-71b13e20-6339-4bee-96bb-b973377ce61c.png)

因上千合成表加载而非常缓慢。因为这个我还被防DDoS检测了一番。

**Comment by Ahrwing** [comment]
临时改为每种最多显示100个合成，之后会再想办法解决，例如加分页或滑动加载更多
