### ISSUE TITLE
请求搜索页面将原版资料显示优先级提高

### ISSUE THREAD

**Issue by VulpesStella** [Ahrwing/mcmod#729]

**Comment by HanlieChina** [comment]
如果指https://search.mcmod.cn/ 不赞成，因为
1.https://www.mcmod.cn/item/list/1-1.html 内有快捷搜索。
2.https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki 内有更完善的内容。

**Comment by VulpesStella** [comment]
👌
