### ISSUE TITLE
资料列表在小屏设备上的适应问题

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#732]
![5PX_O )~12TOGNA$ )UPR3S](https://user-images.githubusercontent.com/37480168/139569716-3ed9e27c-1257-4534-be95-db3f07583756.png)
![6I6PFRQLWULFZZ4P LC$V86](https://user-images.githubusercontent.com/37480168/139569725-5b94f962-ca15-4efa-84c7-dcc3ec3c1430.png)
![YTYC%D415MC 00MQ38O1RW](https://user-images.githubusercontent.com/37480168/139569731-a1182ac4-a2a1-40a9-a054-e7a9435af655.png)

宽屏下理想效果：
![{X`48 R5T JTM8%98CHY1HB](https://user-images.githubusercontent.com/37480168/139569744-0fd34429-9210-4df8-a3a8-e56b1f3ad1d5.png)

测试页面：https://www.mcmod.cn/item/list/1634-127.html

**Comment by sxjeru** [comment]
图片当背景的缩放问题，由于移动版网页自适应宽度，与图片尺寸对不上号。
脑子里有两个方案。

第一种，固定宽度。
![image](https://user-images.githubusercontent.com/20513115/139569894-1d5b0536-050b-4552-b6da-8ea9d5ab1046.png)

第二种，既然已经将背景拆成上中下三部分来适应可变高度，何不再拆分成八部分来适应可变宽度呢？
```
╭ ─ ╮
│   ┃
╰ ━ ╯

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/139573147-29ea8759-6003-4a01-b96a-58c05470a436.png)
已改为固定宽度。
