### ISSUE TITLE
网站连接问题

### ISSUE THREAD

**Issue by 6QXD9** [Ahrwing/mcmod#733]
网站出现问题，个人页面均无法打开，提示拒绝连接，自己的和其他人的都不可以

**Comment by Ahrwing** [comment]
ping 一下 www.mcmod.cn 看看返回的是哪个节点

**Comment by 6QXD9** [comment]
> ping 一下 [www.mcmod.cn](http://www.mcmod.cn) 看看返回的是哪个节点
正在 Ping www.mcmod.cn.cname.yunjiasu-cdn.net [150.138.151.138] 具有 32 字节的数据:
来自 150.138.151.138 的回复: 字节=32 时间=41ms TTL=54
来自 150.138.151.138 的回复: 字节=32 时间=42ms TTL=54
来自 150.138.151.138 的回复: 字节=32 时间=41ms TTL=54
来自 150.138.151.138 的回复: 字节=32 时间=42ms TTL=54

150.138.151.138 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 41ms，最长 = 42ms，平均 = 41ms

**Comment by Ahrwing** [comment]
这边测试正常，具体是哪个页面呢

**Comment by 6QXD9** [comment]
> 这边测试正常，具体是哪个页面呢

自己和他人账号的个人主页，收藏夹等。具体提示是：center.mcmod.cn 已拒绝连接。ERR_CONNECTION_REFUSED

**Comment by Ahrwing** [comment]
如果 center.mcmod.cn 与 www.mcmod.cn 返回的节点一致，但只有 center.mcmod.cn 无法访问，那很有可能是浏览器或本地的原因，更换浏览器或或者等一段时间后再试试看，也可以试试手机在不连WIFI的情况下访问

**Comment by 6QXD9** [comment]
> 如果 center.mcmod.cn 与 [www.mcmod.cn](http://www.mcmod.cn) 返回的节点一致，但只有 center.mcmod.cn 无法访问，那很有可能是浏览器或本地的原因，更换浏览器或或者等一段时间后再试试看，也可以试试手机在不连WIFI的情况下访问

抱歉现在才回复，2点刚才停电了，我无法查看是否返回节点一致，但经过手机流量浏览发现可以正常打开，所以可能是我自己的问题，待来电醒了后我在进行测试查看，感谢你的解答
