### ISSUE TITLE
请求增强短评频道图标

### ISSUE THREAD

**Issue by VulpesStella** [Ahrwing/mcmod#736]
如果“喷泉广场”和“冒险者公会”的字样后能显示各自频道的短评数 会不会更好地发挥频道的功能？

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/143201338-4f374b31-5846-4514-bf5a-e7ce5265492d.png)
已上线，统计正在更新中，部分短评的显示要稍后才能看到。

**Comment by VulpesStella** [comment]
Perfect！感谢~

**Comment by VulpesStella** [comment]
部分模组页面下该功能因未知原因失效 :(
https://www.mcmod.cn/class/5038.html
(话说这里怎么插图片来着)

**Comment by mamaruo** [comment]
> 部分模组页面下该功能因未知原因失效 :( https://www.mcmod.cn/class/5038.html (话说这里怎么插图片来着)

[README](https://github.com/Ahrwing/mcmod/blob/master/README.md)中有描述。

**Comment by VulpesStella** [comment]
![QQ截图20211224121606](https://user-images.githubusercontent.com/81358657/147318541-9f1870c9-f098-4f7b-b330-a7b2f8a6519b.png)

**Comment by Ahrwing** [comment]
> 部分模组页面下该功能因未知原因失效 :(
> https://www.mcmod.cn/class/5038.html

已修复。

**Comment by VulpesStella** [comment]
:D
