### ISSUE TITLE
取消 link.mcmod.cn

### ISSUE THREAD

**Issue by rsp4jack** [Ahrwing/mcmod#737]
如题，在各种超链接到站外（包括页脚的几个）的全部使用直链，不再使用 link.mcmod.cn

**Comment by sxjeru** [comment]
使用本域跳转链接可避免搜索权重流失，有利于网站SEO。
（应该可以理解为使搜索引擎排名靠前）

**Comment by rsp4jack** [comment]
那么能否提供一个直链跳转的开关或类似的东西

**Comment by Ahrwing** [comment]
这项改动影响的范围太大了，不能取消。但可以在不影响功能的情况下做合理的改进与微调，你想要取消外链跳转的原因是什么呢？

**Comment by rsp4jack** [comment]
我想点击超链接后在浏览器地址栏直接显示目标网址，而不是link.mcmod.cn代理过后的人类不可读的URL

**Comment by HanlieChina** [comment]
> 我想点击超链接后在浏览器地址栏直接显示目标网址，而不是link.mcmod.cn代理过后的人类不可读的URL

<img width="280" alt="image" src="https://user-images.githubusercontent.com/48323966/144243668-6d05a681-3f81-4b81-9c10-bcb2381eb844.png">

**Comment by rsp4jack** [comment]
> > 我想点击超链接后在浏览器地址栏直接显示目标网址，而不是link.mcmod.cn代理过后的人类不可读的URL
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/48323966/144243668-6d05a681-3f81-4b81-9c10-bcb2381eb844.png">

**浏览器地址栏**。

**Comment by Ahrwing** [comment]
如果由 base64 改为可读形式的地址呢，例如：
https://link.mcmod.cn/?target=https%3A//github.com/Ahrwing/mcmod/issues/737

**Comment by rsp4jack** [comment]
这样会变成urlencode格式，倒还不如还用base64。
此外，我在尝试对 https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now 添加支持mcmod的功能

**Comment by sxjeru** [comment]
> 这样会变成urlencode格式，倒还不如还用base64。 此外，我在尝试对 https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now 添加支持mcmod的功能

这脚本不也是经一次跳转获得目标链接吗……

**Comment by rsp4jack** [comment]
但是可以在地址栏显示原始URL。

**Comment by sxjeru** [comment]
难道原本跳转完不显示目标url ？

**Comment by rsp4jack** [comment]
如果目标网址无效（例如被GFW封了），会花费很长时间卡在link.mcmod.cn。

**Comment by sxjeru** [comment]
有个折中方案，使用 [链接助手](https://greasyfork.org/zh-CN/scripts/422773-%E9%93%BE%E6%8E%A5%E5%8A%A9%E6%89%8B) 脚本。
直接双击黑色链接文字即可访问目标url，无中转。

![image](https://user-images.githubusercontent.com/20513115/144245998-8582193f-cca8-4c2d-921c-b1160489678f.png)

**Comment by rsp4jack** [comment]
经实验，跳转不能显示目标链接可能是浏览器的原因。
