### ISSUE TITLE
主页添加随机跳转按钮

### ISSUE THREAD

**Issue by rsp4jack** [Ahrwing/mcmod#739]
如题，就是添加一个按钮在主页上，点击可以跳转到随机一个页面。

**Comment by sxjeru** [comment]
见 banner 右下角“苦力怕”。

![image](https://user-images.githubusercontent.com/20513115/144607173-7ed6dd00-5ccc-4d50-b6de-ec34fe62f097.png)

**Comment by rsp4jack** [comment]
thx.
