### ISSUE TITLE
一级标题小于3个时默认不显示目录

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#744]

**Comment by Ahrwing** [comment]
在标题少但内容多，两个标题之间跨度较远的情况下，也会需要用到目录。
新增了提醒，让编者自己来判断吧（目录在3个或3个以下时会提醒）：
![图片](https://user-images.githubusercontent.com/5197567/146511324-a99119fd-4d81-4ed1-8f6d-1db6bd5b3710.png)
