### ISSUE TITLE
新增过滤器：仅含二级标题检查

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#745]
MediaWiki 的习惯是内文二级标题起始，所以有的用户会把二级标题作为第一 标题使用。

建议新增过滤器：当文档中存在 h2~h5 中的任意一个或多个，发出警告级别提醒，以提醒编者使用一级标题。

**Comment by HanlieChina** [comment]
新增过滤器：
当使用数量<X时，启用检测是否包含[ban:title_menu]。
理由：
在仅几个时，没必要包含目录。

**Comment by mamaruo** [comment]
> 新增过滤器： 当使用数量<X时，启用检测是否包含[ban:title_menu]。 理由： 在仅几个时，没必要包含目录。

#744

**Comment by HanlieChina** [comment]
> > 新增过滤器： 当使用数量<X时，启用检测是否包含[ban:title_menu]。 理由： 在仅几个时，没必要包含目录。
> 
> #744

3<x<6（不是）

**Comment by Ahrwing** [comment]
新增了目录跨级检测，只要跨级使用都会提醒（例如使用了2级标题却没有用1级标题、使用了3级标题，却没有用1、2级标题）
但目前仅实现了个数判断，还未做位置判断，所以子目录在父目录的前面时也能通过检测。
![图片](https://user-images.githubusercontent.com/5197567/146511832-9650564f-0778-4afb-9b15-f96f3e99864e.png)
