### ISSUE TITLE
自适应图标组快捷添加数字前后空格

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#747]
在插入面板添加一个功能，决定是否给自适应图标组快捷添加数字前后的空格。

勾选前：
`[icon:health=1,点]`
![image](https://user-images.githubusercontent.com/37480168/146962196-ce82857a-6e9f-407f-96ca-00b7e62f5673.png)

勾选后：
`&nbsp;[icon:health=1,&nbsp;点]`
![image](https://user-images.githubusercontent.com/37480168/146962127-d51398e1-fad0-4b34-bae1-7e2664f3d865.png)

**Comment by Ahrwing** [comment]
间距统一会更好些吧

**Comment by mamaruo** [comment]
> 间距统一会更好些吧

这是《中文文案排版指北》的要求之一。

**Comment by Ahrwing** [comment]
![gg](https://user-images.githubusercontent.com/5197567/147512356-adfa62ad-85af-4db4-b863-fb271eb3f1e4.png)
自适应图标组现已支持第二参数为空（之前的用法是用空格代替单位字符，但这样为了显示扩展格式会多一个空格），可实现扩展格式中隐藏单位，例如[icon:health=20,]。

**Comment by Ahrwing** [comment]
现在会自动在前后加空格了（无单位时不会在结尾加）。

**Comment by mamaruo** [comment]
> 现在会自动在前后加空格了（无单位时不会在结尾加）。

我的错，原来希望`添加一个快捷插入（编辑器中的）图标组数字前后的空格的勾选项`，但我没有考虑辅助标签不好实现自定义的问题（再加一个参数？使用难度又大了）。

根据[社区意见](https://bbs.mcmod.cn/thread-7116-1-1.html)，对于《指北》的这个要求中立和反对的用户居多。恐怕这个改动会引起争议，而且会导致内文格式不统一。

现在改变建议内容如下：
1. 撤回全域添加空格的改动。
2. （可选）提供类似“牛排”功能中“**在链接前后加空格**”的选项，实现勾选后自动插入“█[icon:health=1,█点]”的效果。

重生辛苦了~
