### ISSUE TITLE
测试沙盒解析图标错误

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#748]
![image](https://user-images.githubusercontent.com/37480168/147377830-a645682a-be95-42b8-8826-857fd87e7042.png)
刷新后
![image](https://user-images.githubusercontent.com/37480168/147386768-5d9de8f1-a607-4aa4-be7a-341eff27b503.png)

另外，测试沙盒中连续的两个图标也不会解析

**Comment by HanlieChina** [comment]
刷新即可。

**Comment by MCTF-Alpha-27** [comment]
> 

我这里用谷歌浏览器，它确实解析了，但是没显示图标，只有字段

**Comment by MCTF-Alpha-27** [comment]
> 刷新即可。

我这里用谷歌浏览器，它确实解析了，但是没显示图标，只有字段

**Comment by Ahrwing** [comment]
已修复。
