### ISSUE TITLE
无单位字段的自适应图标组

### ISSUE THREAD

**Issue by mamaruo** [Ahrwing/mcmod#749]
1. 建议无单位字段的自适应图标组以“数字（图标）”解析：
```
攻击力
简单：[icon:health=22.5]
普通：[icon:health=43]
```
现在的解析：
![image](https://user-images.githubusercontent.com/37480168/147377957-09ff255e-fad2-43ba-8815-f3ca924b3a4e.png)

我建议的解析：
![image](https://user-images.githubusercontent.com/37480168/147378002-00201aa1-b809-40da-a6b4-d6ccb751f069.png)

2. 提供勾选项目，让用户选择默认插入无单位的图标组

**Comment by MCTF-Alpha-27** [comment]
其实写成
简单：[icon:health=22.5,点]
普通：[icon:health=43,点]
就行了

**Comment by Ahrwing** [comment]
![gg](https://user-images.githubusercontent.com/5197567/147512356-adfa62ad-85af-4db4-b863-fb271eb3f1e4.png)
自适应图标组现已支持第二参数为空（之前的用法是用空格代替单位字符，但这样为了显示扩展格式会多一个空格），可实现扩展格式中隐藏单位，例如[icon:health=20,]。
