### ISSUE TITLE
模组搜索列表的版本选择调整为多选

### ISSUE THREAD

**Issue by zinsser901224** [Ahrwing/mcmod#753]
https://www.mcmod.cn/modlist.html?mcver=49
比如1.18版本，其实大版本下的mod是互相兼容的。但由于版本隔离导致我检索完1.18.1版本的列表之后必须再次检索1.18的列表。中间会重复看到很多重复的mod。建议这里做一个多选，把所有升级到1.18版本的mod一次性排重查出，提升效率

**Comment by Ahrwing** [comment]
功能已实现：
![图片](https://user-images.githubusercontent.com/5197567/157858078-33ccfad4-1840-4a2c-b5ab-d8b1d3a48d1f.png)
