### ISSUE TITLE
找服玩服务器无法上传图片

### ISSUE THREAD

**Issue by 4o4E** [Ahrwing/mcmod#758]
上传图片会提示：`The PHP installation does not meet the minimum system requirements for CKFinder. Missing PHP extensions: Fileinfo. Please refer to CKFinder documentation for more details.`

**Comment by mamaruo** [comment]
#645

**Comment by 4o4E** [comment]
> #645

ok

**Comment by mamaruo** [comment]
上传图片图标已被隐藏
![image](https://user-images.githubusercontent.com/37480168/149654907-f97923f0-85bf-4e50-b500-2f614270effb.png)
