### ISSUE TITLE
创建账号问题

### ISSUE THREAD

**Issue by WalterPlaysMinecraft** [Ahrwing/mcmod#759]
为什么创建账号时不能使用网易邮箱？

**Comment by HanlieChina** [comment]
因为其账号注册流程较为简单，这通常意味着其账号批量购买价格低，这使得其成为广告机的首要选择之一。
且确实有大量@126、@163用户对本站发送大量垃圾信息。其内容包括但不限于广告、钓鱼链接。
且不论国内国外，网易邮箱对于个人都“非必要”。国内绝大部分人使用的是QQ邮箱；国外则是谷歌邮箱。支持这部分邮箱的注册足以满足绝大多数人的使用。
故不暂不支持网易邮箱在注册时使用。
