### ISSUE TITLE
[edited]搜索功能太垃圾了了

### ISSUE THREAD

**Issue by fgt1t5y** [Ahrwing/mcmod#763]
受教了。十分抱歉，请原谅我以这种口吻向大家提意见

----------

我想搜索无尽贪婪，我习惯搜英文名，于是我输入avar，结果。。。

什么都搜不到。

我输入完整名称“avaritia”才能搜出来。。。一言难尽。

都不支持模糊搜索的吗？

**Comment by NancalaStarry** [comment]
指天画地，直言不讳 (✓)

**Comment by fgt1t5y** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sxjeru** [comment]
您知道吗？即便使用专业的 Google 或 Baidu，依旧很难只通过“avar”就搜得“avaritia”。

**Comment by HanlieChina** [comment]
抱歉没有找到与“avar site:mcmod.cn”相关的网页。 ——Baidu.com

**Comment by 3TUSK** [comment]
![Screen Shot 2022-02-04 at 18 50 49](https://user-images.githubusercontent.com/9113033/152626205-6de9bc32-aee9-4974-9b01-24e4bfbe67e0.png)
![Screen Shot 2022-02-04 at 18 51 27](https://user-images.githubusercontent.com/9113033/152626223-6bad56f2-ed51-409b-a8a0-6742e577a051.png)

不过模糊搜索也不是不能有，只是你如果允许搜索 avar 时，百科的后端将这个关键字当作正则表达式 avar.* 处理，会不会因此在搜索别的关键字的时候引入一大堆垃圾信息……？

**Comment by fgt1t5y** [comment]
> 指天画地，直言不讳 (✓)

抱歉
