### ISSUE TITLE
鼠标划过链接导致浏览器卡死

### ISSUE THREAD

**Issue by xys20071111** [Ahrwing/mcmod#765]
### 具体表现
鼠标在划过如物品名称，超链接等时，有一定几率导致游览器无响应，只能通过kill关闭
### 是否可复现
是
### 浏览器版本
Google Chrome 版本 98.0.4758.80（正式版本） （64 位）

**Comment by HanlieChina** [comment]
需要更多信息。

**Comment by Ahrwing** [comment]
我这边测试的版本是 98.0.4758.81（正式版本） （64 位），暂未重现此问题。

**Comment by xys20071111** [comment]
应该说是划过像
![pic1](https://user-images.githubusercontent.com/20025465/152977280-77561c29-cb90-4c14-846a-4c3aae651e81.png)
和
![image](https://user-images.githubusercontent.com/20025465/152977547-2d00b26f-28ae-4bad-b56c-ba990b358381.png)
这样的连接时，有一定几率那个小框一直闪，浏览器彻底卡死

**Comment by sxjeru** [comment]
本地试了一下，当在正中从上往下慢慢移动，确实会出现一直闪框的情况，但浏览器没有卡死。（CPU占用略微增加）
`chrome 97.0.4692.71`

**Comment by Ahrwing** [comment]
已为此功能的显示与隐藏增加了 0.1 ~ 0.2 秒的延迟，应该可以缓解此问题（需要进一步测试）。
