### ISSUE TITLE
每日签到没点领取, 关掉再打开就变成已签到状态

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#77]
![image](https://cloud.githubusercontent.com/assets/5229241/9704950/7ae22c0c-54e8-11e5-8ec3-52237d58c766.png)

**Comment by Ahrwing** [comment]
这边没遇到这种情况 0 0.. 在什么情况下出现的... 问问群里有没有出现过相同问题的情况……

**Comment by Meow-J** [comment]
正常情况下出现/w\

**Comment by AstonIceDog** [comment]
然并卵

**Comment by Ahrwing** [comment]
已去掉签到/反馈按钮，考虑以后以更简洁的方式展现。
