### ISSUE TITLE
自动链接和win10输入法疑似有冲突

### ISSUE THREAD

**Issue by Huiaei** [Ahrwing/mcmod#774]
使用<kbd>Alt</kbd>+<kbd>A</kbd> 快捷键后，win10拼音输入法经常会出现无法打字的问题，需要重新切换输入法或者窗口焦点移除浏览器再回到编辑器能可能才会好。

浏览器：FireFox 98.0 64位
系统：Windows 10 企业版 LTSC 21H2

**Comment by sxjeru** [comment]
~~自动链接应当是 Alt + X。~~

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/158001385-67795254-7deb-40c5-bbed-f964271924ca.png)
可改用<kbd>Alt</kbd>+<kbd>X</kbd> 。

**Comment by Huiaei** [comment]
> ![图片](https://user-images.githubusercontent.com/5197567/158001385-67795254-7deb-40c5-bbed-f964271924ca.png) 可改用Alt+X 。

好的，下次编辑尝试使用 <kbd>Alt</kbd>+<kbd>X</kbd>试试
