### ISSUE TITLE
合成表有时看不清数量

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#78]
![image](https://cloud.githubusercontent.com/assets/5229241/9709016/b3c9f2a2-5556-11e5-9162-7d9945e9d988.png)

**Comment by Ahrwing** [comment]
唔... 這個要怎麼解決捏.. 改顏色.. 或者增加字號..
不過左邊有顯示數量啊~~

**Comment by Meow-J** [comment]
mc字体很粗就没什么问题/w\
