### ISSUE TITLE
关于服务器审核问题

### ISSUE THREAD

**Issue by Coldsmiles** [Ahrwing/mcmod#786]
我不知道审核是什么顺序，我看见刚申请几天的服务器就有通过或者没通过的，而我的服务器申请十几天的服务器一直没有处理，类似的情况我看到了很多，所以我想问问服务器审核区可不可以按照提交的顺序进行审核

**Comment by HanlieChina** [comment]
找服玩群可以通过催审提高优先级。存在明显问题的会直接退回。结论是不可以，效率低，部分存在需要讨论内容，会暂时忽略。
