### ISSUE TITLE
Mod下载页面标签颜色

### ISSUE THREAD

**Issue by VulpesStella** [Ahrwing/mcmod#788]
![image](https://user-images.githubusercontent.com/81358657/165300856-8ac2991f-2a32-4137-8563-d80169c6581d.png)
白底感觉有点辣眼睛，换成紫罗兰色怎么样（

**Comment by sxjeru** [comment]
这是目前所有标签配色，至少有三个标签需更改底色或字体颜色。

![image](https://user-images.githubusercontent.com/20513115/166136425-f54afd13-5bee-44d3-8e57-7eb927a73b69.png)
![image](https://user-images.githubusercontent.com/20513115/166136420-fe3ea437-f29f-4ed7-8cfb-50369ae7bc6f.png)

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/172655499-1df8b4b2-335e-40d9-b31e-aa70a26ed6d0.png)
√
