### ISSUE TITLE
合成表审核显示有错误

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#79]
![image](https://cloud.githubusercontent.com/assets/5229241/9760376/20cc26a0-5727-11e5-9201-edd735411d59.png)

点击审核之后修改内容是正常的，但是未修改内容在审核前错乱， 这种现象出现好多次了

**Comment by Ahrwing** [comment]
修了一下 又是愚蠢的错误… 下回如果有合成表审核 再看一下.. 如果是正常的就可以关了ww

**Comment by Meow-J** [comment]
@Ahrwing 并没有/w\

**Comment by Meow-J** [comment]
![image](https://cloud.githubusercontent.com/assets/5229241/12134854/9e9dbff4-b46e-11e5-814d-0c5075149396.png)
![image](https://cloud.githubusercontent.com/assets/5229241/12134858/a881268c-b46e-11e5-8c8a-98bb7503102f.png)

**Comment by Ahrwing** [comment]
这回应该没问题了ww 另外 修改合成表也加入了跳到物品的链接~
