### ISSUE TITLE
开发组“申请”按钮无效

### ISSUE THREAD

**Issue by vvvbbbcz** [Ahrwing/mcmod#795]
如题，在申请加入开发组时，点击“申请”按钮后会打开加群链接，但QQ应用没有反应
![img](https://s1.ax1x.com/2022/05/07/OQzJBT.png)

其次，“编辑讨论群”的链接和群号均已失效。
![img](https://s1.ax1x.com/2022/05/07/OQz2Ue.png)

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/167252514-1ac011e3-952d-4e72-8a93-3af44d721f1a.png)
离谱。
可临时发送模组ID、申请用户ID、开发者证明到 admin@mcmod cn 来申请。

**Comment by mamaruo** [comment]
离谱，这怎么被限制搜索了

> 模组ID、申请用户ID

注：这里指MC百科中的ID而非modid或Minecraft用户名，即模组页链接和个人主页链接末尾的数字。

**Comment by sxjeru** [comment]
~~建议重生可以检查下群设置中的“查找方式”项目。~~
不用了，可能是群被举报了。

![image](https://user-images.githubusercontent.com/20513115/167254049-76e85d09-fc94-428b-a752-57d540248a18.png)

**Comment by mamaruo** [comment]
![image](https://user-images.githubusercontent.com/37480168/167254154-395dfdab-0a7d-4f38-8e53-33189179d04f.png)

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/167255329-be1cd5cc-2c10-4012-a388-d47599f6c42a.png)
√
