### ISSUE TITLE
编辑器在超过几千字的时候会非常卡

### ISSUE THREAD

**Issue by Krasjet** [Ahrwing/mcmod#8]
编辑版本日志时候经常遇到

**Comment by Meow-J** [comment]
想体验被卡的快感可以在这篇日志尝试做一些更改: http://www.mcmod.cn/class/version/edit/836

**Comment by Ahrwing** [comment]
这么长的字符串…… 估计换什么编辑器都撑不住... 我建议以后日志很长的话就截取其中的一段，然后最后放上源站链接，说到官网去看..

**Comment by sxjeru** [comment]
感觉是小水管造成的加载速度慢。

**Comment by Ahrwing** [comment]
已改善此问题! 
>虽然仍然会卡, 但相比4年前缓解了许多
