### ISSUE TITLE
Why? Why? Why? 

### ISSUE THREAD

**Issue by user111192** [Ahrwing/mcmod#804]
![image](https://user-images.githubusercontent.com/67212831/173261440-777e20fb-a484-4d9c-8fbd-34151ae1ad4a.png)
为什么**连伪原创的机会都不给? ? ?**

**Comment by user111192** [comment]
@Biggest_Xuan

**Comment by MCTF-Alpha-27** [comment]
你复制wiki的时候标明出处了吗

**Comment by user111192** [comment]
> 你复制wiki的时候标明出处了吗

可是连补出处的机会都没了
怎么办

**Comment by user111192** [comment]
+通缉Biggest_Xuan
理由：↑

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/173265219-cebc8020-980a-434f-b1a8-af2ee65e1f24.png)
已查到你曾提交的内容，呃… 
![图片](https://user-images.githubusercontent.com/5197567/173338883-ca6ae2bb-3aaa-43cf-914f-c77159e6b450.png)
怎么说你好呢…

**Comment by JieningYu** [comment]
这确实🌝

**Comment by mamaruo** [comment]
我站不允许原样照搬Minecraft Wiki，允许在 CC 协议下转载。

关于CC协议，Minecraft Wiki 和 MC 百科都在页尾明确指出。
![image](https://user-images.githubusercontent.com/37480168/173339558-e582a4d3-a974-4e89-ac75-53c6b341e037.png)
![image](https://user-images.githubusercontent.com/37480168/173339621-af9edbf9-2d6c-456f-99d9-c8727ece0809.png)


**你仅在MC原版被封，其他模组仍可正常编辑。** 都来模组百科了，何不四处逛逛呢。

另重生麻烦声明一下这位是多次提交仍不改正，不然我认为 1 个月量刑过重。

**Comment by Ahrwing** [comment]
> 另重生麻烦声明一下这位是多次提交仍不改正，不然我认为 1 个月量刑过重。

他一共提交了两次，第一次提交是我退回的，回复说不能复制wiki，第二次提交如上图，美其名曰“伪原创”，无力吐槽，也是醉了…

**Comment by mamaruo** [comment]
> > 另重生麻烦声明一下这位是多次提交仍不改正，不然我认为 1 个月量刑过重。
> 
> 他一共提交了两次，第一次提交是我退回的，回复说不能复制wiki，第二次提交如上图，美其名曰“伪原创”，无力吐槽，也是醉了…

收到

综上，封禁合理
