### ISSUE TITLE
属性评比显示bug

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#81]
![image](https://cloud.githubusercontent.com/assets/5229241/9790885/138fdee8-580b-11e5-829c-b0861c6a42d8.png)
![image](https://cloud.githubusercontent.com/assets/5229241/9790889/1880c8d6-580b-11e5-9da1-b94d683aee49.png)
![image](https://cloud.githubusercontent.com/assets/5229241/9790895/1dba1c76-580b-11e5-9b83-c99ce2c99f5d.png)
![image](https://cloud.githubusercontent.com/assets/5229241/9790903/249eb2f4-580b-11e5-866b-8c87f5f086bd.png)

**Comment by Ahrwing** [comment]
已解决
