### ISSUE TITLE
更多相关链接

### ISSUE THREAD

**Issue by Ginsway** [Ahrwing/mcmod#814]
建议添加：

- 爱发电 https://afdian.net/
- QQ https://im.qq.com/
- Twitch https://twitch.tv/
- 官方论坛

**Comment by HanlieChina** [comment]
爱发电、QQ、Twitch在模组/整合包页的使用率不高。作者页有一定需求。
官方论坛可以使用官方，并在备注中说明。

**Comment by HanlieChina** [comment]
可以使用自定义（其它）。

**Comment by Ahrwing** [comment]
爱发电一直没有找到合适的 svg 图标，现在只有链接选项
QQ已经有了，在选择“其它”时填写“QQ”、“QQ群”、“QQ号”、“QQ讨论组”都会显示QQ图标
官方论坛可以使用第一个选项“官方”，在备注中写“官方论坛”

作者页即将添加：Twitch、MCPEDL、Gitea
模组/整合包页即将添加：Google Drive、MCPEDL、Gitea

**Comment by Ahrwing** [comment]
![image](https://user-images.githubusercontent.com/5197567/197424991-1695fc37-e53a-4880-b494-37bf5106d595.png)

`已更新：新增了 Twitch、Google Drive、MCPEDL、Gitea 的相关链接图标：`
![image](https://user-images.githubusercontent.com/5197567/197424966-f9c3246c-94d9-46b6-8103-eebd70bf37b8.png)

`顺便更新了一下备注：`
![image](https://user-images.githubusercontent.com/5197567/197423067-54c64b1f-ca5f-4959-92ef-8f0061d73d58.png)

**Comment by Ginsway** [comment]
谢谢重生！！
