### ISSUE TITLE
审核太严格了

### ISSUE THREAD

**Issue by ITVGD** [Ahrwing/mcmod#815]
我自己想发一个mod，审核规则看不懂，退回3次了，外加禁止编辑1天，我用我自己的所有力气换来的是3次退回1天“封号”对我这个开发者好吗？这不好。然后没办法只能放在网盘和我网站上，唉。

**Comment by JieningYu** [comment]
那请问你做的mod是什么mod

**Comment by ITVGD** [comment]
很普通

**Comment by JieningYu** [comment]
具体是什么mod，退回原因是什么，请说清楚些

**Comment by ITVGD** [comment]
![image](https://user-images.githubusercontent.com/109856535/180606333-ac2c1f41-be8c-4288-be72-808ead79a392.png)

**Comment by JieningYu** [comment]
不符合收录标准说明这mod有问题，再怎么提交也没用
建议close这个issue
