### ISSUE TITLE
我的模组区域里显示的Mod不完整

### ISSUE THREAD

**Issue by Glyceryl6** [Ahrwing/mcmod#818]
我自己上传了4个自行开发的Mod，并且均已通过，但是我的模组区域里只显示之前所提交的3个，第4个并未显示，如图：
![QQ截图20220803205635](https://user-images.githubusercontent.com/29040933/182614100-b0b6eeb1-9e89-49d9-8315-3abcf371efd7.png)
![QQ截图20220803205732](https://user-images.githubusercontent.com/29040933/182614103-e307aad2-5cc2-4821-91e6-04d51c4ea754.png)

**Comment by HanlieChina** [comment]
开发者部分情况下需自行申请。

**Comment by HanlieChina** [comment]
**申请开发者的条件是什么？**
申请者必须为模组核心开发成员，非核心参与人员必须在征得核心成员的同意后才能申请。

**如何申请开发者？**
请将以下申请材料发送至邮箱 admin@mcmod.cn：

1. 模组在百科的ID（见模组地址栏）；
2. 申请者的用户ID（见个人中心地址栏）；
3. 开发者证明（需用具有说服力的方式证明）。

**开发者会有哪些功能？**

1. 模组开发者可以上传模组文件，可通过“头像菜单->文件管理”进入文件管理界面；
2. 模组开发者会在模组短评与个人中心内显示醒目的标识。

**Comment by Glyceryl6** [comment]
好的，明白了，谢谢！

**Comment by Ahrwing** [comment]
![图片](https://user-images.githubusercontent.com/5197567/182621423-3cb188ce-a77b-4ce9-916f-bac4c09906aa.png)
√
