### ISSUE TITLE
增加图片显示比例

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#82]
http://www.mcmod.cn/post/192.html
像你这篇图片明显就太大了

**Comment by Ahrwing** [comment]
_(:з」∠)_ 这个不是设计上的BUG啦… 这个教程内显示的图片是实际尺寸1:1而非拉伸过的.. 
可能是截图的时候设的屏幕分辨率较高的缘故吧... 这点在编辑的时候注意一下可以手动缩放~
系统无法判定图片内容是否“看起来很大”啊...

**Comment by 3TUSK** [comment]
花了 2 年时间解决的问题。

**Comment by Ahrwing** [comment]
`只是忘了关`
