### ISSUE TITLE
help.qwq.fun无法连接

### ISSUE THREAD

**Issue by heipiao233** [Ahrwing/mcmod#821]

**Comment by HanlieChina** [comment]
原因：8月1日起个人版不再支持绑定域名 请尽快迁移至知识管理 —— [顶想云知识管理正式上线——看云文档启动迁移服务](https://www.kancloud.cn/book/mcmod/help/domain)

**Comment by heipiao233** [comment]
所以应该访问https://www.kancloud.cn/mcmod/help/content吗

**Comment by HanlieChina** [comment]
> 所以应该访问[https://www.kancloud.cn/mcmod/help/content吗](https://www.kancloud.cn/mcmod/help/content%E5%90%97)

不应该。

**Comment by HanlieChina** [comment]
> 所以应该访问[https://www.kancloud.cn/mcmod/help/content吗](https://www.kancloud.cn/mcmod/help/content%E5%90%97)

暂时可以。

**Comment by Ahrwing** [comment]
现在可以了（会自动重定向）

**Comment by sxjeru** [comment]
http 正常跳转，https 略有问题。

![image](https://user-images.githubusercontent.com/20513115/197429958-670c5e5d-b177-4c87-b3a7-462f382b7939.png)
