### ISSUE TITLE
添加Spigot之类的插件索引

### ISSUE THREAD

**Issue by neila-a** [Ahrwing/mcmod#832]
就是把服务端的那些插件以其他方式收录进mc百科
以下方式可供参考：

1. 在modlist.html里的运作方式里添加"Spigot"及更多
2. 脱离模组分区，建立第三个分区“插件”（前两个为“模组”和“整合包”）

**Comment by sxjeru** [comment]
类似 #383 #766

**Comment by neila-a** [comment]
确实，插件就去mineplugin
