### ISSUE TITLE
希望更新一个模块可以上传汉化材质包

### ISSUE THREAD

**Issue by fgr178707** [Ahrwing/mcmod#834]
希望能在这一块增加一个汉化材质包上传
因为好多好用的辅助模组都是因为没有简体中文
但是有玩家自制的简体中文材质包
这样方便其他玩家使用
不用去一些其他网站寻找汉化方法
![QQ截图20220927194502](https://user-images.githubusercontent.com/109357981/192516859-e5ca1cea-a130-47bd-a848-ddebf84fed29.png)

**Comment by Ginsway** [comment]
https://github.com/CFPAOrg/Minecraft-Mod-Language-Package

**Comment by Ginsway** [comment]
做一个直达不错

**Comment by fgr178707** [comment]
加一个独立这个模组的独立汉化多好

**Comment by fgr178707** [comment]
> https://github.com/CFPAOrg/Minecraft-Mod-Language-Package

我知道这个
但是里边儿有没有用的呀
辅助模组就那几个
我觉得还是搞一个模块合适

**Comment by Ginsway** [comment]
康康喵呜机会不会搞吧（大概率不会）

**Comment by Ginsway** [comment]
https://cfpa.site/ 已经很完善了

**Comment by fgr178707** [comment]
> 康康喵呜机会不会搞吧（大概率不会）

提一提说不定呢

**Comment by NancalaStarry** [comment]
毕竟还是太善良了，不会想到玩家自主上传的东西有病毒吗？出了事情……
放评论区是最优解（个人观点），随时间可以筛走，说不定哪一天官中就可以出来。

**Comment by NancalaStarry** [comment]
当然有时候有社区推荐的翻译资源包，也不是不可以在正文放转到资源包发布的链接，有些时候还是有点余地的

**Comment by fgr178707** [comment]
> 毕竟还是太善良了，不会想到玩家自主上传的东西有病毒吗？出了事情…… 放评论区是最优解（个人观点），随时间可以筛走，说不定哪一天官中就可以出来。

 zip格式才能往里面放啥，谁知道呢看看官方吧

**Comment by EvanHsieh0415** [comment]
是說其實可以直接發pr給原作者或是相對應的中文化模組/資源包
如 i18n或RPMTW
