### ISSUE TITLE
广告 “千疑千寻”为基督教传教广告

### ISSUE THREAD

**Issue by Mobius0526** [Ahrwing/mcmod#841]
《互联网宗教信息服务管理办法》第十七条 除本办法第十五条、第十六条规定的情形外，任何组织或者个人不得在互联网上传教，不得开展宗教教育培训、发布讲经讲道内容或者转发、链接相关内容，不得在互联网上组织开展宗教活动，不得以文字、图片、音视频等方式直播或者录播拜佛、烧香、受戒、诵经、礼拜、弥撒、受洗等宗教仪式。

第十八条 任何组织或者个人不得在互联网上成立宗教组织、设立宗教院校和宗教活动场所、发展教徒。

第十五条 取得《互联网宗教信息服务许可证》的宗教团体、宗教院校和寺观教堂，可以且仅限于通过其依法自建的互联网站、应用程序、论坛等由宗教教职人员、宗教院校教师讲经讲道，阐释教义教规中有利于社会和谐、时代进步、健康文明的内容，引导信教公民爱国守法。参与讲经讲道的人员实行实名管理。

第十六条 取得《互联网宗教信息服务许可证》的宗教院校，可以且仅限于通过其依法自建的专用互联网站、应用程序、论坛等开展面向宗教院校学生、宗教教职人员的宗教教育培训。专用互联网站、应用程序、论坛等对外须使用虚拟专用网络连接，并对参加教育培训的人员进行身份验证。

**Comment by Ahrwing** [comment]
https://bbs.mcmod.cn/forum.php?mod=viewthread&tid=7898&page=1#pid40771
