### ISSUE TITLE
黄历评论排版错乱

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#85]
![image](https://cloud.githubusercontent.com/assets/5229241/9958665/efa84e9a-5e3e-11e5-877d-2095631d2052.png)

**Comment by Ahrwing** [comment]
不僅是黃曆... 很多頁面都有這個問題.. 正在排查..

**Comment by Meow-J** [comment]
点击只看自己也会出问题

**Comment by Ahrwing** [comment]
修好了~
