### ISSUE TITLE
邮箱注册显示邮箱发送失败

### ISSUE THREAD

**Issue by Vamco2022** [Ahrwing/mcmod#855]
邮件发送失败: (Mailer Error: SMTP Error: data not accepted.SMTP server error: DATA command failed Detail: Reject by behaviour spamANTISPAM_BAT[01201311R1868S4430114234, ay29a033002195075]: too frequently sending SMTP code: 554)
一直都是这样

**Comment by Ahrwing** [comment]
现在测试正常
