### ISSUE TITLE
(备忘) 批量导入相关

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#86]
- [x] 批量分类
- [x] Base64添加/修改物品图标
- [x] 图标显示bug
- [x] 图标导入bug
- [x] 按照mod显示/操作物品

**Comment by Meow-J** [comment]
+4

**Comment by Ahrwing** [comment]
按照mod显示/操作物品 是什么来着… Orz..

**Comment by Meow-J** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5229241/11843378/414da952-a444-11e5-8271-c9583eb3b239.png)

**Comment by Meow-J** [comment]
我当初是怎么用鼠标写出来这样的字的/w\

**Comment by Ahrwing** [comment]
鼠绘天赋 +++
