### ISSUE TITLE
评比继续出问题

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#88]
![image](https://cloud.githubusercontent.com/assets/5229241/10075032/3b071116-6306-11e5-9018-00a479a7980b.png)
某些时候会出现

**Comment by elctove** [comment]
这玩意bug真是多……

**Comment by AstonIceDog** [comment]
感觉这个东西不科学

**Comment by 3TUSK** [comment]
没有修就干掉好了，这玩意总感觉不客观（笑）

**Comment by AstonIceDog** [comment]
1.首先，这个评比不应分单人模式和多人模式
2.然后，评比方式不正确，不应该是每日签到形式的，应该是一次性评比，也就是说**每人评比一个模组仅有一次机会**
3.评比的属性有点问题，有点太多了，实用，难度，趣味，兼容，这些就够了
---------------------------------
以上是我个人的一些拙见，希望采纳。23333

**Comment by AstonIceDog** [comment]
我也看到了
![image](https://cloud.githubusercontent.com/assets/13271372/12073936/4bc606d0-b174-11e5-86ec-8f2e95a0c74b.png)

**Comment by Ahrwing** [comment]
已修复
