### ISSUE TITLE
主页存在两个搜索框

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#90]
![image](https://cloud.githubusercontent.com/assets/5229241/10261557/81cb59f6-69d0-11e5-9781-0b8b89a79e5c.png)

**Comment by Ahrwing** [comment]
首页那个搜索框只会在首页显示…… 而顶上的搜索框会在任何页面显示……
以首页作为入口人比较多，所以加了一个不能点就能看到的搜索框……
