### ISSUE TITLE
【建议】给模组筛选添加更细的选项

### ISSUE THREAD

**Issue by block13566** [Ahrwing/mcmod#907]
如题，例如在元素筛选中增加版本、加载器、客户端或服务端等详细筛选

**Comment by HanlieChina** [comment]
没有吗？

**Comment by block13566** [comment]
> 没有吗？

选核心元素不能同时选版本，搜索时也没有筛选选项

**Comment by sxjeru** [comment]
其实是有的。
https://www.mcmod.cn/modlist.html?mcver=1.12.2&api=1&category=24

**Comment by block13566** [comment]
> 其实是有的。
> https://www.mcmod.cn/modlist.html?mcver=1.12.2&api=1&category=24

藏这么深啊

**Comment by HanlieChina** [comment]
> > 其实是有的。
> > https://www.mcmod.cn/modlist.html?mcver=1.12.2&api=1&category=24
> 
> 藏这么深啊

模组列表不是一直都可以吗？

**Comment by block13566** [comment]
> > > 其实是有的。
> > > https://www.mcmod.cn/modlist.html?mcver=1.12.2&api=1&category=24
> > 
> > 
> > 藏这么深啊
> 
> 模组列表不是一直都可以吗？

不是，我这边用的手机版网页完全看不到有这个

**Comment by sxjeru** [comment]
目前百科的网页基本是自适应网页，手机与电脑显示内容与效果应该是相同的。
你可以试试点击任意mod的元素标签，看看能否到检索页。
