### ISSUE TITLE
多端登录问题

### ISSUE THREAD

**Issue by qznfbnj** [Ahrwing/mcmod#911]
是否能允许至少一个移动端和PC端同时登录？每次移动端登录后PC端都会退出登录，反之亦然

**Comment by sxjeru** [comment]
可以修改设置以允许多端登录。
个人中心 -》设置 -》安全设置 -》允许多设备登录。

**Comment by qznfbnj** [comment]
> 可以修改设置以允许多端登录。 个人中心 -》设置 -》安全设置 -》允许多设备登录。

这样啊，谢了
