### ISSUE TITLE
恶性Bug，更换头像任务无法领取奖励

### ISSUE THREAD

**Issue by MyrChRya2** [Ahrwing/mcmod#944]
任务中修改头像的连接无法打开，通过其他方式修改头像也无法在此领奖，导致无法正常升级，不能发帖讨论
![image](https://github.com/Ahrwing/mcmod/assets/111130638/3bf1ca8f-0cca-4e90-bb33-fd4644c8a115)

**Comment by HanlieChina** [comment]
不影响正常升级。

**Comment by MyrChRya2** [comment]
> 不影响正常升级。

请问除了新用户三任务以外还有其他方式获取经验吗？太难找了😢😢😢

**Comment by HanlieChina** [comment]
> 请问除了新用户三任务以外还有其他方式获取经验吗？太难找了😢😢😢

总积分=RF+(AE/2)+(EUX4)+(VisX8)+(ManaX16)

**Comment by HanlieChina** [comment]
> 总积分=RF+(AE/2)+(EUX4)+(VisX8)+(ManaX16)

编辑会提供AE。

**Comment by MyrChRya2** [comment]
> > 总积分=RF+(AE/2)+(EUX4)+(VisX8)+(ManaX16)
> 
> 编辑会提供AE。

ok,我试试
所以那个奖励领不了还有打不开换头像连接是Bug吗？

**Comment by HanlieChina** [comment]
> ok,我试试 所以那个奖励领不了还有打不开换头像连接是Bug吗？

社群的换头像相关功能已移除，所以后者不是bug。

**Comment by MyrChRya2** [comment]
> > ok,我试试 所以那个奖励领不了还有打不开换头像连接是Bug吗？
> 
> 社群的换头像相关功能已移除，所以后者不是bug。

ok我了解了，谢谢你💕💕希望mcmod能多加一些对新用户的引导功能，新用户真的一头雾水，我甚至差点找不到注册按钮，祝mcmod越来越好
