### ISSUE TITLE
登陆

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#95]
/w\突然想起来这个问题好像很久没解决了
![image](https://cloud.githubusercontent.com/assets/5229241/10344098/faccc408-6d53-11e5-9aa1-03f984962650.png)
![image](https://cloud.githubusercontent.com/assets/5229241/10344103/ffcb4e3e-6d53-11e5-87c1-591089f023a9.png)
![image](https://cloud.githubusercontent.com/assets/5229241/10344110/08eb072a-6d54-11e5-9c44-63e05f508b78.png)

**Comment by Meow-J** [comment]
第二个还没改呢

**Comment by 3TUSK** [comment]
难道不是[*登录*](https://zh.wikipedia.org/wiki/%E7%99%BB%E5%85%A5)？

**Comment by Meow-J** [comment]
话说上次看UPlay也用的登陆

**Comment by 3TUSK** [comment]
所以到底哪个是正字...对这个问题疑惑很久了...

**Comment by AstonIceDog** [comment]
。。。这个无伤大雅好吗

**Comment by AstonIceDog** [comment]
我感觉登录比较好

**Comment by 3TUSK** [comment]
所以这个问题究竟是什么...

**Comment by Ahrwing** [comment]
@3TUSK 所有登陆改成登录 目前大部分文字部分已改好 但是图片里的还木有改

**Comment by 3TUSK** [comment]
建议现在就去解决，应该不是难事吧？能少一个issue是一个。

**Comment by Ahrwing** [comment]
correct √

**Comment by Meow-J** [comment]
戳一下

**Comment by 3TUSK** [comment]
我似乎给站长立了个Flag...

**Comment by Ahrwing** [comment]
已解决…

**Comment by 3TUSK** [comment]
本 issue 从提出到解决共耗时接近 21 个月（笑）
