### ISSUE TITLE
出现了在添加mod时被识别为站长的bug

### ISSUE THREAD

**Issue by wit24** [Ahrwing/mcmod#955]
![image](https://github.com/Ahrwing/mcmod/assets/172932854/a94be23c-c9b4-44d4-854c-6a33a5d4d608)
![image](https://github.com/Ahrwing/mcmod/assets/172932854/a8c20e4f-8f41-488e-8de9-866465179e1b)

**Comment by Ahrwing** [comment]
真巧，刚才在优化这个页面中的“提醒撞车小助手”，正好碰到施工现场了（仅显示异常，实际登录用户没有改变），现在应该正常了
