### ISSUE TITLE
合成表筛选

### ISSUE THREAD

**Issue by Meow-J** [Ahrwing/mcmod#96]
![image](https://cloud.githubusercontent.com/assets/5229241/10344978/f2d5ef0e-6d58-11e5-8070-e6c2dd5bf6e1.png)
![image](https://cloud.githubusercontent.com/assets/5229241/10344957/d95f7aa4-6d58-11e5-9751-0a92a6354713.png)
另外筛选应该排在第二行吧

**Comment by Ahrwing** [comment]
修好了.. 昨天晚上莫名断网 Orz..
